### ISSUE TITLE
Mocha support (server)

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#10]
Server sided Mocha tests are not yet supported by stryker. See [#11](https://github.com/infosupport/stryker/issues/11) for browser based Mocha test support.

**Comment by simondel** [comment]
Existing projects such as [grunt-mocha-test](https://github.com/pghalliday/grunt-mocha-test) can be used as reference.
The API can also be viewed in the [source](https://github.com/mochajs/mocha/blob/master/lib/mocha.js#L51)

**Comment by simondel** [comment]
We only copy the source files of a project to a different location to run the tests. This can cause issues when files are linked to each other using `require` statements that have relative paths. Since the test files are not copied, they will still `require` the original source files, instead of the copy.

**Comment by nicojs** [comment]
Wow! Nice find. This is indeed a problem.

The way i see it: we have 2 possibilities

1. Override the global `require` function. Then, if a `require` call is made, we forward it to the original `require` directly, unless it starts with `.` or `..`, in that case we *rewire* the `require` to the sand-boxed version of the file. 
2. We just include the test files in the sandbox.

The second solution is safest but comes with a performance overhead. 

The first solution is very error prone. For example:

1. As part of the unit test, the user can use something like `Mockery` or `Rewire` to override the global require themselves. This might not be a problem, but we'll have to test it anyway.
2. How do we distinguish between a `require` statement from the unit test framework and the production code. I might `require` something like `'../../src/MySystemUnderTest'` (clearly should be *rewired* to the sandbox version), but it could also be something like `'../mocks/MockHelper'` (clearly not to be rewired)
3. We also use `require` to make our code work. That one will also be the *rewired* one. We need to make sure this doesn't break anything.

I would go for the second solution for now, as it is safer. We can later change it if we want to optimize for performance.

**Comment by simondel** [comment]
https://github.com/stryker-mutator/stryker-mocha-runner
