### ISSUE TITLE
Race condition in integration test

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#1001]
Build fails sometimes because of a race condition in `ResilientTestRunnerFactory when test runner behind has a slow init and dispose cycle`

```
  1) ResilientTestRunnerFactory
       when test runner behind has a slow init and dispose cycle
         should be able to run twice in quick succession:
      Run status was Timeout, while Complete expected
      + expected - actual
      -2
      +0
```

**Comment by simondel** [comment]
Should we increase the timeout?

**Comment by nicojs** [comment]
This test doesn't exist anymore in the current code base. Closing for now.
