### ISSUE TITLE
Improve Mocha support

### ISSUE THREAD

**Issue by prsn670** [stryker-mutator/stryker#1046]
### Summary

Hello all, I was hoping somebody could let me know what I'm doing wrong here. I keep getting a syntax error on CSS files. We're using Stryker version 0.14.1. We are also using react/redux with the mocha test framework. We are not using webpack. I'm unsure if it is some configuration error, version issue, or something completely different. The error is as follows:

[2018-07-26 13:02:05.874] [ERROR] InitialTestExecutor - One or more tests resulted in an error:
        SyntaxError: Unexpected token .
C:\code_base\poi\node_modules\form\lib\util\block.css:1
(function (exports, require, module, __filename, __dirname) { .a-form-v3-10-0-block {

### Stryker config

```js
module.exports = function(config){
  config.set({
   files: [
        "src/**/*.js",
        "test/**/*.js"
    ],
    mutate:[
      "src/pages/poi/*.js"
    ],
    testRunner: "mocha",
    mutator: "javascript",
    transpilers: ["babel"],
    reporter: ["html", "clear-text", "progress"],
    testFramework: "mocha",
    coverageAnalysis: "off",
    babelrcFile: ".babelrc"
  });
}
```

### Stryker environment

```
+-- stryker@x0.14.1
+-- stryker-api@x0.11.0
+--stryker-babel-transpiler@0.2.2
+--stryker-html-reporter@0.11.1
+--stryker-javascript-mutator@0.2.3
+--stryker-mocha-framework@0.7.0
+==stryker-mocha-runner@0.10.0
```

### Your Environment
| software                | version(s)
| -------------------- | -------  
| node                      | 6.1.0
| npm                       | 3.8.6
| Operating System | Windows 7 Enterprise

**Comment by nicojs** [comment]
Thanks for reporting this issue. I see that you have both a webpack configuration and a Babel configuration. You normally won't need webpack when using mocha as a test runner. What does your babelrc and npm test command look like?

**Comment by simondel** [comment]
@nicojs the post was edited after placing it. The webpack config is now gone and the post mentions they don't use webpack. (I was about to ask the same question)

**Comment by prsn670** [comment]
Sorry about the mistake in the config file, I did edit it right after I noticed it. Here is my babelrc and npm test command.

## babelrc
```
{
  "env": {
    "test": {
      "plugins": [
        [
          "istanbul",
          {
            "exclude": [
              "src/main.js",
              "src/redux/configureStore.js"
            ],
            "include": [
              "src/"
            ]
          }
        ]
      ]
    }
  },
  "ignore": ["dist/", "coverage/"],
  "presets": ["env", "stage-2", "react"]
```
## npm test command
"test": "cross-env NODE_ENV=test mocha \"./test/**/*-tests.js\"",

**Comment by simondel** [comment]
As a check, could you upgrade the Stryker dependencies to their latest versions? If you use Git for this project, you may be able to remove the `files` property from the config as well.

**Comment by prsn670** [comment]
Sorry for taking so long to reply. I was able to update Stryker to the latest version, but may have to wait till Monday till the other dependencies can be updated. I tried running with just the updated Stryker and got this error:

module.js:440
    throw err;
    ^

Error: Cannot find module 'stryker-api/logging'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\code_base\pc-property-renters-proof-of-insurance\node_modules\stryker\src\config\ConfigReader.js:5:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)


Trying to delete the old conf file and running init again also results in the same error. I'm thinking I'll have to update stryker-api at least before I can do anything more.

**Comment by simondel** [comment]
Yeah, we've recently revamped the logging so you'll have to update all Stryker dependencies (including the plugins such as stryker-mocha-runner).

Don't worry about taking a while to respond. We're here to help you and if you need some time that's perfectly fine. We also don't have time to reply or fix things right away :)

**Comment by prsn670** [comment]
I installed the upgraded dependencies this morning and reran the init command. The only thing the setup asked me was what type of reporters I wanted and the package manager I was using. The config file had a few labels with nothing filled in so I filled it in. I'm still receiving an error:

08:01:56 (13016) ERROR TestRunnerChildProcessAdapter Child process exited with non-zero exit code 1. Last 10 message from the child process were:

08:01:56 (13016) ERROR InitialTestExecutor One or more tests resulted in an error:
        SyntaxError: Unexpected token .
C:\code_base\poi\.stryker-tmp\sandbox5164784\src\pages\poi-trap\poi-trap.css:10
.trap-section-container
^
SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\code_base\poi\.stryker-tmp\sandbox5164784\src\pages\poi-trap\poi-trap.js:13:1)
    at Module._compile (module.js:541:32)
08:01:56 (13016) ERROR StrykerCli an error occurred Error: Something went wrong in the initial test run
    at InitialTestExecutor.validateResult (C:\code_base\poi\node_modules\stryker\src\process\InitialTestExecutor.js:129:15)
    at InitialTestExecutor.<anonymous> (C:\code_base\poi\node_modules\stryker\src\process\InitialTestExecutor.js:45:30)
    at step (C:\code_base\poi\node_modules\stryker\node_modules\tslib\tslib.js:133:27)
    at Object.next (C:\code_base\poi\node_modules\stryker\node_modules\tslib\tslib.js:114:57)
    at fulfilled (C:\code_base\poi\node_modules\stryker\node_modules\tslib\tslib.js:104:62)
    at process._tickCallback (internal/process/next_tick.js:103:7)

### Stryker config



```js
module.exports = function(config){
  config.set({
   mutate: [
        "src/pages/poi-email/*.js"
    ],
    testRunner: "mocha",
    mutator: "javascript",
    transpilers: ["babel"],
    reporter: ["clear-text", "progress"],
    packageManager: "npm",
    coverageAnalysis: "off",
    babelrcFile: ".babelrc"
  });
}
```

### Stryker environment



```
+-- stryker@x0.25.1
+-- stryker-api@x0.18.0
+--stryker-babel-transpiler@0.6.0
+--stryker-javascript-mutator@0.8.0
+--stryker-mocha-framework@0.11.0
+==stryker-mocha-runner@0.13.0
```

**Comment by prsn670** [comment]
I tried the configuration @nicojs suggested but I get a syntax error on the import. This happens when we don't include the babel transpiler. We do have a mocha.opts file in which our mocha-hook.js file is required. babel-register is required in the hook.js file, which should also disable our css imports. Could there be an issue where the mocha.opts file is not being used correctly?

**Comment by nicojs** [comment]
> Could there be an issue where the mocha.opts file is not being used correctly?

Yes, this is most definitely it. It is not used by default. Mocha has no clean way of providing the mocha.opts file, instead we had to recreate the functionality. See https://github.com/stryker-mutator/stryker/tree/master/packages/stryker-mocha-runner#configuring

I our implementation _doesn't support local requires_. Could you try this:

```js
module.exports = function(config){
  config.set({
    mutate:[
      "src/pages/poi/*.js"
    ],
    testRunner: "mocha",
    testFramework: "mocha",
    mutator: "javascript",
    reporter: ["html", "clear-text", "progress"],
    coverageAnalysis: "off",
    mochaOptions: {
      files: [ './test/**/*-tests.js' ],
      opts: 'mocha.opts',
      require: [require.resolve('./mocha-hook.js']
    }
  });
}
```

That should do the trick.

**Comment by prsn670** [comment]
Alright, I think we're almost there. I am getting a different error:

11:17:04 (7868) ERROR TestRunnerChildProcessAdapter Child process exited with non-zero exit code 1. Last 10 message from the child process were:

11:17:04 (7868) ERROR InitialTestExecutor One or more tests resulted in an error:
        TypeError: (0 , _mocha.describe) is not a function
TypeError: (0 , _mocha.describe) is not a function

I am using chai, enzyme, and sinon along with mocha if that makes a difference. I also need to add our dom.js file to the require tag under mochaOptions, but I'm unsure of the usage 'require.resolve'. Will I just need to add another require to the array and put in the corresponding path or does resolve take multiple strings as arguments?

**Comment by prsn670** [comment]
Unfortunately, adding the dom.js file to the require.resolve didn't have any impact. I'm still receiving the error of mocha.describe not being a function.

**Comment by prsn670** [comment]
Unfortunately adding the dom.js didn't resolve any issues. I'm still getting the same error for mocha.describe.

**Comment by nicojs** [comment]
Yes, they should make sure `describe` is on the global scope.

Hmm ok, time to pull out the big guns. Could you open up `/node_modules/stryker-mocha-runner/src/MochaTestRunner.js` and replace the `additionalRequires` function? Should be on line 109 to 113. Replace it with this:

```js
MochaTestRunner.prototype.additionalRequires = function () {
        var _this = this;
        if (this.mochaRunnerOptions.require) {
            var stuffToRequire = this.mochaRunnerOptions.require
                .map(function (theModule) { return theModule.startsWith('.') ? path.resolve(theModule) : theModule; });
            stuffToRequire.forEach(function (theModule) { return _this.log.info("Importing " + theModule); });
            stuffToRequire
                .forEach(LibWrapper_1.default.require);
        }
        else {
            this.log.info('Nothing to require');
        }
    };
```

That should make local requires possible (and add some logging). 

If you now remove the entire `require` from your `stryker.conf.js` file (but leave the `mochaOptions.opts` key in there), that would make sure that you're requiring the _local sandboxed_ files. That might do the trick.

If that doesn't work, would you mind creating a small reproduction repository? The smaller the better. If we could take a look, I'm sure we could figure it out.

**Comment by prsn670** [comment]
I'll see to creating a small repository that reproduces the problem (today). Unfortunately the replacement of the function did not help, I'm still getting the same error. I also added the ui tag and gave it 'bdd', but that didn't seem to help either. 

I also wanted some clarification on location of the config file. The readme says that it is expected to be the current working directory, but then goes on to say: 

"As you can see, the config file is not a simple JSON file. It should be a node module."

I have my config file in the root directory, just want to make sure this isn't an issue.

**Comment by nicojs** [comment]
> I have my config file in the root directory, just want to make sure this isn't an issue.

No, no issue there.

> I'll see to creating a small repository that reproduces the problem (today

Awesome! I'm sure we'll be able to fix this issue once we can reproduce it 👍

**Comment by prsn670** [comment]
So I figured out what was causing describe not be recognized as a function. I got the idea [here](https://stackoverflow.com/questions/47716547/typescript-mocha-describe-is-not-a-function). I simply had to remove my import statement for mocha and it started working. The weird thing is when I tried to reproduce the error on my computer with the import statements it would still work and give me no error. It may be some anomaly with the environment, there's a lot of code and environment setup that was done by other people. Thanks so much to everyone for your help.

**Comment by nicojs** [comment]
I would like to keep this issue open. I want to fix 3 things:

- [ ] use your mocha.opts file by default (if exists)
- [ ] Make sure relative imports when using `--require` (same as mocha does it)
- [ ] Make sure `const { describe } = require('mocha');` works as well.

**Comment by simondel** [comment]
@nicojs Shall we create an issue for the problems you mention?

**Comment by nicojs** [comment]
I was thinking to use this issue for them. Doesn't matter really.

**Comment by bharaninb** [comment]
Working on it
