### ISSUE TITLE
Support "presets" during `stryker init`

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#1049]
Running `stryker init` can be complicated. You get a number of questions that are pretty technical. People using angular or react might not even know what _test runner_ or _test framework_ they're using.

Therefore I propose one additional question:

* Choose a preset for your project:
  * Angular (uses angular cli)
  * React (uses react-scripts)
  * Custom (choose for yourself)

If you choose a preset, I would suggest one more question: the one about the package manager you want to use. After that, you're all set.

How do we want to implement presets? Right now, the answers to the questions are queried at run-time. I would like to maintain that flexibility, but forcing people to create npm packages for presets might be overkill. We could investigate using the git wiki for this and query that at run-time instead.

@stryker-mutator/contributors @JoshuaKGoldberg I'm curious to know what you guys think about this

**Comment by JoshuaKGoldberg** [comment]
This sounds nice!

> package manager

If there exists a `package-lock.json` or `yarn.lock`, we could auto-choose that option as a default for the non-custom ones.

**Comment by nicojs** [comment]
> If there exists a package-lock.json or yarn.lock, we could auto-choose that option as a default for the non-custom ones.

Well... maybe... but they might just as well be absent. It would also not surprise me if one or the other would support both in a short while. I wouldn't want to invest the time when it turns out that this functionality changes.

I've did a little digging around. It seems that you can get the raw *.md file from git wikis pretty easily by adding the `".md"` postfix. 

I've created this page: https://raw.githubusercontent.com/wiki/stryker-mutator/stryker/Configuration. We could access it during `stryker init` and use that to fill our "presets" list: https://raw.githubusercontent.com/wiki/stryker-mutator/stryker/Configuration.md

We could just split the content on h3s: `###`. A bit dirty, but it will do the trick.

What do you think @stryker-mutator/contributors ?

**Comment by simondel** [comment]
@JoshuaKGoldberg I discussed this with @nicojs and the Wiki does not sound like a good place to put documentation if we want others to contribute.

What we propose is the following: have a separate repo with documentation for stryker (and stryker scala, stryker.net etc.). This documentation can include example configurations for different types of projects. We can link to that repo from our website and from the wiki to get people to read it. This is quite similar to the way TypeScript does it with their [TypeScript-handbook](https://github.com/microsoft/typescript-handbook).

We hope that this will make it easier for users to get up-and-running using stryker.

**Comment by nicojs** [comment]
I don't feel like we should do live queries to the stryker-handbook anymore. It is too error prone:

* Configuration on the https://github.com/stryker-mutator/stryker-handbook can be out sync with your installed version of Stryker
* Editing the stryker handbook can result in error in `stryker init` configuration. This is undesirable.

Let's just program them right into the stryker main package. That way it's easier to understand, although we need to except _some_ duplication.

@stryker-mutator/contributors do you agree?

**Comment by simondel** [comment]
Adding a mention to the handbook in the generated stryker.conf.js would be nice so you have a reference to documentation.

**Comment by nicojs** [comment]
Definitely. Thanks!
