### ISSUE TITLE
Inconsistency with object keys

### ISSUE THREAD

**Issue by andy128k** [stryker-mutator/stryker#1057]
Semantically `{ "key": "value" }` and `{ key: "value" }` are the same, but Stryker creates 2 mutants for former and only one for latter.

So it is possible to hide uncovered code (bug?) from Stryker just by removing quotes.

**Comment by nicojs** [comment]
Hmm good catch. I think this is just an oversight. @simondel, I think this mutant is a false positive, right?

**Comment by simondel** [comment]
What we need to check here is if the parent of the `StringLiteral` node is a `PropertyAssignment` and the current node is the `name` property of that parent. (Names of types/properties may differ between Babylon and TypeScript.

We should add this to the mutator specification so both mutators have to comply with it.

@andy128k Would you be interested in making this change? We can help to guide you to the right places if you want to pick it up.

**Comment by nicojs** [comment]
Sounds good. Don't forget:

```js
{ ["key"]: "value" }
```

Let's make sure the following keeps working though:

```
var a = 3;
{ ["key" + a]: "othervalue" }
{ [`test${a}`]: "othervalue" }
```

**Comment by roelandvanbatenburg** [comment]
This is resolved and can be closed.

**Comment by nicojs** [comment]
Thanks @roelandvanbatenburg
