### ISSUE TITLE
Build: use typescript 3 project references

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#1058]
Using typescript 3's project references could mean a big quality of life improved for us. Goals:

- Smaller build time
- Not able to use things like `describe` in production code anymore

Bear minimum example: https://github.com/RyanCavanaugh/learn-a?files=1
Ts 3 changeling: https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/

**Comment by simondel** [comment]
We've given this the Pesto label, but we suggest fixing some other typescript related issues in Stryker first to get to know the workflow of working with a mono repo with typescript.

**Comment by simondel** [comment]
@nicojs Can this be closed?

**Comment by simondel** [comment]
Yes, we have this.
