### ISSUE TITLE
Adopt the Just World License

### ISSUE THREAD

**Issue by jeznag** [stryker-mutator/stryker#1061]
I would love to see Stryker adopt the Just World License: https://github.com/raisely/jwl

See https://medium.com/@jeremynagel/is-open-source-working-for-the-enemy-80f113ca1b0 for rationale.

**Comment by nicojs** [comment]
Wow, awesome initiative. I'm definitely going to discus this with our company. 

A question. If the build is taking 4 hours longer because of Stryker, which means the server is consuming more power, which means that the power plant is burning more coal considered "environmental destruction" according to the license? 

Another question: is it ethical to use JWL software if you're working for an oil company for example?

**Comment by Archcry** [comment]
> Another question: is it ethical to use JWL software if you're working for an oil company for example?

If [this](https://github.com/raisely/jwl/pull/13) pull request is approved then it's definitely not.

If we were to adapt this license we would lose some of the apache-2.0 license goodies. Also, how many changes to the license can we expect in the near future the license becomes more popular and gets more pull-requests?

**Comment by chrisjensen** [comment]
Thanks guys for considering the license. We'll lock down a 0.1 of the license as it is now so you can have some stability, and work towards a 1.0.

In terms of what it ideologically encompasses, it's pretty stable barraing someone bringing up a glaring omission. I'd welcome any input on things we can do to make our standpoint clearer.

Can I check what apache-2.0 aspects you'd miss?

**Comment by chrisjensen** [comment]
I've frozen an [initial release](https://github.com/raisely/NoHarm/tree/v0.1) at if you're keen to use this now

**Comment by simondel** [comment]
The Open Source Consortium has a baseline definition for licenses for open source software.

Two of these criteria conflict with the JtW license because they are about descrimination:
```
5. No Discrimination Against Persons or Groups
The license must not discriminate against any person or group of persons.

6. No Discrimination Against Fields of Endeavor
The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.
```
Source: https://opensource.org/osd-annotated

Because of this, I don't think we should adopt the JtW license.

**Comment by simondel** [comment]
I've discussed this with @nicojs and we're not adopting the license for now.
