### ISSUE TITLE
Support git submodules

### ISSUE THREAD

**Issue by blabno** [stryker-mutator/stryker#1072]
If I don't specify `files` inside `stryker.conf.js` then by default `git ls-files --others --exclude-standard --cached --exclude .stryker-tmp` is used. 

The problem appears when repo has git submodules, as those are included by the command above.
Then stryker tries to copy such folder as if it was a file which ends up in cryptic error:

> ERROR StrykerCli an error occurred { Error: EISDIR: illegal operation on a directory, read errno: -21, code: 'EISDIR', syscall: 'read' }
 
There is a silent assumption in `InputFileResolver` that the git command returns only files.

Solution could be either to add `--recurse-submodules` to the git command, but it conflicts with `--others`

> fatal: ls-files --recurse-submodules unsupported mode

Alternatively `InputFileResolver` should filter out entries returned by current version of git command, to exclude directories.

**Comment by nicojs** [comment]
Thanks for the great bugreport @blabno. Would it be safe to ignore directories? Or are they needed to run your tests? 

As a workaround for now you could define files yourself.

**Comment by blabno** [comment]
In my case, I don't need submodule for running unit tests, thus for stryker, so for me it would be safe to ignore directory if it happens to be on the list returned by `git ls-files`.

**Comment by nicojs** [comment]
Let's go with the excluding of directories.

**Comment by alexvictoor** [comment]
I ran into the same issue. I am pretty eager to try the fix on my day job project, hope the next release will come soon :)

**Comment by simondel** [comment]
Hi @alexvictoor I just started a release :) Hope this fixes it for you!
