### ISSUE TITLE
Rename 'project' config key to 'projectType'

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#1076]
As mentioned by @nrg500 in https://github.com/stryker-mutator/stryker-handbook/pull/2 the config setting `'project'` in the stryker-karma-runner and stryker-jest-runner can be quite confusing because your project name could be a valid value. A name such as `'projectType'` would probably result in less confusion about the intended use of the property.

**Suggestion:** 
Add a property `'projectType'` and make it the default property to use. 
If a user still uses `'project'`, then the value should be moved to the `'projectType'` property and a deprecation warning should be logged.
The projectType `default` should be renamed to `custom` for the jest-runner. There should be a deprecation warning if the user has manually set the projectType to `default`

The stryker-jest-runner and stryker-karma-runner packages are affected by this. 
It's important to take into account that the [initStrykerConfig](https://github.com/stryker-mutator/stryker/blob/master/packages/stryker-karma-runner/package.json#L55) in the package.json of the two packages may be setting the `project` property. This should be changed to `projectType` if it is present.
When we merge a pull request that resolves this, we should also update the [stryker handbook](https://github.com/stryker-mutator/stryker-handbook)

**Comment by simondel** [comment]
Nice catch! I have updated the main post.

**Comment by nicojs** [comment]
While you're at it, please update the name of `default` to `custom` in the jest-runner. It doesn't make sense to say a `projectType` is `default` imo

**Comment by kmdrGroch** [comment]
@simondel, @nicojs I think it can be closed.

**Comment by nicojs** [comment]
Closed via #1107 thanks again @kmdrGroch  👍
