### ISSUE TITLE
Struggling to Setup Stryker

### ISSUE THREAD

**Issue by takuhii** [stryker-mutator/stryker#1083]
I have followed your instructions pretty much to the letter, but I cannot get Stryker to work... I have managed to get it to this point;

```
$ stryker run
11:00:04 (50347) INFO ConfigReader Using stryker.conf.js in the current working directory.
11:00:07 (50347) INFO InputFileResolver Found 250 of 250 file(s) to be mutated.
11:00:07 (50347) INFO InitialTestExecutor Starting initial test run. This may take a while.
11:02:14 (50347) WARN InitialTestExecutor No tests were executed. Stryker will exit prematurely. Please check your configuration.
11:02:16 (50347) INFO Stryker 12701 Mutant(s) generated
11:02:16 (50347) WARN MutantTestMatcher No coverage result found, even though coverageAnalysis is "perTest". Assuming that all tests cover each mutant. This might have a big impact on the performance.
```
My stryker.conf.js looks like this;

```
module.exports = function(config) {
    config.set({
        plugins: ['stryker-html-reporter', 'stryker-karma-runner', 'stryker-jasmine', 'stryker-javascript-mutator'],
        mutate: ['common/javascript/app/**/*.js'],
        files: ['common/javascript/app/**/*.js'],
        mutator: 'javascript',
        packageManager: 'npm',
        testRunner: 'karma',
        testFramework: 'jasmine',
        coverageAnalysis: 'perTest',
        reporter: ['html', 'clear-text', 'progress']
    });
};
```
Any help would be greatly appreciated

**Comment by simondel** [comment]
Thanks for opening this issue! What kind of project am I looking at? 
I would recommend removing the `plugins` section of the config as it's not required in your case.
Are you using git? If that's the case then I would also remove the `files` option in your config. If you aren't using git. Please add all files you need in your project (sources, tests, karma config etc.) to the files array.

**Comment by kmdrGroch** [comment]
@takuhii you need to add karma config to it.

**Comment by takuhii** [comment]
It is a gulp build pipeline

**Comment by simondel** [comment]
Awesome, what does the logging say after you use the new stryker.conf.js?
Where in your repository is your karma.conf.js?

**Comment by takuhii** [comment]
Says exactly the same thing;
```
$ stryker run
14:43:23 (53292) INFO ConfigReader Using stryker.conf.js in the current working directory.
14:43:27 (53292) INFO InputFileResolver Found 250 of 2837 file(s) to be mutated.
14:43:27 (53292) INFO InitialTestExecutor Starting initial test run. This may take a while.
14:45:36 (53292) WARN InitialTestExecutor No tests were executed. Stryker will exit prematurely. Please check your configuration.
14:45:38 (53292) INFO Stryker 12701 Mutant(s) generated
14:45:38 (53292) WARN MutantTestMatcher No coverage result found, even though coverageAnalysis is "perTest". Assuming that all tests cover each mutant. This might have a big impact on the performance.
```

The stryker.conf.js sits here;
![screenshot 2018-08-15 at 17 11 26](https://user-images.githubusercontent.com/193907/44159161-7d324400-a0ae-11e8-9e86-eefa8ddd2d84.png)

**Comment by takuhii** [comment]
I would like to point out that the `common/javascript/app` folder contains the working JS, not the test files...the test files reside NEXT to the app folder;

```
Javascript
|
|- App
|- Test
|- ...
|- ...
```

**Comment by simondel** [comment]
Thanks for the info!
Could you add 
```js
"karma": {
      "project": "custom",
      "configFile": "karma.conf.js",
      "config": {}
    }
```
To the root of the config object? (Same level as the mutator and testFramework). The bit of config above is usually added by the `stryker init` command.

**Comment by simondel** [comment]
Hi @takuhii Did you happen to find some time to test stryker with the karma settings I metioned in the previous comment?

**Comment by takuhii** [comment]
Hi,
Sorry I was OoO yesterday and unable to test... I have made those amends and now have this in my stryker.conf.js;

```
module.exports = function(config) {
    config.set({
        mutate: ['common/javascript/app/**/*.js'],
        mutator: 'javascript',
        testRunner: 'karma',
        testFramework: 'jasmine',
        karma: {
            project: 'Custom',
            configFile: 'karma.conf.js',
            config: {}
        },
        coverageAnalysis: 'off',
        reporter: ['html', 'clear-text', 'progress']
    });
};
```
and now get this for every JS file;
```
Error: Script error for "pdp/controls/myJS", needed by: /base/common/javascript/spec/modules/pdp/controls/MyJSSpec.js
http://requirejs.org/docs/errors.html#scripterror
```
I think it is because we use RequireJS in this project, So I thought about adding 
`frameworks: ['require']`
to the config in stryker.conf.js?

**Comment by takuhii** [comment]
When I add
`framework: ['jasmine', 'requirejs']`

I get this in the terminal;
```
10:09:36 (11145) INFO ConfigReader Using stryker.conf.js in the current working directory.
10:09:44 (11145) INFO InputFileResolver Found 250 of 2837 file(s) to be mutated.
10:09:44 (11145) INFO InitialTestExecutor Starting initial test run. This may take a while.
10:09:52 (11147) INFO stryker-karma.conf.js Importing config from "/Users/xxxxxxx/Workspace/my-site-src/.stryker-tmp/sandbox9495949/karma.conf.js"
10:10:00 (11145) WARN InitialTestExecutor No tests were executed. Stryker will exit prematurely. Please check your configuration.
10:10:02 (11145) INFO Stryker 12701 Mutant(s) generated
```

My new stryker.conf.js looks like this;
```
module.exports = function(config) {
    config.set({
        mutate: ['common/javascript/app/**/*.js'],
        mutator: 'javascript',
        testRunner: 'karma',
        testFramework: 'jasmine',
        karma: {
            project: 'Custom',
            configFile: 'karma.conf.js',
            config: {
                frameworks: ['jasmine', 'requirejs']
            }
        },
        coverageAnalysis: 'off',
        reporter: ['html', 'clear-text', 'progress']
    });
};
```

**Comment by simondel** [comment]
Thanks for testing it! Could you add `fileLogLevel: 'trace'` to the root of the stryker config object? That will generate a log file. Could you send that with your karma.conf.js to simondelang@gmail.com? Feel free to obfuscate paths to files if that helps you :)

**Comment by takuhii** [comment]
I will do this ASAP ;) Sorry for the delay, weekend and all...

**Comment by takuhii** [comment]
Hi Simon, I have sent you an email

Kind regards
Darren

**Comment by simondel** [comment]
@takuhii Did you have time to look at my last mail? (mailed 2 september)

**Comment by simondel** [comment]
Since we haven't heard from you in a while, we're closing this issue for now.

If you need any help in the future, feel free to let us know!

**Comment by JimLynchCodes** [comment]
Hi @simondel, I'm finding stryker to be buggy as well.

It says, "no tests were executed" even though there are clearly unit tests there to be executed, and they get executed when I run karma normally... 😔
