### ISSUE TITLE
Docker + Stryker

### ISSUE THREAD

**Issue by rodoabad** [stryker-mutator/stryker#1085]
### Summary

Hey Nico, I have a test repository here with docker and I keep getting an error whenever I run my tests through docker.

I've posted the log below and was wondering if this is something you're familiar with.

I've added a link to my repo if you want to test it out yourself (I've updated the read me just in case).

```
docker-compose run dev npm run test
```

https://github.com/rodoabad/automatic-palm-tree

And then when you try and delete the directory, you cannot remove right away.

```
$ rm -rf .stryker-tmp/
rm: cannot remove '.stryker-tmp/sandbox7080524': Directory not empty
rm: cannot remove '.stryker-tmp/sandbox7263049': Directory not empty
```

### Stryker config

```js
module.exports = (config) => {
  config.set({
    babelrcFile: '.babelrc',
    coverageAnalysis: 'off',
    logLevel: 'warn',
    mutate: [
      'src/**/*.js',
      '!src/**/__tests__/**/*.js'
    ],
    mutator: 'javascript',
    packageManager: 'npm',
    reporter: [
      'clear-text',
      'dashboard',
      'progress'
    ],
    testRunner: 'jest',
    transpilers: ['babel']
  });
};

```

### Stryker environment

```
+-- stryker@0.25.1
+-- stryker-api@0.18.0
+-- stryker-babel-transpiler@0.6.0
+-- stryker-javascript-mutator@0.8.0
`-- stryker-jest-runner@1.0.0
```

```
+-- jest@23.4.2
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             |  8, 9, 10
| npm              |  6.2.0
| Operating System | Windows

### Add stryker.log

```
02:32:01 (127) INFO ConfigReader Using stryker.conf.js in the current working directory.
02:32:08 (127) WARN Sandbox Unexpected error while trying to symlink "/usr/src/app/node_modules" in sandbox directory. { [Error: EINVAL: invalid argument, symlink '/usr/src/app/node_modules' -> '/usr/src/app/.stryker-tmp/sandbox1119410/node_modules']
  errno: -22,
  code: 'EINVAL',
  syscall: 'symlink',
  path: '/usr/src/app/node_modules',
  dest: '/usr/src/app/.stryker-tmp/sandbox1119410/node_modules' }
Mutation testing  [==================================================] 100% (ETC 0.0s) 16/16 tested (0 survived)
```

**Comment by roelandvanbatenburg** [comment]
I suspect this has something to do with you using node_modules as an anonymous volume. Can you confirm that by temporarily removing that anonymous volume?

I have the node_modules inside my container and no issues.

**Comment by simondel** [comment]
Sorry for not responding to this! We're closing this issue for now as we've made a lot of changes recently. If the issue still appears in the latest version of Stryker, could you let us know?
