### ISSUE TITLE
Support for Jenkins

### ISSUE THREAD

**Issue by takuhii** [stryker-mutator/stryker#1093]
Would it be possible to support Jenkins CI with Stryker?

**Comment by simondel** [comment]
What kind of support are you looking for?

**Comment by takuhii** [comment]
Integration as with Travis and CircleCI

**Comment by takuhii** [comment]
I might also add, it is a private repo

**Comment by simondel** [comment]
> Integration as with Travis and CircleCI
What kind of integration do we have with Travis and CircleCI? For Travis we support the dashboard reporter but I don't think we do anything for CircleCI.

How would you expect to use Stryker in your Jenkins pipeline?

**Comment by nicojs** [comment]
Right now, we only support public repositories. We're planning to enable the full HTML report, so it doesn't really make sense to enable it for private repos.

Integration with Jenkins (public repo) should be rather straightforward. We just need environment variables which tell us:

1. the name of the repo,
2. Whether or not it is a PR
3. The branch name

See https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/src/reporters/ci/TravisProvider.ts for inspiration. 

We're happy to accept a PR

**Comment by takuhii** [comment]
I will wait for the FULL HTML Reporter ;) thank you for your time :)
