### ISSUE TITLE
Scan entire folder for Mutations except for one sub-folder?

### ISSUE THREAD

**Issue by takuhii** [stryker-mutator/stryker#1094]
How can I scan an entire directory as part of my mutation tests, but exclude one folder within said directory?

Basically I have a POLYFILLS directory within my JS folder. I want to scan the entire JS folder without scanning the polyfills folder, but I still NEED the polyfills folder as part of the testing...

```
JS < -- Scan this folder
|-AddToCart < -- Scan this folder
|-Checkout < -- Scan this folder
|-Polyfills < -- DO NOT scan this folder
|-AdWords < -- Scan this folder
```

**Comment by simondel** [comment]
Could you try:
```js
mutate: [
'JS/**/*.js',
'!JS/Polyfills/**/*.js'
]
```

**Comment by takuhii** [comment]
I could couldn't I. Sorry, completely missed that...
