### ISSUE TITLE
Stryker hangs in the middle of Angluar 6 tests 

### ISSUE THREAD

**Issue by blabno** [stryker-mutator/stryker#1096]
I've got standard Angular 6 project generated with `ng create`

First attempt to run `stryker run` told me to update `@angular/cli`, so I've run `ng update @angular/cli`.
But now tests hang somewhere between mutations.
Log file revealed that stryker was doing this mutation:
```
@Component({
  selector: 'dp-alert-modal',
  templateUrl: '',
  styleUrls: ['./alertModal.component.scss']
})
```
`templateUrl` got replaced with empty string which resulted in:
```
ERROR in ./src/app/common/alertModal.component.ts
Module not found: Error: Can't resolve './' in '.../src/app/common'
 @ ./src/app/common/alertModal.component.ts 41:22-35
 @ ./src/app/common/alertModal.service.unit-spec.ts
 @ ./src sync \.(unit-spec|integration-spec)\.ts$
 @ ./src/test-all.ts
```

**Comment by blabno** [comment]
Solution was to update `@angular-devkit/build-angular` as well.

    ng update @angular-devkit/build-angular

**Comment by nicojs** [comment]
Great you got it working. This is documented in the [handbook](http://github.com/stryker-mutator/Stryker-Handbook), however many people seems to run into this issue so I think a runtime check might be in order.

**Comment by simondel** [comment]
This is in the handbook *because* he ran into the issue :p

**Comment by nicojs** [comment]
Right, so now all info is in one place ✌️

**Comment by blabno** [comment]
You recommend there karma 2.0.4 but it causes false reports. When mutation causes compilation write it is reported as survived.

**Comment by simondel** [comment]
We're closing this issue for now as both Angular and Stryker have been updated quite a bit. If it's still a problem, let us know!
