### ISSUE TITLE
Support for 'perTest' coverage analysis for Mocha (client side)

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#11]
Browser based Mocha tests are not yet supported. This feature could use the Karma test runner. See #10 for server sided Mocha support

**Comment by simondel** [comment]
Existing projects such as [grunt-mocha](https://github.com/kmiyashiro/grunt-mocha), which uses PhantomJS, can be used as reference.
The Mocha API can also be viewed in the [Mocha source](https://github.com/mochajs/mocha/blob/master/lib/mocha.js#L51)

**Comment by nicojs** [comment]
I'm not sure about this issue. I think mocha is already supported as long as you use a test runner that supports the mocha framework. For example, you can use karma right now (of course at this moment without a `mochaTestSelector`). Unfortunately i don't believe, `grunt-mocha` is not a clean test runner. @simondel How would you go about supporting these kind of test runners?

**Comment by simondel** [comment]
We haven't done anything for this in two years so let's close it.

**Comment by nicojs** [comment]
I've done some work on this issue recently during the revamp of the mocha test framework. It might actually already work. I should be able to test it this week. Let's keep it open for now.

**Comment by simondel** [comment]
Great! I'll add a proper tag.
