### ISSUE TITLE
Launching Browser PhantomJS error in stryker run, Karma works

### ISSUE THREAD

**Issue by Chowarmaan** [stryker-mutator/stryker#1115]
### Summary
I have karma installed and configured to use Chrome and Chromium as the headless browser.  These work correctly and run the tests correctly.  PhantomJS is not listed in my karma configuration at all.

When running a test with Stryker, the PhantomJS browser fails to run.  As Stryker should be using my karma installation, not sure why I need to install and configure PhantomJS as well.

### Stryker config

```js
module.exports = function (config) {
	config.set({
	    coverageAnalysis: "perTest",	// "off",
		htmlReporter: {
			baseDir: 'coverage/mutation'
		},
	    karma: {
			projectType: "angular-cli",	// 'custom',
			configFile: "karma.conf.js",
			config: {}
	    },
		loglevel: "debug",
		mutate: [
			'src/**/*.ts',
			'!src/**/*.module.ts',
			'!src/**/*.spec.ts',
			'!src/environments/*.ts',
			'!src/polyfills.ts',
			'!src/main.ts'
		],
		mutator: {
			name: "typescript",
			excludedMutations: [ ]
		},
		packageManager: "npm",
		reporters: ["html", "progress"],		//  , "dashboard"
	    testFramework: "jasmine",
	    testRunner: "karma",		
    	transpilers: ["typescript"],
		tsconfigFile: "tsconfig.json"
	});
};
```

### Stryker environment

```
+-- stryker@0.29.1
+-- stryker-api@0.21.0
+-- stryker-cli@0.2.0
+-- stryker-html-reporter@0.16.1
+-- stryker-jasmine@0.10.1
+-- stryker-karma-runner@0.18.0
+-- stryker-typescript@0.13.2```
```

```
+-- @types/jasmine@2.8.8
+-- @types/jasminewd2@2.0.3
+-- jasmine-core@2.99.1
+-- jasmine-spec-reporter@4.2.1
+-- karma@3.0.0
+-- karma-chrome-launcher@2.2.0
+-- karma-coverage-istanbul-reporter@2.0.2
+-- karma-jasmine@1.1.2
+-- karma-jasmine-html-reporter@0.2.2
+-- stryker-karma-runner@0.18.0
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | 10.8.0
| npm              | 6.4.0
| Operating System | Windows 10 

### Add stryker.log

[stryker.log](https://github.com/stryker-mutator/stryker/files/2328731/stryker.log)
[karma.conf.txt](https://github.com/stryker-mutator/stryker/files/2328732/karma.conf.txt)

**Comment by kmdrGroch** [comment]
@Chowarmaan In stryker config make:
karma.config.browsers -> ["Chrome"] or [ "ChromeHeadless" ]
like:

```javascript
module.exports = config => {
    config.set({
        "coverageAnalysis": "perTest",
        "files": [
            path.join(basePath, "src/**/*.js"),
            path.join(basePath, "tests/**/*.js")
        ],
        "karma": {
            "config": {
                basePath,
                "logLevel": "debug",
                "browsers": [ "ChromeHeadless" ]
            },
            "configFile": "../../karma.conf.js",
            "project": "custom"
        },
        "mutate": [ path.join(basePath, "src/**/*.js") ],
        "mutator": "javascript",
        "packageManager": "npm",

        "reporter": [ "html", "clear-text" ],
        "testFramework": "jasmine",
        "testRunner": "karma"
    });
};```

**Comment by Chowarmaan** [comment]
Thank you. That was so obvious.  I can remove the PhantomJS install then, as the older outdated software fails on the basic Angular tests.

**Comment by kmdrGroch** [comment]
@Chowarmaan Can you share a log?

**Comment by Chowarmaan** [comment]
Actually, it is my Jest that is failing on the test with the basic
application.

**Comment by nicojs** [comment]
It isn't trivial to switch from karma to jest. For one: there is no browser in jest tests. What is your use case?

**Comment by Chowarmaan** [comment]
I was getting an error with embedded browser support, and thought it was
something similar to the karma test.  Once I transfered to jest my tests on
their own were not working, when I had the jest.config.js setting of
`testEnvironment: "node"` configured.  When I removed this, my jest tests
began to run properly again, and Stryker was also then able to get through
its test mutations.
