### ISSUE TITLE
New mutator: Error mutator

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1116]
We could add error mutator, so each Error / TypeError etc will be changed to `return` or empty Error

**Comment by nicojs** [comment]
Empty error is already tested with the `StringLiteral` mutator. Do we really need an additional `return` there? 

I would feel more for a "throw statement mutator". So `throw` is removed from code. @stryker-mutator/contributors do you agree?

**Comment by simondel** [comment]
I think this is fine as it is right now.
