### ISSUE TITLE
Add the ability to exclude files from being transpiled

### ISSUE THREAD

**Issue by severen** [stryker-mutator/stryker#1119]
I'm working on a [project](//github.com/severen/disposition) for loading configuration files that are written in TypeScript, which means that during its tests I want to test if it can correctly load configuration files from the disk. Unfortunately, since Stryker (seems to) transpile *every* TypeScript file in the project, [one of my tests](//github.com/severen/disposition/blob/master/test/disposition.test.ts#L60) fail, as it directly references a configuration file with its extension. On top of this, it subtlety messes with the other tests that implicitly load a TypeScript configuration file, which is bad.

So, based on the above, it would be useful if there was an option to exclude directories/files from being transpiled _or_ default to only transpiling the files that will be mutated.

**Comment by severen** [comment]
It's also worth noting that Stryker worked perfectly fine _until_ I decided to have it transpile my TypeScript files (which is useful for catching mutations via the type checker, if I understand how it works).

**Comment by nicojs** [comment]
@severen thanks for reporting this issue. 

Stryker should use your tsconfig file and only transpile those files that are also included in your typescript project. I think that when #1120 is solved, this issue should be solved as well, no?

> although in that case it makes me wonder why you wouldn't just run the type checker and not actually transpile anything

This is an excellent idea. We're thinking about as feature for Stryker vNext. It might make configuring Stryker easier. First want to get 1.0 out the door, then we will make a roadmap for this.

**Comment by severen** [comment]
Thanks for the quick response!

>Stryker should use your tsconfig file and only transpile those files that are also included in your typescript project. I think that when #1120 is solved, this issue should be solved as well, no?

Neat, I did not think of that. I believe this issue will be solved as well then in that case.

>This is an excellent idea. We're thinking about as feature for Stryker vNext. It might make configuring Stryker easier. First want to get 1.0 out the door, then we will make a roadmap for this.

Really pushing for some fully-integrated TypeScript support would be pretty nice, as well as a good selling point.

Also, I would like to say that aside from the issues I reported using Stryker has been a pleasure, and it worked perfectly out of the box (excluding my issues with transpilation afterwards). It's been a fun and enjoyable introduction to mutation testing.

**Comment by nicojs** [comment]
I'm closing this issue for now, since we're triaging this issue in #1120
