### ISSUE TITLE
Fails to run with TypeScript transpilation enabled and includes specified in tsconfig.json

### ISSUE THREAD

**Issue by severen** [stryker-mutator/stryker#1120]
### Summary

Stryker fails to run when I have transpilation enabled for TypeScript files _and_ the `include` field set in `tsconfig.json` (which is `"include": ["./src"]` in my case). It functions fine when I remove that (ignoring my issue in #1119).

### TypeScript Config

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "moduleResolution": "node",
    "lib": ["es2015", "es2016", "es2017"],
    "jsx": "react",
    "esModuleInterop": true,
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "typeRoots": ["./node_modules/@types", "./@types"]
  },
  "include": ["./src"]
}
```

### Stryker Config

```js
module.exports = (config) => {
  config.set({
    testRunner: 'jest',
    mutate: ['src/**/*.ts'],
    mutator: 'typescript',
    transpilers: ['typescript'],
    tsconfigFile: 'tsconfig.json',
    packageManager: 'yarn',
    // Currently does not work with Jest.
    coverageAnalysis: 'off',
    reporters: ['clear-text', 'progress', 'html'],
  });
};
```

### Stryker Environment

```
+-- stryker@0.29.1
+-- stryker-api@0.21.0
+-- stryker-jest-runner@1.2.0
+-- stryker-typescript@0.13.2
+-- jest@23.5.0
+-- typescript@3.0.3
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | 10.9.0
| yarn             | 1.9.4
| Operating System | Arch Linux (packages updated 2018-08-31)

### stryker.log

[stryker.log](https://github.com/stryker-mutator/stryker/files/2337231/stryker.log)

**Comment by severen** [comment]
Something else worth noting is that I am using Jest with ts-jest and have the following configuration:

```js
module.exports = {
  testEnvironment: 'node',

  transform: { '^.+\\.tsx?$': 'ts-jest' },
  testRegex: '(/__tests__/.*|\\.(test|spec))\\.(jsx?|tsx?)$',
  moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx', 'json', 'node'],

  globals: {
    'ts-jest': {
      'use-babelrc': true,
      enableTsDiagnostics: true,
    },
  },

  coverageThreshold: {
    global: {
      // branches: 90,
      functions: 95,
      lines: 95,
      statements: 95,
    },
  },
  coveragePathIgnorePatterns: ['/node_modules/', '/test/'],
};
```

I've also done some more investigation by poking around in the sandbox directory Stryker makes, and it seems that the TypeScript in my src directory is _already_ being transpiled by something else (ts-jest?) _before_ Stryker runs TypeScript on the code itself. So when TypeScript _does_ get to running on `./src`, it errors due to the fact that it cannot locate any TypeScript files to transpile. When I remove `"include": ["./src"]`, TypeScript defaults to compiling the entire project directory, which means it can successfully find *some* TypeScript files to transpile, albeit my tests and fixtures, which shouldn't be transpiled.

**Comment by Archcry** [comment]
Jest transpiles the typescript files, could you try running with the typescript compiler turned off?

**Comment by nicojs** [comment]
@severen Indeed you shouldn't need the typescript transpiler when using jest. Could you please try without it?

**Comment by simondel** [comment]
As mentioned you don't need the typescript transpiler. We're closing this issue for now. If it still persists with the latest version of Stryker, please let us know!
