### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1135]
I noticed that travis doesn't work when PR from branch other than ``master`` :/

**Comment by simondel** [comment]
Do you have an example?

**Comment by kmdrGroch** [comment]
you can see my PR @simondel https://github.com/stryker-mutator/stryker/pull/1134

**Comment by simondel** [comment]
I got no issue with#1136

**Comment by simondel** [comment]
Could you try to update your branch with a small change? You can revert it later but I think Travis just didn't trigger.

**Comment by kmdrGroch** [comment]
Sure @Simondel. I think I can find small place
