### ISSUE TITLE
grunt --force <task> gives error: unknown option --gruntfile

### ISSUE THREAD

**Issue by phazebroek** [stryker-mutator/stryker#114]
grunt <task> -- force does work, but with --force before the task it gives this error.
This is annoying because we want to use the Grunt run config from IntelliJ which puts the --force before the task. 

When running with --verbose the errors shows when parsing the files from Stryker and after I've removed Stryker I was able to run grunt --force <task> without any problems.

Using: Stryker 0.3.2, grunt 0.4.5, grunt-cli: 0.1.2 and node 6.0.0 with npm 3.8.6 (on windows)

**Comment by nicojs** [comment]
Thanks for your feedback!

This is probably a bug for `grunt-stryker` is it not? If so please close this one and move it to that repo.

I will take a look at it after the release of stryker 0.4.

**Comment by phazebroek** [comment]
I only removed stryker and the problem was "solved" so I highly suspect stryker instead of grunt-stryker...

**Comment by simondel** [comment]
Does this still happen?
