### ISSUE TITLE
Reduce amount of test helpers

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1146]
I noticed there are a lot of helpers / mocks. But there are being duplicated. We could reduce it's size by putting it in some other folder and importing from that 1.

**Comment by nicojs** [comment]
What do you suggest exactly? When it comes to tests, a bit of redundancy doesn't hurt. The most important thing is that the tests are easily to read and understand. I've made some

**Comment by kmdrGroch** [comment]
I'll see what I can do :)

**Comment by nicojs** [comment]
> Like `logMock` is presented in 10-12 places.
I would like to make 1 folder called `helpers` or `mocks`

I presume you mean that it is duplicated across multiple packages. That is true, and you're right those can be consolidated. Any ideas? The only thing I can think of is having a package called `test-helpers` and make that reusable across the packages.

**Comment by kmdrGroch** [comment]
Ohh it makes sense @nicojs. I haven't thought about it. Maybe package like you said or `stryker-testmocks` / `stryker-mocks` could be cool too.
