### ISSUE TITLE
Reduce size of Stryker

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1154]
We should look for unused packages, or try to replace some of them. Whole stryker - in dev form - weights 1.6GB. Thats really big.
I understand there are other dependencies which have other depe... etc... But still. 260000files and 1.6GB...

**Comment by simondel** [comment]
This is the distribution on my machine:
![image](https://user-images.githubusercontent.com/4221997/45920394-ac08ba80-bea3-11e8-967f-0c3921a1ba9f.png)

Could you try a fresh repo to see if you also end up with that size?

**Comment by simondel** [comment]
I created #1155 to remove two dependencies.

**Comment by kmdrGroch** [comment]
@simondel did you build too? or only `npm install` I was removing folder today and it said "1.6GB"

**Comment by simondel** [comment]
Yes, I did an `npm install` and an `npm test` (to ensure the integration tests also had their dependencies installed)

**Comment by kmdrGroch** [comment]
Well, ok. Strange then. But as you have already done, we can find and remove dependencies from integration tests (unused dependencies)
