### ISSUE TITLE
SwitchCase mutation mishandles empty fallthrough cases

### ISSUE THREAD

**Issue by CheshireSwift** [stryker-mutator/stryker#1156]
### Summary

When handling an empty fallthrough case, e.g.:

```js
switch (value) {
  case 'A':
  case 'B':
    ...
}
```

SwitchCase will raise an unchanged (thus unkillable) mutant which simply removes + readds the `case 'A'` (maybe changing the formatting slightly, but not the semantics).

### Stryker config

```js
module.exports = function(config) {
  config.set({
    mutator: "javascript",
    packageManager: "npm",
    reporters: ["clear-text", "progress"],
    testRunner: "jest",
    transpilers: [],
    coverageAnalysis: "off",
    mutate: ["src/**/*.js"]
  });
};
```

### Stryker environment

```
stryker@0.29.2
stryker-api@0.21.1
stryker-javascript-mutator@0.10.0
stryker-jest-runner@1.2.1
```

```
jest@23.6.0
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | multiple
| npm              | multiple
| Operating System | multiple

### Add stryker.log

[stryker.log](https://github.com/stryker-mutator/stryker/files/2408130/stryker.log)

Executable repro repo [here](https://github.com/CheshireSwift/stryker-switchcase-repro).

**Comment by nicojs** [comment]
Thanks for reporting. This is most definitely a bug. It is recently introduced as this is a new mutator. @tommilligan would you mind taking a look? Maybe if you have some time, fixing this issue? Thanks for any feedback you might have.

**Comment by tommilligan** [comment]
No problem, will put in a fix this evening. Thanks for letting me know

**Comment by kmdrGroch** [comment]
@nicojs I think it is ready to close

**Comment by Archcry** [comment]
Closing this issue, when you encounter further problems feel free to reopen.
