### ISSUE TITLE
Configure mocha timeout in package.json

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1157]
| Operating System | win10

So i managed to find that issue which is like always.

1) A babel project with the `only` option enabled
       should be able to transpile the input files:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\user\Desktop\stryker\packages\stryker-babel-transpiler\test\integration\BabelProjects.it.js)

It happens all the time in first test. After second one, it passes *WTF*

Honestly i dunno how to "recreate" that, since as i told, it happens only once, and then it works (i think after restarting PC it should happen again(?) [maybe some caching or coz I test it in VScode or not enough RAM(? 8GB)]

I found second one <3

1) CoverageInstrumenterTranspiler
       when coverage analysis is "all"
         should instrument code of mutated files:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\user\Desktop\stryker\packages\stryker\test\unit\transpiler\CoverageInstrumenterTranspilerSpec.js)

**Comment by nicojs** [comment]
OK, thanks for reporting. It might take some time, but I'll definitely take a look once I get some time.

**Comment by nicojs** [comment]
The test would probably be green the first time as well, if we upped the timeout. The failing tests need more timeout.

 It's difficult to choose correct timeouts at this moment. It is set from within the tests. I want to propose the following:

Remove all `this.timeout(xxxxx)` from code, instead using the [`--timeout` mocha option](https://mochajs.org/#usage). To do this, change up all `npm test` commands from this format: 

```json
    "test": "nyc --check-coverage --reporter=html --report-dir=reports/coverage --lines 80 --functions 80 --branches 75 mocha \"test/helpers/**/*.js\" \"test/unit/**/*.js\" \"test/integration/**/*.js\"",
```

```json
    "test": "nyc --check-coverage --reporter=html --report-dir=reports/coverage --lines 80 --functions 80 --branches 75 npm run mocha",
    "mocha": "mocha \"test/helpers/**/*.js\" \"test/unit/**/*.js\" && mocha --timeout 20000 \"test/helpers/**/*.js\" \"test/integration/**/*.js\"",
```

**Comment by simondel** [comment]
Just to clarify, this issue is about our own unit tests. We should improve those package.json scripts (and test files) with the fix that @nicojs is suggesting. This should probably be changed in all packages that we have.

**Comment by kmdrGroch** [comment]
yes @simondel I happens sometimes. Like first run after PC reboot

**Comment by bharaninb** [comment]
Working on it

**Comment by kmdrGroch** [comment]
![image](https://user-images.githubusercontent.com/28489774/49307286-f5ddd480-f4d4-11e8-88a5-7aeb9035f0c2.png)
The issue is still present. We should either increase this timeout or fix it other way

**Comment by nicojs** [comment]
Hmm.. it seems that `stryker-babel-transpiler` didn't get patched.  Let's reopen it and fix it.
