### ISSUE TITLE
Inform the user when no mutator plugin is specified

### ISSUE THREAD

**Issue by kgwebsites** [stryker-mutator/stryker#1161]
### Summary

The javascript mutator is not included with `stryker-api` or `stryker`, packages.

After configuring everything, I tried to run `./node_modules/.bin/stryker run` and got this error:
```

17:54:23 (93019) ERROR StrykerCli an error occurred Error: Could not find a mutant-generator with name javascript, did you install it correctly (for example: npm install --save-dev stryker-javascript)?
    at MutatorFactory.Factory.create (/Users/ME/Documents/Projects/thisproject/node_modules/stryker-api/src/core/Factory.js:43:19)
    at MutatorFacade.mutate (/Users/ME/Documents/Projects/thisproject/node_modules/stryker/src/MutatorFacade.js:12:14)
    at Stryker.mutate (/Users/ME/Documents/Projects/thisproject/node_modules/stryker/src/Stryker.js:89:34)
    at Stryker.<anonymous> (/Users/ME/Documents/Projects/thisproject/node_modules/stryker/src/Stryker.js:60:51)
    at step (/Users/ME/Documents/Projects/thisproject/node_modules/tslib/tslib.js:133:27)
    at Object.next (/Users/ME/Documents/Projects/thisproject/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/Users/ME/Documents/Projects/thisproject/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

The main issue is that the npm package `stryker-javascript` as defined in the error, does not exist. It should say `stryker-javascript-mutator`. Once I installed that package, it worked as expected.

### Stryker config

```js
module.exports = function(config) {
  config.set({
    testRunner: 'jest',
    mutator: 'javascript',
    coverageAnalysis: 'off',
    mutate: ['src/**/*.js*'],
  });
};
```

### Stryker environment
```
├─ stryker-api@0.21.1
├─ stryker-jest-runner@1.2.1
├─ stryker@0.29.2
```

### Jest Config
```
"jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,mjs}",
      "!src/__tests__/**",
      "!src/index.js"
    ],
    "coverageThreshold": {
      "global": {
        "branches": 98,
        "functions": 98,
        "lines": 98,
        "statements": 98
      }
    },
    "coverageReporters": [
      "text",
      "cobertura",
      "html"
    ],
    "reporters": [
      "default",
      "jest-junit"
    ],
    "setupFiles": [
      "<rootDir>/config/polyfills.js"
    ],
    "setupTestFrameworkScriptFile": "<rootDir>/config/setupTests.js",
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.(spec|test).{js,jsx,mjs}"
    ],
    "testEnvironment": "jsdom",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx|mjs)$": "babel-jest",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|mjs|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs)$"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web"
    },
    "testEnvironmentOptions": {
      "url": "http://test-fcl.company.com/"
    },
    "moduleFileExtensions": [
      "web.js",
      "js",
      "json",
      "web.jsx",
      "jsx",
      "node",
      "mjs"
    ]
  }
```

```
+-- jest@23.5.0
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | 8.11.4
| npm              | 5.6.0
| Operating System | 
macOS High Sierra @10.13.6

### Add stryker.log
Running stryker run takes over 18 hours.

**Comment by simondel** [comment]
Thanks for opening this issue! We expect that most users will setup Stryker using the `stryker init` command. That will most likely ensure that the correct mutator is installed.

As I read it now, you manually configured Stryker, is that correct? 

@nicojs how do you think we should handle this case? It may happen more after we remove the ES5 mutator with v1.0

**Comment by simondel** [comment]
I agree that we should have a check when there is no mutator specified and the stryker-javascript-mutator is not installed so we can throw a more helpful message.

**Comment by simondel** [comment]
Let's change two things:
1. Add an info log message when no `mutator` property is specified by the user, informing you that we will fall back to the 'javascript' mutator.
2. Change the 'error' message when a mutator plugin cannot be found so it says:
_Could not find a mutant-generator with name javascript, did you install it correctly (for example: npm install --save-dev stryker-javascript-mutator)?_ for the javascript mutator. The current message says you have to install stryker-javascript while the package is called stryker-javascript-mutator

**Comment by bharaninb** [comment]
@simondel Currently when no `mutator` is specified, default mutator is `es5`
