### ISSUE TITLE
Stryker and BigInt notation

### ISSUE THREAD

**Issue by GeneralYouri** [stryker-mutator/stryker#1172]
### Summary

Stryker crashes while parsing BigInt notation, such as `4n`.

It looks like stryker-javascript-mutator uses Babel 6, while Babel 7 is required to support such BigInt notation (through @babel/plugin-syntax-bigint).

My project does contain the proper version of Babel, and the proper .babelrc file, but these are ignored. I also tried stryker-babel-transpiler as it lets me explicitly specify Babel as the transpiler, including linking towards my .babelrc file. However even this package, while it uses my .babelrc file, does not use my Babel installation, meaning it's trying to run Babel v6 with my Babel v7 config (which obviously fails).

This points to a bigger problem where Stryker can't apply its JS mutations without Babel, yet doesn't use the Project's own Babel and config, and doesn't provide the required hooks to properly configure Babel either. Essentially, any code that requires a different Babel version than is being used by the aforementioned packages, will simply crash Stryker.

### Stryker config

```js
module.exports = (config) => {
    config.set({
        mutate: ['src/**/solution.js'],
        testRunner: 'command',
        coverageAnalysis: 'off',
        mutator: 'javascript',
        transpilers: [],
        reporters: ['clear-text', 'progress'],
        packageManager: 'npm',
    });
};
```

### Stryker environment

```
+-- stryker@0.29.5
+-- stryker-api@0.21.2
+-- stryker-javascript-mutator@0.10.2
+-- stryker-jest-runner@1.2.2
```

```
+-- jest@23.5.0
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | 10.9.0
| npm              | 6.4.1
| Operating System | Windows 10

### Add stryker.log

[stryker.log](https://github.com/stryker-mutator/stryker/files/2447102/stryker.log)

**Comment by GeneralYouri** [comment]
I don't see the actual output in the log file, including the error being thrown, so I figured I'd post that here (the stack trace is omitted, it just lists a bunch of Babylon files).

17:58:10 (17192) INFO ConfigReader Using stryker.conf.js in the current working directory.
17:58:11 (17192) INFO InputFileResolver Found 29 of 202 file(s) to be mutated.
17:58:11 (17192) INFO InitialTestExecutor Starting initial test run. This may take a while.
17:58:45 (17192) INFO InitialTestExecutor Initial test run succeeded. Ran 1 tests in 34 seconds (net 33367 ms, overhead 2 ms).
17:58:45 (17192) ERROR StrykerCli an error occurred { SyntaxError: Identifier directly after number (8:53)

**Comment by simondel** [comment]
Thanks for letting us know! We use a submodule of Babel (Babylon, now @babel/parser). This submodule does not support the regular Babel config but instead requires its own config.

We have a branch open which migrates the stryker-javascript-mutator to @babel/parser and that _should_ fix your issue. While migrating I ran into an issue with migrating switch statements, which is why it's not patched yet.

When merging the new functionality, we should add the bigint plugin defined on the docs page: https://babeljs.io/docs/en/babel-parser#ecmascript-proposals-https-githubcom-babel-proposals

**Comment by GeneralYouri** [comment]
Oh that's good news, do you have any ETA on this migration?

Until that's done, I suppose there's no option other than avoidng those files?

**Comment by nicojs** [comment]
@simondel thanks for sharing.

I'm working on a solution using a decorator pattern-like thing. It looks like this:

```ts
interface NodeMutator {
  name: string;
  mutate(node: NodeWithParent): Mutant[];
}

abstract class AstNodeMutator implements NodeMutator {
  mutate(node: NodeWithParent): Mutant[] {
      // call this.mutateAstNode
      // translate the mutated nodes to mutants
  }
  abstract mutateAstNode(node: NodeWithParent): types.Node[];
}
```

Part of the `generateMutants` logic moves to the `AstNodeMutator`. The `CaseSwitchMutator` will be the only mutator to directly implement the `NodeMutator` interface.

I'll work on this more probably this evening.

**Comment by nicojs** [comment]
Wow, that was a lot simpler than expected. Didn't need any of that decorator stuff, as it turns out you simply _can generate code for a single case statement_. See PR #1175, should fix this issue.

**Comment by simondel** [comment]
Nice find! The docs still say you have to pass an AST instead of a Node so I didn't try that option.

**Comment by nicojs** [comment]
A single node is also an AST.

**Comment by simondel** [comment]
True, but the V6 generator crashed if you tried to give it a regular Node.

**Comment by nicojs** [comment]
Than I'm glad I didn't know that and tried it anyway :+1:
