### ISSUE TITLE
StringMutator replaces single quotes with double quotes

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [stryker-mutator/stryker#1177]
### Summary

```
Mutant survived!
C:\Code\robobar-example\src\success-component\success-component.js:12:21
Mutator: StringLiteral
-           templateUrl: '/src/success-component/success-component.html',
+           templateUrl: "",
```

I'd be surprised if this is actually an issue for anyone, but it'd be nice to use the source string's quotation style.

### Stryker config

From the robobar-example config:

```js
module.exports = function(config) {
  config.set({
    mutate: ["src/**/*.js"],
    mutator: "javascript",
    transpilers: [],
    reporters: ["clear-text"],
    testRunner: "karma",
    testFramework: "jasmine",
    coverageAnalysis: "perTest",
    maxConcurrentTestRunners: 4,
    karma: {
      configFile: "karma.conf.js"
    }
  });
};
```

### Stryker environment

```
    "stryker": "^0.29.2",
    "stryker-api": "^0.21.1",
    "stryker-html-reporter": "^0.16.2",
    "stryker-jasmine": "^0.10.2",
    "stryker-javascript-mutator": "^0.10.0",
    "stryker-karma-runner": "^0.18.1"
```

```
    "jasmine-core": "^3.2.1",
    "karma": "^3.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage": "^1.1.2",
    "karma-jasmine": "^1.1.2",
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             |  9.7.1
| npm              |  6.4.1
| Operating System |  Windows 10

### Add stryker.log

[stryker.log](https://github.com/stryker-mutator/stryker/files/2454483/stryker.log)

**Comment by nicojs** [comment]
Although I am sympathetic, I don't see an immediate solution. Maybe someone can take a look.

**Comment by simondel** [comment]
I've looked at this and I think it's more effort to fix it than the value it delivers when we fix it. I'm closing this issue for now. If it turns out this is a problem for people, we'll look at it! (Good to know that we have this issue at least!)
