### ISSUE TITLE
Test-runner-agnostic interface

### ISSUE THREAD

**Issue by KainHaart** [stryker-mutator/stryker#118]
Hello!
I've got an idea and I would like to know what do you think about it

Could stryker be (or support via config option) test-runner-agnostic?
I mean take only test command (like "npm test" script) and determine pass/failure by exit code?
It believe this common interface will make possible to run mutation testing with many test runners and test frameworks

**Comment by nicojs** [comment]
Hi @KainHaart, thanks for your request!

Your approach is simple. 
I think the [js-mutation-testing](https://github.com/paysdoc/js-mutation-testing) project is using your approach. But we think there are 2 major drawbacks with this. 

1. You will have to mutate the source files. If anything goes wrong (or you kill the run halfway) you'll have to manually rollback the changes. Also, you are mandatory not to touch your code for the time that Stryker is running. Of course you could warn people for the dangers and use git to rollback local changes, but we don't think its an elegant way.

2. With that approach, you cannot really scale up to multiple test runner instances. What we now do with Stryker is that we spin up multiple test runners in forked processes (right now, its the nr of processors you have, but we will add a config option this). This dramatically speeds up the amount of time it takes to run stryker. Although we still need to tweak it a little bit.

What we are doing with stryker right now, is make the test runner pluggable. From v0.4 onward (hopefully we can release this somewhere this week), we split off the karma plugin to its [separate repository](https://github.com/stryker-mutator/stryker-karma-runner). We'll also support the [mocha test runner](https://github.com/stryker-mutator/stryker-mocha-runner). What we also do is document what you should do to create your own implementation of the test runner. Its pretty simple, you'll only have to implement this method ` run(options: RunOptions): Promise<RunResult>;`. You can already see [what it looks like here](https://github.com/stryker-mutator/stryker-api/blob/master/src/test_runner/TestRunner.ts). 

@KainHaart what do you think of our plugin approach? I'm closing this issue for now, but please don't keep that from further discussing this topic.
