### ISSUE TITLE
Strict typedefing

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1191]
In TSlint there is an option to enforce using type definitions everywhere. Now the question is, do you want it, or should it be optional (like it is now).

https://palantir.github.io/tslint/rules/typedef/

for now I'm testing this setup:
```
"typedef": [
      true,
      "call-signature",
      "parameter",
      "arrow-parameter",
      "property-declaration",
      "variable-declaration",
      "member-variable-declaration",
      "object-destructuring",
      "array-destructuring"]
```
what are your opinions?

**Comment by nicojs** [comment]
My opinion is that we shouldn't enforce typedefs everywhere. For example:

```ts
const foo: string = 'bar';
```

I personally think this is very annoying to maintain. I would rather enable `strict` mode. With at least `noImplicitAny` to ensure we cannot do this:

```
function (foo /*forgetting typedef here!*/) {
}
```

@kmdrGroch could you come up with a few examples where you think explicit typedef would help code maintainability?

**Comment by kmdrGroch** [comment]
@nicojs I could try enforcing config to require type everywhere where it is necessary - and remove where it is "obvious-type" or sth like that

**Comment by kmdrGroch** [comment]
maintainability... it is rather for "everywhere is the same" since in some files you type everything, in other you don't.

**Comment by nicojs** [comment]
I think a lot of IDE's have the same kind of support. 

>  it is rather for "everywhere is the same" since in some files you type everything, 

I understand that this can be frustrating, I myself have also a bit of OCD-like symptoms. Is there a setting where we can enforce explicitly type return values of _public_ functions and _public_ attributes alone? I think there is value in explicitly typing public functions, as you don't want the return type to change without a developer wanting it to.

I wouldn't want to enforce explicit typing of private functions/variables.

**Comment by kmdrGroch** [comment]
@nicojs 
```
"call-signature" checks return type of functions.
"arrow-call-signature" checks return type of arrow functions.
"parameter" checks type specifier of function parameters for non-arrow functions.
"arrow-parameter" checks type specifier of function parameters for arrow functions.
"property-declaration" checks return types of interface properties.
"variable-declaration" checks non-binding variable declarations.
"member-variable-declaration" checks member variable declarations.
"object-destructuring" checks object destructuring declarations.
"array-destructuring" checks array destructuring declarations.
```
only settings like that
