### ISSUE TITLE
Wrong mutants + reports don't show replacement

### ISSUE THREAD

**Issue by goldbergyoni** [stryker-mutator/stryker#1193]
Thanks for this amazing framework!

Would like to have your help with the following - After running stryker successfully it tells me that some mutants survived but this seems to be wrong and the HTML reports don't show the replacements (See prtscn). Issue 1 - I don't think there are mutants (very simple code attached). Issue 2 - The reporter shows both survived and killed on the same location and doesn't specify replacements of survived mutants

Report image: https://user-images.githubusercontent.com/8571500/47085808-6af49380-d220-11e8-8b8e-21bfe68037d7.png

Config:
```
module.exports = config => {
  config.set({
    mutator: "javascript",
    packageManager: "npm",
    reporters: ["html", "progress"],
    testRunner: "jest",
    transpilers: [],
    coverageAnalysis: "off",
    mutate: ["./Test/order-service.js"]
  });
};
```

```
Stryker environment:
```
├─┬ stryker@0.30.0
│ ├── @stryker-mutator/util@0.0.1
├─┬ stryker-api@0.21.4
├─┬ stryker-html-reporter@0.16.5
│ ├── @stryker-mutator/util@0.0.1 deduped
├─┬ stryker-javascript-mutator@0.11.2
├─┬ stryker-jest-runner@1.2.4

```

Test runner: 
```
jest@23.6.0
│ └─┬ jest-cli@23.6.0
│   ├─┬ jest-changed-files@23.4.2
│   ├─┬ jest-config@23.6.0
│   │ ├─┬ babel-jest@23.6.0
│   │ │ └─┬ babel-preset-jest@23.2.0
│   │ │   ├── babel-plugin-jest-hoist@23.2.0
│   │ ├── jest-environment-jsdom@23.4.0 deduped
│   │ ├─┬ jest-environment-node@23.4.0
│   │ │ ├── jest-mock@23.2.0 deduped
│   │ │ └── jest-util@23.4.0 deduped
│   │ ├── jest-get-type@22.4.3 deduped
│   │ ├─┬ jest-jasmine2@23.6.0

Your Environment:

| software         | version(s)
| ---------------- | -------  
| node             | 10.11
| npm              | 6.4.1
| Operating System | Mac siera 

Test code:
```class OrderService {
  CalculatePrice(userType, productPrice, isOnSale) {
    if (userType === "premium") {
      return productPrice * 0.9;
    } else if (isOnSale) {
      return productPrice * 0.8;
    }

    return productPrice;
  }
}


it('Scenario - very broad and vague scenario. Expectation - hmm just pass maybe?', () => {
    const priceToTest = new OrderServiceUnderTest().CalculatePrice("premium", 100, true);
    expect(priceToTest).toBeLessThan(100);
  });

  it('Scenario - a premium user. Expectation - get the right discount', () => {
    const priceToTest = new OrderServiceUnderTest().CalculatePrice("premium", 100, false);
    expect(priceToTest).toEqual(90);
  });

  it.only('Scenario - a product on sale. Expectation - get the right discount', () => {
    const priceToTest = new OrderServiceUnderTest().CalculatePrice("regular", 100, true);
    expect(priceToTest).toEqual(80);
  });```

Log is attached

![image](https://user-images.githubusercontent.com/8571500/47085808-6af49380-d220-11e8-8b8e-21bfe68037d7.png)

[stryker.log](https://github.com/stryker-mutator/stryker/files/2487328/stryker.log)

**Comment by simondel** [comment]
Thanks for opening this issue!

Could you click on one of the numbers in the report? such as the green `1` just after the if-statement?
You should see something similar to this:
![image](https://user-images.githubusercontent.com/4221997/47086262-4b0da180-d219-11e8-9f59-e78b1daf59f8.png)
source: https://stryker-mutator.io/robobar-example/reports/mutation/html/services/OrderService.js.html

**Comment by nicojs** [comment]
I think @i0natan is referring to the table on the right side. I've noticed too that it doesn't always show the correct code. Weird. For example: mutant 8 in the table. 

However, as @simondel explains, clicking on the mutant works well. We should explain that better in the report. Also fix the issue with the table.

**Comment by simondel** [comment]
The table on the right has been removed for some time now. I'm closing this issue.
