### ISSUE TITLE
Block in execution of Stryker for AngularJS in docker container

### ISSUE THREAD

**Issue by f-arruza** [stryker-mutator/stryker#1202]
Hello, Can someone please help me with this topic?

I made the configuration of a Docker container that includes Stryker for Angular with the following definition in the DockerFile:
```ruby
FROM node:8.9.4

# install Chromebrowser
RUN \
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
  echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list && \
  apt-get update && \
  apt-get install -y dbus-x11 google-chrome-stable && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /app

ADD ./webapp/. /app

# Install app dependencies
RUN npm install

EXPOSE 8080
```
The source code of the application under test is in the **/webapp** folder, therefore, it is included in the container.
The container is constructed and executed from a docker-compose, with the following definition:
```ruby
version: '3'

services:
  stryker:
    build:
      context: ./dockerfiles/Stryker
      dockerfile: Dockerfile
    command: npm run stryker
```
In the execution of the container is presenting with inconvenience when defining as WORKDIR the folder of the sandbox, see next image.

![Screenshot](https://raw.githubusercontent.com/f-arruza/autotesting/master/images/auto_testing_tool/ejecucion_stryker.png)

At that point that blocked. Any idea what may be happening?

Thank you,

**Comment by simondel** [comment]
Thanks for opening an issue! Could you please post your karma.conf.js and stryker.conf.js?

Also, what did you set the `logLevel` property to? If it's not `"trace"` could you try running it with that?

**Comment by f-arruza** [comment]
Hello, I share the configuration files. Thank you very much for your answer.

[config.zip](https://github.com/stryker-mutator/stryker/files/2516495/config.zip)

**Comment by simondel** [comment]
Thanks for the info! Could you take a look inside the container when it's running? Is the node_modules folder symlinked correctly?

Could you also run it with `logLevel: 'trace'`? Perhaps you'll see some more output.

**Comment by f-arruza** [comment]
This is the error.
![captura de pantalla 2018-10-25 a la s 3 44 43 p m](https://user-images.githubusercontent.com/21024069/47529316-116a1580-d86d-11e8-82d8-6c7118c8fbd7.png)

**Comment by f-arruza** [comment]
The /node_modules folder is linked correctly.

![captura de pantalla 2018-10-25 a la s 3 48 10 p m](https://user-images.githubusercontent.com/21024069/47529559-cac8eb00-d86d-11e8-9931-7218bdae3247.png)

**Comment by f-arruza** [comment]
I changed the browser settings and it worked. Thanks for the help.
```ruby
       browsers: ['ChromeHeadlessNoSandbox'],
        customLaunchers: {
          ChromeHeadlessNoSandbox: {
            base: 'ChromeHeadless',
            flags: ['--no-sandbox']
          }
       },
```

![captura de pantalla 2018-10-25 a la s 8 04 51 p m](https://user-images.githubusercontent.com/21024069/47538565-b1399a80-d891-11e8-9534-edc99975f8d6.png)

**Comment by simondel** [comment]
Glad to hear that that helped!
