### ISSUE TITLE
Enable `noUnusedParameters` tsconfig option

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#1211]
Enable `noUnusedParameters` tsconfig option (in the root tsconfig.json file) and fix any build errors that come along.

Refactor tip: let's say you have this function:

```ts
function foo(bar: string, baz: number, qux: bool) {
   console.log(qux);
}
```

You can signal that you don't need the first 2 parameters by using `_`:

```ts
function foo(_: string, _1: number, qux: bool) {
   console.log(qux);
}
```

**Comment by lucaslago** [comment]
Taking a look into this :)

**Comment by simondel** [comment]
Awesome :) if you need some help, feel free to let us know!
