### ISSUE TITLE
Refactor readme layout of configuration options

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#1213]
The layout of the configuration options of our current main stryker package readme is old fashion. We already started using a new layout for the configuration options in the stryker-mocha-runner package. We should also use that for the stryker package.

For example:

this:

> #### Transpilers  
> **Config file:** `transpilers: '['typescript']'`  
> **Default value:** `[ ]`  
> **Mandatory**: no  
> **Description:**  
> With `transpilers` you configure which transpiler plugins should transpile the code before it's executed. This is an array where the transpilers are called in the other of the array. This defaults to an empty array meaning no transpilation will be done.  

Should become like:

> ### `transpilers  ` [`string[]`]
> 
> Default: `[]`
> 
> With `transpilers` you configure which transpiler plugins should transpile the code before it's executed. This is an array where the transpilers are called in the other of the array. This defaults to an empty array meaning no transpilation will be done.

**Comment by mattacus** [comment]
Working on it!
