### ISSUE TITLE
Inconsitency in testing

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1220]
While running code in travis, one test passed (node 6), while second didnt with error:
```
1) After running stryker on angular project
       should report 15% mutation score:
      AssertionError: expected 1 to equal 2
      + expected - actual
      -1
      +2
      
      at Object.<anonymous> (verify/verify.ts:14:32)
      at step (verify/verify.ts:32:23)
      at Object.next (verify/verify.ts:13:53)
      at fulfilled (verify/verify.ts:4:58)
```
details:
https://travis-ci.org/stryker-mutator/stryker/jobs/447486517

**Comment by kmdrGroch** [comment]
so should I do a small change in my PR to see if it fails again, or we assume it is working correctly since once of tests passed?

**Comment by nicojs** [comment]
I've restarted the build for node8. Should be green now.

Could we keep the discussion in this issue to the problem at hand? Communication about different PR's can be done in those PR's please 👍

**Comment by kmdrGroch** [comment]
@nicojs I posted it as an issue since it happened before as well. Wanted to point that out

**Comment by nicojs** [comment]
Integration tests have been consistent for some time now. Closing this issue. If the integration tests are unstable again, we can always reopen this one, or open a new issue.
