### ISSUE TITLE
Implement new naming of mutators

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#1257]
We've aligned on naming of the mutators here: https://github.com/stryker-mutator/stryker-handbook/issues/11

It would be awesome if we could implement this in Stryker.

**Comment by simondel** [comment]
@nicojs Would you like to do this for v1 as well?

**Comment by kmdrGroch** [comment]
Isn't it fixed by now?

**Comment by nicojs** [comment]
I don't think so, feel free to give it a shot, it should pretty straight forward

**Comment by simondel** [comment]
When implementing this, users that use the 'old' naming, should get a warning with a suggested fix.
Stryker should fix the config and continue working.

For example, the logging _may_ be:
```
WARNING: Deprecated mutation detected, please change the excludedMutation "BinaryOperator" to "ArithmeticOperator"
```
