### ISSUE TITLE
Sport a higher timeout setting when running tests in a cold Sandbox

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#1262]
### Summary

When running Stryker in an angular-cli project for example, you might get a lot of `timeout` mutants. The reason for this is that running tests in a cold sandbox (a sandbox that didn't run tests before) takes more time. Even though we measure test runner overhead during initial test run it still can result in an unexpected timeout when all sandboxes are starting in parallel.

### Suggestion

They idea for this feature is that we configure a higher timeout for cold sandboxes. I was thinking `timeoutMS * 2`. 

Another approach might be to allow for a slower ramp-up of Sandboxes. Making them not all start at the same time. But that would take a bit more time.

**Comment by simondel** [comment]
We start two sandboxes in parallel right now. I believe this fixes the issue. If that's not the case, we'll revisit this issue.
