### ISSUE TITLE
Stryker init stops after installing stryker

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#1268]
When executing `stryker init` I noticed that the init exits after installing Stryker, as if I pressed the `enter` button twice when installing:
![image](https://user-images.githubusercontent.com/4221997/49437044-ee5f4980-f7ba-11e8-85f8-340125cf961f.png)
If I run `stryker init` again, I get the questionnaire and I can select a preset.

**Comment by nicojs** [comment]
Yeah, noticed this as well... But I think it has to do with Stryker cli, right?

**Comment by simondel** [comment]
I can't reproduce this anymore so I assume it's been fixed 🎉

**Comment by kmdrGroch** [comment]
@nicojs, @simondel isn't a version from CLI a bit obsolete? I can read from the SS it has installed version 0.33.1 of stryker??

**Comment by simondel** [comment]
The screenshot is from December 2018, almost a year ago.

**Comment by kmdrGroch** [comment]
NVM @simondel xD I thought it is a fresh issue
