### ISSUE TITLE
Stryker does not support multiple projects in Angular 6

### ISSUE THREAD

**Issue by jameshmread** [stryker-mutator/stryker#1272]
### Summary

Creating a new angular 6 project with `ng new mutation-test`
Installing and running Stryker works fine here. However if you add a library with `ng generate library my-library` it breaks with the following error...
```
12:03:17 (11436) TRACE ChildProcessProxy Schema validation failed with the following errors:
  Data path ".progress" should be boolean.
```

### Stryker config

```js
module.exports = function(config){
  config.set({
    .mutate: [
      "src/**/*.ts",
      "!src/**/*.spec.ts",
      "!src/test.ts",
      "!src/environments/*.ts"
    ],
    mutator: "typescript",
    testRunner: "karma",
    karma: {
      configFile: "src/karma.conf.js",
      projectType: "angular-cli",
      config: {
        browsers: ["ChromeHeadless"]
      }
    },
    reporters: ["clear-text", "html"],
    maxConcurrentTestRunners: 4, // Recommended to use about half of your available cores when running stryker with angular.
    coverageAnalysis: "off",
    logLevel: 'trace'
  });
}
```

### Stryker environment

```
    "stryker": "^0.33.1",
    "stryker-api": "^0.22.0",
    "stryker-html-reporter": "^0.16.9",
    "stryker-karma-runner": "^0.21.1",
    "stryker-typescript": "^0.16.1",
```

```
{
  "name": "mutation",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.2.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0",
    "@angular-devkit/build-ng-packagr": "~0.8.0",
    "@angular/cli": "~6.2.5",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^4.1.0",
    "protractor": "~5.4.0",
    "stryker": "^0.33.1",
    "stryker-api": "^0.22.0",
    "stryker-html-reporter": "^0.16.9",
    "stryker-karma-runner": "^0.21.1",
    "stryker-typescript": "^0.16.1",
    "ts-node": "~7.0.0",
    "tsickle": ">=0.29.0",
    "tslib": "^1.9.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  }
}

```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | 8.11.0
| npm              | 5.6.0
| Operating System | Windows 10
| Angular-cli | 6.2.8

### Add stryker.log

PS C:\git\spikes\mutation> ./node_modules/.bin/stryker run
12:03:14 (11436) INFO ConfigReader Using stryker.conf.js in the current working directory.
12:03:14 (11436) DEBUG PluginLoader Loading stryker-* from C:\git\spikes\mutation\node_modules
12:03:14 (11436) DEBUG PluginLoader Loading plugins stryker-html-reporter (matched with expression stryker-*)
12:03:14 (11436) DEBUG PluginLoader Loading plugins stryker-karma-runner (matched with expression stryker-*)
12:03:14 (11436) DEBUG PluginLoader Loading plugins stryker-typescript (matched with expression stryker-*)
12:03:14 (11436) DEBUG PluginLoader Loading plugins stryker-html-reporter
12:03:14 (11436) DEBUG PluginLoader Loading plugins stryker-karma-runner
12:03:15 (11436) DEBUG PluginLoader Loading plugins stryker-typescript
12:03:15 (11436) DEBUG TypescriptConfigEditor No 'tsconfigFile' specified, not loading any config
12:03:15 (11436) DEBUG Stryker Using config: {"logLevel":"trace","fileLogLevel":"off","timeoutMS":5000,"timeoutFactor":1.5,"plugins":["stryker-*"],"port":9234,"reporter":[],"reporters":["clear-text","html"],"coverageAnalysis":"off","testRunner":"karma","mutator":"typescript","transpilers":[],"maxConcurrentTestRunners":4,"symlinkNodeModules":true,"thresholds":{"break":null,"high":80,"low":60},"allowConsoleColors":true,"mutate":["src/**/*.ts","!src/**/*.spec.ts","!src/test.ts","!src/environments/*.ts"],"karma":{"configFile":"src/karma.conf.js","projectType":"angular-cli","config":{"browsers":["ChromeHeadless"]}},"configFile":"stryker.conf.js"}
12:03:15 (11436) DEBUG TestFrameworkOrchestrator The `coverageAnalysis` setting is "off", not hooking into the test framework to achieve performance benefits.
12:03:15 (11436) INFO InputFileResolver Found 4 of 63 file(s) to be mutated.
12:03:15 (11436) DEBUG InputFileResolver All input files: [
  "C:\\git\\spikes\\mutation\\projects\\my-library\\karma.conf.js",
  "C:\\git\\spikes\\mutation\\projects\\my-library\\ng-package.json",
  "C:\\git\\spikes\\mutation\\projects\\my-library\\package.json",
  "C:\\git\\spikes\\mutation\\projects\\my-library\\src\\lib\\my-library.component.spec.ts",
  "C:\\git\\spikes\\mutation\\projects\\my-library\\src\\lib\\my-library.component.ts",
  "C:\\git\\spikes\\mutation\\projects\\my-library\\src\\lib\\my-library.module.ts",
  "C:\\git\\spikes\\mutation\\projects\\my-library\\src\\lib\\my-library.service.spec.ts",
  "C:\\git\\spikes\\mutation\\projects\\my-library\\src\\lib\\my-library.service.ts",
  "C:\\git\\spikes\\mutation\\projects\\my-library\\src\\public_api.ts",
  "C:\\git\\spikes\\mutation\\projects\\my-library\\src\\test.ts",
  "C:\\git\\spikes\\mutation\\projects\\my-library\\tsconfig.lib.json",
  "C:\\git\\spikes\\mutation\\projects\\my-library\\tsconfig.spec.json",
  "C:\\git\\spikes\\mutation\\projects\\my-library\\tslint.json",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\app.component.ts.html",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\index.html",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\strykerResources\\bootstrap\\css\\bootstrap-grid.css",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\strykerResources\\bootstrap\\css\\bootstrap-grid.min.css",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\strykerResources\\bootstrap\\css\\bootstrap-reboot.css",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\strykerResources\\bootstrap\\css\\bootstrap-reboot.min.css",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\strykerResources\\bootstrap\\css\\bootstrap.css",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\strykerResources\\bootstrap\\css\\bootstrap.min.css",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\strykerResources\\bootstrap\\js\\bootstrap.bundle.js",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\strykerResources\\bootstrap\\js\\bootstrap.bundle.min.js",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\strykerResources\\bootstrap\\js\\bootstrap.js",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\strykerResources\\bootstrap\\js\\bootstrap.min.js",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\strykerResources\\highlightjs\\styles\\default.css",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\strykerResources\\jquery\\dist\\jquery.slim.min.js",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\strykerResources\\popper.js\\dist\\umd\\popper.min.js",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\strykerResources\\stryker-80x80.png",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\strykerResources\\stryker.css",
  "C:\\git\\spikes\\mutation\\reports\\mutation\\html\\strykerResources\\stryker.js",
  "C:\\git\\spikes\\mutation\\stryker.conf.js",
  "C:\\git\\spikes\\mutation\\.editorconfig",
  "C:\\git\\spikes\\mutation\\.gitignore",
  "C:\\git\\spikes\\mutation\\README.md",
  "C:\\git\\spikes\\mutation\\angular.json",
  "C:\\git\\spikes\\mutation\\e2e\\protractor.conf.js",
  "C:\\git\\spikes\\mutation\\e2e\\src\\app.e2e-spec.ts",
  "C:\\git\\spikes\\mutation\\e2e\\src\\app.po.ts",
  "C:\\git\\spikes\\mutation\\e2e\\tsconfig.e2e.json",
  "C:\\git\\spikes\\mutation\\package-lock.json",
  "C:\\git\\spikes\\mutation\\package.json",
  "C:\\git\\spikes\\mutation\\src\\app\\app.component.css",
  "C:\\git\\spikes\\mutation\\src\\app\\app.component.html",
  "C:\\git\\spikes\\mutation\\src\\app\\app.component.spec.ts",
  "C:\\git\\spikes\\mutation\\src\\app\\app.component.ts",
  "C:\\git\\spikes\\mutation\\src\\app\\app.module.ts",
  "C:\\git\\spikes\\mutation\\src\\assets\\.gitkeep",
  "C:\\git\\spikes\\mutation\\src\\browserslist",
  "C:\\git\\spikes\\mutation\\src\\environments\\environment.prod.ts",
  "C:\\git\\spikes\\mutation\\src\\environments\\environment.ts",
  "C:\\git\\spikes\\mutation\\src\\favicon.ico",
  "C:\\git\\spikes\\mutation\\src\\index.html",
  "C:\\git\\spikes\\mutation\\src\\karma.conf.js",
  "C:\\git\\spikes\\mutation\\src\\main.ts",
  "C:\\git\\spikes\\mutation\\src\\polyfills.ts",
  "C:\\git\\spikes\\mutation\\src\\styles.css",
  "C:\\git\\spikes\\mutation\\src\\test.ts",
  "C:\\git\\spikes\\mutation\\src\\tsconfig.app.json",
  "C:\\git\\spikes\\mutation\\src\\tsconfig.spec.json",
  "C:\\git\\spikes\\mutation\\src\\tslint.json",
  "C:\\git\\spikes\\mutation\\tsconfig.json",
  "C:\\git\\spikes\\mutation\\tslint.json"
]
12:03:15 (11436) DEBUG InputFileResolver Files to mutate: [
  "C:\\git\\spikes\\mutation\\src\\app\\app.component.ts",
  "C:\\git\\spikes\\mutation\\src\\app\\app.module.ts",
  "C:\\git\\spikes\\mutation\\src\\main.ts",
  "C:\\git\\spikes\\mutation\\src\\polyfills.ts"
]
12:03:15 (11436) INFO InitialTestExecutor Starting initial test run. This may take a while.e a while.                                                                       tion\.stryker-tmp\sandbox8334458
12:03:15 (11436) DEBUG Sandbox Creating a sandbox for files in C:\git\spikes\mutation\.stryker-tmp\sandbox833445812:03:15 (11436) DEBUG Sandbox Creating test runner 0 using settings {port: 9234}
12:03:15 (11436) DEBUG ChildProcessProxy Starting **C:\git\spikes\mutation\node_modules\stryker\src\test-runner\ChildProcessTestRunnerWorker.js in child process 1724812:03:17 (11436) TRACE ChildProcessProxy Schema validation failed with the following errors:
  Data path ".progress" should be boolean.12:03:15 (17248) DEBUG PluginLoader Loading stryker-* from C:\git\spikes\mutation\node_modules **
12:03:15 (17248) DEBUG PluginLoader Loading plugins stryker-html-reporter (matched with expression stryker-*)12:03:15 (17248) DEBUG PluginLoader Loading plugins stryker-karma-runner (matched with expression stryker-*)
12:03:15 (17248) DEBUG PluginLoader Loading plugins stryker-typescript (matched with expression stryker-*)
12:03:15 (17248) DEBUG PluginLoader Loading plugins stryker-html-reporter
12:03:15 (17248) DEBUG PluginLoader Loading plugins stryker-karma-runner12:03:16 (17248) DEBUG PluginLoader Loading plugins stryker-typescript
12:03:16 (17248) DEBUG ChildProcessProxyWorker Changing current working directory for this process to C:\git\spikes\mutation\.stryker-tmp\sandbox8334458

After the above line, the process just hangs for 20+ mins

**Comment by nicojs** [comment]
I've tested it out and works fine for me. Closing this issue. If
