### ISSUE TITLE
Better warning

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1278]
![image](https://user-images.githubusercontent.com/28489774/50049707-8fb79b00-00eb-11e9-84fd-a5feab3f8a7e.png)
```js
module.exports = function (config) {
  config.set({
    tsconfigFile: 'tsconfig.json',
    mutator: 'typescript',
    testRunner: 'mocha',
    testFramework: 'mocha',
    mochaOptions: {
      asyncOnly: false,
      files: [ 'test/**/*.js' ],
      require: [],
      timeout: 3000,
      ui: 'bdd'
    }
  });
}```
That message should be more precise. Since you are like 'eee?? what the fuck am i supposed to do'

**Comment by nicojs** [comment]
Agreed. What error message would you prefer?

**Comment by kmdrGroch** [comment]
i think there was a problem that i had to download `stryker-mocha-framework`.
So something like `use npm install --save-dev stryker-mocha-framework`. Just the same kind of error like when you don't have `runner` (i guess)

**Comment by nicojs** [comment]
Yeah makes sense. Did you generate this stryker config with `stryker init`?

**Comment by kmdrGroch** [comment]
Nope. By hand. And then while running `stryker run` I got that error

**Comment by kmdrGroch** [comment]
> i think there was a problem that i had to download `stryker-mocha-framework`.
> So something like `use npm install --save-dev stryker-mocha-framework`. Just the same kind of error like when you don't have `runner` (i guess)

@nicojs :P
I am really bad at inventing names and error "quotes", so ^

**Comment by nicojs** [comment]
I don't want to put additional information about specific Stryker plugins in the Stryker core. Any other suggestions?
