### ISSUE TITLE
improve mutators logic(?)

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1282]
It is a bit conceptual topic, but I would really love to make stryker "think" a bit more.
I've got piece of code:
```js
const max = Math.max(a.comma, b.comma);
const min = Math.min(a.comma, b.comma);
if (a.comma >= b.comma) {
    a.number *= BigInt(10) ** BigInt(max - min);
  } else {
    b.number *= BigInt(10) ** BigInt(max - min);
  }
```
Stryker keeps saying `change >= to >, change > to >=`
Well, from logics point of view, there is no difference between `>=` and `>`. since when these values are equal, `max - min = 0` and so I do not change any variable at all. I hope you know what i mean.

There are dozen problems like this, like 'I could remove that line, but it optimizes code a bit'
Or `const c = a <= 0 ? -a : a`. (working on BigInts)
Honestly, I have no idea how it could be done, but it would be a huge improvement

**Comment by kmdrGroch** [comment]
Well, I will try to keep you up-to-date, since I'm working on a math project with a bunch of algorithms (everything can happen for Stryker ;P )

**Comment by kmdrGroch** [comment]
![image](https://user-images.githubusercontent.com/28489774/50224616-a0dc0280-039e-11e9-834a-07afd2fea0ef.png)
![image](https://user-images.githubusercontent.com/28489774/50224637-a89ba700-039e-11e9-9e17-60c67553afe7.png)
These are errors I have found

**Comment by kmdrGroch** [comment]
I was thinking a lot about it, and one solution could be to use sth like debugger to check for example variables if values are the same. Of course, it would dramatically decrease performance and tests speed but it would allow to analyze it really good (I guess). It could be separate mod in stryker or it could be switched on by for example /* stryker:analyze-next-function */ of /* stryker:analyze-file */

**Comment by kmdrGroch** [comment]
> Yeah that would be awesome indeed. This is called an "equivalent mutant". Finding them in code with certainty is literally impossible for a computer to do because of something called the _[halting problem](https://en.wikipedia.org/wiki/Halting_problem)_. Of course you could program/hard code a couple of those scenarios into the code, but I feel it would be hard to maintain and never cover the exact scenario a user might encounter.
> 
> Two things I would consider:
> 
> 1. Be able to mark a mutant as "equivalent", but this is far into the future.
> 2. Document equivalent mutants on [our handbook](https://github.com/stryker-mutator/stryker-handbook) and explain why we can't do much about it. Maybe link to this issue.

Since it is not fixable, I guess this issue can be closed

**Comment by nicojs** [comment]
Thanks @kmdrGroch , feel free to open a PR on our handbook to explain what it is and why we can't do anything about it (or choose to not do anything about it)

**Comment by kmdrGroch** [comment]
I can add a section 'equivalent mutants', describe it a bit and add these I have found

**Comment by nicojs** [comment]
That would be great! It will help others and give us something to point to if others find this issue.

**Comment by kmdrGroch** [comment]
Where exactly should i document this issue in handbook? I can't find the best matching place :/

**Comment by nicojs** [comment]
Just on the top level a document called "Equivalent mutants" would be great
