### ISSUE TITLE
Getting started manual results in errors

### ISSUE THREAD

**Issue by Kimpossibru** [stryker-mutator/stryker#129]
If I run this:
npm install stryker stryker-api --save-dev

And then this:
node node_modules/stryker/bin/stryker --help

I get this error:
module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\projects\mutant\node_modules\stryker\bin\stryker'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

This is because the bin map is missing.
If I clone the repository and run npm install && npm start I can use the application, but for first time users this isn't very user friendly.

**Comment by simondel** [comment]
We're about to release version 0.4 of Stryker. Unfortunately for you the README in this repository has already been changed for the release.

The [README on npmjs.com](https://www.npmjs.com/package/stryker) contains the setup information for Stryker 0.3.2 (latest release as of right now), so I would suggest using that one to setup Stryker.

If you run into any more issues, feel free to let us know!

_I'll close this issue once version 0.4 is out._

**Comment by simondel** [comment]
0.4 is out so I'm closing this issue :)
