### ISSUE TITLE
Rename "integrationTest" to "e2e"

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#1298]
Right now, we have 2 kinds of integration tests:

1. **Integration tests for a specific package.**
  These tests are located inside a specific package 'test' directory
2. **Overall integration tests.**
  These tests are located inside the "integrationTests" directory.

We should rename one of them, because this is quit confusing. I think renaming "integrationTest" to "e2e" will be the best solution, as that is what they are: we're testing Stryker end to end with different plugin configurations.

**Comment by kmdrGroch** [comment]
@nicojs these "global" integration tests should be `e2e` or these "local"
