### ISSUE TITLE
reduce `npm test` time

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1301]
We can shrink testing time by reducing `tslinting`
I noticed we are doing sth like:
- lint
- build
- lint
- build
....
- unit tests
- integration tests

We could do:
- lint all / throw error if exist /
- build
- tests

It will reduce development time, since sometimes there is small linting issue in last package, but you have to wait until everything before it is built

**Comment by kmdrGroch** [comment]
Also there should be 2 / 3 versions for testing -
- "full testing" just lint, build, test
- "screw lint", just ommit linting (well it is not nessesary since linting is pretty fast)
- "screw build", building is really slow (if you have to run it 10th time, you will notice it...). And just do tests

**Comment by nicojs** [comment]
The TS project references fixes a lot of these issues. It introduces 1 `tsc` command build (improvement of 2 minutes), as well as 1 tslint process.

The main `npm test` command takes a long time because it also runs the e2e tests. Not sure how we can improve performance there.

**Comment by kmdrGroch** [comment]
@nicojs I thought about sth like removing all `postbuild` commands from packages (lint commands), and instead of that put one for the whole project on the beginning. I could prepare some PR so you can see what I mean

**Comment by nicojs** [comment]
No need. The TS project references branch removed all `build` and `postbuild` steps from all packages. So it fixes this issue IMHO

**Comment by kmdrGroch** [comment]
Indeed
