### ISSUE TITLE
Remove "port" property from Stryker configuration

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#1304]
The "port" property in Stryker options is a remnant of the past. It is specific to the Karma test runner. Since then Karma supports automatic free port selection. This is also supported by Stryker since #1239 . I think it is time to remove the setting from the config options and `TestRunnerSettings`.

**Comment by kmdrGroch** [comment]
after you check my PR I can take this issue :) It looks easy

**Comment by nicojs** [comment]
Why do I need to check your PR? :) Just work on 2 at a time ☮️

**Comment by kmdrGroch** [comment]
honestly it is much harder than i expected. There are so many `ports` there that i dunno which i can remove which not O,o
