### ISSUE TITLE
TSlint new rules

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1307]
I was thinking of changing TSlint config from `recommended` to `all` and then just switch off rules we don't want. I will allow us to check rules faster (we don't need to go and look for rules we want in docs, just see it in action).

It will also help in some progression.

For now I would recommend adding:
- "ban-types": [true, ["String"], ["Number"], ["Boolean"]] - it will force us to use `string`, `number`, `boolean` instead of these
- "deprecation" - it finds deprecations in code `Deprecated APIs should be avoided, and usage updated.`
- "no-duplicate-imports" - we can combine some imports into one `Using a single import statement per module will make the code clearer because you can see everything being imported from that module on one line.`
- "no-empty" - empty classes, constructors `Empty blocks are often indicators of missing code.`
- "no-empty-interface" - remove empty interfaces `An empty interface is equivalent to its supertype (or {}).`
- "no-implicit-dependencies" - `Disallows importing modules that are not listed as dependency in the project’s package.json
Disallows importing transient dependencies and modules installed above your package’s root directory.`
- "no-non-null-assertion" <https://palantir.github.io/tslint/rules/no-non-null-assertion/>
- "no-unnecessary-class" - Disallows classes that are not strictly necessary.
- "no-unnecessary-qualifier" - Warns when a namespace qualifier (A.x) is unnecessary.
- "prefer-template" - <https://palantir.github.io/tslint/rules/prefer-template/>
- "strict-type-predicates" - <https://palantir.github.io/tslint/rules/strict-type-predicates/> we can find some issues in stryker coz of that (we can do separate issue for that too)
- "cyclomatic-complexity": [true, 30] - (there is no issue from that line, but it can prevent one in the future) - <https://palantir.github.io/tslint/rules/cyclomatic-complexity/>
- "member-access": [true, "check-accessor", "check-parameter-property"] - set `public`, `private` of `get`, `set` too, it makes code cleaner i guess
- <https://palantir.github.io/tslint/rules/no-inferrable-types/> - remove obvious types
- <https://palantir.github.io/tslint/rules/no-unnecessary-type-assertion/>
- "trailing-comma": [true, {"multiline": "never", "singleline": "never"}] - remove trailing comma, more consistent code
- <https://palantir.github.io/tslint/rules/whitespace/> - more consistent, readable code
- <https://palantir.github.io/tslint/rules/newline-before-return/> - readability
- <https://palantir.github.io/tslint/rules/no-irregular-whitespace/>
- <https://palantir.github.io/tslint/rules/no-redundant-jsdoc/> - Forbids JSDoc which duplicates TypeScript functionality.
- <https://palantir.github.io/tslint/rules/prefer-object-spread/> - `Object spread allows for better type checking and inference.`
- <https://palantir.github.io/tslint/rules/no-misused-new/>

+ what we have now

- order
<https://palantir.github.io/tslint/rules/member-ordering/>
import ordering
in-objects ordering
in-namespaces ordering
(couldn't find all of them)

Most of these rules will be super easy to implement since we might have no issue with that.
If you agree with sth like that I can make PR changing only TSlint config just from recommended to all (no changes on files)

**Comment by nicojs** [comment]
I agree with most rules. I'm a big fan of the cyclomatic complexity rule and stuff like `no-inferrable-types`. Also, stuff that can be fixed automatically seems like a good idea as well. 

The once I don't agree with:

* https://palantir.github.io/tslint/rules/newline-before-return/ - I don't see the point here. Maybe we can create a separate issue for it and a separate PR so we can really see the changes. 
* https://palantir.github.io/tslint/rules/member-ordering/ - I actually agree with the statement on the rule description page: 
  > A common opposite practice to `member-ordering` is to keep related groups of classes together.
  I also feel like a lot of ordering feels like 'pampering'. A developer that chooses a specific order can have some great reasons why. Forcing an ordering now also results in huge file changes and hard to track history (not the greatest reason not to do something, but if the code actually remains the same, I don't file like we should force it).

@kmdrGroch can you find yourself in my reasoning?

**Comment by kmdrGroch** [comment]
There is nothing to complain, as you are `member` and `owner` of this package. I am just giving you some idea about it. I also prepared PR with "reverse implementation" of tslint, you might want to take a look. Actually, we don't really need `member-ordering` but I think `newline-before-return` makes a difference in some "crowded" places, so you can really see where you return some value. But it is personal preference etc.

**Comment by nicojs** [comment]
> There is nothing to complain, as you are `member` and `owner` of this package. 

It's open source, so room for discussion 👍 

> I also prepared PR with "reverse implementation" of tslint,

Yeah, I've taken notice. You can use that branch to implement the rules that we agree on.

> I think `newline-before-return` makes a difference in some "crowded" places, so you can really see where you return some value

After we've implemented the rules that we agree on, you can do a PR specifically for this one rule. That way I can see what the differences are.

**Comment by kmdrGroch** [comment]
We could decide which of these highlighted by me you would like to have and we can make some issues. It will be easier to fix I guess, as long as you don't want me to make 6000changes PR
