### ISSUE TITLE
Stryker fails to run on an Angular 6 project which has a library.

### ISSUE THREAD

**Issue by jameshmread** [stryker-mutator/stryker#1311]
### Summary
Hello again, it seems to still not work with new versions (as of today).
Related to Issue #1272. Still the same issue.
Stryker fails to run on an Angular 6 project which has a library.

### How to recreate
Create a new cli project with `ng new mutation`
Add a library in the root dir of that project with `ng generate library my-lib`
Install local versions of Stryker `npm install --save-dev stryker stryker-api`
`./node_modules/.bin/stryker init`
select the `angular-cli` and `npm` options
`./node_modules/.bin/stryker run`

`14:53:14 (3220) TRACE ChildProcessProxy Schema validation failed with the following errors:
  Data path ".progress" should be boolean.`

### Stryker config

```js
module.exports = function(config) {
  config.set({
    mutate: [
      "src/**/*.ts",
      "!src/**/*.spec.ts",
      "!src/test.ts",
      "!src/environments/*.ts"
    ],
    mutator: "typescript",
    testRunner: "karma",
    karma: {
      configFile: "src/karma.conf.js",
      projectType: "angular-cli",
      config: {
        browsers: ["ChromeHeadless"]
      }
    },
    reporters: ["progress", "clear-text", "html"],
    maxConcurrentTestRunners: 4, // Recommended to use about half of your available cores when running stryker with angular.
    coverageAnalysis: "off"
  });
};
```

### Stryker environment

```
    "stryker": "^0.34.0",
    "stryker-api": "^0.23.0",
    "stryker-html-reporter": "^0.17.0",
    "stryker-karma-runner": "^0.23.0",
    "stryker-typescript": "^0.17.0",
```

```
"dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.2.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0",
    "@angular-devkit/build-ng-packagr": "~0.8.0",
    "@angular/cli": "~6.2.5",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^4.1.0",
    "protractor": "~5.4.0",
    "stryker": "^0.34.0",
    "stryker-api": "^0.23.0",
    "stryker-html-reporter": "^0.17.0",
    "stryker-karma-runner": "^0.23.0",
    "stryker-typescript": "^0.17.0",
    "ts-node": "~7.0.0",
    "tsickle": ">=0.29.0",
    "tslib": "^1.9.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  }
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             |  8.11.0
| npm              | 5.6.0
| Operating System | Win 10

### Add stryker.log

PS C:\git\spikes\mutation> ./node_modules/.bin/stryker run --logLevel trace
14:53:11 (3220) INFO ConfigReader Using stryker.conf.js in the current working directory.
14:53:11 (3220) DEBUG ConfigReader Loading config stryker.conf.js
14:53:11 (3220) DEBUG PluginLoader Loading stryker-* from C:\git\spikes\mutation\node_modules
14:53:11 (3220) DEBUG PluginLoader Loading plugins stryker-html-reporter (matched with expression stryker-*)
14:53:11 (3220) DEBUG PluginLoader Loading plugins stryker-karma-runner (matched with expression stryker-*)
14:53:11 (3220) DEBUG PluginLoader Loading plugins stryker-typescript (matched with expression stryker-*)
14:53:11 (3220) DEBUG PluginLoader Loading plugins stryker-html-reporter
14:53:12 (3220) DEBUG PluginLoader Loading plugins stryker-karma-runner
14:53:12 (3220) DEBUG PluginLoader Loading plugins stryker-typescript
14:53:12 (3220) DEBUG TypescriptConfigEditor No 'tsconfigFile' specified, not loading any config
14:53:12 (3220) DEBUG Stryker Using config: {"mutate":["src/**/*.ts","!src/**/*.spec.ts","!src/test.ts","!src/environments/*.ts"],"logLevel":"trace","fileLogLevel":"off","timeoutMS":5000,"timeoutFactor":1.5,"plugins":["stryker-*"],"port":9234,"reporter":[],"reporters":["
clear-text","html"],"coverageAnalysis":"off","testRunner":"karma","mutator":"typescript","transpilers":[],"maxConcurrentTestRunners":4,"symlinkNodeModules":true,"thresholds":{"break":null,"high":80,"low":60},"allowConsoleColors":true,"karma":{"configFile":"src/karma.conf
.js","projectType":"angular-cli","config":{"browsers":["ChromeHeadless"]}},"configFile":"stryker.conf.js"}
14:53:12 (3220) DEBUG TestFrameworkOrchestrator The `coverageAnalysis` setting is "off", not hooking into the test framework to achieve performance benefits.
14:53:12 (3220) INFO InputFileResolver Found 4 of 45 file(s) to be mutated.
14:53:12 (3220) DEBUG InputFileResolver All input files: [
  "C:\\git\\spikes\\mutation\\projects\\my-lib\\karma.conf.js",
  "C:\\git\\spikes\\mutation\\projects\\my-lib\\ng-package.json",
  "C:\\git\\spikes\\mutation\\projects\\my-lib\\package.json",
  "C:\\git\\spikes\\mutation\\projects\\my-lib\\src\\lib\\my-lib.component.spec.ts",
  "C:\\git\\spikes\\mutation\\projects\\my-lib\\src\\lib\\my-lib.component.ts",
  "C:\\git\\spikes\\mutation\\projects\\my-lib\\src\\lib\\my-lib.module.ts",
  "C:\\git\\spikes\\mutation\\projects\\my-lib\\src\\lib\\my-lib.service.spec.ts",
  "C:\\git\\spikes\\mutation\\projects\\my-lib\\src\\lib\\my-lib.service.ts",
  "C:\\git\\spikes\\mutation\\projects\\my-lib\\src\\public_api.ts",
  "C:\\git\\spikes\\mutation\\projects\\my-lib\\src\\test.ts",
  "C:\\git\\spikes\\mutation\\projects\\my-lib\\tsconfig.lib.json",
  "C:\\git\\spikes\\mutation\\projects\\my-lib\\tsconfig.spec.json",
  "C:\\git\\spikes\\mutation\\projects\\my-lib\\tslint.json",
  "C:\\git\\spikes\\mutation\\stryker.conf.js",
  "C:\\git\\spikes\\mutation\\.editorconfig",
  "C:\\git\\spikes\\mutation\\.gitignore",
  "C:\\git\\spikes\\mutation\\README.md",
  "C:\\git\\spikes\\mutation\\angular.json",
  "C:\\git\\spikes\\mutation\\e2e\\protractor.conf.js",
  "C:\\git\\spikes\\mutation\\e2e\\src\\app.e2e-spec.ts",
  "C:\\git\\spikes\\mutation\\e2e\\src\\app.po.ts",
  "C:\\git\\spikes\\mutation\\e2e\\tsconfig.e2e.json",
  "C:\\git\\spikes\\mutation\\package-lock.json",
  "C:\\git\\spikes\\mutation\\package.json",
  "C:\\git\\spikes\\mutation\\src\\app\\app.component.css",
  "C:\\git\\spikes\\mutation\\src\\app\\app.component.html",
  "C:\\git\\spikes\\mutation\\src\\app\\app.component.spec.ts",
  "C:\\git\\spikes\\mutation\\src\\app\\app.component.ts",
  "C:\\git\\spikes\\mutation\\src\\app\\app.module.ts",
  "C:\\git\\spikes\\mutation\\src\\assets\\.gitkeep",
  "C:\\git\\spikes\\mutation\\src\\browserslist",
  "C:\\git\\spikes\\mutation\\src\\environments\\environment.prod.ts",
  "C:\\git\\spikes\\mutation\\src\\environments\\environment.ts",
  "C:\\git\\spikes\\mutation\\src\\favicon.ico",
  "C:\\git\\spikes\\mutation\\src\\index.html",
  "C:\\git\\spikes\\mutation\\src\\karma.conf.js",
  "C:\\git\\spikes\\mutation\\src\\main.ts",
  "C:\\git\\spikes\\mutation\\src\\polyfills.ts",
  "C:\\git\\spikes\\mutation\\src\\styles.css",
  "C:\\git\\spikes\\mutation\\src\\test.ts",
  "C:\\git\\spikes\\mutation\\src\\tsconfig.app.json",
  "C:\\git\\spikes\\mutation\\src\\tsconfig.spec.json",
  "C:\\git\\spikes\\mutation\\src\\tslint.json",
  "C:\\git\\spikes\\mutation\\tsconfig.json",
  "C:\\git\\spikes\\mutation\\tslint.json"
]
14:53:12 (3220) DEBUG InputFileResolver Files to mutate: [
  "C:\\git\\spikes\\mutation\\src\\app\\app.component.ts",
  "C:\\git\\spikes\\mutation\\src\\app\\app.module.ts",
  "C:\\git\\spikes\\mutation\\src\\main.ts",
  "C:\\git\\spikes\\mutation\\src\\polyfills.ts"
]
14:53:12 (3220) INFO InitialTestExecutor Starting initial test run. This may take a while.
14:53:12 (3220) DEBUG Sandbox Creating a sandbox for files in C:\git\spikes\mutation\.stryker-tmp\sandbox8218056
14:53:12 (3220) DEBUG Sandbox Creating test runner 0 using settings {port: 9234}
14:53:12 (3220) DEBUG ChildProcessProxy Starting C:\git\spikes\mutation\node_modules\stryker\src\test-runner\ChildProcessTestRunnerWorker.js in child process 13452
14:53:14 (3220) TRACE ChildProcessProxy Schema validation failed with the following errors:
  Data path ".progress" should be boolean.

14:53:14 (3220) ERROR StrykerCli an error occurred Error: Error: `ng test` command failed with exit code 1. Please run with logLevel 'trace' to see the angular-cli console output (actual command was ng test --progress=false --karma-config=C:\git\spikes\mutation\node_modu
les\stryker-karma-runner\src\starters\stryker-karma.conf.js)
Error: `ng test` command failed with exit code 1. Please run with logLevel 'trace' to see the angular-cli console output (actual command was ng test --progress=false --karma-config=C:\git\spikes\mutation\node_modules\stryker-karma-runner\src\starters\stryker-karma.conf.j
s)
    at C:\git\spikes\mutation\node_modules\stryker-karma-runner\src\starters\angularStarter.js:44:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at ChildProcess.<anonymous> (C:\git\spikes\mutation\node_modules\stryker\src\child-proxy\ChildProcessProxy.js:108:69)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
You can drag and drop it here. -->

**Comment by nicojs** [comment]
Hi @jameshmread, sorry we didn't get back to you. Did you get it solved?

**Comment by InfoSec812** [comment]
I believe I am experiencing a similar problem. I will try to create a simple reproducer and post back here.
