### ISSUE TITLE
Use `oneFailurePerSpec` option in the stryker-jasmine-runner

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#1315]
When running our jasmine integration tests we see this deprecation warning:

> Setting throwOnExpectationFailure directly on Env is deprecated, please use the oneFailurePerSpec option in `configure`

We should address this.

**Comment by enyfour5** [comment]
Hi @nicojs is this issue beginner friendly? If so, I would like to help out. Can you please point me in the right direction as to where to find the specific issue and what needs to be done? I'm already reading your contribution guidelines so I can get started. Thanks!

**Comment by dhuang612** [comment]
Hi,

I would like to work on this

**Comment by simondel** [comment]
Hi @dhuang612, welcome! If you need any help, please let me or @nicojs know :)

**Comment by dhuang612** [comment]
created PR #1775

**Comment by dhuang612** [comment]
I updated my PR with some comments

**Comment by dhuang612** [comment]
someone else can take this over, thanks
