### ISSUE TITLE
problem while running tests in travis

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1318]
<https://travis-ci.com/kmdrGroch/BigMath/jobs/169979295>
While running same code on my local machine i have no issue, but on travis it says: 
```
ERROR InitialTestExecutor One or more tests resulted in an error:
	ReferenceError: config is not defined
ReferenceError: config is not defined
    at Object.<anonymous> (/home/travis/build/kmdrGroch/BigMath/.stryker-tmp/sandbox2332043/src/config.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/travis/build/kmdrGroch/BigMath/.stryker-tmp/sandbox2332043/src/util.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
13:36:42 (4437) ERROR StrykerCli an error occurred Error: Something went wrong in the initial test run
    at InitialTestExecutor.validateResult (/home/travis/build/kmdrGroch/BigMath/node_modules/stryker/src/process/InitialTestExecutor.js:125:15)
    at InitialTestExecutor.<anonymous> (/home/travis/build/kmdrGroch/BigMath/node_modules/stryker/src/process/InitialTestExecutor.js:45:30)
    at step (/home/travis/build/kmdrGroch/BigMath/node_modules/tslib/tslib.js:133:27)
    at Object.next (/home/travis/build/kmdrGroch/BigMath/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/home/travis/build/kmdrGroch/BigMath/node_modules/tslib/tslib.js:104:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
It is strange

packages:
```
    "stryker": "^0.34.0",
    "stryker-api": "^0.23.0",
    "stryker-html-reporter": "^0.17.0",
    "stryker-mocha-framework": "^0.14.0",
    "stryker-mocha-runner": "^0.16.0",
    "stryker-typescript": "^0.17.0",
```

**Comment by kmdrGroch** [comment]
Stryker has some real problem on travis, and i would be grateful if you come up with an idea, solution to it, or i will have to remove this package from the project. <https://travis-ci.com/kmdrGroch/BigMath/jobs/176948416>
apparently, it is looking for non-existing variables? how does it mutate files to create such an issue (it works on my local machine, that's the biggest problem)

**Comment by nicojs** [comment]
This is a very strange issue. I was able to reproduce it with big math on a Linux VM (any Linux VM seems to do the trick).

The bitOperations.js file gets transpiled to:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const util_1 = require("./util");
/**
 * bitwise <<
 */
exports.bitLeft = (a, b) => util_1.normalize(BigInt(util_1.stringify(a)) << BigInt(util_1.stringify(b)));
/**
 * bitwise >>
 */
exports.bitRight = (a, b) => util_1.normalize(BigInt(util_1.stringify(a)) >> BigInt(util_1.stringify(b)));
/**
 * bitwise &
 */
exports.bitAND = (a, b) => util_1.normalize(BigInt(util_1.stringify(a)) & BigInt(util_1.stringify(b)));
/**
 * bitwise |
 */
exports.bitOR = (a, b) => util_1.normalize(BigInt(util_1.stringify(a)) | BigInt(util_1.stringify(b)));
/**
 * bitwise ^
 */
exports.bitXOR = (a, b) => util_1.normalize(BigInt(util_1.stringify(a)) ^ BigInt(util_1.stringify(b)));
/**
 * bitwise ~
 */
exports.bitNOT = (a) => util_1.normalize(~BigInt(util_1.stringify(a)));
rations.js.map
```

The last line is the issue. There should be `//# sourceMappingURL=bitOperations.js.map` on that line, but apparently, that isn't the case. 

More investigation is needed...

**Comment by kmdrGroch** [comment]
@nicojs I guess it can be an issue Ill make a PR and try see if it works

**Comment by nicojs** [comment]
> And @nicojs if you say that it transpiles code that way on linux machines, that should be posted in Typescript issues.

My first thought was the typescript transpiler plugin in `@stryker-mutator/typescript` ;)

**Comment by nicojs** [comment]
So, I found out what the issue is. Our `typescript` transpiler (located in `@stryker-mutator/typescript`) receives both `bitOperations.ts` and `bitOperations.js` (because it was build earlier). It will pass through one of them, the other one it transpiles to js. The result is logged to debug:

```
< 10:12:46 (219) DEBUG InitialTestExecutor Transpiled files: [
...
<   "/mnt/c/y/github/kmdrGroch/BigMath/index.js",
<   "/mnt/c/y/github/kmdrGroch/BigMath/index.js",
<   "/mnt/c/y/github/kmdrGroch/BigMath/src/basic.js",
<   "/mnt/c/y/github/kmdrGroch/BigMath/src/bitOperations.d.ts",
<   "/mnt/c/y/github/kmdrGroch/BigMath/src/bitOperations.js",
<   "/mnt/c/y/github/kmdrGroch/BigMath/src/bitOperations.js",
<   "/mnt/c/y/github/kmdrGroch/BigMath/src/comparison.d.ts",
<   "/mnt/c/y/github/kmdrGroch/BigMath/src/comparison.js",
<   "/mnt/c/y/github/kmdrGroch/BigMath/src/comparison.js",
<   "/mnt/c/y/github/kmdrGroch/BigMath/src/constants.d.ts",
<   "/mnt/c/y/github/kmdrGroch/BigMath/src/constants.js",
...
```

So there are duplicate files there... shouldn't be the case. Stryker will write all files to the sandbox directory in parallel and the result on Linux is apparently a mangled file. Which kind of makes sense, because a process is allowed to write multiple times to the same file, but because of the async nature if NodeJS, it is done in parallel.

I'll be working on a fix in the typescript transpiler plugin. In the meantime, the workaround is to make sure you clean your output files before running Stryker.

@simondel I think every transpiler can have this problem. An easy (but API breaking) change would be to rewrite the files from being an array to being an object (the key is the filename). What do you think?

**Comment by kmdrGroch** [comment]
so i should run `clean && test && clean && stryker`?

**Comment by kmdrGroch** [comment]
@nicojs cleaning repo before running stryker actually did work. I can use stryker again :)
