### ISSUE TITLE
Use of .env/.env.test file

### ISSUE THREAD

**Issue by VincentLanglet** [stryker-mutator/stryker#1343]
### Summary

I'm using a react application from "Create react app", I have variable in .env file, called 'REACT_APP_SOMETHING. When i use jest, test pass.  When I use stryker, they don't. It seems like the .env.test and .env are not loaded because when I console.log the variable expected, it's undefined.

### Stryker config

```js
module.exports = function(config) {
  config.set({
    mutate: ['src/**/*.ts?(x)', '!src/**/index.ts?(x)', '!src/setupTests.ts', '!src/**/*.test.ts?(x)'],
    mutator: 'typescript',
    testRunner: 'jest',
    reporters: ['progress', 'clear-text', 'html'],
    coverageAnalysis: 'off',
    jest: {
      projectType: 'react',
    },
  });
};

```

### Stryker environment

```
    "stryker": "^0.34.0",
    "stryker-api": "^0.23.0",
    "stryker-html-reporter": "^0.17.0",
    "stryker-jest-runner": "^1.3.0",
    "stryker-typescript": "^0.17.0",
```

```
    "react-scripts": "^2.1.3",
```

**Comment by VincentLanglet** [comment]
`env-cmd .env.test stryker run` is a solution

**Comment by simondel** [comment]
Glad to hear that you've found a solution! I'm closing this issue for now.
