### ISSUE TITLE
Support react-scripts-ts?

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#1362]
It seems that react-scripts-ts is no longer needed for typescript enabled react applications. More info here: https://vincenttunru.com/migrate-create-react-app-typescript-to-create-react-app/

Running jest 24 results in a failing test on windows: 

```
  Integration test for Strykers Jest runner
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In C:\z\github\stryker-mutator\stryker\packages\stryker-jest-runner\testResources\reactTsProject
  9 files checked.
  testMatch: C:/z/github/stryker-mutator/stryker/packages/stryker-jest-runner/testResources/reactTsProject/src/**/__tests__/**/*.(j|t)s?(x),C:/z/github/stryker-mutator/stryker/packages/stryker-jest-runner/testResources/reactTsProject/src/**\?(*.)(spec|test).(j|t)s?(x) - 0 matches
  testPathIgnorePatterns: \\node_modules\\ - 9 matches
  testRegex:  - 9 matches
Pattern:  - 0 matches
```

I've created a small reproduction repo here: https://github.com/nicojs/jest-run-cli-windows

I have no clue why this happens, but this is the case since jest 24.

@mthmulders do you know what is the way to move forward here? Should we remove react-ts project type support? Or warn that it only works for 24? Is react-scripts-ts support being dropped in favor of react-scripts?

**Comment by simondel** [comment]
Since nothing has happened on this for about a year and no one has upvoted it. I'm closing this issue.
