### ISSUE TITLE
Remove reports folder from distribution

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#139]
Every distribution of Stryker includes the `reports` folder which contains 1004(!!!) files from the events reporter. The total size of the reports folder is 4.40MB while Stryker is 9.42MB in total, so the reports folder is **almost 50% of the size of Stryker**. Because of this, I think it's a good idea to remove the reports folder from the distribution and add a grunt task/npm script to generate them if someone wants them.

**Comment by nicojs** [comment]
... :astonished: of course the reports folder should never have been there.. :sweat:

Are you removing it? Or shall i? :+1:

**Comment by nicojs** [comment]
By removing i think you mean adding it to the `.npmignore` right? Well in that case: `stryker.conf.js`, `.bithoundrc`, `.tmp`, `.tscache`, `.vscode`, `.npmignore`, `.editorconfig`, thank you :+1:

**Comment by simondel** [comment]
What about the coverage folder?

**Comment by nicojs** [comment]
True, forgot that one. Too bad npm doesn't support a whitelist format.

**Comment by nicojs** [comment]
Thank you!
