### ISSUE TITLE
Support HTML files

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#14]
Projects which include HTML files (such as AngularJS projects) are not properly supported. Support for these projects has to be added. This feature could be tested on an AngularJS project to ensure it works.

**Comment by nicojs** [comment]
We should test this but i think its pretty much supported right now. We support custom karma config so anything you can put into that *should* be propagated to the testrunner processes.

**Comment by nicojs** [comment]
As polymer 3 is going to do the es modules route, i don't see any use cases for mutating html or javascript inside the html. Karma plugins are already supported. I think this issue can be closed.
