### ISSUE TITLE
Rename all test files to `*.spec.ts`

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#1408]
We should refactor all test files:

* Unit tests to `NameOfUnit.spec.ts`
* Integration tests to `TitleOfStuffToTest.it.spec.ts`. 

Naming files *.spec.ts will show them as test icon in vscode and is more of an industry standard 

![image](https://user-images.githubusercontent.com/1828233/52805109-2837b080-3086-11e9-999d-cbf9b6a039cd.png)

**Comment by kmdrGroch** [comment]
I can do it :D
