### ISSUE TITLE
HTML Reporter doesn't highlight in Chrome

### ISSUE THREAD

**Issue by jmpresso** [stryker-mutator/stryker#1427]
### Summary

@stryker-mutator/html-reporter generates HTML reports that highlight the code. It shows green crossed out lines for killed mutants, or red highlights with red boxes for line numbers around killed mutants.

This is working for me in IE11, but not on my version of Chrome.

It does not highlight in Chrome, or show the boxes with line numbers. It appears to flash briefly highlighting, but then goes away. I attempted to uncheck/check the various survived / killed checkboxes, but nothing happened.

I am using Chrome 68 (locked down at work). If it works for people in newer versions, then perhaps it's a non issue for most, but I'm not able to easily verify that currently.

### Stryker config

		mutator: 'javascript',
		testRunner: 'mocha',
		testFramework: 'mocha',
		coverageAnalysis: 'all',
		reporters: ['clear-text', 'html', 'event-recorder'],

### Stryker environment

		"@stryker-mutator/core": "1.0.2",
		"@stryker-mutator/html-reporter": "1.0.3",
		"@stryker-mutator/javascript-mutator": "1.0.2",
		"@stryker-mutator/mocha-runner": "1.0.2",
		"@stryker-mutator/mocha-framework": "1.0.2",
		"grunt-stryker": "1.0.1"

		"mocha": "5.2.0"

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             |  8.9.4
| npm              |  6.1.0
| Operating System | Win 10
| Chrome | 68

### Add stryker.log

Skipping this to avoid scrubbing, unless someone thinks it is relevant.

**Comment by nicojs** [comment]
Thanks for opening an issue! 

We're implementing a new version of the html reporter based on the web components specification [here](https://github.com/stryker-mutator/mutation-testing-elements). I think this issue should be solved once we're using that version.

Chrome 68 should be supported as well: https://caniuse.com/#search=web%20components

**Comment by nicojs** [comment]
Should be fixed since Stryker 1.2, if not comment here.
