### ISSUE TITLE
Problems with regular expressions in karma.webpack configuration

### ISSUE THREAD

**Issue by knegusen** [stryker-mutator/stryker#143]
First, I really like this project!

Second, i don't know if this should be posted here or in stryker-karma-runner.

Third, my issue is almost the same as this one, [karma-webpack issue](https://github.com/webpack/karma-webpack/issues/42)

The thing is that I can use it when I don't use babel-loader in my webpack configuration but when i use babel-loader I get this message:

```
[2016-08-15 17:01:40.857] [TRACE] IsolatedTestRunnerAdapter - webpack: bundle is now INVALID.

[2016-08-15 17:01:40.891] [TRACE] IsolatedTestRunnerAdapter - 15 08 2016 17:01:40.886:ERROR [karma]: [Error: [object Object] is not a valid test]
Error: [object Object] is not a valid test
    at asMatcher (/Users/axelsson/ProjectsWebstorm/stryker-test/node_modules/webpack/node_modules/webpack-core/lib/LoadersList.js:48:9)
    at LoadersList.matchPart (/Users/axelsson/ProjectsWebstorm/stryker-test/node_modules/webpack/node_modules/webpack-core/lib/LoadersList.js:65:16)
    at LoadersList.matchObject (/Users/axelsson/ProjectsWebstorm/stryker-test/node_modules/webpack/node_modules/webpack-core/lib/LoadersList.js:91:12)
    at LoadersList.<anonymous> (/Users/axelsson/ProjectsWebstorm/stryker-test/node_modules/webpack/node_modules/webpack-core/lib/LoadersList.js:78:12)
    at Array.map (native)
    at LoadersList.match (/Users/axelsson/ProjectsWebstorm/stryker-test/node_modules/webpack/node_modules/webpack-core/lib/LoadersList.js:71:19)
    at /Users/axelsson/ProjectsWebstorm/stryker-test/node_modules/webpack/lib/NormalModuleFactory.js:111:68
    at /Users/axelsson/ProjectsWebstorm/stryker-test/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /Users/axelsson/ProjectsWebstorm/stryker-test/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/axelsson/ProjectsWebstorm/stryker-test/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /Users/axelsson/ProjectsWebstorm/stryker-test/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/axelsson/ProjectsWebstorm/stryker-test/node_modules/webpack/node_modules/async/lib/async.js:723:17
    at /Users/axelsson/ProjectsWebstorm/stryker-test/node_modules/webpack/node_modules/async/lib/async.js:167:37
    at /Users/axelsson/ProjectsWebstorm/stryker-test/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:29:4
    at onResolved (/Users/axelsson/ProjectsWebstorm/stryker-test/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:39:10)
    at /Users/axelsson/ProjectsWebstorm/stryker-test/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:123:21
```

I don't know if it is the same as the one in the link above but it looks like it is a similar problem. Any suggestions? Have you managed to use webpack and any loader?

This [link](https://github.com/lazd/gulp-karma/issues/37#issuecomment-77195552) coulb also be helpful.

// Dennis

**Comment by nicojs** [comment]
@knegusen Thanks for your issue! I think you are right. We are running test runners in there own process. We are communicating with them through the standard node messaging mechanism. I can see that, if you pass a regex in the config of Stryker, it gets deserialized in the child process an empty object.

See [IsolatedTestRunnerAdapter line 137](https://github.com/stryker-mutator/stryker/blob/6c0e22960d7883e3f3f64f3aa8d75380207710be/src/isolated-runner/IsolatedTestRunnerAdapter.ts#L137)

I think the only way i can think of to solve this is using a custom serializer that supports Regex's. Does anyone know of a serializer for this? Or a better solution?

**Comment by nicojs** [comment]
@knegusen could you please see if #146 fixes your issue?

**Comment by knegusen** [comment]
Great work. It looks like it working now. Now my problem is that if I tell stryker to mutate a file, I think that stryker trying to mutate the not compiled version which does not recognise es6 code like export. It works with module.exports though. Any thoughts?

**Comment by knegusen** [comment]
Did some more investigations. It seems like the problem with es6 and exports are similar as in [this issue](https://github.com/stryker-mutator/stryker/issues/133).
If I add `sourceType: 'module'` to `esprimaOptions` it works. 
Then I get another error though, `:ERROR [preprocessor.coverage]: Line 10: Unexpected token` but stryker does continue and makes mutations and runs the tests correct as it did when I had `module.exports` instead of `export`.
It feels like the `preprocessor.coverage` error is more like a warning.

**Comment by nicojs** [comment]
We just did a new release with the fix in it, can this bug be closed?

Yes i think it is the same problem as #133 . Could you please add your wishes to that issue? We want to solve it but are not sure how just yet.

Stryker will use code coverage results if it can. If not, it just runs all your tests for all mutants, as it cannot determine which to run. In a small project, there is not much difference. In bigger once it can be a huge time loss. The mechanism to determine code coverage used in 0.4.x is karma-coverage with the preprocessor, that's why you see the warning. This will change in 0.5.0 where we do our own instrumentation. We will also provide you with an option to disable code coverage analysis, so you won't see the error/warning if your using new code constructs which are not yet supported by the code coverage engine ([istanbul](https://npmjs.org/package/istanbul)).
