### ISSUE TITLE
ENOMEM TestRunnerDecorator

### ISSUE THREAD

**Issue by anthony-telljohann** [stryker-mutator/stryker#1430]
### Summary

```sh
Mutation testing 34% (ETC 8m, 31s) 127/373 tested (8 survived)
(node:3835) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 14): Error: spawn ENOMEM
(node:3835) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3835) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): Error: spawn ENOMEM
(node:3835) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 16): Error: spawn ENOMEM
(3835) ERROR StrykerCli[39m an error occurred { Error: spawn ENOMEM
  at _errnoException (util.js:1024:11)
  at ChildProcess.spawn (internal/child_process.js:323:11)
  at exports.spawn (child_process.js:502:9)
  at Object.exports.fork (child_process.js:103:10)
  at new ChildProcessProxy (/node_modules/stryker/src/child-proxy/ChildProcessProxy.js:23:39)
  at Function.ChildProcessProxy.create (/node_modules/stryker/src/child-proxy/ChildProcessProxy.js:48:16)
  at new ChildProcessTestRunnerDecorator (/node_modules/stryker/src/test-runner/ChildProcessTestRunnerDecorator.js:14:51)
  at TimeoutDecorator.testRunnerProducer (/node_modules/stryker/src/test-runner/ResilientTestRunnerFactory.js:14:76)
  at TimeoutDecorator.TestRunnerDecorator.createInnerRunner (/node_modules/stryker/src/test-runner/TestRunnerDecorator.js:17:33)
  at TimeoutDecorator.TestRunnerDecorator (/node_modules/stryker/src/test-runner/TestRunnerDecorator.js:6:14) code: 'ENOMEM', errno: 'ENOMEM', syscall: 'spawn' }
```

### Stryker config

```js
// stryker.conf.js

module.exports = function(config) {
  config.set({
    mutator: 'typescript',
    packageManager: 'npm',
    reporters: ['html', 'clear-text', 'progress'],
    testRunner: 'jest',
    transpilers: ['typescript'],
    coverageAnalysis: 'off',
    tsconfigFile: 'tsconfig.json',
    mutate: ['src/**/*.ts', '!**/*{spec,stubs}.ts'],
    thresholds: { high: 100, low: 85, break: 85 }
  })
}

```

### Stryker environment

```
+-- stryker@0.35.1
+-- stryker-api@0.24.1
+-- stryker-html-reporter@0.18.1
+-- stryker-jest-runner@1.4.1
+-- stryker-typescript@0.18.1
+-- jest@24.1.0
```

### Test runner environment

```
# Test command
cross-env PORT=8080 stryker run
```

```js
// jest.conf.js

module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  collectCoverageFrom: ['src/**/*.ts'],
  coverageDirectory: 'reports/coverage',
  coverageThreshold: {
    global: {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100
    }
  },
  setupFiles: ['jest-date-mock'],
}
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | 10.14.1
| npm              | 6.7.0
| Operating System | macOS High Sierra 10.13.6

### Add stryker.log

[stryker.log](https://gist.github.com/anthony-telljohann/e4ed1a2aa5a0be2cda574733714944e9)

**Comment by simondel** [comment]
Thanks for opening this issue! You could have a memory leak in your application. Do you by any chance use Sinon in your tests?

**Comment by nicojs** [comment]
Probably no Sinon, as @anthony-telljohann is using Jest.

`ENOMEM` is the error code for your system being out-of-memory. This results in Stryker being unable to spawn additional child processes. It needs to do just that because it detected 4 timeouts. 

Could you try again with these tweaks:

1. Use `maxConcurrentTestRunners: 2` in your stryker.conf.js file, to make sure you're not overloading your system.
2. Don't use your PC (browser, slack, etc) during the mutation testing process. This can result in starvation.
3. Look with one eye at your process monitor tool.

I'm curious to see the memory usage of the main Stryker and the Stryker sandbox (child) processes. Memory leaks in your tests could result in crashing child processes, but that doesn't seem the case here. For some reason, Stryker is unable to spawn child processes, so there must be another process demanding memory. I'm hoping it's not the main Stryker process itself.

**Comment by anthony-telljohann** [comment]
> Do you by any chance use Sinon in your tests?
Nope!

**Comment by nicojs** [comment]
Thanks for your answer @anthony-telljohann. Did you have time to look at my suggestion as well?

**Comment by anthony-telljohann** [comment]
@nicojs that definitely fixed the issue. I think the root cause is from having a test that starts and stops a node http server. I'll figure out a better way to write the test and bump the test runners back up.  Thanks for the suggestion!

**Comment by nicojs** [comment]
> I think the root cause is from having a test that starts and stops a node http server.

That is definitely a good idea. Stryker works best with pure unit tests, as it will run multiple test processes in parallel. We should document that better somehow.
