### ISSUE TITLE
Make it possible to attach a custom reporter programmatically

### ISSUE THREAD

**Issue by ebousse** [stryker-mutator/stryker#1432]
### Enhancement suggestion

In a small project I am calling Stryker programmatically instead of running `npx stryker run`. Here is a  code snippet of where I call Stryker in my code:
```typescript
export function runMutation(projectFolder: string) {

    // Stryker relies on the nodejs process current folder to find files
    process.chdir(projectFolder)

    // Configuring stryker
    const minimalOptions: Partial<StrykerOptions> = {
        allowConsoleColors: true,
        mutator: "typescript",
        packageManager: "npm",
        reporters: ["clear-text", "progress"],
        testRunner: "jasmine",
        transpilers: ["typescript"],
        testFramework: "jasmine",
        coverageAnalysis: "perTest",
        jasmineConfigFile: "spec/support/jasmine-stryker.json",
        tsconfigFile: "tsconfig.json",
        mutate: ["src/move-validation.ts"]
    };

    // Starting stryker
    let stryker = new Stryker(minimalOptions)
    stryker.runMutationTest().then(() => {
        console.log("Ending.")
    })
```
In this context, I would like to attach a custom *reporter* to the execution, which I defined in the very same project as the code above. Broadly, I would love to do the following:

```typescript
stryker.addReporter(new MyCutomReporter())
```

Unfortunately, as far as I understood, there is no way to do such thing, and the only way to give a custom plugin (in this case, a reporter) to Stryker is to create it as an independent module that Stryker will look for in the `node_modules` folder of the current project (as I found [here](https://github.com/stryker-mutator/stryker/blob/24467e11dcbf68ec2e6fdbb4fadb0c70e71206c3/packages/core/src/di/PluginLoader.ts#L54)).

Would you consider making the Stryker API more usable for such a programmatic use?

and thanks for Stryker, it's a neat project :)

**Comment by nicojs** [comment]
Hi @ebousse, thanks for opening this issue!

Its definitely possible to add a custom reporter plugin. Documentation is here: 
https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md#plugins

> Stryker will look for in the `node_modules` folder of the current project (as I found [here](https://github.com/stryker-mutator/stryker/blob/24467e11dcbf68ec2e6fdbb4fadb0c70e71206c3/packages/core/src/di/PluginLoader.ts#L54)).

That is only true if there is a wildcard (`*`) in the name. For example: `@stryker-mutator/*` (which is the default plugin declaration). So to add a custom (local) plugin:

```js
// stryker.conf.js
{
  plugins: ['@stryker-mutator/*', require.resolve('./my-custom-reporter')]`
}
```

```ts
// my-custom-reporter.ts
import { PluginKind, declareClassPlugin, commonTokens, tokens } from '@stryker-mutator/api/plugin';
import { Reporter } from '@stryker-mutator/api/report';
import { StrykerOptions } from '@stryker-mutator/api/options';

export const strykerPlugins = [
  declareClassPlugin(PluginKind.Reporter, 'html', MyReporter)
];

class MyReporter implements Reporter {

  public static inject = tokens(commonTokens.options);
  constructor(options: StrykerOptions) {
  }

  // See `Reporter` interface for all actual methods, like:
  onScoreCalculated(scoreResult: ScoreResult) {
    // do stuff with the result
    console.log(scoreResult.mutationScore); // pseudo code
  }
}

```

(example is typescript, but ofcourse could be JS as well, but missing type safety).

Hope this helps!

**Note:** The plugin documentation is at a bare minimum at the moment. Feel free to improve that as well, that's the reason why we've put it in it's own git repo, should be really easy to do PR's right from your browser 😅 

> Would you consider making the Stryker API more usable for such a programmatic use?

I hope it is, because that is most definitly one of the design goals!

> Broadly, I would love to do the following `stryker.addReporter(new MyCutomReporter())`

This would rely on a static side effects (registering a plugin). We've migrated away from that API as of v1. Now you export your plugin and it is used in Stryker.

**Comment by ebousse** [comment]
I had not expected such a fast and extensive answer, many thanks :)! I had indeed not understood that modules were looked for in `node_modules` only when wildcards were used. I solved my problem thanks to your line `plugins: ['@stryker-mutator/*', require.resolve('./my-custom-reporter')]`, allowing me to load my reporter defined in a file next to my code, and it works perfectly now.

I can't promise that I will contribute to the plugin documentation but I'll keep that in mind in case I find time to contribute :).

While I am at it, small additional question: is there any way for a *reporter* to produce a result (eg. an array or an object) that could be retrieved after `runMutationTests` finishes? It seems that currently a reporter is only supposed to produce side effects elsewhere (eg. in the console or in a written file), but in my case I would love to compute/gather metrics and make use of them after having programmatically called `runMutationTests`.

**Comment by nicojs** [comment]
> While I am at it, small additional question: is there any way for a _reporter_ to produce a result (eg. an array or an object) that could be retrieved after `runMutationTests` finishes? 

Hmm, this is a great question. No, this is not possible at the moment. The way it could work is to fill a static field with data and `require` that after `runMutationTests` finishes. However, we would be open to suggestions. Maybe we could use the `wrapUp` method for that (which is called to finish up any async work being executed) or something.

**Comment by ebousse** [comment]
Yes filling a static field is the solution I had to pick for now, which is fine, but I wanted to make sure I hadn't missed anything in the API.

Thanks for answering all my questions, I'll close the issue then!
