### ISSUE TITLE
Clarity on projectType=react

### ISSUE THREAD

**Issue by coleturner** [stryker-mutator/stryker#1435]
### Summary

Hi! I'm getting started with this project and I wanted to share some confusion I had around `projectType=react`.

I think it's worth clarifying that `react` here is create-react-app and not general purpose React. During the installation I selected this thinking it came with specific Babel transforms or mutants. Then I ran into an error about missing `react-scripts/` which I was able to recognize. There's not much in the way of issues for this particular error however and that lead me to create this issue.

Would you consider expanding the terminology (particularly for installation) to clarify that it's create-react-app specifically?

**Comment by simondel** [comment]
Thanks for opening this issue!

Do you mean the setting in the Jest runner as described in its README:
https://www.npmjs.com/package/@stryker-mutator/jest-runner#configuring-jest

Or do you mean the 'react' option in the preset configurations? (which also sets the jest-runner to 'react'):
![image](https://user-images.githubusercontent.com/4221997/53678415-13caf900-3cbf-11e9-95e1-e7cc9ddf9d0d.png)

**Comment by coleturner** [comment]
Hey @simondel thanks for replying! That is the correct menu I selected though I think it might be worth keeping them both aligned. I know CRA is ubiquitous but I worry for those who have never used it and wouldn't recognize the error :)

**Comment by simondel** [comment]
Well, the preset is actually for `create-react-app` projects so I think it's ok to rename that to `create-react-app`.

**Comment by nicojs** [comment]
We could also simply improve the documentation in both places. Instead of another deprecation 😰

**Comment by coleturner** [comment]
Good point @nicojs I was worried about the major semver change, I think even parenthesis with (create-react-app) would suffice. For the JS configuration files it's a little different but I think a JS comment would suffice too.

**Comment by skyboyer** [comment]
it works for my non-CRA application but I had to put 
```
      projectType: 'custom',
```
and remove `config` entry from `stryker.conf.js` to make it run without errors

**Comment by MrFix93** [comment]
I can confirm that the fix from @skyboyer works for non-'create-react-app' react projects. I think the suggestion from @simondel to rename the option to `create-react-app` in the cli, should be sufficient to inform people this only works for these kinds op react projects.

**Comment by nicojs** [comment]
Ok, sounds good. We're welcoming PR's. Please implement it without breaking changes (log a deprecation warning accordingly).

**Comment by kmdrGroch** [comment]
Is it still a valid issue? There were quite a lot of changes and also some deprecations and removals (especially in stryker 4)

**Comment by coleturner** [comment]
LGTM! Thanks @MrFix93
