### ISSUE TITLE
Support "extends" property in tsconfig from within a sandbox

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#1437]
When transpiling ts files from within a sandbox, with a tsconfig file that extends a parent tsconfig file from the parent directory, it will not be able to find it.

For example: when using the `karma-webpack` plugin to transpile ts files with the `ts-loader` with a tsconfig file that extends: '../../tsconfig.settings.json': 

```
WARNING in ./test/unit/components/mutation-test-report-app.spec.ts
Module build failed (from C:/z/github/stryker-mutator/mutation-testing-elements/node_modules/ts-loader/index.js):
Error: error while parsing tsconfig.json
    at Object.loader (C:\z\github\stryker-mutator\mutation-testing-elements\node_modules\ts-loader\dist\index.js:19:18)
```

The work around is to create a separate `stryker.tsconfig.json` file which extends `../../../../settings.tsconfig.json`. It would be cool if we could somehow support this scenario out of the box. Not sure yet how 🤷‍♂️

**Comment by nicojs** [comment]
Ok, I've thought about it and have a suggestion

 We could introduce a transpiler to transform the tsconfig.json files from `"extends": "../../tsconfig.json"` to `"extends": "../../../../tsconfig.json"`. A rough version can be found here: https://github.com/stryker-mutator/mutation-testing-elements/blob/master/packages/mutation-testing-elements/tsconfig-transpiler.js (we should improve on the implementation)

I think we can include this transpiler in the `@stryker-mutator/typescript` suite of plugins.

This isn't the best thing, but I don't have another idea.

**Comment by simondel** [comment]
Where is the parent config in this case? If it's in the repo, it should just be in the sandox right? So why would we have to alter pahts?

**Comment by nicojs** [comment]
See this scetch of our own repo:

```
/stryker
  tsconfig.settings.json
  /packages
    /core
      tsconfig.json
      stryker.conf.js
```

So the parent config is outside of the sandbox. 

My purposed solution isn't elegant, but it will work.

**Comment by nicojs** [comment]
Btw, Stryker itself might not be needing this plugin, as we're using the `'typescript'` transpiler plugin (it loads the sources from the project directory directly). However, if you would use other means of transpiling (like the karma-webpack plugin), you do need it.

**Comment by michael42** [comment]
We're running into the same issue with our project. I think it would be easier and cleaner to simply switch the directory structure from:

```
📁 projectName/
    📄 package.json
    📄 tsconfig.json
    📁 .stryker-tmp/
        📁 sandbox3026627/
            📄 package.json
            📄 tsconfig.json
```

to:
```
📁 projectName/
    📄 package.json
    📄 tsconfig.json

📁 .stryker-sandbox-projectName-3026627/
    📄 package.json
    📄 tsconfig.json
```

That should fix the whole class of issues (instead of only for `tsconfig.json`'s `extends` property), but might cause temporary folders appear outside of any workspace or git repository for projects without sub-projects...
