### ISSUE TITLE
Exclude mutations with filter function

### ISSUE THREAD

**Issue by Hoten** [stryker-mutator/stryker#1464]
#652 added support for disabling specific mutation types. However, we have a use case where we'd like to disable only _certain_ `StringLiteral` mutations, not all of them. It'd be super rad if Stryker exposed a filter function that provided the mutation to be made + the ast node of the code being mutated. That'd allow for a lot of granularity.

**Comment by simondel** [comment]
Sounds like a nice feature :) How would you see yourself use this filter as a user? (from a configuration standpoint)

**Comment by simondel** [comment]
We've opened a specific issue for supporting this feature. I have referenced it above.

**Comment by nicojs** [comment]
Ignore-plugins are released in StrykerJS 7.3 🎉 . Ignoring something arbitrary statements is now possible. If you need help, don't hesitate to ask.

https://twitter.com/stryker_mutator/status/1713557660832792870

https://stryker-mutator.io/docs/stryker-js/disable-mutants/#using-an-ignore-plugin
