### ISSUE TITLE
Support for karma preprocessors

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#148]
In order to support things like karma preprocessors we should run child processes from their respective sandbox folder. I tested stryker with a karma preprocessor here: https://github.com/nicojs/karma-preprocessor-stryker-test and it doesn't work.

As a bonus we should do the initial test run from an actual sandbox. This will make sure stryker is configured correctly.

**Comment by nicojs** [comment]
I think we could support this if we change the current working directory to the sandbox folder right after we load the plugins before we instantiate the runner:

https://github.com/stryker-mutator/stryker/blob/master/src/isolated-runner/IsolatedTestRunnerAdapterWorker.ts#L44

@simondel what do you think?

**Comment by zxxc** [comment]
+1

**Comment by nicojs** [comment]
Moved to stryker-karma-runner#19
