### ISSUE TITLE
New html reporter should escape html characters in strings

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#1482]
The new HTML reporter should escape HTML strings. Right now, a `</script>` in the client's code results in an invalid HTML document, rendering the HTML report useless.

**Comment by nicojs** [comment]
The report looks like this:

![image](https://user-images.githubusercontent.com/1828233/55533202-d0461f00-56b0-11e9-80c8-dc7738cc3ac4.png)

**Comment by hugo-vrijswijk** [comment]
We should also update the examples in the elements repo and explain why not to do this for new reports
