### ISSUE TITLE
Running Mutation testing on Polymer 2 application

### ISSUE THREAD

**Issue by batraanupriya** [stryker-mutator/stryker#1487]
### Summary

I need to run the mutation testing on my polymer 2 application. Since it is web component based all my compoenents are imported using html import and all are html files rather than js files. So i am not sure how to run the mutation testing onthese files.

### Stryker config

```js
module.exports = function(config) {
  config.set({
    mutator: "typescript",
    packageManager: "npm",
    reporters: ["html", "clear-text", "progress"],
    testRunner: "mocha",
    transpilers: ['typescript'],
    testFramework: "mocha",
    coverageAnalysis: "perTest",
    mutate: ["src/**/*.html"]
  });
};
```

### Stryker environment

```
"@stryker-mutator/babel-transpiler": "^1.2.0",
    "@stryker-mutator/core": "^1.2.0",
    "@stryker-mutator/html-reporter": "^1.2.0",
    "@stryker-mutator/javascript-mutator": "^1.2.0",
    "@stryker-mutator/mocha-framework": "^1.2.0",
    "@stryker-mutator/mocha-runner": "^1.2.0",
    "@stryker-mutator/typescript": "^1.2.0",
    "@stryker-mutator/wct-runner": "^1.2.0",
    "@stryker-mutator/webpack-transpiler": "^1.2.0",
```

```
"mocha": "^5.1.1",
"web-component-tester": "~6.5.0",
```

### Test runner environment

```
"test": "polymer test --skip-selenium-install",

```

```const path = require('path');

const ret = {
  suites: ['test/index.html'],
  webserver: {
    pathMappings: [],
  },
  plugins: {
    local: {
      browsers: ['chrome'],
      browserOptions: {
        chrome: ['--no-sandbox'],
      },
    },
    istanbub: {
      dir: './coverage',
      reporters: ['text-summary', 'lcov'],
      include: [
        '**/*.html',
      ],
      thresholds: {
        global: {
          statements: 90,
          branches: 90,
          functions: 90,
          lines: 90,
        },
      },
      exclude: [
        '**/bower_components/**',
        '**/test/**',
      ],
    },
  },
};

const mapping = {};
const rootPath = (__dirname).split(path.sep).slice(-1)[0];

mapping[`/components/${rootPath}/bower_components`] = 'bower_components';

ret.webserver.pathMappings.push(mapping);

module.exports = ret;

```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             |  8.15.1
| npm              | 6.9.0
| Operating System | Ubuntu

### Add stryker.log

Trouble figuring out what went wrong? Try `npx stryker run --fileLogLevel trace --logLevel debug` to get some more info.

**Comment by nicojs** [comment]
unfortunately, we don't support mutating html files yet. We might be doing that in the future, but we first want to migrate to mutation switching, which will take some time. Feel free to create your own mutator (you can base it on the [vue mutator](https://github.com/stryker-mutator/stryker/tree/master/packages/vue-mutator), which support `.vue` files)

As a workaround:

My Polymer 2 is a bit rusty, but to my understanding: it is possible to use external scripts:

```html
<!-- my-component.html -->
<dom-template>
  <!-- ... -->
</dom-template>
<script src="my-component.js"></script>
```

```js
// my-component.js

// <-- move your content here!
```

After you've done that, you should be able to mutate `my-component.js`

**Comment by nicojs** [comment]
@batraanupriya did this help you? If so, would it be OK to close this issue?

**Comment by simondel** [comment]
Hi! I'm closing this issue for now. We dropped support for WCT with Stryker v4. You could however, try to use it with the command test runner.
