### ISSUE TITLE
Error while running for mocha test framework

### ISSUE THREAD

**Issue by mpadmaraj** [stryker-mutator/stryker#1499]
### Summary
I'm trying out Stryker for the first time. I have a project that used Mocha test framework. I was following the steps given in the Quickstart page. But I get this error:
```
23:10:48 (11376) WARN ChildProcessProxy Child process [pid 20800] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
        D:\bac\node_modules\typed-inject\src\InjectorImpl.js:35
                    throw new Exception_1.Exception(`Could not inject "${Class.name}"`, error);
                    ^

        Error: Could not inject "ChildProcessTestRunnerWorker". Inner error: Could not inject "MochaTestRunner". Inner error: Cannot find module 'test/setup.js'
```
### Stryker config
```js
module.exports = function(config) {
  config.set({
    mutator: "javascript",
    packageManager: "npm",
    reporters: ["html", "clear-text", "progress", "dashboard"],
    testRunner: "mocha",
    transpilers: [],
    testFramework: "mocha",
    coverageAnalysis: "perTest"
  });
};

```

```js
module.exports = function(config){
  config.set({
    ....
  });
}
```

### Stryker environment

```
 "@stryker-mutator/core": "^1.2.0",
    "@stryker-mutator/html-reporter": "^1.2.0",
    "@stryker-mutator/javascript-mutator": "^1.2.0",
    "@stryker-mutator/mocha-framework": "^1.2.0",
    "@stryker-mutator/mocha-runner": "^1.2.0",
```

```
"mocha": "^3.2.0"
```

### Test runner environment

```
# Test command
"test": "nyc mocha",
```

mocha.opts is empty
```json
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | v10.0.0
| npm              | 5.6.0
| Operating System |Windows 10 

### Add stryker.log
[stryker.log](https://github.com/stryker-mutator/stryker/files/3086210/stryker.log)

**Comment by nicojs** [comment]
Hi @mpadmaraj 👋 Thanks for trying out Stryker.

Apparently, Stryker cannot find the "test/setup.js" file. Can you confirm that this file is located inside your git repository and located at that location (as seen from the current working directory)?

If so, could you try changing it to "./test/setup.js" in your mocha.opts file?

**Comment by mpadmaraj** [comment]
Thanks @nicojs. mocha.opts wasn't empty. I correct it and it went past this error. I'm having some other issues but it could be my project configuration as well. So will close this ticket.
