### ISSUE TITLE
Add support for jest

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#150]
We might need to add support for jest: the facebook JavaScript testing framework+testrunner: https://github.com/facebook/jest

**Comment by nicojs** [comment]
@mthmulders are you interested in implementing this support? If so, i could already bootstrap a git repo for you. Are you comfortable with TypeScript? That way you'll have explicit interfaces to implement.

Is it correct that the `Jest` is both a test runner and a test framework? If so, its a good idea to add them both to the same git repo, lets say `stryker-jest-runner`? Keeping 'runner' in the name feels more natural to me.

**Comment by mthmulders** [comment]
Sure, I'd love to give it a try! The proposed name sounds good to me; if you could bootstrap a repo for me I'll give it a shot and see how things roll.

**Comment by nicojs** [comment]
@mthmulders glad to here it :smiley:! I created a new project called [stryker-plugin-seed](https://github.com/stryker-mutator/stryker-plugin-seed). Than i used that to bootstrap [stryker-jest-runner](https://github.com/stryker-mutator/stryker-jest-runner). You should have write access to it now. Any feedback on the seed project is most welcome.

The seed is based on the new stryker-api 0.3.0-rc2, which means that you can won't be able to do a test with an actual stryker. We'll start working on that implementation this week. Also: the [stryker-karma-runner](https://github.com/stryker-mutator/stryker-karma-runner] and (stryker-mocha-runner)[https://github.com/stryker-mutator/stryker-mocha-runner] are both still using 0.2.x so you can take a look there, but take it with a grain of salt.

We can do feature branches with reviews if you want. We're happy to help. For direct questions you can also use our [gitter](https://gitter.im/stryker-mutator/stryker).

My advice: don't think about code coverage for now. Just focus on getting the jest test runner up-and-running.

**Comment by mthmulders** [comment]
I'd suggest this can be closed now 😄

**Comment by nicojs** [comment]
Thanks!
