### ISSUE TITLE
How do I exclude files with a pattern?

### ISSUE THREAD

**Issue by Project4MobileDev** [stryker-mutator/stryker#1515]
### Summary

How do I exclude files with a pattern? I want to run stryker against a Xamarin .netstandard 2.0 library, I'm using stryker with in the console with the following command:
dotnet stryker -cp stryker-config.json

In the config file I'm specifying files to be excluded but it seems to only allow specific file names rather than using a pattern to exclude them. I've tried a few different ways of specifying a pattern, see the config file below. 

### Stryker config

```{
  "stryker-config": {
    "files-to-exclude": [
      "pattern": "/Views/*",
      "pattern": "**/*.xaml.cs",
      "pattern": "**/*.xaml",
      "/**.xaml.cs",
      "/**.xaml",
      { 
        pattern: "**/*.xaml.cs"
      }
      { 
        pattern: "**/*.xaml"
      }
    ]
  }
}
```

### Test runner

```
xUnit
```

### Environment

Windows 10
.NET Command Line Tools (2.2.203)

**Comment by simondel** [comment]
Thanks for opening this issue! I believe this is related to Stryker.NET which is located here: https://github.com/stryker-mutator/stryker-net

I took the liberty of opening an issue for you there: https://github.com/stryker-mutator/stryker-net/issues/464

For now I'll close this issue.
