### ISSUE TITLE
Use Google TypeScript Style

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1526]
Searching through the internet I have found quite interesting repository <https://github.com/google/gts> (Google TypeScript Style), created by Google (WoW), which just add TypeScript style guide, formatter, and linter. It is built on Tslint and prettier. I would remove the necessity of looking for TSlint updates, updating 'stylesheets', everything would be always up to date with Google's standards.
It would also close all my current and future (probably) issues about style conventions.

(although we still can update it's config:
Opinionated, but not to a fault. We recommend you use the default configuration, but if you need to customize compiler or linter config, you can.)

Looking for your feedback bout it :)

**Comment by nicojs** [comment]
Hmm I like this approach. We need to migrate to eslint sooner or later, might as well migrate to this instead. 

What would the impact on code be? Are we in line with the "Google style" (can't seem to find documentation on what that is exactly)?

**Comment by kmdrGroch** [comment]
Solved by #1615
