### ISSUE TITLE
All tests being run despite config. "Failed find coverage data for this mutant, running all tests."

### ISSUE THREAD

**Issue by davesag** [stryker-mutator/stryker#1528]
### Summary

see https://github.com/davesag/amqp-event-tester

I have two sets of tests, unit tests and integration tests.  I have configured stryker to run the unit tests (using the same config as I use in other projects that do not exhibit this issue) but stryker complains "Failed find coverage data for this mutant, running all tests." then runs both the integration and unit tests.

### Stryker config

```js
module.exports = function(config) {
  config.set({
    mutate: [
      'src/**/*.js',
      '!src/exchange.js',
      '!src/index.js',
      '!src/utils/logger.js'
    ],
    mutator: 'javascript',
    packageManager: 'npm',
    reporters: ['clear-text', 'progress'],
    testRunner: 'mocha',
    mochaOptions: {
      spec: ['./test/unit/**/*.test.js'],
      require: ['./test/unit/testHelper.js']
    },
    transpilers: [],
    testFramework: 'mocha',
    coverageAnalysis: 'perTest',
    thresholds: { high: 80, low: 70, break: null }
  })
}
```

### Stryker environment

```
├─┬ @stryker-mutator/core@1.3.1
│ ├─┬ @stryker-mutator/api@1.3.1
│ ├── @stryker-mutator/util@1.3.1
├─┬ @stryker-mutator/javascript-mutator@1.3.1
│ ├── @stryker-mutator/api@1.3.1 deduped
├─┬ @stryker-mutator/mocha-framework@1.3.1
│ └── @stryker-mutator/api@1.3.1 deduped
├─┬ @stryker-mutator/mocha-runner@1.3.1
│ ├── @stryker-mutator/api@1.3.1 deduped
```

```
+-- mocha@6.1.4
```

### Test runner environment

```
NODE_ENV=test NODE_PATH=. mocha ./test/unit/ --require ./test/unit/testHelper.js --recursive --extension .test.js
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             |  12.0.0
| npm              |  6.9.0
| Operating System |  macOS 10.14.4

### Add stryker.log

[stryker.log](https://github.com/stryker-mutator/stryker/files/3123434/stryker.log)

**Comment by davesag** [comment]
Note the same is happening with https://github.com/davesag/wikiscores

**Comment by simondel** [comment]
Thanks for opening this issue! Unfortunatly, I'm unable to run your projects. An `npm install` only installs some of your dependencies. It for example skips stryker, mocha and nyc in both projects. I also can't install cross-env to get your project to run on Windows.

Environment:
Node v10.15.3
npm 6.4.1
OS Windows 10 Pro

**Comment by davesag** [comment]
How about the other one, wikiscores, linked above.

**Comment by davesag** [comment]
Sorry I don’t have access to a Windows machine.

**Comment by nicojs** [comment]
@davesag I was able to install your project on my (WSL and windows) machines. I can reproduce the warnings: 16 in total. For example:

```
)07:06:53 (5376) WARN Sandbox Failed find coverage data for this mutant, running all tests. This might have an impact on performance: Block: ({}) file://C:\z\github\davesag\amqp-event-tester\src\server.js:15:35
```

However, I don't see any evidence that it's running the integration tests. For example, I can see you've added a console.log in your integration tests: 

```js
before(async () => {
  console.log('starting tests')
  ;({ stop } = await start())
})
```

But when I run stryker with `--fileLogLevel trace` it doesn't end up in my stryker.log file. Also, Stryker runs quite fast still. Why do you think Stryker runs integration tests here? Is it because of the warning message? Maybe it isn't clear?

It is curious to see that Stryker can't find any coverage data. How this works is that your files to mutate are instrumented with [istanbul](https://github.com/istanbuljs/istanbuljs). Next, mutants are correlated with the statement map inside the istanbul data. It seems that some of the mutants cannot be correlated.  We should look into this. But first I want to confirm that integration tests aren't run.

**Comment by louiskenyon98** [comment]
Please note I have a very similar issue. I have a project with mock files within the __tests__ directory, the mock files have the extension .js - and despite my jest and stryker config explicitly excluding those files, stryker still runs all tests.

The only workaround I have found is to change the file extension on the files I do not want to run.

Just confirming @davesag that you are not the only one to experience an issue like this.

**Comment by davesag** [comment]
Thanks @louiskenyon98 

Hi @nicojs sorry for the delay in response.  When I run the mutation tests I see this warning

```
Failed find coverage data for this mutant, running all tests.
```

So actually, yes you are right, it's **not** running the integration tests (phew) (there are 22 unit tests that run and it runs 22 tests) but the message implies that it is.  So that's my bad and I apologise for leading you astray there.

Maybe it's because of the `/* istanbul ignore next */` lines in my code (yeah I know I ought to do something about those, and I will one day)

**Comment by nicojs** [comment]
> Maybe it's because of the `/* istanbul ignore next */` lines in my code (yeah I know I ought to do something about those, and I will one day)

😅 that might be it. I will take a look. Thanks for the clarification.

@louiskenyon98 could you open an issue for your problem with Jest? It sounds like a bug.

**Comment by louiskenyon98** [comment]
@nicojs No problem, I'll get that opened as soon as possible. I also have a OOM issue with Stryker on another project, so I'll get an issue for that open shortly too.

**Comment by davesag** [comment]
@nicojs I've just experienced the same `Failed find coverage data for this mutant, running all tests.` in a client project in which I just added a bunch of `/* Istanbul ignore next */` statements, so there definitely appears to be an issue with that.

It would be really nice if Stryker were to also ignore stuff that istanbul is specifically told to ignore.

**Comment by kmdrGroch** [comment]
It this issue still present?

**Comment by davesag** [comment]
> It this issue still present?

I just upgraded all my projects to use v4 now and made the necessary adjustments to the config, and I'm not seeing the problem recur.  So it does seem to have been fixed.
