### ISSUE TITLE
Strange "empty-function-body into broken-array" mutation?

### ISSUE THREAD

**Issue by bkimminich** [stryker-mutator/stryker#153]
![image](https://cloud.githubusercontent.com/assets/3531020/18962535/8b060692-8671-11e6-8dcb-c6efbfc9119c.png)

This looks like it wants to mutate
```
angular.module('juiceShop').controller('AboutController', [
  function () {}])
```
into
```
angular.module('juiceShop').controller('AboutController', [
  function () { })
```
which doesn't seem like a good idea, syntax-wise with that missing closing angular bracket... or maybe it's just rendered wrong in the HTML report?

**Comment by simondel** [comment]
Is that this one?
![image](https://cloud.githubusercontent.com/assets/4221997/19015381/b3d372d8-8803-11e6-97cc-49848844957f.png)
If so, the `clear-text reporter` reports it as:
![image](https://cloud.githubusercontent.com/assets/4221997/19015383/c77ab83c-8803-11e6-82b0-c17a54b8baba.png)
So it seems like an issue with the `stryker-html-reporter`

On a other note, perhaps the BlockStatementMutator should not mutate block statements if they are empty or only contain spaces. @nicojs Do you agree?

**Comment by nicojs** [comment]
@simondel Well... in this case it does contain a `'use strict'` statement. I agree that we shouldn't mutate it, it will always result in an equivalent mutant.

I created issue https://github.com/stryker-mutator/stryker-html-reporter/issues/5 for the extra character. We'll keep this issue open to fix the equivalent mutant?

**Comment by bkimminich** [comment]
I did remove the 'use strict' because I thought that triggered the mutation. But it still mutated the empty block.

I would just ignore empty blocks, if anything other than statements (even comments!) is in a block, it should mutate. This kind of brought the useless 'use strict' with no subsequent code to my attention.

**Comment by nicojs** [comment]
Just did committed #160 to fix this issue. Unfortunately we cannot distinguish between an empty block or a block with only a comment. I choose to not mutate empty blocks in this case.

Just to be clear: `"use strict";` **is still mutated**

**Comment by bkimminich** [comment]
Fine for me. Plese ping me when I should re-test this!
