### ISSUE TITLE
Current version build not passing

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1542]
It seems that the current version has some issue (node-sass not found) and so it says on GitHub that your build is failing
![image](https://user-images.githubusercontent.com/28489774/57548509-641aa300-7361-11e9-94be-70d38a6a1b33.png)

**Comment by nicojs** [comment]
Yep, working on it in my spare time. We're having problems with the cleanup after a run. Sometimes the cleanup results in an error, producing an exit code 1. This can be reproduced with our perf tests on linux. 

Thanks for reporting 🙇

**Comment by davesag** [comment]
@nicojs yes I am seeing the cleanup error you mention.  Only on Linux though and not on macOS.  See https://circleci.com/gh/davesag/amqp-simple-pub-sub/272 for example.

The solution appears to be to set the number of test runners to 2.

```
maxConcurrentTestRunners: 2
```

This appears to relate to #1525

**Comment by nicojs** [comment]
Most definitely related to #1525. This might sound silly, but I'm actually waiting on TS3.5 release later this month, as that hopefully solves a compile error in the [async dispose branch](https://github.com/stryker-mutator/stryker/tree/feat/async-dispose). At least, the compile error seems to be solved with 3.5-rc. 

TypeScript seems to have problems with [typed-inject](https://github.com/nicojs/typed-inject). See this PR for more info: https://github.com/nicojs/typed-inject/pull/7

**Comment by davesag** [comment]
Yet another reason to avoid TypeScript. :-)

**Comment by nicojs** [comment]
Yeah, I can understand the sentiment. However, typed-inject is an extreme example of type-safety. It makes our code more type-safe than Java with Spring or C# with .NET core. 

I wouldn't want to maintain sug a big code base as Stryker without type-safety.

**Comment by davesag** [comment]
I was writing Javascript in 1995, well before I ever heard of Java and a decade before C# existed, so I've learned to love type-flexibility and a pure functional style of coding.

You might enjoy the following articles I wrote on this topic a while back (Or you might hate them — lol)

* [Don’t do `this`  —  Part One: Objects and their misuse](https://itnext.io/dont-do-this-part-one-objects-and-their-misuse-bd0771c3178a)
* [Don’t do `this`  —  Part Two: The trouble with Typescript](https://itnext.io/dont-do-this-part-two-the-trouble-with-typescript-8ea9b26892e2)
