### ISSUE TITLE
make stryker command failed each times when less than 80% of mutants are killed

### ISSUE THREAD

**Issue by trollepierre** [stryker-mutator/stryker#1559]
### Summary

make stryker command failed each times when less than a certain percentage of mutants are killed

**Comment by kmdrGroch** [comment]
@trollepierre isn't it available as a threshold? https://github.com/stryker-mutator/stryker/tree/master/packages/core#thresholds-object

**Comment by trollepierre** [comment]
Yes! my bad! Thanks

**Comment by trollepierre** [comment]
Maybe the documentation doesn’t mention it enough...

**Comment by nicojs** [comment]
@trollepierre 

> Maybe the documentation doesn’t mention it enough...

Where were you looking? We're always looking to improve our documentation.

**Comment by trollepierre** [comment]
I was looking here:
https://stryker-mutator.io/stryker/quickstart
