### ISSUE TITLE
Stryker es6 import not working on typescript + mocha

### ISSUE THREAD

**Issue by JeroenVanSteijn** [stryker-mutator/stryker#1560]
I have searched and tried all related issues. They are mostly related to turning off coverageAnalysis and having ts-node so not needing `transpilers: ['typescript'],`

### Summary

When I setup using `stryker init`, put in the configurations and run `stryker run` I get the following error:

```
ERROR InitialTestExecutor One or more tests resulted in an error:
SyntaxError: Unexpected token *
/Users/jeroen/git/cb-02/api/.stryker-tmp/sandbox5720760/test/action-server.test.ts:1
(function (exports, require, module, __filename, __dirname) { import * as server from './mock-action-server';
SyntaxError: Unexpected token *
```

### Stryker config

```js
module.exports = function (config) {
	config.set({
		mutator: 'typescript',
		packageManager: 'npm',
		reporters: ['clear-text', 'progress'],
		testRunner: 'mocha',
		mochaOptions: {
			spec: ['test/**/*.ts'],
		},
		transpilers: [],
		testFramework: 'mocha',
		coverageAnalysis: 'off',
		tsconfigFile: 'tsconfig.json',
		mutate: ['src/**/*.ts'],
	});
};
```

### Stryker environment

```
├─┬ @stryker-mutator/core@2.0.0
│ ├─┬ @stryker-mutator/api@2.0.0
│ ├── @stryker-mutator/util@2.0.0
├─┬ @stryker-mutator/mocha-framework@2.0.0
│ └── @stryker-mutator/api@2.0.0 deduped
├─┬ @stryker-mutator/mocha-runner@2.0.0
│ ├── @stryker-mutator/api@2.0.0 deduped
├─┬ @stryker-mutator/typescript@2.0.0
│ ├── @stryker-mutator/api@2.0.0 deduped
│ ├── @stryker-mutator/util@2.0.0 deduped
```

```
mocha@6.1.4
```

### Test runner environment

```
# Test command
mocha test/*.test.ts -r ts-node/register
```

tsconfig.json
```json
{
	"compilerOptions": {
		"module": "commonjs",
		"target": "es5",
		"strictNullChecks": true,
		"moduleResolution": "node",
		"sourceMap": true,
		"outDir": "dist",
		"baseUrl": ".",
		"paths": {
			"*": [
				"node_modules/*"
			]
		}
	},
	"include": [
		"src/**/*"
	],
	"exclude": [
		"node_modules",
	],
}
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             |  v11.3.0
| npm              | 6.4.1
| Operating System | MacOS Mojave 10.14.3

### Add stryker.log

[stryker.log](https://github.com/stryker-mutator/stryker/files/3219518/stryker.log)

**Comment by nicojs** [comment]
Thanks @JeroenVanSteijn for openining this issue.

Could you try to add [`require` to your `mochaOptions`](https://github.com/stryker-mutator/stryker/tree/master/packages/mocha-runner#mochaoptionsrequire-string) in your stryker.conf.js file?


```ts
		mochaOptions: {
			spec: ['test/**/*.ts'],
                        require: ['ts-node/register']
		},
```

**Comment by JeroenVanSteijn** [comment]
Hi @nicojs thank you so much! It's fixed :)

**Comment by nicojs** [comment]
Great to hear! If you want to take advantage of coverage analysis, you actually have a way of doing that. It would boost performance significantly. 

In order to enable coverage analysis, you should be able to use this setup:

```ts
module.exports = function (config) {
	config.set({
		mutator: 'typescript',
		packageManager: 'npm',
		reporters: ['clear-text', 'progress'],
		testRunner: 'mocha',
		mochaOptions: {
			spec: ['test/**/*.js'],
		},
		transpilers: [ 'typescript' ],
		testFramework: 'mocha',
		coverageAnalysis: 'perTest',
		tsconfigFile: 'tsconfig.json',
		mutate: ['src/**/*.ts'],
	});
};
```

What this does is transpile the code with the typescript compiler for you (what ts-node does under the hood) and you use the resulting JS files to run mocha with. Furthermore, because the output is plain JS, Stryker is able to instrument it for code coverage.
