### ISSUE TITLE
React enzyme adapter fails with symlinkNodeModules=true

### ISSUE THREAD

**Issue by jRichardeau** [stryker-mutator/stryker#1564]
### Summary

I'm using stryker in a react project that uses _enzyme_ with react adapter.

With the _symlinkNodeModules_ option to true, enzyme initialization fails with this error : 

```
Enzyme Internal Error: configured enzyme adapter did not inherit from the EnzymeAdapter base class

 > Enzyme.configure({ adapter: new Adapter() });
```

Thank you

### Stryker config

```js
module.exports = function(config) {
   config.set({
      mutate: ["source/**/*.js", "!source/**/*@(.test|.spec|Spec).js", "!source/scripts/**/*.*"],
      files: [
         '*.js', 
         '__mocks__/*.js',
         'testUtils/*.js',
         'source/**/*.js?(on)',
         "!source/scripts/**/*.*"
      ],
      mutator: "javascript",
      packageManager: "yarn",
      reporters: ["html", "clear-text", "progress"],
      htmlReporter: {
         baseDir: 'stryker-reports/mutation/html'
      },
      testRunner: "jest",
      coverageAnalysis: "off",
      jest: {
         projectType: "custom",
         config: require('./jestrc.json'),
         enableFindRelatedTests: true
      }
   });
};
}
```

### Stryker environment

```
+-- @stryker-mutator/core@2.0.0
| +-- @stryker-mutator/api@2.0.0
| +-- @stryker-mutator/util@2.0.0
+-- @stryker-mutator/html-reporter@2.0.0
| +-- @stryker-mutator/api@2.0.0 deduped
| +-- @stryker-mutator/util@2.0.0 deduped
+-- @stryker-mutator/javascript-mutator@2.0.0
| +-- @stryker-mutator/api@2.0.0 deduped
+-- @stryker-mutator/jest-runner@2.0.0
| +-- @stryker-mutator/api@2.0.0 deduped
```

```
+-- jest@24.5.0
+-- enzyme@3.9.0
+-- enzyme-adapter-react-16@1.11.2
```

### Test runner environment

```
# Test command

jest --config jestrc.json

```

jestrc.json

```
{
   "moduleFileExtensions": [
      "js"
   ],
   "moduleDirectories": [
      "source",
      "node_modules"
   ],  
   "moduleNameMapper": {
      "\\.(scss|css)$": "<rootDir>/__mocks__/styleMock.js",
      "\\.(png|svg)$": "<rootDir>/__mocks__/fileMock.js",
      "testUtils": "<rootDir>/testUtils"
   },
   "testPathIgnorePatterns": [
      "/node_modules/",
      "source/scripts/"
   ],
   "coveragePathIgnorePatterns": [
      "/node_modules/",
      "source/scripts/"
   ],
   "setupFiles": ["jest-canvas-mock", "jest-prop-type-error"],
   "setupFilesAfterEnv": ["<rootDir>/unittests.config.js"]
}
```
unitests.config.json

```
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });
```
### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | 10.15.3
| npm              | 6.4.1
| Operating System | Windows 10 Enterprise

### Add stryker.log

[stryker.log](https://github.com/stryker-mutator/stryker/files/3228098/stryker.log)

**Comment by nicojs** [comment]
Interesting, so it does work with `symlinkNodeModules` set to `false`? 

I think this has something to do with Enzyme or jest not being able to handle symlinked node_modules. #717 seems to have the same issue, so it might be fixed when https://github.com/facebook/jest/issues/5356 gets implemented.

If it does work with setting `symlinkNodeModules` to `false`, how would you suggest improving the documentation for that? I guess you did quite a lot of searching to find that option 😅

**Comment by jRichardeau** [comment]
> If it does work with setting symlinkNodeModules to false, how would you suggest improving the documentation for that? I guess you did quite a lot of searching to find that option 😅

Yes I searched for a little while 😄, and yes it does work with `symlinkNodeModules` to false.
I think it could be documented on the jest plugin _readme_ in the `symlinkNodeModules` option ?

You think the issue comes from jest ? Not enzyme ?
And last question, does set `symlinkNodeModules` to false change something for performance ?

**Comment by kmdrGroch** [comment]
Is this issue still present?

**Comment by jRichardeau** [comment]
Sorry but I don't know if it's still present, I'm not using stryker anymore because of some performance issues.

**Comment by kmdrGroch** [comment]
try Stryker 4.0! its much faster now :)

**Comment by simondel** [comment]
I'm closing this issue for now.

**Comment by nicojs** [comment]
You can also use the new [`--inPlace`](https://stryker-mutator.io/docs/stryker/configuration#inplace-boolean) mode, new since Stryker 4.4. Closing this issue for now, please open a new one if this problem persists.
