### ISSUE TITLE
Stryker for nodeunit + jscoverage

### ISSUE THREAD

**Issue by bkimminich** [stryker-mutator/stryker#158]
I have a tiny side project that is so simple it gets away with `nodeunit` and `jscoverage` for testing. The project uses `grunt` to fire off the tests. See https://github.com/bkimminich/z85-cli

It would be nice to have styker support it, but I'm not sure if the JS community considers these as dead horses...? :horse:

**Comment by nicojs** [comment]
I think we should support `nodeunit`. I think adding an other node testrunner should be rather simple. It's both a test runner and a test framework correct?

As for `jscoverage`: we're actually working on the next major version of the `stryker-api` (should be 0.3). We will move the responsibility for code coverage instrumentation to Stryker itself, as well as the responsibility for reporting on the code coverage for node based test runners. You can see our plans in https://github.com/stryker-mutator/stryker-api/issues/4.

**Comment by simondel** [comment]
I haven't used jscoverage myself, why would you use it over something like Istanbul?

**Comment by nicojs** [comment]
Are you still interested in nodeunit support? If not, i want to close this issue for now. We haven't had anyone else that's interested in using nodeunit.
