### ISSUE TITLE
automated speed tests for functions

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1581]
I am currently working on speed test library, which would take stryker code, transform it and proceed speed test (Test setup will look like integration test [basically you run 1 integration test], so it goes through all / most functions and reports which of them takes how much time to execute).

The rule of these tests will look like:
Let's take all source code of your src, transform all functions in the way:
```js
const hello = () => {
    return "hello";
}
```
to
```js
const hello = () => {
    console.time("hello");
    return "hello";
    console.timeEnd("hello");
}
```
(this is only to represent logic of this. I will probably use some fancier function, so we can filter out ex. functions which spend less time than "xxx" or remove transposing function with name "xxx"

Would you be interested in such a solution?

**Comment by nicojs** [comment]
I wouldn't `console.time` functions all over our source code, no. It's also not as simple. Your example already has a mistake in it. `console.timeEnd("hello")` isn't getting called since the function already returned to the caller.  This would work:

```ts
const hello = () => {
    try {
      console.time("hello");
      return "hello";
    } finally {
      console.timeEnd("hello");
    }
}
```

What are you trying to achieve exactly?

**Comment by kmdrGroch** [comment]
Measure which function drastically improve execution time (I know it didn't work, it was just to show how +- it would llook like)

**Comment by kmdrGroch** [comment]
Update on the topic:
I have finally managed to parse the whole stryker repo (after tenths of failures),
Right now I am going to work on decreasing parsing time, adding a configuration.
After long thinking I guess, the whole script could be triggered by your 'perf' script, since it seems to fit the best for it.
