### ISSUE TITLE
JasmineTestRunner.spec.ts - missing properties

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1587]
![image](https://user-images.githubusercontent.com/28489774/59562906-07cb3300-9033-11e9-83f4-17065ed617bc.png)

I dunno if your VSCode cries about it too, but mine says like in 10 places, you are missing some properties or that given property doesn't even exist in Jasmine.
If it is intended, ok, if not I guess *to be fixed*

**Comment by nicojs** [comment]
It has to do with updated jest typings, correct? 

👍 we're happy to accept PRs for this.
