### ISSUE TITLE
Seems to fail with requirejs

### ISSUE THREAD

**Issue by jeznag** [stryker-mutator/stryker#159]
Hi, I'm running stryker against files that use requirejs for module support and get this error. Has anyone got Stryker working with requirejs?

`[2016-10-06 14:30:07.227] [ERROR] Stryker - One or more tests errored in the initial test run:
    Uncaught Error: Mismatched anonymous define() module: function (){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['1']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['2']++;var REGEX_ARRAY=/\[[0-9]*\]/g,helper={_getPathIndexObject:function(pathName){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['2']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['3']++;return pathName.split(/[.\[]+/);},_getUpperPath:function(pathName){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['3']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['4']++;var pathParts=_getPathIndexObject(pathName),upperPathParts=[];__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['5']++;pathParts.pop();__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['6']++;_forOwn(pathParts,function(path){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['4']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['7']++;if(path.indexOf(']')!==-1){__cov_6EmRw3RcVX0CZ_pDRevu7Q.b['1'][0]++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['8']++;var prevPath=upperPathParts.pop();__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['9']++;prevPath+='['+path;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['10']++;upperPathParts.push(prevPath);}else{__cov_6EmRw3RcVX0CZ_pDRevu7Q.b['1'][1]++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['11']++;upperPathParts.push(path);}});__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['12']++;return upperPathParts.join('.');},_isArrayName:function(pathName){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['5']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['13']++;return pathName.indexOf('[')!==-1;},_maxKeyValue:function(object){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['6']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['14']++;var intKeys=Object.keys(object).map(function(key){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['7']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['15']++;return parseInt(key,10);}),maxValue=Math.max.apply(null,intKeys);__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['16']++;return maxValue>=0?(__cov_6EmRw3RcVX0CZ_pDRevu7Q.b['2'][0]++,maxValue):(__cov_6EmRw3RcVX0CZ_pDRevu7Q.b['2'][1]++,-1);},_getPathIndex:function(pathName){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['8']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['17']++;var res=pathName.match(REGEX_ARRAY);__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['18']++;return(__cov_6EmRw3RcVX0CZ_pDRevu7Q.b['4'][0]++,_isArray(res))&&(__cov_6EmRw3RcVX0CZ_pDRevu7Q.b['4'][1]++,res.length)?(__cov_6EmRw3RcVX0CZ_pDRevu7Q.b['3'][0]++,parseInt(res[0].replace('[','').replace(']',''),10)):(__cov_6EmRw3RcVX0CZ_pDRevu7Q.b['3'][1]++,0);},_isArray:function(obj){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['9']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['19']++;return Object.prototype.toString.call(obj)==='[object Array]';},_isObject:function(obj){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['10']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['20']++;return Object.prototype.toString.call(obj)==='[object Object]';},_isFunction:function(obj){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['11']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['21']++;return Object.prototype.toString.call(obj)==='[object Function]';},_isEmpty:function(data){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['12']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['22']++;if(this._isArray(data)){__cov_6EmRw3RcVX0CZ_pDRevu7Q.b['5'][0]++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['23']++;return!!!data.length;}else{__cov_6EmRw3RcVX0CZ_pDRevu7Q.b['5'][1]++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['24']++;if(this._isObject(data)){__cov_6EmRw3RcVX0CZ_pDRevu7Q.b['6'][0]++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['25']++;return this._isEmpty(Object.keys(data));}else{__cov_6EmRw3RcVX0CZ_pDRevu7Q.b['6'][1]++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['26']++;return false;}}},_isUndefined:function(obj){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['13']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['27']++;return typeof obj==='undefined';},_isNull:function(obj){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['14']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['28']++;return obj===null;},_isEmptyString:function(obj){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['15']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['29']++;return obj==='';},_forOwn:function(object,callback,context,isArray){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['16']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['30']++;var index=-1,props=Object.keys(object),length=props.length,key;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['31']++;if(isArray){__cov_6EmRw3RcVX0CZ_pDRevu7Q.b['7'][0]++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['32']++;props=sortKeysNumerically(props);}else{__cov_6EmRw3RcVX0CZ_pDRevu7Q.b['7'][1]++;}__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['33']++;while(++index<length){__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['34']++;key=props[index];__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['35']++;callback.call(context,object[key],key,object);}__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['36']++;return object;},_isPathSimilar:function(path1,path2){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['17']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['37']++;return path1.replace(/\[[0-9]*\]/g,'[0]')===path2.replace(/\[[0-9]*\]/g,'[0]');}};function sortKeysNumerically(keys){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['18']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['39']++;Array.prototype.sort.call(keys,function(numericKey1,numericKey2){__cov_6EmRw3RcVX0CZ_pDRevu7Q.f['19']++;__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['40']++;return parseInt(numericKey1,10)-parseInt(numericKey2,10);});__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['41']++;return keys;}__cov_6EmRw3RcVX0CZ_pDRevu7Q.s['42']++;return helper;}
http://requirejs.org/docs/errors.html#mismatch
at http://localhost:9234/base/node_modules/requirejs/require.js?640c874a2dac17894676783f02cf5dd1ba4744af:143`

**Comment by nicojs** [comment]
Hi @jeznag thanks for your issue. Stryker is framework agnostic, so it should work with requirejs as well. 

Did you add requirejs to the list of files? Also it should be somewhere at the top, because stryker will use the exact order that you supply to pass through to the test runner.

If that didn't solve the issue, could you please share the stryker configuration you are using?

**Comment by sharikovvladislav** [comment]
If I want to enable requirejs support I just have to put path to requirejs in the files property?

**Comment by simondel** [comment]
This should be fixed with Stryker `0.5.4` so I'll close this issue for now. If you still have issues, could you reopen it? Thanks!
