### ISSUE TITLE
Directory /tmp/logs not created in the sandbox

### ISSUE THREAD

**Issue by gbarrion4ccor** [stryker-mutator/stryker#1600]
### Summary

When I run stryker (stryker run), I have an error because the tmp/logs directory of the sandbox doesn't exist. If I create this directories during the step "InitialTestExecutor Starting initial test run. This may take a while." the tests run.

### Stryker config

```js
module.exports = function(config) {
  config.set({
    mutate           : ['app/components/summary/**/*.vue'],
    mutator          : 'vue',
    testRunner       : 'jest',
    jest             : {
      config : require('./jest.config.js')
    },
    reporters        : ['progress', 'clear-text', 'html'],
    coverageAnalysis : 'off'
  });
};
```

### Stryker environment

```
├─┬ @stryker-mutator/core@2.0.0
│ ├─┬ @stryker-mutator/api@2.0.0
│ ├── @stryker-mutator/util@2.0.0
├─┬ @stryker-mutator/html-reporter@2.0.0
│ ├── @stryker-mutator/api@2.0.0 deduped
│ ├── @stryker-mutator/util@2.0.0 deduped
├─┬ @stryker-mutator/javascript-mutator@2.0.0
│ ├── @stryker-mutator/api@2.0.0 deduped
├─┬ @stryker-mutator/jest-runner@2.0.0
│ ├── @stryker-mutator/api@2.0.0 deduped
├─┬ @stryker-mutator/vue-mutator@2.0.0
│ └── @stryker-mutator/api@2.0.0 deduped
```

```
+-- jest@24.8.0
```

### Test runner environment

```
stryker run

```

```js
module.exports = {
  collectCoverage    : true,
  coverageDirectory  : '<rootDir>/test/coverage',
  setupFilesAfterEnv : [
    '<rootDir>/test/jest_setup',
    '<rootDir>/test/setup'
  ],
  moduleFileExtensions : [
    'js',
    'vue'
  ],
  moduleNameMapper : {
    '^~/assets/i18n/i18n_(.*).json' : '<rootDir>/test/fixtures/i18n.fixture.json',
    '^~(.*)$'                       : '<rootDir>/app$1',
    '^\@app(.*)$'                   : '<rootDir>/app$1',
    '^\@server(.*)$'                : '<rootDir>/server$1',
    '^\@shared(.*)$'                : '<rootDir>/shared$1',
    '^\@fixtures(.*)$'              : '<rootDir>/test/fixtures$1'
  },
  modulePathIgnorePatterns : [
    '/tasks/'
  ],
  transform : {
    '^.+\\.js$'   : '<rootDir>/node_modules/babel-jest',
    '.*\\.(vue)$' : '<rootDir>/node_modules/vue-jest',
    '^.+\\.svg$'  : '<rootDir>/test/fixtures/dummy.js'
  },
  testPathIgnorePatterns : [
    '/node_modules/',
    '/dist/',
    '/.nuxt/',
    '/test/coverage/'
  ]
};
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             |  8.9.4
| npm              | 5.6.0
| Operating System | MacOS Mojave 10.14.5

### Add stryker.log

20:56:50 (51166) INFO ConfigReader Using stryker.conf.js in the current working directory.
20:56:50 (51166) INFO InputFileResolver Found 12 of 1541 file(s) to be mutated.
20:56:50 (51166) INFO InitialTestExecutor Starting initial test run. This may take a while.
20:58:57 (51166) ERROR InitialTestExecutor One or more tests resulted in an error:
          ● Test suite failed to run

    ENOENT: no such file or directory, mkdir '/my-path/.stryker-tmp/sandbox2421751/tmp/logs'

      40 |     ),
      41 |     transports : [
    > 42 |       new (transports.File)({
         |       ^
      43 |         dirname          : LOG_DIR,
      44 |         filename         : 'access.log',
      45 |         prepend          : true,

      at File._createLogDirIfNotExist (../../node_modules/winston/lib/winston/transports/file.js:694:10)
      at new File (../../node_modules/winston/lib/winston/transports/file.js:92:28)
      at Object.<anonymous>.exports.createLogger (shared/logger.js:42:7)
      at Object.createLogger (app/nuxt.config.js:2:45)
      at Object.require (app/index.js:2:27)
      at Object.require (app/index.spec.js:2:18)

20:58:57 (51166) ERROR StrykerCli an error occurred Error: Something went wrong in the initial test run
    at InitialTestExecutor.validateResult (/my-path/node_modules/@stryker-mutator/core/src/process/InitialTestExecutor.js:85:15)
    at InitialTestExecutor.run (/my-path/node_modules/@stryker-mutator/core/src/process/InitialTestExecutor.js:40:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by nicojs** [comment]
This might have something to do with your tests. Does your `winston/transports/file.js` file create a temp file by any chance?

This might be fixed by adding a dummy file inside your repo `tmp/logs/.gitkeep` (`.gitkeep` is a convention often used to make sure directories exist in the repo).

**Comment by simondel** [comment]
Since we haven't heard back from you. I'm closing this issue for now.
