### ISSUE TITLE
maintenance: order in imports

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1606]
It would be a big PR to order all imports in files. The order would be like this:

External imports (all packages) (sorted alphabetically)
Internal imports (files in that package) (also sorted alphabetically)

It will make everything a bit more readable I guess, and for sure more convenient and easier to access

**Comment by nicojs** [comment]
Is there an auto-fix tslint setting for it? If not, I would be against this fix. @simondel would you agree with strict ordering of imports?

**Comment by kmdrGroch** [comment]
@nicojs auto fix works just fine, it is really easy to do (i believe i have even prepared a branch for that PR...)

**Comment by nicojs** [comment]
In that case: I'm all for it. Could we also make sure that imports of core nodejs modules are above imports of other externals?

**Comment by kmdrGroch** [comment]
I can make it like this:

external modules from node (sorted)

external modules other than node ones (sorted)

internal modules (sorted)

(this new line between is intended. If no new lines are added it will look like:
external modules (all, sorted)
internal modules (sorted)
)

**Comment by kmdrGroch** [comment]
@nicojs What about this ^? (I haven't found an option to autofix to the state you want. I can only do default one / manually sort them)

**Comment by nicojs** [comment]
Than let's do the default one, if that is the autofixable one. We need autofix, otherwise you'll go mad :)

**Comment by kmdrGroch** [comment]
Sure. 'Delivery is assumed to be in 5 days' ;D
