### ISSUE TITLE
maintenance: export default names vs file names

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1607]
Maybe a bit controversial subject, so I am waiting for your opinion on that.
I do believe that when you are doing 'export default' the function name (or class name) should be the same as a file name. For example, you have a file called 'babelReporter' but you export 'babelProvider', sth like this.
and imports, I guess it should be used the same way:

import babelReporter from 'babelReporter'

instead of

import babelProvider from 'babelReporter'

Well, it's only my suggestion,
feel free to comment and give your feedback

**Comment by nicojs** [comment]
I agree with that. I think if it's not in sync, it got out of sync without us realizing.

**Comment by kmdrGroch** [comment]
It is pretty easy to solve. (I would really like to have permission to do all stuff with exports and imports at once, but it'll be a huge PR [fixing that + order in imports] (mostly order in imports))

**Comment by nicojs** [comment]
You mean permission to do #1606 ? Go ahead, 2 birds with one stone

**Comment by kmdrGroch** [comment]
I can do it as soon as we clarify #1606

**Comment by nicojs** [comment]
Since #1606 is solved, can we close this?

**Comment by kmdrGroch** [comment]
yeah forgot to close that, nice catch! :)
