### ISSUE TITLE
perf: reduce next stryker runs

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1610]
I have been lurking through issues and files, and I have found, that we could improve stryker performance, by checking, which files have been updated since the last commit.

The easiest way would be:
`git diff HEAD^ HEAD --name-only`

we could use this command in JS simply with exec or spawn:

`const child = require('child_process');`

`child.spawnSync('git', ['diff', 'HEAD^', 'HEAD' ,'--name-only']).stdout.toString()`

`git diff HEAD^ --name-only` with staged change
![image](https://user-images.githubusercontent.com/28489774/60270447-bbb0a600-98f0-11e9-8728-0c20d28d824c.png)

`git diff HEAD^ HEAD --name-only` with staged change
![image](https://user-images.githubusercontent.com/28489774/60270460-c2d7b400-98f0-11e9-905a-b1c6a5b0343e.png)

`git diff HEAD^ --name-only` without staged change
![image](https://user-images.githubusercontent.com/28489774/60270472-c9662b80-98f0-11e9-92a3-9cf0495ccac7.png)

I guess it can be customizable for user, for example, to choose between `git diff HEAD^ HEAD --name-only` and `git diff HEAD^ --name-only` or to switch it off.

**Comment by kmdrGroch** [comment]
After small rethinking, options would be `enableGitOptimisation: boolean | string = false`
if true - by default it would be `HEAD`.  `string` is just an initial commit from which it should watch files and stryker will check all files between that commit and what is now  `git diff string --name-only` command

**Comment by Djaler** [comment]
What about merging the results?

**Comment by kmdrGroch** [comment]
@Djaler merging the results?

**Comment by Djaler** [comment]
I mean reports

**Comment by kmdrGroch** [comment]
I don't quite understand @Djaler what you mean :/

**Comment by Djaler** [comment]
I mean that by running stryker only for changed files you will get report only for this files. But we need to see the whole picture

**Comment by kmdrGroch** [comment]
@Djaler So we have two options...
1. Combine reports - it will be super hard to achieve (at least thinking about it right now)
combining reports would have to get some metadata of previous mutation (JSON or another format),
then it should replace data of files that were changed, then it should again calculate mutation score for folders
2. Do not combine reports - it has to be fast check, so let's check and give output only for files that were changed (then the user can have two stryker scripts 'full' and 'git optimized')

**Comment by Djaler** [comment]
I think this is related to #322

**Comment by kmdrGroch** [comment]
It is slightly, yea. I think we should finish #1514 for now and maybe try this, at least using point '2' so we have an experimental version of this feature, and then we can try changing '2' into '1' :)

**Comment by nicojs** [comment]
Great discussion here ❤️ 

The problem with only running Stryker on changed files can not always be trusted. Let's say you only change test files in a PR. There is no way to verify exactly which mutatations should be retested. So it would only works for changes made to source files to be mutated.

I think it's pretty easy to add a small part of code to your stryker.conf.js file to do this. Or use the [stryker-diff-runner](https://github.com/tverhoken/stryker-diff-runner) by @tverhoken that does exactly this.

> Combine reports - it will be super hard to achieve (at least thinking about it right now)

I think this is the easy part. In fact, we've created the [mutation-testing-report-schema](https://github.com/stryker-mutator/mutation-testing-elements/tree/master/packages/mutation-testing-report-schema) with exactly this goal in mind. It's basically merging the `files` json object. This is an example: https://github.com/stryker-mutator/mutation-testing-elements/blob/86bd8050f7e0bd9748b97237e26d596407331266/packages/mutation-testing-report-schema/testResources/strict-report.json#L7-L43
