### ISSUE TITLE
Newbie - Unable to generate HTML report

### ISSUE THREAD

**Issue by AlexTeixeira** [stryker-mutator/stryker#1612]
### Summary

I'm newbie with stryker and I'm not able to generate/find the mutation html report :(
Is not a big problem because I have the console result, but HTML is better for reading and to look at the other mutations :)

### Stryker config

```js
module.exports = function(config) {
  config.set({
    mutate: ['app/src/**/*.ts'],
    mutator: "typescript",
    packageManager: "npm",
    reporter: ['html', 'progress', 'event-recorder'],
    testRunner: "jest",
    tsconfigFile: "./tsconfig.json",
    coverageAnalysis: "off"
  });
};

```

### Stryker environment

```
+-- @stryker-mutator/core": "^2.0.0
+-- @stryker-mutator/jest-runner": "^2.0.0
+-- @stryker-mutator/typescript": "^2.0.0
```

## Test Runner

```

+--jest": "^24.8.0
+-- karma@x.x.x
+-- angular-cli@x.x.x
+-- react-scripts@x.x.x
```

### Test runner environment

NPM Test as configured simply :` test: jest`

JEST Config file

```
module.exports = {
    roots: ['app/'],
    transform: {
        "^.+\\.tsx?$": "ts-jest"
    },
    collectCoverageFrom: ["app/src/**/*.{ts,js}"],
    testRegex: 'test/unit/.*\\.ts?$',
    moduleFileExtensions: ['ts', 'js', 'json'],
    collectCoverage: false
};
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | 12.1.0
| npm              | 6.9.0
| Operating System | macOS Mojave 10.14.5

### Add stryker.log

[stryker.log](https://github.com/stryker-mutator/stryker/files/3337664/stryker.log)

**Comment by kmdrGroch** [comment]
I am using config like this:
```
module.exports = function(config) {
  config.set({
    mutator: "typescript",
    packageManager: "npm",
    reporters: ["html", "clear-text", "progress"],
    testRunner: "mocha",
    transpilers: ["typescript"],
    testFramework: "mocha",
    coverageAnalysis: "off",
    tsconfigFile: "tsconfig.json",
    mutate: ["src/**/*.ts"]
  });
};
```
and html reporter works. Maybe try adding 'transpilers' and 'testFramework'?

**Comment by AlexTeixeira** [comment]
thank, it revealed the folder with the files.
Seems that with hidden folder activated or by terminal, the folder did not appear.

thanks :)

**Comment by nicojs** [comment]
Great to hear you found the report! Have fun mutation testing 👽.

For anyone else facing this problem, the option is called `reporters` (not `reporter`). This changed since a year or so ago and got deprecated before we removed it completely in the 1.0 release.
