### ISSUE TITLE
Missing final CRLF after progress reporter finishes

### ISSUE THREAD

**Issue by bkimminich** [stryker-mutator/stryker#162]
A small cosmetic bug that happens when using `reporter: ['html', 'progress']`:

![image](https://cloud.githubusercontent.com/assets/3531020/19183420/7fd0584c-8c78-11e6-8f7d-ebc674aeee62.png)

The `clear-text` reporter does an initial CRLF on the sysout using this helper method:

```
private writeLine(output?: string) {
    this.out.write(`${output || ''}\n`);
  }
```

That's why it doesn't happen when using `clear-text` together with `progress`:

![image](https://cloud.githubusercontent.com/assets/3531020/19183535/19bbc50e-8c79-11e6-8b69-35693ac8f5c5.png)

**Comment by nicojs** [comment]
I think the easiest way to fix this is to add this method to add this method to the `ProgressReporter`

```
onAllMutantsTested(): void { 
   console.log();
}
```

Not sure if this would help in all situations though.

**Comment by nicojs** [comment]
Merged into the master brache, will be released later this week.
