### ISSUE TITLE
Support excluding files via System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute

### ISSUE THREAD

**Issue by brooknovak** [stryker-mutator/stryker#1622]
People are familiar with the System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute to mark files for exclusion of test coverage.
Plus we want to report the line coverage using the inbuilt dotnet test coverage tooling, for our most of CI/CD pipeline cases (where we use the ExcludeFromCodeCoverageAttribute). And use Stryker for pull request builds (since it really slows the build time to a point where it isn't viable to run on every build)

**Comment by nicojs** [comment]
Hi, @brooknovak 👋 welcome to the club.

I believe this is an issue related to [Stryker.NET](https://github.com/stryker-mutator/stryker-net). Feel free to [open an issue there](https://github.com/stryker-mutator/stryker-net/issues/new/choose)
