### ISSUE TITLE
trasnpile with esm

### ISSUE THREAD

**Issue by rhpereda** [stryker-mutator/stryker#1639]
**Question**
Is possible to run stryker mutation tests with ESM for load the ES6 code?

Every time i run it agains a small simple nodejs project that use ESM, stryker throws an exception related to the imports and exports syntax used is ES6.

Any help will be appreciated.

Thanks in advance

**Comment by kmdrGroch** [comment]
@rhpereda what about using babel transpiler? Stryker doesn't support `import` and `export` since Node doesn't support it too.

**Comment by rhpereda** [comment]
Thanks for the reply, use babel could be one option, but is not that simple, i will need to rewrite some code for it. That's why i decided to ask if the mutator support esm as es6 loader, but suppose the easier and faster way to go is migrate to babel. Thanks!! 
Appreciate the help!

**Comment by kmdrGroch** [comment]
rewrite code for babel? I think you would only need to change some config files and thats all (maybe I am missing a point since I have never used esm

**Comment by nicojs** [comment]
Hi @rhpereda esm is certainly something that we can support. Which test runner are you using and how is it registering esm in normal testing use cases? Then we can figure out how Stryker should load it. 

Generally, we like to keep your testing configuration in line with how Stryker runs your tests.

**Comment by rhpereda** [comment]
Hi @nicojs, thanks for the reply and the interest to support ESM in stryker. In answer to the questions you made:
- My test runner is mocha
- i run the unit test like this: `NODE_ENV = test mocha -r esm ./test/unit --recursive`, and the integration in a similar way.
- Also use nodemon for dev, and executed like this: `nodemon start.js`, where the` start.js` file contains this configuration:
`
require = require ("esm") (module)
const server = require ('./ server.js'). default
`
- Last but not lest, the app use pm2 to serve in production, like this: `pm2 start ecosystem.config.js --env production && pm2 logs --raw`, and the` ecosystem.config.js` file calls the `start.js` file mentioned in the previous point.

If you need anything else, do not hesitate to reach me out !!
Thanks in advance ...

**Comment by nicojs** [comment]
Thanks for your reply.

Did you try the `require` mocha options in stryker.conf.js? It is documented here: https://github.com/stryker-mutator/stryker/tree/master/packages/mocha-runner#configuring

I think that should solve the problem.

**Comment by rhpereda** [comment]
Hi @nicojs , i manage to make it work using the `testRunner: "command"` option, like this:
`module.exports = function (config) {
    config.set({
        thresholds: {
            break: 80
        },
        mutator: "javascript",
        packageManager: "npm",
        reporters: ["html"],
        testRunner: "command",
        commandRunner: {
            command: 'npm test'
        }
    });
};`

Maybe this can be included in the documentation to make it more clear!!

Thanks for all your help!!!

**Comment by nicojs** [comment]
The command runner should always works yes. The mocha runner will be a lot more performant and should work with ESM as well. I'll add the setup with ESM to the [stryker-handbook](https://github.com/stryker-mutator/stryker-handbook). Is that where you were looking @rhpereda?

**Comment by rhpereda** [comment]
Actually no, i was looking at this: https://github.com/stryker-mutator/stryker/tree/master/packages/core#readme. I wasn't able to found how to do this in the handbook, also the handbook documentation only mention three guides: https://github.com/stryker-mutator/stryker-handbook#readme, would be really helpful to add the commandRunner in here. I wasn't able to make it work with mocha-runner thats why i decided to go with the commandRunner. I can't share the code, but if you wan to i can make a copy removing all the confidential lines, just let me know.

**Comment by screendriver** [comment]
Same problem here. I'm using `TypeScript` together with `Mocha` and compile my files to `ESM` (so I set `"module": "esnext"` in my `tsconfig.json`). To let my tests run in Node.js directly with `esm` I require the [esm](https://github.com/standard-things/esm) package

### .mocharcjs

```js
module.exports = {
  spec: 'test/unit/**/*.test.*',
  require: ['esm', 'ts-node/register/transpile-only'],
  extension: ['ts'],
};
```

And my `stryker.conf.js` looks like that

```js
module.exports = function(config) {
  config.set({
    mutator: 'typescript',
    packageManager: 'yarn',
    reporters: ['clear-text', 'dots', 'dashboard'],
    testRunner: 'mocha',
    transpilers: ['typescript'],
    testFramework: 'mocha',
    coverageAnalysis: 'off',
    tsconfigFile: 'tsconfig.json',
    mutate: ['src/**/*.ts'],
  });
};
```

I also tried something like that

```js
module.exports = function(config) {
  config.set({
    mutator: 'typescript',
    packageManager: 'yarn',
    reporters: ['clear-text', 'dots', 'dashboard'],
    testRunner: 'mocha',
    transpilers: ['typescript'],
    testFramework: 'mocha',
    mochaOptions: {
      spec: ['test/unit/**/*.test.*'],
      require: ['esm', 'ts-node/register/transpile-only'],
    },
    coverageAnalysis: 'off',
    tsconfigFile: 'tsconfig.base.json',
    mutate: ['src/**/*.ts', '!src/cdk/**/*'],
  });
};
```

but it didn't work. I always get a 

```sh
13:43:47 (16364) ERROR InitialTestExecutor One or more tests resulted in an error:
        SyntaxError: Cannot use import statement outside a module
/Users/me/project/.stryker-tmp/sandbox8941033/test/unit/foo.test.js:1
(function (exports, require, module, __filename, __dirname) { import { assert } from 'chai';
```

**Comment by kmdrGroch** [comment]
Is this issue still relevant?

**Comment by rhpereda** [comment]
Hi @kmdrGroch , currently i'm not working on that, i was able to make it work as i explained before, but maybe @screendriver has something else to add.

**Comment by simondel** [comment]
Hi! I'm closing this issue for now. If it still persists with Stryker version 4, please open a new issue. Thanks!

**Comment by rhpereda** [comment]
Sorry for the late response. I think it is fine to close it. If the issue arise again someone will open a new ticket....

Thanks in advance....

**Comment by itzhaolin** [comment]
I have same question when `npx stryker run`
![image](https://user-images.githubusercontent.com/37429047/148024114-21c0b7b5-29fa-4aae-89b4-3ce78a4fca94.png)
