### ISSUE TITLE
Add support for jasmine-node test runner

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#164]
We should add support for the jasmine-node test runner.

See https://github.com/bkimminich/juice-shop/issues/219

Follow progress non the `164-feat-jasmine-runner` branch.

Still todo:

- [ ] Add unit tests (worked with integration tests so far)
- [ ] Support the jasmine test framework ( + IT).
- [ ] Add an integration test to run stryker with node-jasmine (integrationTest module)

**Comment by alinturlac** [comment]
Support for simply jasmine as a runner would also be amazing. I have a node back-end and I run my tests by running `jasmine --config=test/support/jasmine.json`, so none of the runners work for me

**Comment by simondel** [comment]
What is your usecase for running jasmine for a node back-end instead of something else?

**Comment by alinturlac** [comment]
jasmine was the framework i was familliar with and the back-end is exclusively a set of APIs so I went with that, and also managed to configure nyc with it. Since jasmine now comes with its own runner, I kept it simple. I've tried moving to karma prior to writing on this issue, but it doesn't seem to work with tests that don't use a browser. Is there a better way? Thanks!

**Comment by nicojs** [comment]
@alinturlac no I think you have an excellent use case. The jasmine test runner plugin should be fairy strait forward to implement as well. Could you provide an example project of your code? Maybe you use plugins or something?

**Comment by alinturlac** [comment]
@nicojs here's my jasmine-config:
```
{
  "spec_dir": "src/test",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "support/global_spec_setup.js",
    "helpers/**/*.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}
```

where the global_spec_setup.js just makes sure that the tests use PromiseMock instead:

```
'use strict';
const PromiseMock = require('promise-mock');
const mock = require('mock-require');

beforeEach(() => {
	PromiseMock.install();
});

afterEach(() => {
	Object.keys(require.cache).forEach((key) => {
		delete require.cache[key];
	});
	mock.stopAll();
	PromiseMock.uninstall();
});
```
And basically that's it, the rest is simply test code that's run through `jasmine --config=./jasmine-config.json`
