### ISSUE TITLE
Problem running Stryker.

### ISSUE THREAD

**Issue by RuudVerhoef** [stryker-mutator/stryker#1645]
I am trying to run Stryker but I must be doing something wrong as I can not get it to work properly.

I am running Stryker using Mocha 6.1.4 as a test runner.  As I do not want to install anything globally I installed Stryker using the command: "npm install --save-dev @stryker-mutator/core".

After going through the set up my stryker.conf.js looks like:

```
module.exports = function(config) {
   config.set({
     mutator: "javascript",
     packageManager: "npm",
     reporters: ["clear-text", "progress"],
     testRunner: "mocha",
     transpilers: [],
     testFramework: "mocha",
     coverageAnalysis: "perTest",
     files: ['test/controllers/auth.controller.spec.js'],
     mutate: ['controllers/auth.controller.js'],
   });
};
```

I added the files and mutate array's myself after doing a bit of googling after I got some errors.

To get a more complete picture my dev-dependencies now look like:
```
"devDependencies": {
    "@stryker-mutator/core": "^2.0.2",
    "@stryker-mutator/javascript-mutator": "^2.0.2",
    "@stryker-mutator/mocha-framework": "^2.0.2",
    "@stryker-mutator/mocha-runner": "^2.0.2",
    "mocha": "^6.1.4"
  }
```

**Now the issues:**
When I run: "npx stryker run" I get this output:
![image](https://user-images.githubusercontent.com/43232271/61311824-6b45ad80-a7f7-11e9-8736-650b14c25851.png)

To me this looks like it can't find the file with the tests in it or the file containing the code that needs to be mutated.

My file structure is: 
![image](https://user-images.githubusercontent.com/43232271/61311956-bbbd0b00-a7f7-11e9-9a08-90ace672a430.png)

What could be causing this?

**Comment by nicojs** [comment]
You're specifying `files` here. With `files` you select _all files needed to run your tests_. The default is to use your local git repository, which is normally what you want. So removing it would probably fix your issue. This is documented here: https://github.com/stryker-mutator/stryker/tree/master/packages/core#files-string

**Comment by RuudVerhoef** [comment]
I was trying to run it in a non-git project.

I just "git init" the project and removed the files array, Running Stryker then yields this error:
![image](https://user-images.githubusercontent.com/43232271/61327467-46623200-a819-11e9-868f-342f28133596.png)
Besides the error, I also wonder what the initial test run does. It states it ran 1 test but I know there are 3 tests written (split up in 2 files).

I do not know if it matters but I am using Windows as my operating system (webpack is not part of my dependencies (found this could be a cause according to Google)).
