### ISSUE TITLE
Mutants generated. Is it possible to know ?

### ISSUE THREAD

**Issue by gohackfelipe** [stryker-mutator/stryker#1646]
**Question**

Hi guys,
Some questions:

**1.** Is it possible to know how many mutants will be generated for a specific javascript code ? 

**2.** In positive case, could I know what type of mutation was applied? 

I'd know this information before to run the _stryker run_ . Could guys give me an ideia for how get it ?

**Comment by kmdrGroch** [comment]
Isn't stryker show how many mutants are created?
When you get result, you see (or at least saw in previous versions), which mutation was applied

However you can't get this number before running stryker. You could estimate it on your own, by checking your code, but for bigger projects it would be impossible.

I dont know why would you like to know number of mutants before running stryker, but if @nicojs agrees, we could make some 'fast audit' to check how many mutants can be generated, and what type (the second one requires bigger PR i think)

**Comment by gohackfelipe** [comment]
Actually I'm studying how to build something like stryker-runner.
My intention is to build an artifact able to run any source to mutate, unit test using your own dataset as webserver api.  

To understand how many mutants will be generated get a batch processing flexibility. 

However, understanding your answer, I have found that this is not a good way to keep on.

**Comment by kmdrGroch** [comment]
Basically, as I understand, Stryker first of all generate all mutants and count them. If you want to do it without generating them, honestly I don't know the best way to achieve it.

**Comment by nicojs** [comment]
As @kmdrGroch explained, there is currently no way to know what mutants will be generated.

I don't truly understand your reason for it. Do you want to badge process? It's probably easiest to do this on file level using the `mutate` property to steer which file you would like to mutate in a badge.

**Comment by simondel** [comment]
This is not something we will be supporting for now. So I'm closing this issue for now.
