### ISSUE TITLE
Do not mutate types

### ISSUE THREAD

**Issue by Djaler** [stryker-mutator/stryker#1647]
Just look at this report part:
![image](https://user-images.githubusercontent.com/7964583/61434297-4019a600-a93e-11e9-8f37-862f15c232ea.png)

**Stryker config**

```js
module.exports = function(config){
  config.set({
        mutate: ['src/**/*.ts'],
        mutator: 'typescript',
        packageManager: 'npm',
        reporters: ['html', 'progress', 'event-recorder'],
        testRunner: 'jest',
        coverageAnalysis: 'off',
    });
}
```

**Stryker environment**

```
@stryker-mutator/core@2.0.2
@stryker-mutator/html-reporter@2.0.2
@stryker-mutator/jest-runner@2.0.2
@stryker-mutator/typescript@2.0.2
```

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker/files/3405064/stryker.log)

**Comment by kmdrGroch** [comment]
I don't think it is a bug. Since you are using constants in interface, it is like you would make class
```
class sortableHeader {
   sortable: true
}
```
so it is normal it will be mutated to `false`.

If you don't want it to be mutated, use `.d.ts` files. Otherwise i think it is correct to mutate it :/

**Comment by Djaler** [comment]
I don't think so. Such things will not compile at all if I'll have some implementations for this interfaces

**Comment by simondel** [comment]
Thanks for bringing this to our attention! This is something we should fix in my opinion.

**Comment by nicojs** [comment]
Although I agree with the sentiment, wouldn't the better solution be to mark the mutant as `CompileError`? 

If you have an `interface` with a literal value. It should be either tested, or throw a compile error. That way you know the interface is actually being used correctly.

The TypeScript transpiler plugin reports compile errors, but only if they happen in the same file as mutation. This is done for performance reasons. WIth the new architecture of using mutation switches (still no progress on that yet) we probably will support a `TypeCheckPlugin` type. I would suggest that the TypeChecker plugin will have multiple settings so you can tune performance and correctness.

If people here don't agree, I would be happy to review & merge the PR of @kmdrGroch

**Comment by Djaler** [comment]
@nicojs I think this PR can be a good temporary workaround for now, because, as you say, mutation switches are only a plans now.

**Comment by icehaunter** [comment]
I also ran into a similar error with mutations in function overload declarations:
![image](https://user-images.githubusercontent.com/1357760/64763993-cec72f80-d549-11e9-81f7-3eb205918f42.png)

**Comment by nicojs** [comment]
> I think this PR can be a good temporary workaround for now, because, as you say, mutation switches are only a plans now.

Agreed. It might be changed in the future, but for now, let's merge this in. Thanks for the feedback 👍  And thanks to @kmdrGroch for implementing
