### ISSUE TITLE
update and integrate `stryker-mutator/stryker-plugin-seed`

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1658]
I can see, there is a repository called stryker-mutator/stryker-plugin-seed, but it seems to be outdated.

We could add it's updated version here in some `modding` or `development` section.

**Comment by nicojs** [comment]
I think we should delete it. This repo was mainly there to help us start new repositories before we migrated everything in 1 monorepo using lerna. Plugin creators tend to make their own setup anyway. I've created a small document here: https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md that explains how to create and use plugins. That should be sufficient. I'm archiving the stryker-plugin-seed repo.

Feel free to comment if you think this isn't the right decision.
