### ISSUE TITLE
Option to disable initial test run

### ISSUE THREAD

**Issue by Djaler** [stryker-mutator/stryker#1659]
On my CI system I always run Stryker after the normal run of tests. So, I don't need Stryker to run this tests again.
What about simple command line flag `--disableInitialRun` or something similar?

**Comment by kmdrGroch** [comment]
@Djaler Stryker has to run tests again in order to check for mutants are being killed or not.
Unless I don't understand your question.

**Comment by Djaler** [comment]
I talk about initial run (which Stryker use to check, if there are no errors without mutants)

**Comment by nicojs** [comment]
I understand the sentiment, but the initial run is _vital for mutation testing_. 

I know you can run your tests and they will pass, but it is important to know that Stryker can do so as well. Stryker runs your tests very different than you yourself do. It creates sandboxes and copies your files to there to create isolation. The sandboxing of your files alone can be enough to make your tests fail. The initial test run also uses a sandbox to mimick this scenario and make sure that it can run normally.

The initial test run is also the place where coverage analysis is done, so skipping it would force users to use coverage analyisis `'off'`.

**Comment by Djaler** [comment]
Yeah, I agree that tests can fail in sandbox (#1590)

**Comment by nicojs** [comment]
Ok, closing this issue for now. If someone thinks it is a mistake please let us know
