### ISSUE TITLE
repo (mostly docs) cleanup

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1667]
We should make some clean up repository, and possibly update documentation a bit.

Cleanup:
- `docs` folder should be removed if it is not needed.

Documentation:
there is an issue in https://github.com/stryker-mutator/stryker/tree/master/packages/util
since `download` and `node` badges are not displayed as intended

Updating `main` README / somehow merging with `core` README. Since they are +- 1 to 1.
For example:
```
Getting started
For the quickstart, see quickstart.

Usage
For details on the stryker run command and others, see stryker's readme

Configuration
See the stryker's package readme for all config options.

Supported mutators
See our website for the list of currently supported mutators.
```
This part can be easy replaced by `core` README. Some tweaks might be needed tho

We should also consider making 1 unified README for stryker project instead of making tens of them (or at least reduce the amount).

Alternative option to the previous one is to make `main` README a bunch of links (like it is now) to our website, and making better docs on website (including all READMEs [or at least the most important parts]). This unfortunately will again increase number of unnesessary files.

**Comment by gugacavalieri** [comment]
Hey Guys!

I just took a quick look at the repo and I think all the docs moved to the handbook repo, am I right?
(https://github.com/stryker-mutator/stryker-handbook#readme)

And the `docs` folder in the main repo hasn't been updated in two years.

How are you handling documentation? Maybe I could give a hand with that :smile:

**Comment by kmdrGroch** [comment]
thanks, @gugacavalieri for initiative! I would like @nicojs or @simondel to opinion that too, but for now, I think adding documentation for #1731 and #1623 would be nice :3 (You can PR to my repo so I'll add it). Also it's a bit hard for me to tell where exactly docs are. Since half of them are in handbook like you said, but also a big part of them is on the website https://github.com/stryker-mutator/stryker-mutator.github.io. So it's a bit messy in my opinion, but I can't do anything without their permission :/ (any idea, of course, is good!)

**Comment by gugacavalieri** [comment]
Cool !

I will take a look at the docs then and check where the main part is also looking for some typos or grammar mistakes :)

It's feels kind of messy right now but I think we might be able to organize it!

Let's see what @nicojs and @simondel think as well

**Comment by kmdrGroch** [comment]
@gugacavalieri My main point is to change the amount of docs. We have docs in 3-4 different places and so it's messy and hard to maintain (just look on main repo doc)
```
Introduction
For an introduction to mutation testing and Stryker's features, see stryker-mutator.io.

Getting started
For the quickstart, see quickstart.

Usage
For details on the stryker run command and others, see stryker's readme

Configuration
See the stryker's package readme for all config options.
```

There are links to at least 2 places with +- the same docs

+ https://github.com/stryker-mutator/stryker/blob/master/packages/core/README.md#configuration
could be a bit 'more compact', alphabetized (always easier to look for sth which is in some order).


again `core/readme` has a line:
`Please follow the quickstart on the website.`

too much information in too many places. It can be messy sometimes ._.

**Comment by gugacavalieri** [comment]
@kmdrGroch I just took a quick look and the docs on the website are just a quick start.

Most of the technical details are in the `core/readme` file. So I think that is the one we should improve then.

Although sometimes the `readme` redirects the user to the website or to the handbook, maybe we could include all the info that is related to the `core` in this `readme` file and maybe start improving it with a `Table of Contents` section should be a good idea.
