### ISSUE TITLE
All tests timing out when using Stryker & JEST with Typescript?

### ISSUE THREAD

**Issue by shaunswales** [stryker-mutator/stryker#1680]
**Question**
Have you seen all tests timeout before when using Stryker & JEST with Typescript?

**Stryker environment**
```
    "@stryker-mutator/core": "^2.0.2",
    "@stryker-mutator/html-reporter": "^2.0.2",
    "@stryker-mutator/jest-runner": "^2.0.2",
    "@stryker-mutator/typescript": "^2.0.2",
    "@stryker-mutator/babel-transpiler": "^2.0.2",
```

```
    "jest": "^24.8.0",
    "jest-emotion": "^10.0.11",
    "jest-fetch-mock": "^2.1.2",
    "jest-html-reporter": "^2.5.0",
    "@types/graphql": "^14.2.0",
    "@types/jest": "^24.0.13",
    "@types/react": "^16.8.19",
    "@types/react-dom": "^16.8.4",
    "@types/react-router-dom": "^4.3.3",
    "@types/single-spa-react": "^2.8.3",
    "@typescript-eslint/eslint-plugin": "^1.10.2",
    "@typescript-eslint/parser": "^1.10.2",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.6",
    "babel-plugin-emotion": "^10.0.9",
```

**Additional context**

I have used the same version of plugins on a repository which is just targeting normal JS files and it works fine. 

I only seem to be having this issue with Typescript.

Also, I have tried doing minimal files and I still get the same results, timeouts.

**Comment by kmdrGroch** [comment]
@shaunswales thanks for reporting this. Is it possible for you to provide us some repository, explanatory code to check this?

**Comment by simondel** [comment]
Hi! Could you post your Stryker.conf.js?

If there's a `translilers` option in there, could you try running it without it?

**Comment by shaunswales** [comment]
`  mutate: [...thefileList],
    reporters: ['html', 'clear-text', 'progress', 'dashboard'],
    mutator: 'typescript',
    tsconfigFile: 'tsconfig.json',
    packageManager: 'yarn',
    testRunner: 'jest',
    testFramework: 'jest',
    coverageAnalysis: 'off',
    jest: { enableFindRelatedTests: false },
    htmlReporter: { baseDir: 'reports/mutation' },
    thresholds: { high: 90, low: 75, break: 70 },
    allowConsoleColors: true,
    timeoutMs: 60000,`

That is as it stands at the moment, with the mutate files I have tried everything and a limited set of files but still getting the same issues.

**Comment by mike-dazn** [comment]
We faced this issue.  We are using `ts-jest` and it was taking longer than the default stryker timeout to do it's transpilation.  Setting `timeoutMS: 30000` seems to solve the issue.

**Comment by shaunswales** [comment]
Sorry yeah, I forgot I had this issue still open...

We found a similar solution where we tweaked the following options to get it to stop timing out:

```
{
    timeoutMs: 30000,
    timeoutFactor: 4,
    maxConcurrentTestRunners: 6
}
```

**Comment by brodybits** [comment]
I think it would be nice to document this as a hint somewhere. Just saying this as an external user and occasional contributor.
