### ISSUE TITLE
As part of Init, add .styrker-tmp folders to gitignore

### ISSUE THREAD

**Issue by GeorgeWL** [stryker-mutator/stryker#1683]
**Is your feature request related to a problem? Please describe.**

By default the stryker temp folders don't seems to be git ignored, this can be frustrating if one forgets to set it as git ignored. 

**Describe the solution you'd like**

detect gitignore files in solution and append 

```bash
# stryker temp files
*.stryker-tmp
```
or use the console to Warn the User to gitignore the temp folder generated by Stryker as part of the `Styrker init` process.

**Describe alternatives you've considered**

1. manually change
2. remind user with console message

**Additional context**

**Comment by kmdrGroch** [comment]
@GeorgeWL do I understand you would like to add "*.stryker.tmp" to the .gitignore file? Or inform the user that he should do it?

**Comment by GeorgeWL** [comment]
the former, automatically.

The alternative of warning the user might make sense though.
