### ISSUE TITLE
Stryker run command is throwing Emit error!

### ISSUE THREAD

**Issue by JoyalJoyMadeckal** [stryker-mutator/stryker#1684]
I am trying run stryker on my repository. Its in react js. It has thrown me a number of lint errors. After fixing all the lint errors in my code I am getting the below error
"ERROR StrykerCli an error occurred Error: Emit error! Could not emit file"

**Comment by simondel** [comment]
What command are you running that causes this issue?
Also, does it log anything else?

Ps: if you already have a stryker.conf.js, could you post it?

**Comment by JoyalJoyMadeckal** [comment]
Stryker installation was successful and configured stryker. Then on running "stryker run" I am getting this error. Image Attached
![image](https://user-images.githubusercontent.com/54176822/63318621-b68e3700-c334-11e9-99d1-b3e7978bf174.png)

My stryker. conf.js file
![image](https://user-images.githubusercontent.com/54176822/63318669-e2a9b800-c334-11e9-9fe5-0251db43685b.png)

**Comment by simondel** [comment]
What does Jest do your Typescript transpiling? If so, you can remove the transpilers and tsconfig settings from the Stryker config.

**Comment by JoyalJoyMadeckal** [comment]
Jest is my test framework. 
This is the error I am getting
![image](https://user-images.githubusercontent.com/54176822/63321761-4802a680-c33f-11e9-8f90-c1670ae092b1.png)

I will remove the transpiler and try.
Our jest is configured in tsconfig

**Comment by JoyalJoyMadeckal** [comment]
I have removed the transpiler and have run.
Now I am getting the following error.
![image](https://user-images.githubusercontent.com/54176822/63322940-366ece00-c342-11e9-9140-4e92d644399e.png)

**Comment by JoyalJoyMadeckal** [comment]
Can anyone help me out here?

**Comment by JoyalJoyMadeckal** [comment]
[joyal.zip](https://github.com/stryker-mutator/stryker/files/3546419/joyal.zip)
This is my application where I am getting the error on srunning Stryker. 
Can anyone jump into this?

**Comment by bejugamSandeep** [comment]
> [joyal.zip](https://github.com/stryker-mutator/stryker/files/3546419/joyal.zip)
> This is my application where I am getting the error on srunning Stryker.
> Can anyone jump into this?

Can someone help us on this issue. You will be able to reproduce the issue directly when you download attached zip file.

**Comment by nicojs** [comment]
This issue was republished under #1691. I've found the issue(s) and reported it in that issue. Closing this as well. 

Thanks for providing a zip file for us to check out. That works a lot better 😅
