### ISSUE TITLE
How to run stryker from outside the project?

### ISSUE THREAD

**Issue by vitalets** [stryker-mutator/stryker#1686]
**Question**

I want to run stryker (js) on my project from time to time.
For that reason I don't want to keep styker and it's dependencies in my package.json.
First I tried to globally install `stryker-cli` and created `stryker.conf.js` inside my project. But that is not enough. It asks to install stryker locally anyway:
```
Do you want to install Stryker locally? no
```
Then I've created `/stryker-run` directory next to `/myproject` and tried to run stryker from there. I've set correct `files` in config pointing to my project. But that also did not work - mocha cant find files.
```
16:10:44 (88714) ERROR StrykerCli an error occurred Error: Error: [MochaTestRunner] No files discovered (tried pattern(s) [
  "test/setup.js",
  "test/specs/*.spec.js"
]). Please specify the files (glob patterns) containing your tests in mochaOptions.files in your stryker.conf.js file.
Error: [MochaTestRunner] No files discovered (tried pattern(s) [
  "test/setup.js",
  "test/specs/*.spec.js"
]). Please specify the files (glob patterns) containing your tests in mochaOptions.files in your stryker.conf.js file.
    at MochaTestRunner.legacyDiscoverFiles (/Users/vitalets/projects/stryker-run/node_modules/@stryker-mutator/mocha-runner/src/MochaTestRunner.js:48:19)
```

Is it possible to run stryker from outside the project somehow?
Thanks!

**Stryker environment**

```
├─┬ @stryker-mutator/core@2.0.2
│ ├─┬ @stryker-mutator/api@2.0.2
│ ├── @stryker-mutator/util@2.0.2
├─┬ @stryker-mutator/javascript-mutator@2.0.2
│ ├── @stryker-mutator/api@2.0.2 deduped
├─┬ @stryker-mutator/mocha-framework@2.0.2
│ └── @stryker-mutator/api@2.0.2 deduped
├─┬ @stryker-mutator/mocha-runner@2.0.2
│ ├── @stryker-mutator/api@2.0.2 deduped
```

**Comment by simondel** [comment]
You may also need to change the relative path for the mocha runner so it's config also points to `../myproject/**/*.spec.js` and such.
