### ISSUE TITLE
Mutators for promises (or custom mutators)

### ISSUE THREAD

**Issue by sharikovvladislav** [stryker-mutator/stryker#169]
Hi.

Is it possible to have this mutation?

Imagine you have this: `return $q.reject('someCode');`. Is it somehow possible to mutate this to: `return $q.when('someCode');`?

I am using $q service in AngularJS. I think I need something like custom mutation there. Is it possible?

**Comment by simondel** [comment]
That's a cool idea! I don't think this should be a mutator that's included by default so this could be Styker's first custom mutator!

We use Esprima to parse our code into an Abstract Syntax Tree. If I give the code
```
function myfunction() {
	return $q.reject('someCode');
}
```
To Esprima (http://esprima.org/demo/parse.html), we get the following tree*:
```
{
    "type": "Program",
    "body": [
        {
            "type": "FunctionDeclaration",
            "id": {
                "type": "Identifier",
                "name": "myfunction"
            },
            "params": [],
            "body": {
                "type": "BlockStatement",
                "body": [
                    {
                        "type": "ReturnStatement",
                        "argument": {
                            "type": "CallExpression",
                            "callee": {
                                "type": "MemberExpression",
                                "computed": false,
                                "object": {
                                    "type": "Identifier",
                                    "name": "$q"
                                },
                                "property": {
                                    "type": "Identifier",
                                    "name": "reject"
                                }
                            },
                            "arguments": [
                                {
                                    "type": "Literal",
                                    "value": "someCode",
                                    "raw": "'someCode'"
                                }
                            ]
                        }
                    }
                ]
            },
            "generator": false,
            "expression": false
        }
    ],
    "sourceType": "script"
}
```
\* Stryker actually gets some more info such as line numbers but I've removed them from this example.

Now, the interesting part lies in this Object:
```
"callee": {
    "type": "MemberExpression",
    "computed": false,
    "object": {
        "type": "Identifier",
        "name": "$q"
    },
    "property": {
        "type": "Identifier",
        "name": "reject"
    }
},
```

If you write a mutator, you will get every object on the syntax tree. One of those objects could match this one. You can check if the object is like this one to be certain (does it have the right `type`? Do the `object` and `property` properties contain the right values?) If that's all true, you could change `"reject"` into `"when"` and boom! 

Now, would you like to write this yourself? (You can either publish it on your own GitHub or on our organization page, whatever you want)

**Comment by nicojs** [comment]
@sharikovvladislav A custom mutator is possible. See the [stryker plugin seed](https://github.com/stryker-mutator/stryker-plugin-seed) for your starting point to start creating mutators. I would just start out with mutators in your local project (using `plugins: ['stryker-*', './myLocalPlugin']` for example. We're using TypeScript in our seed and projects, but this is not a requirement. You can just supply a constructor function with an `applyMutations` implementation. See @simondel's command for the details on how to implement it.

I'm pretty skeptical about the proposed mutation. The proposed mutation would not work in all circumstances. For example: 

```javascript
var promise = $q(function(resolve, reject) { 
  reject('It would be difficult to mutate this particular line');
}
```

or

```javascript
var $q = { reject: function () { } }; 
return $q.reject(); // should not be mutated in this case, because it is not angular's $q 
```

That being said, i think it is still a valuable mutator to turn around promise results (reject -> resolve and vice versa).

It would only work for angular js projects, so if you would want to open source it, i would suggest to put it in an angularjs specific repository.

**Comment by sharikovvladislav** [comment]
@simondel @nicojs Thank you for your answers. 

I am not thinking about this must be build-in feature :) 
Also, I know it will work only for angulajs (and I need it only for angularjs at the moment) and I know that it is hard to mutate some lines (but we don't use $q this way anyway). I just wanted to try stryker in my units.

I will try to make some custom mutator right after I will be able to start stryker at all :)

**Comment by sharikovvladislav** [comment]
I will close this issue. I was inattentive and didn't see that there is ability to create custom mutators. Thank you for your answers.
