### ISSUE TITLE
How to run a npm script ?

### ISSUE THREAD

**Issue by BourgoisMickael** [stryker-mutator/stryker#1692]
**Question**

I'm using mocha and I want to run multiple test environment with stryker, how can I run `npm run test:unit && npm run test:integration` with stryker ?

**Stryker environment**
```bash
+-- @stryker-mutator/core@2.0.2
+-- @stryker-mutator/javascript-mutator@2.0.2
+-- @stryker-mutator/mocha-framework@2.0.2
+-- @stryker-mutator/mocha-runner@2.0.2
+-- mocha@6.0.2
```

**Additional context**

So I have 2 separate commands to do something like `mocha test/unit/init test/unit/ --recursive` and same for integration and I'd like to run that with stryker and have a single report for both commands.

**Comment by simondel** [comment]
You could do this using the testRunner 'command' (see https://npmjs.com/package/@stryker-mutator/core) which allows you to specify a command to run. You will quite a bit of performance compared to this approach though since we can't optimise the test run ourselves.

I hope this helps!

**Comment by BourgoisMickael** [comment]
Thanks so is there a way to call stryker twice for 2 different tests but get only one report ?

For example, with `nyc` I can do something like 

```
nyc --clean true mocha test/unit/ && nyc --clean false mocha test/integration/
```

This way I have a new coverage report when I start the command, but then I use the same report for both tests

**Comment by simondel** [comment]
Yes, as I mentioned. You can use the command test runner: https://www.npmjs.com/package/@stryker-mutator/core#testrunner--string-

**Comment by nicojs** [comment]
@BourgoisMickael You mean 2 different `mocha` commands? For example `mocha test/unit` && `mocha test/integration`? You can put it in 1 `npm script` command and configure that in Stryker with the command runner. You could also make 1 mocha configuration to combine both and run it with the mocha runner plugin https://www.npmjs.com/package/@stryker-mutator/mocha-runner. Closing this question for now.
