### ISSUE TITLE
Mutation testing may freeze

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#17]
In certain situations, the mutation testing process can get stuck. While this happens, several nodeJS, Karma and PhantomJS processes are still running.

If stryker freezes in a certain project, it will always freeze at that point. However, if another pc is used it can freeze at another point in the mutation run, or it does not freeze at all. In some cases stryker only freezes when the option `individualTests` is turned on.

The issue can be fixed by enabling logging of nodeJS, Karma and PhantomJS processes. A temporary workaround has been added which reroutes the stdout of the child processes to an empty function. This enables the logging (which fixes the freezing) while not actually showing anything.

**Comment by simondel** [comment]
It's not certain if this issue still exists due to the new Karma implementation.

**Comment by simondel** [comment]
#83 may fix this

**Comment by simondel** [comment]
I have not seen this issue in the past couple of months so I consider it fixed

**Comment by nicojs** [comment]
Yeah, it had probably to do with the way we ignored the stdout of child processes.
