### ISSUE TITLE
output or saving the jasmine execution contents

### ISSUE THREAD

**Issue by liweis** [stryker-mutator/stryker#1702]
**Question**
is it possible to output or saving the jasmine execution contents/reports so after running the tests we can see which case failed for one particular mutation ?

**Stryker environment**

@stryker-mutator/core@2.0.2

jasmine-runner@2.0.2

**Additional context**

**Comment by nicojs** [comment]
Probably even better if Stryker can just tell you which test failed, right? The jasmine output itself is currently not being used, not even outputted because the jasmine console reporter is disabled for performance reasons

**Comment by simondel** [comment]
I'm closing this issue for now
