### ISSUE TITLE
Setup for a lerna repo

### ISSUE THREAD

**Issue by lbenie** [stryker-mutator/stryker#1721]
**Question**

I'm trying to add stryker to a lerna repo. I'm getting unresolved imports for my sandboxed spec files. it's not importing my `__mocks__/*.ts` files.

i.e
```
Cannot find module './mocks/some-models' from 'myTest.spec.ts'
```

**Stryker environment**

stryker-cli@1.0.0
```
+-- "@stryker-mutator/core": "2.0.2",
+-- "@stryker-mutator/html-reporter": "2.0.2",
+-- "@stryker-mutator/jest-runner": "2.0.2",
+-- "@stryker-mutator/typescript": "2.0.2",
```

```
+-- "jest": "^24.7.1",
```

**Additional context**
stryker.conf.js file
```js
module.exports = function(config) {
  config.set({
    mutator: 'typescript',
    packageManager: 'npm',
    reporters: ['html', 'clear-text', 'progress'],
    testRunner: 'jest',
    transpilers: ['typescript'],
    coverageAnalysis: 'off',
    tsconfigFile: 'tsconfig.json',
    mutate: [
      'packages/**/src/**/*.ts',
      '!packages/**/src/__mocks__/**/*.ts',
      '!packages/**/index.ts',
      '!packages/**/*.spec.ts',
    ],
    testMatch: ['<rootDir>/packages/**/*.spec.ts'],
    jest: {
      projectType: 'custom',
      config: require('./jest.config'),
      enableFindRelatedTests: true,
    },
    htmlReporter: {
      baseDir: 'coverage/stryker-reports/',
    },
  })
}
```

jest.config.js
```js
module.exports = {
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  transform: {
    '.(ts|tsx|js|jsx)': '<rootDir>/node_modules/babel-jest',
  },
  testEnvironment: 'node', 
  testRegex: '(\\.(test|spec))\\.(ts|tsx|js)$',
  transformIgnorePatterns: [
    '<rootDir>/node_modules/',
  ],
  modulePathIgnorePatterns: ['dist'],
  coveragePathIgnorePatterns: ['/node_modules/'],
  coverageThreshold: {
    global: {
      branches: 90,
      functions: 95,
      lines: 95,
      statements: 95,
    },
  },
  collectCoverageFrom: [
    '**/src/**/*.{js,ts}',
  ],
  coverageReporters: ['text', 'cobertura'],
  setupFilesAfterEnv: ['<rootDir>/fetch.js', '<rootDir>/jest-extended.js'],
  moduleNameMapper: {
    '^@getgo/(.*)': '<rootDir>/node_modules/@getgo/$1',
    '^@types/(.*)': '<rootDir>/node_modules/@types/$1',
  },
}
```

**Comment by nicojs** [comment]
Hi @lbenie thanks for opening this issue.

Stryker should work with lerna, no problem (we're using it ourselves as well). Could you specify where the `mocks/some-models` is located on disk? Is it checked into source control? 

I think you should also remove the transpiler here. Since you're using jest, it will be responsible for the transpiling (not stryker).

**Comment by lbenie** [comment]
> Hi @lbenie thanks for opening this issue.
> 
> Stryker should work with lerna, no problem (we're using it ourselves as well). Could you specify where the `mocks/some-models` is located on disk? Is it checked into source control?

some are located in 

`/packages/package1/__mocks__`

and yes they are checked in source control

> 
> I think you should also remove the transpiler here. Since you're using jest, it will be responsible for the transpiling (not stryker).
Thanks I will try that!

**Comment by amrondonp** [comment]
@lbenie Were you able to solve the problem?

I have a lerna project and I have been able to run stryke on a single package and a **single test**. The test does not have dependencies on other packages so it works fine.

I tried with my suite of tests and as stryker is not copying the modules onto the temporal folder it does not find them.

I have also looked at the code of stryker itself to see how the project is managed but I don't see an obvious thing that I'm missing

Did you find a solution?

**Comment by lbenie** [comment]
> @lbenie Were you able to solve the problem?
> 
> I have a lerna project and I have been able to run stryke on a single package and a **single test**. The test does not have dependencies on other packages so it works fine.
> 
> I tried with my suite of tests and as stryker is not copying the modules onto the temporal folder, it does not find them.
> 
> I have also looked at the code of stryker itself to see how the project is managed but I don't see an obvious thing that I'm missing
> 
> Did you find a solution? 
> 

Hey man @amrondop, I haven't tried in a while. Had to get on some other features. If you find anything keep me posted!

I'll try next month when I get some more free time

**Comment by simondel** [comment]
Hi! I'm closing this issue for now. If it still persists with Stryker version 4, please open a new issue. Thanks!
