### ISSUE TITLE
Easily debug initial test run

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#173]
We need a way to debug the initial test run more easily. Right now its a pain. 

Take this workflow for example:

1. Rerun stryker using `logLevel: 'trace'`
2. Lookup the karma config it prints to the console
3. Shut down Stryker
4. Move the karma config to a seperate karma.conf.js file
5. Change reporters to include the `'progress'` reporter.
6. Run karma on the newly created config. Interpret what the issue is. Fix and rerun.
7. Alter stryker.conf.js and start again from 1.

Once we have this feature: #171 we could add a `debug` command for example. 

The debug command should: 

1. Print log messages from the test runner.
2. Give the user the possibility to inspect the test runner (the browser if you're using karma).

In order for 1 to work, we should run the testrunner *in the same process* as Stryker. No isolation into a separate process.

In order for 2 to work, we should notify the test runner that it is ran with the `debug` command (`command: 'debug' or something). The stryker-karma-runner could than load the test run with `singleRun: false` for example, keeping the browser open.

@sharikovvladislav what do you think of this proposal? Would this be helpful enough for you?

**Comment by sharikovvladislav** [comment]
I can debug unit tests which are using karma runner in IDEA/WebStorm (like any other nodejs/grunt/gulp/etc application). I just put breakpoint in code, run debug and . Will I be able to do it after this implementing this feature?

**Comment by nicojs** [comment]
Ah yes, you probably will. It will be the same process as Stryker runs in, so running stryker with the debugger might just do the trick. Not sure though, we'll have to see.

**Comment by simondel** [comment]
@nicojs Stryker will now suggest rerunning when it fails unexpectedly. Can we close this?

**Comment by nicojs** [comment]
It might we worth it to introduce a `--runInBand` flag (like [jest's --runInBand](https://jestjs.io/docs/en/cli.html#runinband)). 

If anyone wants this feature, please comment here, so we can reopen it.
