### ISSUE TITLE
rename `typescript` to `typescript-mutator`

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1743]
Since we are naming packages like `transpiler`, `runner`, `framework` etc, shouldn't `typescript` be called `typescript-mutator` as there is `javascript-mutator`. A small change, but for me, that's quite annoying and each time I see `typescript` I am like 'oww... you mean typescript-mutator. Why it's not mutator. Mutator...'

**Comment by simondel** [comment]
Yeah, but it also includes a transpiler...

**Comment by kmdrGroch** [comment]
doesn't `vue` also include transpiler despite being called `vue-mutator`? Also `javascript-mutator` uses babel to "transpile" files so I guess it's also a transpiler at some point ;P

**Comment by simondel** [comment]
The Vue mutator extracts the JavaScript/TypeScript code from the template so it can be passed on to the configured child-mutator (JavaScript or TypeScript)

**Comment by kmdrGroch** [comment]
well ok, then it can be closed.
