### ISSUE TITLE
Angular End-to-End tests are unstable

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#1749]
The Angular End-to-End tests are unstable. The mutation score differs sometimes because one specific mutant has a different state (survived instead of killed).

The mutation that survives is this Block mutation:
https://github.com/stryker-mutator/stryker/blob/8a20a17d75ee15edacae530cdbd82aafc9f0319c/e2e/test/angular-project/src/app/app.component.ts#L3-L7

Which is **mutated** into:
```ts
@Component({ })
```

This should cause tests in [app.component.spec.ts](https://github.com/stryker-mutator/stryker/blob/master/e2e/test/angular-project/src/app/app.component.spec.ts) to fail because the component cannot be created. For some reason, sometimes this does not happen.

**Comment by kmdrGroch** [comment]
Have you tried putting 
```js
{ 
   selector: 'app-root', 
   styleUrls: ['./app.component.css'], 
   templateUrl: './app.component.html' 
 }
```
into a variable? It could be caused coz of `@Component` (somehow). It should be always changed in variable tho :/

**Comment by simondel** [comment]
@kmdrGroch The mutated code is default Angular code. This shouldn't cause an issue. We can't ask our users to adopt a different syntax. If this issue is due to the syntax (and not the build environment for example), it should be fixed in Stryker.

**Comment by kmdrGroch** [comment]
I know, I am just curious about the origin of that issue. Is it because decorator or some parser can't find it or what

**Comment by nicojs** [comment]
This might be a race condition in the Angular-cli / karma itself.

Writing mutation to disk -> run karma -> see result.

The way compilation errors are reported is by this line of code:


I'm updating the tests to pass in the mean time. This is causing too many red builds

**Comment by kmdrGroch** [comment]
It might also be caused by coz obsolete versions of testing tools / angular. Let's if anything changes after #1832

**Comment by simondel** [comment]
As we've implemented a workaround, I'm closing this issue for now.
