### ISSUE TITLE
Not able to test mongoose models.

### ISSUE THREAD

**Issue by RuudVerhoef** [stryker-mutator/stryker#1754]
I am trying to test some mongoose models to see if required properties are indeed throwing an error if they are not set.

This throws a sandbox runtime error:

> DEBUG Sandbox A runtime error occurred: TypeError [ERR_INVALID_ARG_VALUE]: ERR_INVALID_ARG_VALUE (undefined) TypeError [ERR_INVALID_ARG_VALUE]: The argument 'id' must be a non-empty string. Received ''

Is this fixable (or can I exclude test files in stryker.conf.js) or should I exclude testing this logic?

**Comment by kmdrGroch** [comment]
You could exclude file via `mutate` or `files` option. For now, we don't support specific exclusions.

**Comment by RuudVerhoef** [comment]
I am not be able to exclude those files.

The problem is that when creating a object from a mongoose schema (what happens in the tests). Mongoose throws an error under the hood when required properties are not set. This error causes the sandbox to crash (so it seems).

I had to fix it by splitting up my tests in 2 folders. Pointing Stryker only to the folder with tests that do not throw a sandbox error when they run.

**Comment by kmdrGroch** [comment]
It really seems to be a problem. If it is not an issue for you, could you please share repository, or prepare some example one, so we can work on this? :)

**Comment by simondel** [comment]
Hi! I'm closing this issue for now. If it still persists with Stryker version 4, please open a new issue. Thanks!
