### ISSUE TITLE
Update `core` readme

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1755]
`Configuration` part could be a bit better written (sorted, some parts written better)

**Comment by gugacavalieri** [comment]
What if we included an index like that in the `Configuration` section ?

### Configuration Properties:
* [mutate](#mutate)
* [testRunner](#testRunner)
* [testFramework](#testFramework)
* [coverageAnalysis](#coverageAnalysis)
* [mutator](#mutator)
* [transpilers](#transpilers)
* [reporters](#reporters)
* [files](#files)
* [symlinkNodeModules](#symlinkNodeModules)
* [plugins](#plugins)
* [tempDirName](#tempDirName)
* [timeoutMS](#timeoutMS)
* [timeoutFactor](#timeoutFactor)
* [maxConcurrentTestRunners](#maxConcurrentTestRunners)
* [thresholds](#thresholds)
* [logLevel](#logLevel)
* [fileLogLevel](#fileLogLevel)
* [allowConsoleColors](#allowConsoleColors)

**Comment by kmdrGroch** [comment]
looks good to me O.O But still I think alphabetical order is the best :/

**Comment by gugacavalieri** [comment]
@kmdrGroch hum, that is a really good idea !
