### ISSUE TITLE
Could not inject "InputFileResolver"

### ISSUE THREAD

**Issue by scaljeri** [stryker-mutator/stryker#1758]
**Summary**
After not have used my project for a while, I noticed that stryker doesn't run anymore

Here is the error when I run it

    $> yarn stryker
    yarn run v1.16.0
    $ ./node_modules/.bin/stryker run
    15:48:04 (53340) INFO ConfigReader Using stryker.conf.js in the current working directory.
    15:48:04 (53340) ERROR StrykerCli an error occurred Exception [Error]: Could not inject "InputFileResolver". Inner error: Could not inject "BroadcastReporter". Inner error: Cannot load Reporter plugin "html". Did you forget to install it? Loaded Reporter plugins were: clear-text, progress, progress-append-only, dots, event-recorder, dashboard
    at ClassProvider.injectClass (/Users/luca/WebstormProjects/my-proj/node_modules/typed-inject/src/InjectorImpl.js:35:19)
    at ClassProvider.injectClass (/Users/luca/WebstormProjects/my-proj/node_modules/typed-inject/src/InjectorImpl.js:95:22)
    at Stryker.runMutationTest (/Users/luca/WebstormProjects/my-proj/node_modules/@stryker-mutator/core/src/Stryker.js:43:48)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
      innerError: Exception [Error]: Could not inject "BroadcastReporter". Inner error: Cannot load Reporter plugin "html". Did you forget to install it? Loaded Reporter plugins were: clear-text, progress, progress-append-only, dots, event-recorder, dashboard

**Stryker config**

```js
module.exports = function(config){
  config.set({
    files: ['test/*.ts', 'src/*.ts'],
    mutator: "typescript",
    packageManager: "yarn",
    reporters: ["html", "clear-text", "progress"],
    testRunner: "mocha",
    transpilers: ['babel'],
    testFramework: "mocha",
    coverageAnalysis: "off",
    tsconfigFile: "tsconfig.json",
    mutate: ["src/*.ts"],
    mochaOptions: {
        files: ['test/*.ts']
    }
  });
}
```

**Test runner config**
No other files required, just `mocha` with all typscript inside `src` and `test`

**Stryker environment**
Here are my devDependencies:

    "devDependencies": {
        "@stryker-mutator/core": "2.0.1",
        "@types/chai": "4.1.7",
        "@types/mocha": "5.2.7",
        "@types/sinon-chai": "3.2.2",
        "chai": "4.2.0",
        "coveralls": "3.0.4",
        "mocha": "6.1.4",
        "nyc": "14.1.1",
        "rxjs": "6.5.2",
        "rxjs-tslint": "^0.1.6",
        "rxjs-tslint-rules": "4.24.3",
        "sinon": "7.3.2",
        "sinon-chai": "3.3.0",
        "stryker": "0.35.1",
        "stryker-api": "0.24.1",
        "stryker-babel-transpiler": "0.10.1",
        "stryker-cli": "1.0.0",
        "stryker-html-reporter": "0.18.1",
        "stryker-mocha-framework": "0.15.1",
        "stryker-mocha-runner": "0.17.1",
        "stryker-typescript": "^0.18.1",
        "ts-node": "8.3.0",
        "tslint": "5.18.0",
        "typescript": "3.5.2"
      },

If I update `@stryker-mutator/core` to `v2.1.0` the error changes to 

    16:00:56 (55147) INFO ConfigReader Using stryker.conf.js in the current working directory.
    16:00:56 (55147) ERROR StrykerCli an error occurred Exception [Error]: Could not inject "InputFileResolver". Inner error: Could not inject "BroadcastReporter". Inner error: Cannot load Reporter plugin "html". Did you forget to install it? 
    Loaded Reporter plugins were: clear-text, progress, progress-append-only, dots, event-recorder, dashboard

**Test runner environment**
My command is 

    $> ./node_modules/.bin/stryker run

```shell
# Test command
```

```json
```

**Your Environment**

| software         | version(s)
| ---------------- | -------  
| node             | v12.8.1
| npm              | v1.16.0
| yarn .            | v6.10.3
| Operating System | MacOSX

**Add stryker.log**
Log is always empty

The project is open source and can be found [here](https://github.com/scaljeri/angular-xxl)

**Comment by kmdrGroch** [comment]
@scaljeri you are currently using outdated versions of stryker.
current version is `2.1.0` and it goes for `@stryker-mutator/core` as well as for other dependencies:
```
    "stryker": "0.35.1",
    "stryker-api": "0.24.1",
    "stryker-babel-transpiler": "0.10.1",
    "stryker-cli": "1.0.0",
    "stryker-html-reporter": "0.18.1",
    "stryker-mocha-framework": "0.15.1",
    "stryker-mocha-runner": "0.17.1",
    "stryker-typescript": "^0.18.1",
```
Right now it should be:
```
   "@stryker-mutator/xxx": "2.1.0"
```
(while xxx is name of runner / reporter / framework etc.)

Try using current `stryker-cli`

**Comment by kmdrGroch** [comment]
current available stryker packages are:
```
    "grunt-stryker"
    "@stryker-mutator/core"
    "@stryker-mutator/api"
    "@stryker-mutator/babel-transpiler"
    "@stryker-mutator/html-reporter"
    "@stryker-mutator/jasmine-framework"
    "@stryker-mutator/jasmine-runner"
    "@stryker-mutator/javascript-mutator"
    "@stryker-mutator/karma-runner"
    "@stryker-mutator/mocha-framework"
    "@stryker-mutator/mocha-runner"
    "@stryker-mutator/util"
    "@stryker-mutator/typescript"
    "@stryker-mutator/vue-mutator"
    "@stryker-mutator/webpack-transpiler"
```

**Comment by kmdrGroch** [comment]
@scaljeri I created a PR for you, so this issue should be solved :)
