### ISSUE TITLE
Error: ENFILE: file table overflow with NFS and too many CPUs

### ISSUE THREAD

**Issue by jeznag** [stryker-mutator/stryker#177]
Hi, my code is stored inside a vagrant VM on NFS. I found that I was getting mysterious failures with no info. It turns out it was due to
```{ [Error: ENFILE: file table overflow, open '/Users/jeremynagel/salt-developer/code/api/questioneditor/.stryker-tmp/2570072/test-runner-files2860198/www/latest/app/views/components/panels/jsonSourcePanel.js']
  errno: -23,
  code: 'ENFILE',
  syscall: 'open',
  path: '/Users/jeremynagel/salt-developer/code/api/questioneditor/.stryker-tmp/2570072/test-runner-files2860198/www/latest/app/views/components/panels/jsonSourcePanel.js' }
```

The error does not happen if I use fewer CPUs. I therefore suggest we allow a config option for CPU count. I created a basic PR: https://github.com/stryker-mutator/stryker/pull/176

It's failing bithound checks atm. The failures seem unrelated to my change.

**Comment by nicojs** [comment]
Fixed using #176
