### ISSUE TITLE
JavaScript heap out of memory with CRA based React/TypeScript application

### ISSUE THREAD

**Issue by mauricedb** [stryker-mutator/stryker#1779]
**Summary**

Running Stryker on a Create React App base TypeScript project causes an FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**Performance profile of the application before the fatal error**

![image](https://user-images.githubusercontent.com/3197730/66814681-4e745f80-ef37-11e9-9752-9b627aa0838e.png)

**Stryker config**

```js
// This config was generated using a preset.
// Please see the handbook for more information: https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/guides/react.md#react
module.exports = function(config) {
  config.set({
    mutate: ["src/**/*.ts?(x)", "!src/**/*@(.test|.spec|Spec).ts?(x)"],
    mutator: "typescript",
    testRunner: "jest",
    reporters: ["progress", "clear-text", "html"],
    tempDirName: "stryker-tmp",
    coverageAnalysis: "off",
    jest: {
      projectType: "react"
    }
  });
};
```

**Test runner config**

```
  "jest": {
    "globalSetup": "./src/setupTests.ts",
    "coverageThreshold": {
      "./src/**/*.{ts,tsx}": {
        "lines": 80,
        "statements": 80,
        "branches": 80,
        "functions": 80
      }
    },
    "coverageReporters": [
      "cobertura"
    ]
  },

```

setupTests.ts
```
export default (): void => {
  (global as any).alert = (): void => {};
};
```

**Stryker environment**

```
+-- @stryker-mutator/core@2.1.0
| +-- @stryker-mutator/api@2.1.0
| +-- @stryker-mutator/util@2.1.0
+-- @stryker-mutator/html-reporter@2.1.0
| +-- @stryker-mutator/api@2.1.0 deduped
| +-- @stryker-mutator/util@2.1.0 deduped
+-- @stryker-mutator/jest-runner@2.1.0
| +-- @stryker-mutator/api@2.1.0 deduped
+-- @stryker-mutator/typescript@2.1.0
| +-- @stryker-mutator/api@2.1.0 deduped
| +-- @stryker-mutator/util@2.1.0 deduped
```

```
jest@24.9.0
@testing-library/react@9.1.4
jsdom@14.1.0
full-icu@1.3.0
```

**Test runner environment**

```shell
cross-env NODE_ICU_DATA=node_modules/full-icu react-scripts test
```

```json
```

**Your Environment**

| software         | version(s)
| ---------------- | -------  
| node             | v10.15.3
| npm              | 6.11.3
| Operating System | Windows 10 version 1809

**Add stryker.log**
08:38:37 (5104) INFO ConfigReader Using stryker.conf.js in the current working directory.
08:38:37 (5104) DEBUG BroadcastReporter Broadcasting to reporters ["progress","clear-text","html"]
08:38:37 (5104) DEBUG ConfigReader Loading config stryker.conf.js
08:38:37 (5104) DEBUG PluginLoader Loading @stryker-mutator/* from C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator
08:38:37 (5104) DEBUG PluginLoader Loading plugin "C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator\html-reporter" (matched with expression @stryker-mutator/*)
08:38:37 (5104) DEBUG PluginLoader Loading plugin "C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator\jest-runner" (matched with expression @stryker-mutator/*)
08:38:37 (5104) DEBUG PluginLoader Loading plugin "C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator\typescript" (matched with expression @stryker-mutator/*)
08:38:37 (5104) DEBUG PluginLoader Loading plugins C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator\html-reporter
08:38:37 (5104) DEBUG PluginLoader Loading plugins C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator\jest-runner
08:38:37 (5104) DEBUG PluginLoader Loading plugins C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator\typescript
08:38:37 (5104) DEBUG PluginLoader Loading plugins C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator\core\src\reporters\index.js
08:38:37 (5104) DEBUG TypescriptConfigEditor No 'tsconfigFile' specified, not loading any config
08:38:38 (5104) INFO InputFileResolver Found 516 of 1078 file(s) to be mutated.
08:38:38 (5104) DEBUG InputFileResolver All input files: [
  "C:\\Repos\\Adviesbox-Advies-React\\.azuredevops\\pull_request_template.md",
  "C:\\Repos\\Adviesbox-Advies-React\\.eslintignore",
  "C:\\Repos\\Adviesbox-Advies-React\\.eslintrc.js",
  "C:\\Repos\\Adviesbox-Advies-React\\.gitignore",
  "C:\\Repos\\Adviesbox-Advies-React\\.prettierrc",
  "C:\\Repos\\Adviesbox-Advies-React\\.vscode\\launch.json",
  "C:\\Repos\\Adviesbox-Advies-React\\README.md",
  ... many more omitted files
  "C:\\Repos\\Adviesbox-Advies-React\\src\\zoekscherm\\zoekscherm.tsx"
]
08:52:42 (7064) DEBUG TemporaryDirectory Using temp directory "C:\Repos\Adviesbox-Advies-React\stryker-tmp"
08:52:42 (7064) DEBUG TestFrameworkOrchestrator The `coverageAnalysis` setting is "off", not hooking into the test framework to achieve performance benefits.
08:52:42 (7064) INFO InitialTestExecutor Starting initial test run. This may take a while.
08:52:42 (7064) DEBUG Sandbox Creating a sandbox for files in C:\Repos\Adviesbox-Advies-React\stryker-tmp\sandbox9953131
08:52:43 (7064) DEBUG Sandbox Creating test runner 0
08:52:43 (7064) DEBUG ChildProcessProxy Starting C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator\core\src\test-runner\ChildProcessTestRunnerWorker.js in child process 19376
08:52:43 (19376) DEBUG ChildProcessProxyWorker Changing current working directory for this process to C:\Repos\Adviesbox-Advies-React\stryker-tmp\sandbox9953131
08:52:43 (19376) DEBUG PluginLoader Loading @stryker-mutator/* from C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator
08:52:43 (19376) DEBUG PluginLoader Loading plugin "C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator\html-reporter" (matched with expression @stryker-mutator/*)
08:52:43 (19376) DEBUG PluginLoader Loading plugin "C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator\jest-runner" (matched with expression @stryker-mutator/*)
08:52:43 (19376) DEBUG PluginLoader Loading plugin "C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator\typescript" (matched with expression @stryker-mutator/*)
08:52:43 (19376) DEBUG PluginLoader Loading plugins C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator\html-reporter
08:52:43 (19376) DEBUG PluginLoader Loading plugins C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator\jest-runner
08:52:43 (19376) DEBUG PluginLoader Loading plugins C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator\typescript
08:52:43 (19376) DEBUG PluginLoader Loading plugins C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator\core\src\reporters\index.js
08:52:44 (19376) DEBUG JestTestRunner Running jest with --findRelatedTests flag. Set jest.enableFindRelatedTests to false to run all tests on every mutant.
08:52:44 (19376) DEBUG JestTestRunner Project root is C:\Repos\Adviesbox-Advies-React\stryker-tmp\sandbox9953131
08:52:44 (7064) DEBUG TimeoutDecorator Starting timeout timer (300000 ms) for a test run
08:52:44 (19376) TRACE JestPromiseTestAdapter Invoking Jest with config {"roots":["<rootDir>/src"],"collectCoverageFrom":["src/**/*.{js,jsx,ts,tsx}","!src/**/*.d.ts"],"setupFiles":["C:\\Repos\\Adviesbox-Advies-React\\node_modules\\react-app-polyfill\\jsdom.js"],"setupFilesAfterEnv":["<rootDir>/src/setupTests.ts"],"testMatch":["<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}","<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}"],"testEnvironment":"jsdom","transform":{"^.+\\.(js|jsx|ts|tsx)$":"C:\\Repos\\Adviesbox-Advies-React\\node_modules\\react-scripts\\config\\jest\\babelTransform.js","^.+\\.css$":"C:\\Repos\\Adviesbox-Advies-React\\node_modules\\react-scripts\\config\\jest\\cssTransform.js","^(?!.*\\.(js|jsx|ts|tsx|css|json)$)":"C:\\Repos\\Adviesbox-Advies-React\\node_modules\\react-scripts\\config\\jest\\fileTransform.js"},"transformIgnorePatterns":["[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$","^.+\\.module\\.(css|sass|scss)$"],"modulePaths":[],"moduleNameMapper":{"^react-native$":"react-native-web","^.+\\.module\\.(css|sass|scss)$":"identity-obj-proxy"},"moduleFileExtensions":["web.js","js","web.ts","ts","web.tsx","tsx","json","web.jsx","jsx","node"],"watchPlugins":["jest-watch-typeahead/filename","jest-watch-typeahead/testname"],"rootDir":"C:\\Repos\\Adviesbox-Advies-React\\stryker-tmp\\sandbox9953131","coverageReporters":["cobertura"],"coverageThreshold":{"./src/**/*.{ts,tsx}":{"lines":80,"statements":80,"branches":80,"functions":80}},"globalSetup":"./src/setupTests.ts","collectCoverage":false,"verbose":false,"bail":false,"notify":false,"reporters":[]}
08:55:41 (7064) DEBUG ChildProcessProxy Disposing of worker process 19376
08:55:41 (7064) DEBUG ChildProcessProxy Kill 19376
08:55:41 (7064) INFO InitialTestExecutor Initial test run succeeded. Ran 1531 tests in 2 minutes 59 seconds (net 72308 ms, overhead 104839 ms).

**Comment by simondel** [comment]
Interesting... You don't see a log message saying _'n mutants generated'_?

**Comment by mauricedb** [comment]
@simondel Yes I have seen `MutatorFacade 26902 Mutant(s) generated`.

Seems the last part of the output is missing from the log file. Guess a result of the crash. Still had a copy:

```
08:52:44 (7064) DEBUG TimeoutDecorator Starting timeout timer (300000 ms) for a test run
08:55:41 (7064) DEBUG ChildProcessProxy Disposing of worker process 19376
08:55:41 (7064) DEBUG ChildProcessProxy Kill 19376
08:55:41 (7064) INFO InitialTestExecutor Initial test run succeeded. Ran 1531 tests in 2 minutes 59 seconds (net 72308 ms, overhead 104839 ms).
08:55:43 (7064) INFO MutatorFacade 26902 Mutant(s) generated

<--- Last few GCs --->

[7064:000002BECD70BE50]   196676 ms: Scavenge 1396.2 (1424.7) -> 1395.7 (1425.2) MB, 2.2 / 0.0 ms  (average mu = 0.265, current mu = 0.188) allocation failure [7064:000002BECD70BE50]   197712 ms: Mark-sweep 1396.9 (1425.2) -> 1396.6 (1425.7) MB, 858.0 / 0.0 ms  (+ 0.0 ms in 23 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1040 ms) (average mu = 0.229, current mu = 0.185) all

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 000003B2BE65C5C1]
Security context: 0x011fc951e6e9 <JSObject>
    1: /* anonymous */(aka /* anonymous */) [000002E91AC02201] [C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator\core\src\mutants\MutantTestMatcher.js:~29] [pc=000003B2BE97E4CC](this=0x013e08c026f1 <undefined>,mutant=0x02e91ac049b9 <TestableMutant map = 0000026C48CCA191>)
    2: arguments adaptor frame: 3->1
    3: forEach [0000011FC9506DF1](t...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF735F4F04A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+5114
 2: 00007FF735F2A0C6 node::MakeCallback+4518
 3: 00007FF735F2AA30 node_module_register+2032
 4: 00007FF7361B20EE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF7361B201F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF7366D2BC4 v8::internal::Heap::MaxHeapGrowingFactor+9556
 7: 00007FF7366C9C46 v8::internal::ScavengeJob::operator=+24310
 8: 00007FF7366C829C v8::internal::ScavengeJob::operator=+17740
 9: 00007FF7366D0F87 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF7366D1006 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF73628CDB7 v8::internal::Factory::NewFillerObject+55
12: 00007FF736323179 v8::internal::WasmJs::Install+30617
13: 000003B2BE65C5C1
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! adviesbox@0.1.0 stryker: `cross-env NODE_ICU_DATA=node_modules/full-icu stryker run "--fileLogLevel" "trace" "--logLevel" "debug"`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the adviesbox@0.1.0 stryker script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mauri\AppData\Roaming\npm-cache\_logs\2019-10-15T06_55_59_764Z-debug.log
```

**Comment by kmdrGroch** [comment]
Since we are creating array for all mutants, it could be because of that :/ array with 26902 elements is quite a lot @simondel I guess it's kinda related to my #1761

**Comment by nicojs** [comment]
I'm curious to see what happens when you set `maxConcurrentTestRunners: 2`.

**Comment by nicojs** [comment]
I'm pretty sure this line of code is the problem:

https://github.com/stryker-mutator/stryker/blob/2bb7dd8b6f605eac29ba4af0463aa0cc4f395af2/packages/core/src/mutants/MutantTestMatcher.ts#L56

We're matching all mutants to all tests. Basically creating 26902 arrays with 1531 elements in them. All small elements mind you, but this is pretty much not necessary as we know we'll have to run all tests for all mutants anyway (since coverage analysis is `'off'`). 

I'm 90% sure that fixing this issue would at least get the mutation testing process started.

**Comment by mauricedb** [comment]
@nicojs Did a quick test and looks like the same result.

`stryker.conf.js`
```js
module.exports = function(config) {
  config.set({
    mutate: ["src/**/*.ts?(x)", "!src/**/*@(.test|.spec|Spec).ts?(x)"],
    mutator: "typescript",
    testRunner: "jest",
    reporters: ["progress", "clear-text", "html"],
    tempDirName: "stryker-tmp",
    coverageAnalysis: "off",
    jest: {
      projectType: "react"
    },
    maxConcurrentTestRunners: 2
  });
};
```

```
15:08:11 (18168) INFO ConfigReader Using stryker.conf.js in the current working directory.
15:08:12 (18168) INFO InputFileResolver Found 516 of 1078 file(s) to be mutated.
15:08:12 (18168) INFO InitialTestExecutor Starting initial test run. This may take a while.
15:11:15 (18168) INFO InitialTestExecutor Initial test run succeeded. Ran 1531 tests in 3 minutes 3 seconds (net 72413 ms, overhead 108711 ms).
15:11:17 (18168) INFO MutatorFacade 26902 Mutant(s) generated

<--- Last few GCs --->

[18168:0000023314413EF0]   202065 ms: Mark-sweep 1396.3 (1425.2) -> 1395.8 (1425.2) MB, 1028.9 / 0.0 ms  (+ 0.0 ms in 4 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1030 ms) (average mu = 0.181, current mu = 0.011) al[18168:0000023314413EF0]   203570 ms: Mark-sweep 1397.4 (1425.7) -> 1397.0 (1426.2) MB, 1321.9 / 0.0 ms  (average mu = 0.148, current mu = 0.122) allocation failure GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 000002587D95C5C1]
Security context: 0x01cd72e9e6e9 <JSObject>
    1: /* anonymous */(aka /* anonymous */) [00000101F0B82229] [C:\Repos\Adviesbox-Advies-React\node_modules\@stryker-mutator\core\src\mutants\MutantTestMatcher.js:~29] [pc=000002587DC7242C](this=0x007cf57826f1 <undefined>,mutant=0x03bf50c16d51 <TestableMutant map = 0000014E93F3E321>)
    2: arguments adaptor frame: 3->1
    3: forEach [000001CD72E86DF1](t...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF735F4F04A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+5114
 2: 00007FF735F2A0C6 node::MakeCallback+4518
 3: 00007FF735F2AA30 node_module_register+2032
 4: 00007FF7361B20EE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF7361B201F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF7366D2BC4 v8::internal::Heap::MaxHeapGrowingFactor+9556
 7: 00007FF7366C9C46 v8::internal::ScavengeJob::operator=+24310
 8: 00007FF7366C829C v8::internal::ScavengeJob::operator=+17740
 9: 00007FF7366D0F87 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF7366D1006 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF73628CDB7 v8::internal::Factory::NewFillerObject+55
12: 00007FF736323179 v8::internal::WasmJs::Install+30617
13: 000002587D95C5C1
```

**Comment by nicojs** [comment]
@mauricedb could you try out if v2.2.1 works for you? It has the fix in it

**Comment by mauricedb** [comment]
@nicojs 

👍 Stryker starts up on the whole application just fine now. Still going to take quite some time.

```
> adviesbox-advies-react@0.1.0 stryker C:\Repos\Adviesbox-Advies-React\packages\advies
> cross-env NODE_ICU_DATA=node_modules/full-icu stryker run

19:43:22 (11892) INFO ConfigReader Using stryker.conf.js in the current working directory.
19:43:23 (11892) INFO InputFileResolver Found 546 of 1118 file(s) to be mutated.
19:43:23 (11892) INFO InitialTestExecutor Starting initial test run. This may take a while.
19:47:23 (11892) INFO InitialTestExecutor Initial test run succeeded. Ran 1694 tests in 4 minutes 0 seconds (net 73636 ms, overhead 164539 ms).
19:47:26 (11892) INFO MutatorFacade 27866 Mutant(s) generated
19:47:27 (11892) INFO SandboxPool Creating 4 test runners (based on CPU count)
Mutation testing  [                                                  ] 0% (ETC 44h, 22m, 23s) 97/27866 tested (92 survived, 0 timed out)
```
