### ISSUE TITLE
"Fatal error: Stryker was unable to run the mutation test"

### ISSUE THREAD

**Issue by jeznag** [stryker-mutator/stryker#178]
I'm getting a lot of these kind of errors. It would be helpful if Stryker reported the underlying problem so I can figure out what to do to fix it.

**Comment by simondel** [comment]
How about we always write all logging to a text file in the .stryker-temp folder. If Stryker encounters an unexpected error, the file could be moved to the current working directory before Stryker cleans the .stryker-temp folder. That way the logging of a failed run is always available which can also make it easier for us to help fix issues!

**Comment by jeznag** [comment]
Could it log the error to the console as well? Might be more intuitive.

**Comment by simondel** [comment]
Of course! I noticed that we ask for trace logging in a lot of issues so it would also help us to have a logging file by default in case of an error :)

**Comment by nicojs** [comment]
@simondel @jeznag i think the problem is simply that the error message is swallowed in the [grunt-stryker](https://github.com/stryker-mutator/grunt-stryker):
https://github.com/stryker-mutator/grunt-stryker/blob/master/tasks/stryker.js#L34

Normally stryker also explicitly logs errors, but when an unexpected error occurs, it is swallowed at the moment.

**Comment by jeznag** [comment]
@nicojs it's not just that. There are a few places where there is a `.catch` which does not log any errors from the execution of a promise. I'll try and do a PR for that when I have a chance.

**Comment by jeznag** [comment]
Actually I've checked the code and it looks like that's changed now :) It either goes to log.error or `BroadcastReporter.prototype.handleError`

**Comment by jeznag** [comment]
Closing as I think this is all good now.
