### ISSUE TITLE
Test runner for Roku channel development

### ISSUE THREAD

**Issue by ronenlh** [stryker-mutator/stryker#1781]
**Question**

I'm trying to write a test runner for Roku channel development. 
The special challenge is that for the app to run, it needs to be packaged into a zip file and uploaded to the IP of the device. There are no emulators.
The test results are only available in the device logs, accessed via Telnet/Netcat on the device's IP, and then processed with Regex tools.

**Stryker environment**

Mutation on BrightScript code will be done with a specialized brightscript-mutator plugin under development.

**Comment by simondel** [comment]
Hi! I'm closing this issue for now. A lot has changed with Stryker version 4. If you still wish to support this, could you open a new issue? Thanks!
