### ISSUE TITLE
Remove dependency on lodash

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#1795]
**Is your maintenance request related to a problem? Please describe.**
We use lodash in a hand full of places, however we only do it for simple things. Like checking if a function is a function (instead of `value instanceof Function`), or checking if something is an array (instead of `Array.isArray(value)`). We should be able to remove the dependency.

**Describe the solution you'd like**
Remove all usages of `import * as _ fro lodash` and instead use current ES features.

**Additional context**
We've used lodash before, because back in the day of es5, it was a valid choice. Since then, the JS ecosystem has evolved. Lodash is a pretty big dependency. Let's remove it.

**Comment by MagicCurlyHair** [comment]
Hi @nicojs 
I can take this issue.

**Comment by kmdrGroch** [comment]
@nicojs I have noticed a bug in this template. It doesn't create a label `🔧 Maintenance` and doesn't assign me by default :<

**Comment by nicojs** [comment]
Maybe because I assigned labels directly from "create issue" screen? Sorry about it, I thought it would still add the default label.

**Comment by nicojs** [comment]
Closed with #1799
