### ISSUE TITLE
Enable other rules for eslint

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1796]
As we were talking with Nico in #1731, there are some rules, which could be turned on, as well as tslint rules which are introduced one by one to eslint.
We could make some list which should be enabled.

**Comment by simondel** [comment]
Hi @kmdrGroch! Right now you have 13 open issues. Could you perhaps merge related issues (such as types and eslint rules) and/or remove obsolete issues?

filter: https://github.com/stryker-mutator/stryker/issues/created_by/kmdrGroch

**Comment by brodybits** [comment]
I would *personally* not favor combining too many issues together. Just my (US) $0.02 worth as an outsider.

**Comment by simondel** [comment]
I agree that simply grouping everything together may not be the best plan. However, tracking multiple issues regarding eslint rules for example is also not ideal for maintainers. I'd prefer a single issue in such a case with and up to date list of things that have to be fixed.

**Comment by kmdrGroch** [comment]
put everything in #1834 :)
