### ISSUE TITLE
Progress reporter as a progress bar

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#180]
Right now: the progress reporter isn't really helping to show how long the mutation testing progress will take. It shows progress as dots with S's and T's `...ST...`, but you don't know when it will be done. Also, we need to explain somewhere what a `T`, `.` and `S` means.

I think we can solve these issues by implementing it as a progress bar:

```
Mutation testing [===                      ] 12% 37.0s [140 killed] [41 survived] [4 timeout] [6 error]
```

I made a working example: https://github.com/nicojs/progress-reporter-demo-stryker

@simondel What do you think? This would mean as new method for the reporter interface to report the number of mutants to test.

**Comment by simondel** [comment]
Fixed with #195
