### ISSUE TITLE
ERROR on Stryker run, missingPlugin: [ 'optionalChaining' ]

### ISSUE THREAD

**Issue by guilleflmpeya** [stryker-mutator/stryker#1806]
**Question**

How can I make stryker to use this plugin  'optionalChaining' ?
**Stryker environment**

```
├─ @stryker-mutator/api@2.1.0
├─ @stryker-mutator/core@2.1.0
│  ├─ @stryker-mutator/api@^2.1.0
│  ├─ @stryker-mutator/util@^2.1.0
├─ @stryker-mutator/html-reporter@2.1.0
│  ├─ @stryker-mutator/api@^2.1.0
│  ├─ @stryker-mutator/util@^2.1.0
├─ @stryker-mutator/javascript-mutator@2.1.0
│  ├─ @stryker-mutator/api@^2.1.0
├─ @stryker-mutator/jest-runner@2.1.0
│  ├─ @stryker-mutator/api@^2.1.0
├─ @stryker-mutator/util@2.1.0
├─ stryker-cli@1.0.0
```

```

+-- jest@"^24.8.0"

```

**Additional context**

**Comment by simondel** [comment]
Hello :) I don't know what _missingPlugin: [ 'optionalChaining' ]_ means. Where does it come from?

**Comment by guilleflmpeya** [comment]
Sorry, allow me to improve the description of the issue I'm having.
When I do, 'stryker run' I got this:

![image](https://user-images.githubusercontent.com/46934215/67695836-88585380-f984-11e9-990c-f35cb0296f8f.png)

I think is due to this we used in our project
https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining

So the question is, how I make stryker work along whit this plugin?

**Comment by kmdrGroch** [comment]
actually, for now you can't. Tho there is PR with this feature waiting to merge. Track https://github.com/stryker-mutator/stryker/pull/1764 for more info

**Comment by vijaypemmaraju** [comment]
I'm still seeing this same issue in v2.3.0:
![image](https://user-images.githubusercontent.com/1395086/69292761-c29bc600-0bbb-11ea-9e09-e84d4670dbe9.png)

My dependencies:
```
├─┬ @stryker-mutator/babel-transpiler@2.3.0
│ ├─┬ @stryker-mutator/api@2.3.0
│ ├── @stryker-mutator/util@2.3.0
├─┬ @stryker-mutator/core@2.3.0
│ ├── @stryker-mutator/api@2.3.0 deduped
│ ├── @stryker-mutator/util@2.3.0 deduped
├─┬ @stryker-mutator/html-reporter@2.3.0
│ ├── @stryker-mutator/api@2.3.0 deduped
│ ├── @stryker-mutator/util@2.3.0 deduped
├─┬ @stryker-mutator/javascript-mutator@2.3.0
│ ├── @stryker-mutator/api@2.3.0 deduped
├─┬ @stryker-mutator/jest-runner@2.3.0
│ ├── @stryker-mutator/api@2.3.0 deduped
```

**Comment by simondel** [comment]
This is a @babel/parser and/or @babel/generator issue. The mutants can it be successfully generated.

**Comment by vijaypemmaraju** [comment]
false alarm, I realized that the default configuration for `mutator` didn't include `optionalChaining`, I changed my configuration to include this:
```
mutator: {
      name: 'javascript',
      plugins: [
        'asyncGenerators',
        'classProperties',
        'jsx',
        'objectRestSpread',
        'optionalChaining',
        ['decorators', { decoratorsBeforeExport: true }],
      ],
      sourceType: 'unambiguous',
    },
```
and it seemed to work. I thought it was something with the babel configuration i had to override, but I think I led myself down the wrong path.
