### ISSUE TITLE
Unable to load json modules in Stryker

### ISSUE THREAD

**Issue by mega6382** [stryker-mutator/stryker#1811]
**Summary**

**Stryker config**

```js
module.exports = function(config){
  config.set({
        mutator: "typescript",
        packageManager: "npm",
        reporters: ["html", "clear-text", "progress"],
        testRunner: "mocha",
        transpilers: ["typescript"],
        testFramework: "mocha",
        coverageAnalysis: "off",
        tsconfigFile: "tsconfig.json",
        mutate: ["src/**/*.ts", "src/**/*.json", "!src/Interfaces/**/*.ts"]
 });
}
```

**Test runner config**

```
    "mocha": {
        "delay": true,
        "noOpts": true,
        "timeout": 25000,
        "colors": true,
        "require": [
            "source-map-support/register"
        ],
        "recursive": true,
        "spec": "build/test/**/*.test.js"
    },
```
**Stryker environment**

```
+-- @stryker-mutator/core@2.1.0
| +-- @stryker-mutator/api@2.1.0
| +-- @stryker-mutator/util@2.1.0
+-- @stryker-mutator/html-reporter@2.1.0
| +-- @stryker-mutator/api@2.1.0 deduped
| +-- @stryker-mutator/util@2.1.0 deduped
+-- @stryker-mutator/mocha-framework@2.1.0
| `-- @stryker-mutator/api@2.1.0 deduped
+-- @stryker-mutator/mocha-runner@2.1.0
| +-- @stryker-mutator/api@2.1.0 deduped
+-- @stryker-mutator/typescript@2.1.0
| +-- @stryker-mutator/api@2.1.0 deduped
| +-- @stryker-mutator/util@2.1.0 deduped
```

```
+-- mocha@6.2.0
```

**Test runner environment**

```shell
nyc mocha
```

```json
```

**Your Environment**

| software         | version(s)
| ---------------- | -------  
| node             | v10.15.1
| npm              | 6.11.3
| Operating System | Windows 10

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker/files/3778178/stryker.log)

**Comment by mega6382** [comment]
@nicojs Thanks for replying, I have prepared this mcve for you test(https://github.com/mega6382/stryker-ts-test). There are two issues in total that I am facing. First is that the json files are not being copied over to the build directory when I run stryker, but they are when I run tsc. You can test this by:

1. Run `npm run test` to see that it works with simple tsc and using mocha directly.
2. run `npm run stryker` to see that it does not work with stryker

Also, when I hard code the value of the json module to test stryker without it, it doesn't run any tests and gives the warning "WARN InitialTestExecutor No tests were executed". Now, this has something to do with me surrounding my tests with `(async (): Promise<void> => {/**TEST HERE**/})();` which I need because the tests in my actual code are on async functions and http calls. You can test this by:

1. Remove the `import data` line from app.ts and comment the `const data` declaration. 
2. Run `npm run test` to see that it works using mocha directly.
3. run `npm run stryker` to see that it does not work with stryker

I'll be waiting to here back from you.

**Comment by mega6382** [comment]
@nicojs Any update on this?

**Comment by brodybits** [comment]
I would *personally* categorize this as a feature request, since JSON is not 100% the same thing as JavaScript.

I would recommend considering use of .conf(ig).js or .conf(ig).ts files as a workaround.

**Comment by mega6382** [comment]
@brodybits OK, but there is still a problem, if you were to checkout the repo I shared above you can see that there is still a problem even if I were to hard code the values in the TS file. Can you help me with that please?

**Comment by brodybits** [comment]
@mega6382 I fixed up `src/test/unit/app.test.ts` as follows:

```typescript
import { app } from "../../app/app";
import { expect } from "chai";

  describe("app", () => {
    it("should return string", async () => {
      const result = await app();
      expect(result).to.equal("Test string");
    });
  });
```

Works for me now, I hope it is clear. You should be able to find the explanation elsewhere, if needed.

I was also wondering why you have "|| true" in the package test script entry, does not look right. Maybe I am missing something here.

Please keep in mind that I am not a maintainer, just wanted to help the user community out a little. Considering that most open-source projects are run by overworked volunteers, a little extra patience, research, and debugging on the part of the users would be much appreciated.

**Comment by mega6382** [comment]
@brodybits I had already the tried the approach that you have mentioned above, but it is not feasible for me to use it in my actual code. Because I need to use the instance of app in multiple tests in the same file.  This code works when simply running with mocha, I would just like to know why it doesn't in stryker.

You can ignore the "|| true".

**Comment by kmdrGroch** [comment]
Is this issue still present?

**Comment by simondel** [comment]
Hi! I'm closing this issue for now. If it still persists with Stryker version 4, please open a new issue. Thanks!
