### ISSUE TITLE
change Promises into async functions

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1817]
We should consider changing Promises to async functions. The 'how it works' would stay the same with the increase of performance (really slight tho) and readability (huge)

**Comment by nicojs** [comment]
Sure, go ahead. Be sure to also take error handling into account.

```ts
doWork()
  .then(() => doMoreWork())
  .catch(err => handleError(err))
  .then(() => doEvenMoreWork())
```

Becomes:

```ts
try {
  await doWork();
  await doMoreWork();
} catch(err) {
  await handleError();
}
await doEvenMoreWork();
```
