### ISSUE TITLE
Travis files

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1829]
Are we still using Travis?
I can see we have .travis folder and travis.yml, but we are using GitHub ci, aren't we?

Should them be removed?

**Comment by simondel** [comment]
Yes we are. We use Travis to release. This has not yet been migrated to Github Workflows.

**Comment by brodybits** [comment]
> This has not yet been migrated to Github Workflows.

I wonder if this should be tracked in an issue?

Travis CI seems to be sadly another point of potential CI build failure.

Thanks!
