### ISSUE TITLE
Some generated mutants randomly survive or are killed

### ISSUE THREAD

**Issue by rdroog** [stryker-mutator/stryker#1849]
**Question**
There are mutants generated for my code that are killed in some runs of Stryker, but not in others. It feels like they are randomly killed or they randomly survive sometimes, and I am not sure what could cause this and how I can reproduce it with a smaller code example which I can share (it occurs in commercially used software).

I've already tried almost all options in `stryker.conf.js` which could be the problem, but this didn't fix my problem.

The problem does not occur when I create a smaller set of unit tests to be run (by adding `.only` to a describe which covers a function which had sometimes surviving, sometimes killed mutants).

**Stryker environment**
conf:
```
module.exports = function(config) {
  config.set({
    mutator: "javascript",
    packageManager: "yarn",
    reporters: ["html", "clear-text", "progress"],
    testRunner: "mocha",
    transpilers: [],
    testFramework: "mocha",
    coverageAnalysis: "all",
    files: [
      '**',
      '!node_modules/**'
    ],
    mutate: [
      '**/*.js',
      '!stryker.conf.js',
      '!test/**',
      '!reports/**'
    ]
  });
};
```

Stryker:
```
@stryker-mutator/core@2.2.1
@stryker-mutator/html-reporter@2.2.1
@stryker-mutator/javascript-mutator@2.2.1
@stryker-mutator/mocha-framework@2.2.1
@stryker-mutator/mocha-runner@2.2.1
```

Other:
```
mocha@6.1.4
```

**Comment by kmdrGroch** [comment]
Thanks for sharing this. It might actually be an issue, but we are missing some data. If it's possible. I would like to take a look at your code (unless it's private/unable to share) or some example project where this issue occurs.

**Comment by kmdrGroch** [comment]
It might be an issue with timeouts. Although I think it is mostly solved. Can it be closed for now?

**Comment by simondel** [comment]
Hi! I'm closing this issue for now. If it still persists with Stryker version 4, please open a new issue. Thanks!
