### ISSUE TITLE
Move configuration info to the website

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#185]
Right now, a lot of the README of Stryker contains information about the different available configuration options. This information is duplicated across multiple repo's such as the grunt-stryker repo. I think it would be a good idea to move the information about config options to the [website](https://github.com/stryker-mutator/stryker-mutator.github.io). That way we have one source of the truth.

**Comment by nicojs** [comment]
Hmm sounds logical. How would you version the documentation for multiple versions? Karma does this by keeping a copy of the documentation for every major release. Do you want to do the same thing?

**Comment by philippw** [comment]
@nicojs and @simondel have agreed to not do this.
Instead, we recommend to simply consult the README.md file.

Closing.
