### ISSUE TITLE
Possible performance boosts

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1860]
Lurking through youtube, I have found an interesting video about new features in V8. We might want to check this out.
https://youtu.be/GEDtFdli4Us?t=1217

(+ this issue could be left is anyone finds another possibility [to have everything in 1 place])

**Comment by kmdrGroch** [comment]
@nicojs What is `typed-inject` doing at all? I see it almost everywhere in stryker, but honestly, I have no idea what it a purpose is.
+ have you probably check how performant it is? Since we are using it in quite a few places, if it is slowing stryker down, it might be a great performance improve

**Comment by simondel** [comment]
How is the concurrency improvement in Chrome relevant for us? I would assume that Chrome uses these features automatically.

Typed inject is used for dependency injection. Since it's only used to instantiate classes, I don't think the performance matters in our application

**Comment by kmdrGroch** [comment]
Chrome and node use the same JavaScript engine - V8. Each V8 feature / update could be used in Stryker. And I mostly was thinking about this JSON.parse Vs plain object performance.
