### ISSUE TITLE
Pro-society activity - Stryker a cancer killer

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1863]
I was thinking if we could set up some donations (via GitHub sponsors or patreon or something like this, and collect money for cancer treatment charities). We could also promote other activities such as giving blood or other cancer-treatment-related things, via ex. our license / readme.

Since stryker is about 'mutation testing' I find it quite relevant to support this kind of activity.

What are your thoughts about it? :)

**Comment by brodybits** [comment]
Please change the title to read something like "Stryker a cancer killer". When I first saw the title I thought it meant something else.

Otherwise +100

**Comment by kmdrGroch** [comment]
Thanks for feedback @brodybits, done :)

**Comment by simondel** [comment]
I'm closing this for now. I don't think it's something we'll so.
