### ISSUE TITLE
Unexpected ConditionalExpression for assignment

### ISSUE THREAD

**Issue by mauricedb** [stryker-mutator/stryker#1866]
**Summary**

When assigning a `displayName` for a React component Stryker mutates this using a `ConditionalExpression` even though there is no condition here at all.

This is part of the following React component:
```TypeScript
import React, { ReactElement, ReactChild } from "react";

type LabelProps = {
  caption: ReactChild;
  name?: string;
};

const Label = ({ caption, name }: LabelProps): ReactElement => {
  return <label htmlFor={name}>{caption}</label>;
};

Label.displayName = "Label";

export default Label;
```

**Stryker config**

```js
// This config was generated using a preset.
// Please see the handbook for more information: https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/guides/react.md#react
module.exports = function(config) {
  config.set({
    mutate: [
      "src/**/*.ts?(x)",
      "!src/*.ts?(x)",
      "!src/**/*@(.test|.spec|Spec).ts?(x)"
    ],
    mutator: "typescript",
    testRunner: "jest",
    reporters: ["progress", "clear-text", "html"],
    coverageAnalysis: "off",
    tempDirName: "stryker-tmp",
    jest: {
      projectType: "react"
    }
  });
};
```

**Test runner config**

This is a non ejected Create-React-App application using Jest.

**Stryker environment**

```
+-- @stryker-mutator/core@2.3.0
| +-- @stryker-mutator/api@2.3.0
| +-- @stryker-mutator/util@2.3.0
+-- @stryker-mutator/html-reporter@2.3.0
| +-- @stryker-mutator/api@2.3.0 deduped
| +-- @stryker-mutator/util@2.3.0 deduped
+-- @stryker-mutator/jest-runner@2.3.0
| +-- @stryker-mutator/api@2.3.0 deduped
+-- @stryker-mutator/typescript@2.3.0
| +-- @stryker-mutator/api@2.3.0 deduped
| +-- @stryker-mutator/util@2.3.0 deduped```
```

```
    "react-scripts": "3.2.0",
```

**Test runner environment**

```shell
 "test": "react-scripts test",
```

```json
```

**Your Environment**

| software         | version(s)
| ---------------- | -------  
| node             | v10.15.3
| npm              | 6.11.3
| Operating System | Windows 10 Version 1809

**Add stryker.log**
[stryker.log](https://github.com/stryker-mutator/stryker/files/3862779/stryker.log)

**Comment by simondel** [comment]
Well well well... Turns out TypeScript classifies this as a BinaryExpression of all things..

![image](https://user-images.githubusercontent.com/4221997/69218610-61e79b80-0b71-11ea-984a-0e332aee5f70.png)

In this case, the EqualsToken should be added to the invalid operators:
https://github.com/stryker-mutator/stryker/blob/f2ff418d73c94b79c5e823cb3f96b8caa52f70bc/packages/typescript/src/mutator/ConditionalExpressionMutator.ts#L25-L37
