### ISSUE TITLE
Automatically check for formatting errors in this and other repos

### ISSUE THREAD

**Issue by brodybits** [stryker-mutator/stryker#1878]
**Is your maintenance request related to a problem? Please describe.**

Not all files are automatically checked for formatting errors. I raised a few recent PRs to clean up trailing whitespace, a few extra blank lines, and replace tabs with spaces in a JSON file.

**Describe the solution you'd like**

A lint task should check for formatting errors in files such as doc (md), JSON, and YML files.

Prettier seems to do this on its doc (md) files, at least.

**Describe alternatives you've considered**

Manual cleanup with help from grep and sed

**Additional context**

I discovered the formatting errors while doing `git log -p`, which highlights the trailing spaces. This is what I sometimes use to check my recent work in a git repo.

I am raising this partially in response to @nicojs <https://github.com/stryker-mutator/stryker/pull/1874#issuecomment-557493115>:

> @brodybits did you use a linting tool for this? If so it might be worth adding it to our linting CI/CD phase so we can prevent this from happening again

**Comment by kmdrGroch** [comment]
Do you want to take this task? Or should do it?

**Comment by brodybits** [comment]
> Or should do it?

That would be awesome, thanks!

**Comment by kmdrGroch** [comment]
Is it still valid? I have made quite a lot changes to linter so far 🤔

**Comment by brodybits** [comment]
I think so, as discussed in #2174. I would love to work on this but am juggling some other priorities right now.

**Comment by simondel** [comment]
I'll close this for now. if someone wants to pick it up, feel free to do so 👍
