### ISSUE TITLE
Arrow Function mutator missing for JavaScript

### ISSUE THREAD

**Issue by brodybits** [stryker-mutator/stryker#1901]
**Summary**

Arrow Function mutator exists in the TypeScript mutator but not in the JavaScript mutator.

This is already fixed by PR #1898, which is going through its review cycle at this point.

I also reported this in <https://github.com/stryker-mutator/stryker/issues/1893#issuecomment-558431379>.

**Stryker config**

see <https://github.com/stryker-mutator/stryker/blob/master/packages/javascript-mutator/stryker.conf.js>

**Test runner config**

see <https://github.com/stryker-mutator/stryker/blob/master/packages/javascript-mutator/package.json>

**Stryker environment**

see <https://github.com/stryker-mutator/stryker/blob/master/packages/javascript-mutator/package.json>

**Test runner environment**

see <https://github.com/stryker-mutator/stryker/blob/master/packages/javascript-mutator/package.json>

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 12.13.1 |
| npm              | 6.12.1 |
| Operating System | Linux, macOS|

~~**Add stryker.log**~~

**Comment by simondel** [comment]
Fixed with #1898
