### ISSUE TITLE
Mutator of Array constructor without `new` missing for TypeScript

### ISSUE THREAD

**Issue by brodybits** [stryker-mutator/stryker#1902]
**Summary**

The following test updates show Array constructor mutator that is missing for TypeScript:

```diff
--- a/packages/mutator-specification/src/ArrayDeclarationMutatorSpec.ts
+++ b/packages/mutator-specification/src/ArrayDeclarationMutatorSpec.ts
@@ -20,6 +20,9 @@ export default function ArrayDeclarationMutatorSpec(name: string, expectMutation
     it('should mutate filled Array constructor calls as empty arrays', () => {
       expectMutation('new Array(a, 1 + 1)', 'new Array()');
       expectMutation("new Array('val')", 'new Array()');
+      // XXX known issue on TypeScript mutator:
+      expectMutation("Array('val')", 'Array()');
+      expectMutation('Array(a, 1 + 1)', 'Array()');
     });
 
     it('should not mutate other new expressions', () => {
@@ -29,6 +32,8 @@ export default function ArrayDeclarationMutatorSpec(name: string, expectMutation
 
     it('should mutate empty array constructor call as a filled array', () => {
       expectMutation('new Array()', 'new Array([])');
+      // XXX known issue on TypeScript mutator:
+      expectMutation('Array()', 'Array([])');
     });
   });
 }

```

**Stryker config**

see <https://github.com/stryker-mutator/stryker/blob/master/packages/javascript-mutator/stryker.conf.js>

**Test runner config**

see <https://github.com/stryker-mutator/stryker/blob/master/packages/javascript-mutator/package.json>

**Stryker environment**

see <https://github.com/stryker-mutator/stryker/blob/master/packages/javascript-mutator/package.json>

**Test runner environment**

see <https://github.com/stryker-mutator/stryker/blob/master/packages/javascript-mutator/package.json>

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 12.13.1 |
| npm              | 6.12.1 |
| Operating System | Linux, macOS|

~~**Add stryker.log**~~

**Comment by kmdrGroch** [comment]
Nice catch!
