### ISSUE TITLE
Pre-test config generation & db start

### ISSUE THREAD

**Issue by guyellis** [stryker-mutator/stryker#1908]
**Question**

In my package.json I have this for testing:

```javascript
"test": "npm run test-db-start && npm run build-test && jest",
```

With stryker, how do I specify that those 2 tasks should run before Stryker runs? Can't find that in the docs.

**Stryker environment**

```
├─┬ @stryker-mutator/core@2.4.0
│ ├─┬ @stryker-mutator/api@2.4.0
│ ├── @stryker-mutator/util@2.4.0
├─┬ @stryker-mutator/html-reporter@2.4.0
│ ├── @stryker-mutator/api@2.4.0 deduped
│ ├── @stryker-mutator/util@2.4.0 deduped
├─┬ @stryker-mutator/jest-runner@2.4.0
│ ├── @stryker-mutator/api@2.4.0 deduped
├─┬ @stryker-mutator/typescript@2.4.0
│ ├── @stryker-mutator/api@2.4.0 deduped
│ ├── @stryker-mutator/util@2.4.0 deduped
```

```
    "jest": "24.9.0",
```

**Additional context**

**Comment by simondel** [comment]
Hi! Right now, the only way to do that is to use the command test runner: https://www.npmjs.com/package/@stryker-mutator/core#testrunner--string-

When using that setting, make sure to set `maxConcurrentTestRunners` to `1` to prevent multiple processes from using your database at the same time: https://www.npmjs.com/package/@stryker-mutator/core#maxconcurrenttestrunners--number-
