### ISSUE TITLE
Something broke from 2.0.2 to 2.4.0

### ISSUE THREAD

**Issue by unsegnor** [stryker-mutator/stryker#1914]
**Summary**

There appear 2 new survivors when updating from 2.0.2 to 2.4.0

Steps to reproduce:

1. clone the public repo: git@github.com:unsegnor/persistent-programming.git
2. npm i
3. npm test
4. everything should pass green
5. npm update
6. npm test
7. now there are 2 extra survivors in the file StatefulObject.js

I hope it helps :)

Thanks in advance for your time.

**Comment by kmdrGroch** [comment]
funny thing... in version 2.1.0 it's working the same. In version 2,2,1 it generates 2 mutants which survive, in version 2,3.0 only 1 survives, in version 2.4 again 2 survive...

**Comment by kmdrGroch** [comment]
@unsegnor  Ok... so I think I have found a solution to this.
These "survivors" found in files are indeed found correctly (more or less). The one with array:
persistent-programming\domain\StatefulObject.js:48:26
-               var objects = []
+               var objects = ["Stryker was here"]

Actually only fails in integration tests! It passes units.

The second one:
-       function isStringValue(value){
-           return (typeof(value) === 'string') || isAListOf(value, 'string')
-       }
+       function isStringValue(value){}

actually fails in a different unit-test file.
A solution to fix that is to change `coverageAnalysis` to `off`

**Comment by kmdrGroch** [comment]
```js
module.exports = function(config) {
  config.set({
    mutator: "javascript",
    packageManager: "npm",
    reporters: ["clear-text", "progress"],
    testRunner: "mocha",
    transpilers: [],
    testFramework: "mocha",
    coverageAnalysis: "perTest",
    mochaOptions:{
      spec: ['domain/*.spec.js', 'adapters/*.spec.js', 'test-doubles/*.spec.js', 'test-integration/*.spec.js']
    },
    mutate: ['domain/*.js',
      '!domain/*.spec.js',
      '!domain/*.port.js',
      '!domain/*.factory.js'],
    maxConcurrentTestRunners: 2
  });
};
```

**Comment by unsegnor** [comment]
Wow! thanks for your quick and complete response :)

I wanted stryker to ensure that I cover all my domain logic just with the unit tests
so I added the missing test for the array error (nice mutator by the way :+1: )
and modified the coverageAnalysis as you said
it worked with any other configuration "off", "all" and "perTestInIsolation"
I still don't get why XD I think I read something about heuristics...

Anyway, thanks again for your time and for taking care of this awesome tool :)

**Comment by kmdrGroch** [comment]
@unsegnor, the point of mutation is to check if a given mutation will cause tests to fail or not. If tests fail after mutation, it means, your tests are complete (you really checked all [most]) cases. If they pass, it means you are missing some points.

If you have any question, feel free to ask, I will try to answer them (the more specific question the better tho, since I'm not an expert too ;D)
