### ISSUE TITLE
jest-runner doesn't work with jest "projects"

### ISSUE THREAD

**Issue by anilanar** [stryker-mutator/stryker#1926]
**Summary**

When using a jest config file with `projects` property, `stryker run` fails with `Jest: Cannot use configuration as an object without a file path.` Related: https://github.com/facebook/jest/issues/5421#issuecomment-363274999

**Stryker config**

```js
module.exports = function(config) {
  config.set({
    mutate: ['src/**/*.(js|ts)?(x)', '!src/**/*@(.test).(js|ts)?(x)'],
    mutator: 'typescript',
    testRunner: 'jest',
    reporters: ['progress', 'clear-text', 'html'],
    coverageAnalysis: 'off',
    jest: {
      projectType: 'custom',
      config: require('./config/jest/jest.config.js'),
    },
  });
};
```

**Test runner config**

```
jest: {
      projectType: 'custom',
      config: require('./config/jest/jest.config.js')
}
```

**Stryker environment**

```
+-- @stryker-mutator/core@2.4.0
+-- @stryker-mutator/api@2.4.0
+-- @stryker-mutator/util@2.4.0
+-- @stryker-mutator/html-reporter@2.4.0
+-- @stryker-mutator/jest-runner@2.4.0
+-- @stryker-mutator/typescript@2.4.0
```

```
+-- jest@24.9.0
```

**Test runner environment**

```shell
jest -c config/jest/jest.config.js
```

```js
module.exports = {
  rootDir: path.join(__dirname, '../../'),
  projects: [
    {
      ...common,
      displayName: 'Foo',
    },
    {
      ...common,
      displayName: 'Bar',
    },
  ],
};
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 11.12.0
| yarn              | 1.19.1
| Operating System | MacOS 10.14.4

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker/files/3972566/stryker.log)

**Comment by simondel** [comment]
Hi @anilanar could you please create a small repository with a reproduction of this issue?

**Comment by simondel** [comment]
Hi! I'm closing this issue for now. If it still persists with Stryker version 4, please open a new issue. Thanks!
