### ISSUE TITLE
No killed mutations running Stryker on Stryker

### ISSUE THREAD

**Issue by Jelle28** [stryker-mutator/stryker#1950]
**Summary**

Running Stryker on Stryker reports a mutation score of 0 for every file, see the image below.
![image](https://user-images.githubusercontent.com/22443689/71818898-8e586800-308a-11ea-9ba4-9142f241f107.png)

**Stryker config**
Stryker.conf.js from core:
```
const path = require('path');
const settings = require('../../stryker.parent.conf');
const moduleName = __dirname.split(path.sep).pop();
settings.dashboard.module = moduleName;
module.exports = function (config) {
  config.set(settings);
};

```
**Stryker environment**

```shell
# Test command
stryker run


**Your Environment**

| software         | version(s)
| ---------------- | -------
| npm              | 6.9.0
| Operating System | windows 10
| mocha            | 6.2.2

**Comment by nicojs** [comment]
Hi @Jelle28 👋

Can't reproduce this one.

I've changed the stryker.conf.js content to only mutate `SourceFile.ts`. Could you try this as well:

```ts
const path = require('path');
const settings = require('../../stryker.parent.conf');
const moduleName = __dirname.split(path.sep).pop();
settings.dashboard.module = moduleName;
module.exports = function (config) {
  config.set(settings);
  config.set({
    mutate: ['src/SourceFile.ts']
  })
};
```

It should look like this:

![image](https://user-images.githubusercontent.com/1828233/71832129-8c9e9c80-30aa-11ea-8fba-ef7fa59acccd.png)


I don't think this is a problem with mocha. Version 6.2.2 is already 3 months old and always worked fine until now. 

Please try from a fresh clone on the master branch.

**Comment by Jelle28** [comment]
Hey @nicojs,
Thanks for the reply, I think I made a mistake creating a fresh clone of the master branch as I'm also unable to reproduce this problem in master now.
Unfortunately this problem is still occuring within my own branch. Updating mocha up to 7 didn't work. Any ideas?

**Comment by lamka-tatya** [comment]
Same problem here. 
No killed mutations running Stryker on Windows 10 (I tried to run Striker for single file - the same result). 
If I run striker on WSL/Ubuntu it shows some killed mutations.

npm --version
6.14.7 (on both Windows 10 and Ubuntu)

My repo: https://github.com/lamka-tatya/otus_react_game_of_life/tree/stryker

Run on Windows 10:
![stryker_windows10](https://user-images.githubusercontent.com/20819222/91097834-1797cb80-e669-11ea-82da-7ee502e3891a.png)

Same for single file (Windows 10):
![mutate_single_file_windows10](https://user-images.githubusercontent.com/20819222/91097927-3ac27b00-e669-11ea-9e2b-34da7e79a3a4.png)

Run the same project on WSL/Uduntu:
![stryker_wsl_ubuntu](https://user-images.githubusercontent.com/20819222/91097954-4746d380-e669-11ea-87e0-1e444b24a2f6.png)
