### ISSUE TITLE
To many open files error.

### ISSUE THREAD

**Issue by fsvieira** [stryker-mutator/stryker#1974]
**Summary**

Everytime I try to run stricker on my project I get 

ERROR StrykerCli an error occurred { [Error: EMFILE: too many open files, open '/media/filipe/Data/fsvieira/github/identicobjects/node_modules/chardet/match.js']
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path:
   '/media/filipe/Data/fsvieira/github/identicobjects/node_modules/chardet/match.js' }

Its always a file from node modules, and not always the same file, maybe stricker is searching node_modules dir ?

**Stryker config**

```js
module.exports = function(config) {
  config.set({
    mutator: "javascript",
    packageManager: "npm",
    reporters: ["html"],
    testRunner: "jest",
    transpilers: [],
    coverageAnalysis: "off"
  });
};
```

**Test runner config**

No Configuration, using Jest.

**Stryker environment**

```
├─┬ @stryker-mutator/core@2.5.0
│ ├─┬ @stryker-mutator/api@2.5.0
│ ├── @stryker-mutator/util@2.5.0
├─┬ @stryker-mutator/html-reporter@2.5.0
│ ├── @stryker-mutator/api@2.5.0 deduped
│ ├── @stryker-mutator/util@2.5.0 deduped
├─┬ @stryker-mutator/javascript-mutator@2.5.0
│ ├── @stryker-mutator/api@2.5.0 deduped
├─┬ @stryker-mutator/jest-runner@2.5.0
│ ├── @stryker-mutator/api@2.5.0 deduped
```

```
+-- jest@24.9.0
```

**Test runner environment**

```shell
# npm test
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v11.12.0
| npm              | 6.13.6
| Operating System | Linux Ubuntu

**Add stryker.log**

npx stryker run --fileLogLevel trace --logLevel debug
22:13:29 (18886) INFO ConfigReader Using stryker.conf.js in the current working directory.
22:13:29 (18886) DEBUG ConfigReader Loading config stryker.conf.js
22:13:29 (18886) DEBUG ConfigReader Loaded config: {
  "mutate": [
    "{src,lib}/**/*.js?(x)",
    "!{src,lib}/**/__tests__/**/*.js?(x)",
    "!{src,lib}/**/?(*.)+(spec|test).js?(x)",
    "!{src,lib}/**/*+(Spec|Test).js?(x)"
  ],
  "logLevel": "debug",
  "fileLogLevel": "trace",
  "timeoutMS": 5000,
  "timeoutFactor": 1.5,
  "plugins": [
    "@stryker-mutator/*"
  ],
  "reporters": [
    "html"
  ],
  "coverageAnalysis": "off",
  "testRunner": "jest",
  "mutator": "javascript",
  "transpilers": [],
  "maxConcurrentTestRunners": null,
  "symlinkNodeModules": true,
  "thresholds": {
    "break": null,
    "high": 80,
    "low": 60
  },
  "allowConsoleColors": true,
  "dashboard": {
    "baseUrl": "https://dashboard.stryker-mutator.io/api/reports",
    "reportType": "mutationScore"
  },
  "tempDirName": ".stryker-tmp",
  "packageManager": "npm",
  "configFile": "stryker.conf.js"
}
22:13:29 (18886) DEBUG PluginLoader Loading @stryker-mutator/* from /media/filipe/Data/fsvieira/github/identicobjects/node_modules/@stryker-mutator
22:13:29 (18886) DEBUG PluginLoader Loading plugin "/media/filipe/Data/fsvieira/github/identicobjects/node_modules/@stryker-mutator/html-reporter" (matched with expression @stryker-mutator/*)
22:13:29 (18886) DEBUG PluginLoader Loading plugin "/media/filipe/Data/fsvieira/github/identicobjects/node_modules/@stryker-mutator/javascript-mutator" (matched with expression @stryker-mutator/*)
22:13:29 (18886) DEBUG PluginLoader Loading plugin "/media/filipe/Data/fsvieira/github/identicobjects/node_modules/@stryker-mutator/jest-runner" (matched with expression @stryker-mutator/*)
22:13:29 (18886) DEBUG PluginLoader Loading plugins /media/filipe/Data/fsvieira/github/identicobjects/node_modules/@stryker-mutator/html-reporter
22:13:29 (18886) DEBUG PluginLoader Loading plugins /media/filipe/Data/fsvieira/github/identicobjects/node_modules/@stryker-mutator/javascript-mutator
22:13:29 (18886) DEBUG PluginLoader Loading plugins /media/filipe/Data/fsvieira/github/identicobjects/node_modules/@stryker-mutator/jest-runner
22:13:29 (18886) DEBUG PluginLoader Loading plugins /media/filipe/Data/fsvieira/github/identicobjects/node_modules/@stryker-mutator/core/src/reporters/index.js
22:13:30 (18886) DEBUG BroadcastReporter Broadcasting to reporters ["html"]
22:13:30 (18886) ERROR StrykerCli an error occurred { [Error: EMFILE: too many open files, open '/media/filipe/Data/fsvieira/github/identicobjects/node_modules/chardet/encoding/unicode.js']
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path:
   '/media/filipe/Data/fsvieira/github/identicobjects/node_modules/chardet/encoding/unicode.js' }

**Comment by ankila1b2** [comment]
did you received answer for this? @fsvieira 
I am having the same error but I think its because of the node version 8.14.0. We are not going to upgrade it. Also, the cluster is hosted on ec2 instances, and I suppose, it requires a node update and an instance which more CPU cores. Please let me know how did you resolved this issue?

**Comment by fsvieira** [comment]
I didn't got any answer and I was unable to solve it. I am running on my personal computer and you can see that I have an upgraded node and still have this problem. 

I just tried another project https://github.com/TheSoftwareDesignLab/mutode , it seems to work.

**Comment by kmdrGroch** [comment]
Yea, it seems Stryker takes node_modules,... Do you have "node_modules" in .gitignore? Or you could try "files" option.

**Comment by fsvieira** [comment]
Hi,

I know that I have tried some file configuration before and didn't work, maybe I used the wrong field.

But now I tried the .gitignore with node_modules and it worked thanks.

**Comment by kmdrGroch** [comment]
@fsvieira option "files" takes by default all files - gitignored. So basically you told Stryker to base on all your files(including node_modules) and mutate these from SRC/test

**Comment by fsvieira** [comment]
@kmdrGroch well I actually tried the field "mutate" like it is in here https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/guides/angular.md

But it didn't work. But .gitignore works for me, thanks.

**Comment by kmdrGroch** [comment]
yeaa. there is a difference between `files` and `mutate` :)
