### ISSUE TITLE
Have a reporter for only the summary

### ISSUE THREAD

**Issue by quoininc-huudatran** [stryker-mutator/stryker#1984]
**Is your feature request related to a problem? Please describe.**
I usually run stryker post coverage (with `nyc`). So in order for me to see the coverage report, I need to scroll up past all the mutant errors.

**Describe the solution you'd like**
I would like to have a reporter (`text-summary`) that would only display the final table. If you look at `nyc`, you have that `text-summary` reporter.

**Describe alternatives you've considered**
My alternative was to remove the `clear-text` reporter and just use `progress` but it's not as informative. I also tried to split my `nyc` coverage test, run `stryker`, then run `nyc report --reporter=text --reporter=text-summary`

**Additional context**
Here is illustrated what the new reporter would output:
![text-summary-reporter](https://user-images.githubusercontent.com/52758369/73046015-484b2480-3e3e-11ea-8025-f00ab9342d2e.png)

**Comment by simondel** [comment]
Hi 👋 I'll update the image you posted today to ensure that we're on the same page :)

**Comment by simondel** [comment]
So if I understand it correctly, what you're proposing is this:
![afbeelding](https://user-images.githubusercontent.com/4221997/74327185-fede5d00-4d8b-11ea-8b8d-aa25748ca8e7.png)

Would you expect the
> Ran 0.00 tests per mutant on average.

To be part of the text-summary as well?

**Comment by quoininc-huudatran** [comment]
I honestly do not look at that runtime stats info, so it's up to you if you feel it's useful or not for other people.

My goal is just to avoid the 5000 lines of output that I would only look at if I'm in dev, and honestly, I just look at the html output, so I will never look at that output myself.

**Comment by simondel** [comment]
I'm leaning towards always showing the table. Even if you only specify the html report. What would you think of that?

**Comment by quoininc-huudatran** [comment]
I think you want that as an option so people could completely hide it if they want.
