### ISSUE TITLE
mocha + babel not running "perTest"

### ISSUE THREAD

**Issue by quoininc-huudatran** [stryker-mutator/stryker#1987]
**Summary**

I do not believe the mutation are done on my code and tests are re-ran. I have a project that works all well, and when I try to add stryker, the output doesn't make sense to me. I think without the `perTest`, the same module in memory is re-used for mutation, which doesn't make sense.

It is very hard to find documentation, so maybe I am missing something.

**Stryker config**

**Test runner config**

**Stryker environment**

**Test runner environment**

For all above, see github project: https://github.com/Quoin/react-utils

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v12.13.1
| npm              | 6.13.1
| Operating System | MacOS 10.15.2

**Add stryker.log**

Obtainable from running the code from git repo above at your convenience.

**Comment by kmdrGroch** [comment]
coverageAnalysis should be `perTest` if you want this feature

**Comment by quoininc-huudatran** [comment]
When I set the `perTest`,  I get the following error:

```
15:28:11 (29283) ERROR StrykerCli an error occurred StrykerError: Could not instrument "<path-to-repo>/react-utils/src/action-creator.js" for code coverage. Inner error: SyntaxError: BABEL_PARSER_SOURCETYPE_MODULE_REQUIRED (undefined) SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (1:0)
```

I am not clear where `sourceType: "module"` should be added/set. Can you help me figuring out how to change my configuration for it to work?




I tried to do the following change on my local to see if it changes anything according to the stryker reports.

```
diff --git a/src/constants.unit.test.js b/src/constants.unit.test.js
index 09ba966..a1217e8 100644
--- a/src/constants.unit.test.js
+++ b/src/constants.unit.test.js
@@ -15,8 +15,11 @@ describe(`src/constants`, () => {
         'ERROR_BOUNDARY_SUFFIX',
         'INIT_TYPE'
     ].forEach((property) => {
-        it(`should have property '${property}'`, () => {
+        it(`has non-empty string property '${property}'`, () => {
             expect(clone).to.have.property(property);
+            expect(clone[property]).to.be.a('string');
+            console.log(`...clone.${property}='${clone[property]}'.`);
+            expect(clone[property]).to.have.length.above(0);
             delete clone[property];
         });
     });
```

**Comment by kmdrGroch** [comment]
It basically complains about syntax... It probably could be fixed in babel config... Basically you have to use `require` syntax instead of `import/export`... Ill take a look

**Comment by quoininc-huudatran** [comment]
Thanks, you can notice that with that specific configuration, the `npm run coverage` works with valid coverage report in `reports/coverage`, so this is why it confuses me when adding stryker. I will much appreciate the help to get this resolved as I am looking into integrating more of our projects with stryker.

**Comment by kmdrGroch** [comment]
@quoininc-huudatran I checked it. Unfortunately, perTest feature is not supported by the babel transpiler:
`Inner error: Invalid `coverageAnalysis` "perTest" is not supported by the stryker-babel-transpiler. Not able to produce source maps yet. Please set it to "off".`

**Comment by quoininc-huudatran** [comment]
Ok, but that only means that the coverage report is basically useless? So no point to use stryker at all as soon as we use babel?

**Comment by kmdrGroch** [comment]
coverageAnalysis just makes stryker run faster. It doesn't affect the result
https://github.com/stryker-mutator/stryker/blob/master/packages/core/README.md#coverageanalysis-string

**Comment by simondel** [comment]
It looks like Babel has added sourcemap support so we may actually be able to implement this. @quoininc-huudatran Would you be willing to give this a shot?

**Comment by quoininc-huudatran** [comment]
@simondel Please show me how this is done?

@kmdrGroch I have tried to add tests covering what stryker changes does, but it did not change the stryker coverage, that's why I wonder if it works.

**Comment by quoininc-huudatran** [comment]
I just needed to wake up a little. I added the sroucemaps to `.babelrc`, and completely removed babel from stryker. See [commit](https://github.com/Quoin/react-utils/commit/f1f9bdfbbb41b64f2fb4a0b561f7beb6ccf2d505)

Only remaining "warnings" for my setup is:

```
npm WARN @stryker-mutator/mocha-framework@2.5.0 requires a peer of mocha@>= 2.3.3 < 7 but none is installed. You must install peer dependencies yourself.
npm WARN @stryker-mutator/mocha-runner@2.5.0 requires a peer of mocha@>= 2.3.3 < 7 but none is installed. You must install peer dependencies yourself.
```

I am using mocha@7 and I am not sure if anything is broken, but that could be another issue for another time.

Thanks all for your help pointing me to the babel sourcemap.
