### ISSUE TITLE
Stryker-CLI - create stryker.conf.json file with $schema

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#2000]
Since we have pushed schema file for Stryker config, w could use it. My idea is to create JSON file config (which we support too ;) ). And add $schema property so intellisence will give help popups:
```json
{
   "$schema": "url_to_schema_from_schemastore/stryker",
  The rest of the stryker options
}
```

**Comment by nicojs** [comment]
Awesome idea! We want to have this in for our v3 release. 👍
