### ISSUE TITLE
Add support for generating a local Stryker mutation score badge

### ISSUE THREAD

**Issue by screendriver** [stryker-mutator/stryker#2011]
**Question**

Is it possible to generate the Stryker badge [![Mutation testing badge](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fbadge-api.stryker-mutator.io%2Fgithub.com%2Fstryker-mutator%2Fstryker%2Fmaster)](https://dashboard.stryker-mutator.io/reports/github.com/stryker-mutator/stryker/master) locally on machine or CI pipeline? The reason for that is that I'm not able to use your dashboard in my current environment.

For example I'm using a really great tool called [jscpd](https://github.com/kucherenko/jscpd) for copy & paste detection and this tool has a [badge reporter](https://github.com/kucherenko/jscpd-badge-reporter) that generates a badge locally during my CI pipeline. I could imagine that Stryker could do something like that in a similar way?

**Comment by simondel** [comment]
That's a great idea! I've changed this to a feature request. If this could be done using an SVG file, it would be great to have it in the core project. If however, you have to generate an actual (binary) image, I'd prefer to have this functionality in a separate plugin.

The new local-badge-reporter (or whatever it will be called) can use this existing part of the API to get it's data:
https://github.com/stryker-mutator/stryker/blob/a3d4f08ac725c822ca93ed663c43a80522aebaf3/packages/api/src/report/Reporter.ts#L49-L54

**Comment by screendriver** [comment]
> Would you be willing to implement this feature?

I would, yes. If you guide me how to do it. I don't know anything about your codebase yet and therefore I don't know where to put this thing into.

For  the badge generation itself I would use [badgen](https://github.com/badgen/badgen). It's a pretty good svg badge generator. 

First steps: should I create a new package within this repository and use `onMutationTestReportReady()` or should I create a dedicated plugin in my own GitHub account?
