### ISSUE TITLE
[Jest] Remove deprecated react pojecttypes

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#2021]
The project types `react` and `react-ts` are deprecated and should be removed.

**Comment by nicojs** [comment]
I would want to keep them in a little bit longer. Project type `react` is just added a month ago. I will add the 4.0 milestone to it.

**Comment by dbartholomae** [comment]
Any news on this? So far I couldn't get it to running :(

**Comment by simondel** [comment]
Hi @dbartholomae how would removing support for a deprecated confit setting help you?

**Comment by dbartholomae** [comment]
Maybe I misunderstood @nicojs comment - I thought there were discussions to reads the feature :)

**Comment by nicojs** [comment]
For anyone that is scratching your head: project types are simply renamed.

`react` -> `create-react-app`
`react-ts` -> `create-react-app-ts`

**Comment by dbartholomae** [comment]
Thanks! It's good to know they are supposed to work. I'll create a separate ticket then on the errors I receive when trying to get this to run :)
