### ISSUE TITLE
Change versioning for all Lint related packages to specific version

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#2030]
To sum up: I have noticed that some linting packages tend to make a breaking change (change in rules / default settings etc) in patch version 0.0.x and since we are using ```~```, there are problems sometimes. Simply removing ```~``` from all linting packages should help. Drawback - more PRs about updating them

**Comment by simondel** [comment]
@kmdrGroch I would be fine with this change. The PRs should be automeged since they're devDependencies.

Would you be willing to fix this?
