### ISSUE TITLE
Mocha test runner doesn't clear test filter

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#2032]
**Summary**

The `@stryker-mutator/mocha-runner` test runner plugin doesn't clear the test filter after a run with a test filter. The consequence is an incorrect result. This can be seen in the report of Stryker itself in a number of places. For example:

https://dashboard.stryker-mutator.io/reports/github.com/stryker-mutator/stryker/master#core/initializer/presets/ReactPreset.ts

![image](https://user-images.githubusercontent.com/1828233/74421016-a9b65000-4e4c-11ea-87cd-ed80a56adf6f.png)

This file should be almost entirely green, since it is well tested 😇. However, you can see it isn't a.t.m. 👿

Current workaround: Don't use coverage analysis `'perTest'` in conjunction with the mocha test runner.

**Stryker config**

```js
module.exports = function(config){
  config.set({
    testRunner: 'mocha',
    coverageAnalysis: 'perTest'
  });
}
```

I'll be working on a fix.

**Comment by simondel** [comment]
Oh no...

**Comment by nicojs** [comment]
This simple test reproduces the problem:

```ts
it('should be able to clear the filter after a filtered run', async () => {
    const testHooks = wrapInClosure(testFramework.filter([test0, test3]));
    await sut.proxy.run({ testHooks });
    const actualResult = await sut.proxy.run({ testHooks: undefined });
    expect(actualResult.tests).lengthOf(5);
});
```

F.y.i. @MrFix93 this is the bug we've spotted together.
