### ISSUE TITLE
Feature: pass a function to the command runner

### ISSUE THREAD

**Issue by jpsilva** [stryker-mutator/stryker#2033]
**Is your feature request related to a problem? Please describe.**
I have an Angular + Jest setup. Running `ng test` normally completes all of my 692 tests in 1-1.5 minutes.
Stryker, using the the jest-runner plugin, takes over 17 hours to run a full mutation test, which I think is far too long.
Using the default command runner (which runs every test for each mutation) would take more than a week straight according to Stryker’s estimation.

**Describe the solution you'd like**
After a lot of research and experimentation, I found the that Jest’s --test-path-pattern CLI param will pass through Angular CLI to Jest, and using that allows me to run just one test file at a time.

To set that param to the correct file each time, I would like to be able to pass a function to the command runner config instead of just a static string. That function should accept RunOptions as a parameter.

The following code takes the path of the mutated file and adds `.spec` to it to get the associated test file:  

```
 const command = 'npx ng test --runInBand --runTestsByPath';

function fileNameToSpecRegex(mutatedFileName) {
  return mutatedFileName.replace(/^.*\/sandbox\d+\//, '').replace(/\.ts$/, '.spec.ts').replace(/\./g, '\\.');
}

module.exports = function(config) {
…
    commandRunner: {
      command: ({ mutatedFileName }) => {
        return mutatedFileName
          ? `${command} --passWithNoTests --test-path-pattern="${fileNameToSpecRegex(mutatedFileName)}"`
          : command;
      }
    }
…
```

This may leave out other tests related to the mutant, meaning some mutants could survive the mutation test when they would actually be killed in a full unit test run. But time saved makes it worth it. Using the code above with a modified CommandTestRunner.js, the mutation test ran in 4.5 hours.

**Describe alternatives you've considered**
Getting the coverage output from `ng test` might help, but I doubt it’d do any better than the Jest plugin’s use of --findRelatedTests.

**Additional context**
I already have a change working in CommandTestRunner.ts. If you’d like this feature, I’ll write an associated unit test for it and create a PR. If a similar solution is already available, please let me know because I've been wracking my brain for different ways to speed up this mutation test.

**Comment by simondel** [comment]
This sounds like a nice improvement. Thanks for the detailed description! Is there a way that we can implement this improvement in our jest-runner package so all users can benefit from it?

**Comment by jpsilva** [comment]
I looked into the jest-runner package first, but I quickly found myself out of my depth. The command-runner seems to me to be the generic, jack-of-all-trades solution. This is also a less invasive method. My change basically just adds a few lines of code to one file.
