### ISSUE TITLE
Allow exclusions (!) in a pattern

### ISSUE THREAD

**Issue by john-ring** [stryker-mutator/stryker#204]
I'm following angular standards (https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md) for test files which place the spec files in the same folder as the code.  

This means I need to load all the *.js separately from the *.spec.js files so that the test files do not get mutated.  Unless I'm misinterpretting the readme, this is not currently supported .

> The pattern property is mandatory and contains the globbing expression used for selecting the files. Using ! to ignore files is not supported here.

My stryker.conf.js is below, relevant lines bolded.

module.exports = function (config) {
    config.set({
        files: [
            {
                pattern: 'public/dist/libs/vendor.js', included: true, mutated: false
            },
            {
                pattern: 'src/app/\*\*/module.js', included: true, mutated: true
            },
            {
                pattern: 'src/app/app.js', included: true, mutated: true
            },
            {
                pattern: 'src/app/\*\*/config.js', included: true, mutated: true
            },
            {
                pattern: 'src/app/\*\*/run.js', included: true, mutated: true
            },
            {
               **pattern: 'src/app/\*\*/!(spec).js', included: true, mutated: true**
            },
            {
                pattern: 'src/app/\*\*/*.html', included: true, mutated: false
            },
            {
                pattern: 'src/app/\*\*/*.json', included: true, mutated: false
            },
            **'src/app/\*\*/*.spec.js'**
        ],
        testRunner: 'karma',
        testFramework: 'jasmine',
        coverageAnalysis: 'perTest',
        reporter: ['progress', 'html'],
        logLevel: 'trace',
        karmaConfig: { // these are the defaults
            browsers: ['PhantomJS'],
            frameworks: ['jasmine']
        }
    });
};

**Comment by nicojs** [comment]
It should be supported in the `files` option. However: only when using the string value (not the object) and it must be the very first character in the index. 

This should work:

```javascript
module.exports = function (config) {
config.set({
files: [
{
pattern: 'public/dist/libs/vendor.js', included: true, mutated: false
},
{
pattern: 'src/app/**/module.js', included: true, mutated: true
},
{
pattern: 'src/app/app.js', included: true, mutated: true
},
{
pattern: 'src/app/**/config.js', included: true, mutated: true
},
{
pattern: 'src/app/**/run.js', included: true, mutated: true
},
'!src/app/**/*spec.js',
{
pattern: 'src/app/**/.html', included: true, mutated: false
},
{
pattern: 'src/app/**/.json', included: true, mutated: false
},
'src/app/**/*.spec.js'
],
testRunner: 'karma',
testFramework: 'jasmine',
coverageAnalysis: 'perTest',
reporter: ['progress', 'html'],
logLevel: 'trace',
karmaConfig: { // these are the defaults
browsers: ['PhantomJS'],
frameworks: ['jasmine']
}
});
};
```

**Comment by john-ring** [comment]
Thanks for the quick reply!  However, that isn't seeming to do what I need. Your globs includes all the files, but mutates none.  Keeping your ! line, but including the "other" files for mutation includes the spec files with mutation: true.  Any other suggestions for excluding the .spec files so I can run the tests correctly?

```javascript
module.exports = function (config) {
config.set({
files: [
'!src/app/analytics/*.spec.js',
'src/app/analytics/*.js',
],
testRunner: 'karma',
testFramework: 'jasmine',
coverageAnalysis: 'perTest',
reporter: ['progress', 'html'],
logLevel: 'trace',
karmaConfig: { // these are the defaults
browsers: ['PhantomJS'],
frameworks: ['jasmine']
}
});
};
```

> {"path":"/Users/comdev/Documents/usom/usom-client/src/app/analytics/constants.js","mutated":false,"included":true},
        {"path":"/Users/comdev/Documents/usom/usom-client/src/app/analytics/mixpanel.factory.js","mutated":false,"included":true},
        {"path":"/Users/comdev/Documents/usom/usom-client/src/app/analytics/mixpanel.factory.spec.js","mutated":false,"included":true},
        {"path":"/Users/comdev/Documents/usom/usom-client/src/app/analytics/usabilla.factory.js","mutated":false,"included":true}

while
```javascript
module.exports = function (config) {
config.set({
files: [
 '!src/app/analytics/*.spec.js',
{
    pattern: 'src/app/analytics/*.js', included: true, mutated: true
},
],
testRunner: 'karma',
testFramework: 'jasmine',
coverageAnalysis: 'perTest',
reporter: ['progress', 'html'],
logLevel: 'trace',
karmaConfig: { // these are the defaults
browsers: ['PhantomJS'],
frameworks: ['jasmine']
}
});
};
```

> {"path":"/Users/comdev/Documents/usom/usom-client/src/app/analytics/constants.js","mutated":true,"included":true},
        {"path":"/Users/comdev/Documents/usom/usom-client/src/app/analytics/mixpanel.factory.js","mutated":true,"included":true},
        {"path":"/Users/comdev/Documents/usom/usom-client/src/app/analytics/mixpanel.factory.spec.js","mutated":true,"included":true},
        {"path":"/Users/comdev/Documents/usom/usom-client/src/app/analytics/usabilla.factory.js","mutated":true,"included":true}

**Comment by nicojs** [comment]
The order of including/excluding is important. Ignored files with a `!` only marks files globbed earlier as ignored. So this should work:

```javascript
files: [
  {
    pattern: 'src/app/analytics/*.js', included: true, mutated: true
  },
  '!src/app/analytics/*.spec.js',
  'src/app/analytics/*.spec.js' // Include the spec files again, but with mutated = false
]
```

I think this should also work:

```javascript
files: [
  'src/app/analytics/*.spec.js', // Include the spec files first with mutated = false
  {
    pattern: 'src/app/analytics/*.js', included: true, mutated: true
  }
]
```

An other solution is using the `mutate` option: 

```javascript
files: [
  'src/app/analytics/*.spec.js', 
  'src/app/analytics/*.js' // Include the source files first with mutated = false
],
mutate: [
  'src/app/analytics/*.js'  // mark these files for mutation
]
```

If you use a string in the `files` array, it is added with default values: `mutated: false, included: true`

**Comment by philippw** [comment]
@nicojs: As @john-ring is using the standard angular way of organizing unit tests, we might want to add this to the FAQ or the README.

**Comment by john-ring** [comment]
@nicojs: that did the trick - thanks for the help!

**Comment by nicojs** [comment]
@john-ring no problem! We've just merged a an import option in the [stryker-karma-runner](https://github.com/stryker-mutator/stryker-karma-runner). You should be able to replace all file globbing with `karmaConfigFile: 'karma.conf.js'` in stryker config. We'll release this tomorrow.

@philippw I would just document the new `karmaConfigFile` option and let people only work with that option. That way, you only need 1 list of file globs, shared by both tools.
