### ISSUE TITLE
Update mutation-testing-elements version

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#2047]
There are a lot of quality of life improvements done on the [mutation-testing-elements](https://github.com/stryker-mutator/mutation-testing-elements) repo. Let's release it and update the version here.

**Comment by simondel** [comment]
@nicojs I think I already did this with https://github.com/stryker-mutator/stryker/pull/2072

Can we close this issue?

**Comment by simondel** [comment]
The elements still has to be updated

**Comment by simondel** [comment]
Fixed
