### ISSUE TITLE
Stryker doesn't seem to work with jest snapshots

### ISSUE THREAD

**Issue by jeffreymeng** [stryker-mutator/stryker#2077]
**Summary**

I'm using snapshots to test my React components, but as soon as I add in the shapshot tests, Stryker throws an error saying that the initial tests have failed. The tests work when I run `jest` without stryker.

P.S. Will stryker support jest 26 soon? I had to fix my jest at 25.x.x to even get this far.

**Stryker config**
```js
module.exports = function(config) {
  config.set({
    mutate: ["src/**/*.ts?(x)", "!src/**/*@(.test|.spec|Spec).ts?(x)"],
    mutator: "typescript",
    testRunner: "jest",
    reporters: ["progress", "clear-text", "html"],
    coverageAnalysis: "off",
    jest: {
      projectType: "react",
    },
    timeoutMS: 60000,
    maxConcurrentTestRunners: 4
  })
}

```

**Test runner config**
jest.config.js is below

**Stryker environment**

```
├─ @stryker-mutator/api@2.5.0
├─ @stryker-mutator/core@2.5.0
├─ @stryker-mutator/html-reporter@2.5.0
├─ @stryker-mutator/jest-runner@2.5.0
├─ @stryker-mutator/typescript@2.5.0
├─ @stryker-mutator/util@2.5.0
```

```
+-- jest@24.3.1
+--ts-jest@24.3.0
```

**Test runner environment**

```shell
# Test command
jest
```

jest.config.js
```javascript
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  snapshotSerializers: [
    "enzyme-to-json/serializer"
  ],
  setupFiles: [
    "./src/setupTests.ts",
  ],
  modulePathIgnorePatterns:["<rootDir>/build/", "<rootDir>/node_modules/", "<rootDir>/.cache/", "<rootDir>/.stryker-tmp/"]

};
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 6.14.1
| Yarn             | 1.22.0
| npm              | 12.12.0
| Operating System | MacOS Catalina 10.15.3

**Add stryker.log**
[stryker.log](https://github.com/stryker-mutator/stryker/files/4302900/stryker.log)

**Comment by jeffreymeng** [comment]
I fixed this issue by changing the project type from react to custom.

**Comment by simondel** [comment]
Hi! Jest 25 support has been released with @stryker-mutator version 3! You can read all about it here: https://stryker-mutator.io/blog/2020-03-11/stryker-version-3
