### ISSUE TITLE
Integrate with Agora

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#208]
The [Agora project](https://github.com/softwerkskammer/Agora/issues/1144) wants to do mutation testing, let's help them!

**Comment by nicojs** [comment]
@avassem85 we just released v0.5.6 of stryker, which fixes the issue of excluding files. Would that help with this?

**Comment by simondel** [comment]
Since we're having issues with getting the project up and running due to integration tests and unit tests being mixed. We're closing this issue for now.
