### ISSUE TITLE
npm deprecate html-reporter

### ISSUE THREAD

**Issue by quoininc-huudatran** [stryker-mutator/stryker#2097]
**Is your maintenance request related to a problem? Please describe.**

The deprecation notice for html-reporter is in the README or in stryker run. Can you make it so the warning is displayed when installing?

**Describe the solution you'd like**
```
npm deprecate @stryker-mutator/html-reporter@3.0.0 "Included in @striker-mutator/core@3"
npm deprecate @stryker-mutator/html-reporter@3.0.1 "Included in @striker-mutator/core@3"
```

**Describe alternatives you've considered**

**Additional context**

**Comment by simondel** [comment]
Done! Thanks for the reminder <3
