### ISSUE TITLE
Typescript mutation

### ISSUE THREAD

**Issue by quoininc-huudatran** [stryker-mutator/stryker#2098]
**Question**

It's not very easy to figure out what went wrong, even following the documentation when dealing with Typescript.

This is the error I get:

```
11:11:12 (51967) ERROR StrykerCli an error occurred Error: Emit error! Could not emit file /some/path/react-utils/src/action-creator.ts
```

Running the "debug" doesn't really help. I've never been able to get a typescript project to work with stryker. This project is a conversion from ES6 to typescript, and stryker was working well after figuring out the map in #1987, so I would like to have stryker working on it back again.

Repo info in additional context below.

Would anyone be able to point me to the right direction?

Regards,

**Stryker environment**

```
├─┬ @stryker-mutator/core@3.0.1
│ ├─┬ @stryker-mutator/api@3.0.1
│ ├── @stryker-mutator/util@3.0.1
├─┬ @stryker-mutator/javascript-mutator@3.0.1
│ ├─┬ @stryker-mutator/api@3.0.1
├─┬ @stryker-mutator/mocha-framework@3.0.1
│ ├─┬ @stryker-mutator/api@3.0.1
│ └── @stryker-mutator/util@3.0.1
├─┬ @stryker-mutator/mocha-runner@3.0.1
│ ├─┬ @stryker-mutator/api@3.0.1
├─┬ @stryker-mutator/typescript@3.0.1
│ ├─┬ @stryker-mutator/api@3.0.1
│ ├── @stryker-mutator/util@3.0.1
```

```
+-- mocha@7.1.0
```

**Additional context**

Node@12 lts

Repo: https://github.com/Quoin/react-utils

```
npm ci
npm run stryker
```

**Comment by kmdrGroch** [comment]
Could you please try newer version of stryker and validate if it is still a valid issue? :)

**Comment by quoininc-huudatran** [comment]
> Could you please try newer version of stryker and validate if it is still a valid issue? :)

I'm sorry, I've converted it back to JS since the project needed TS didn't use this library anymore.
