### ISSUE TITLE
karma-jasmine@3.1.0 does not support test filtering

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#2102]
karma-jasmine@3.1.0 does not support test filtering. This causes Stryker to run more tests than usual and it can impact your mutation score.

More info can be found here: https://github.com/karma-runner/karma-jasmine/issues/256

**Comment by nicojs** [comment]
@simondel did you ever come around to fix this? I thought you were working on this?

**Comment by simondel** [comment]
I added detailed info to the karma-jasmine issue describing what’s causing the issue and asking why the code has been changed like that, but I don’t believe any action has been taken so far

**Comment by nicojs** [comment]
Yes there is. The author states that there were no tests failing so he assumed it was fine. Adding an integration test and putting the code back seems fine.

**Comment by simondel** [comment]
Fixed with karma-jasmine 3.3.1
