### ISSUE TITLE
Improve validation on Stryker options.

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#2103]
Right now there is no standardized and complete way (for both plugins as well as the core) to do the validation. 

For example, this config file will result in no errors at the moment:

```js
{
  "concurrency": 2,
  "reporter": ["clear-text"]
  "thresholds": {
    "error": 80
   }
}
```

**Solution**

I want to allow use [JSON Schema](https://json-schema.org/) to validate. We can use [AJV](https://github.com/epoberezkin/ajv) as validator. As for human-readable error messages we can use [AJV errors](https://github.com/epoberezkin/ajv-errors). As a bonus, we could let AJV [assign defaults](https://github.com/epoberezkin/ajv#assigning-defaults).

Plugins could contribute parts of the schema dynamically by adding a `schema/stryker-plugin.json` (name pending) file in their respective plugins.

Verifying that no additional properties are present can be done by running the schema validation with `additionalProperties: false`. They should be logged as warning. We should allow JSON comments by not warning about settings with the postfix `"comment"`. We could allow a `--noWarnOnAdditionalConfiguration` (name pending) to not warn about additional settings (otherwise people might get frustrated).

**Comment by simondel** [comment]
Sounds good!

**Comment by kmdrGroch** [comment]
I am so happy now that we made this schema :D

**Comment by nicojs** [comment]
A start has been made on #2123 . It will validate the core schema and not yet warn about additional properties, but it's a start.

Feel free to review and merge that one 😅
