### ISSUE TITLE
Mocha 7.x.x Support

### ISSUE THREAD

**Issue by MHeironimus** [stryker-mutator/stryker#2108]
**Is your feature request related to a problem? Please describe.**
If I reference the latest version of Mocha (e.g. 7.1.1), I see the following warnings when doing an `npm install`:

~~~
npm WARN @stryker-mutator/mocha-framework@3.0.2 requires a peer of mocha@>= 2.3.3 < 7 but none is installed. You must install peer dependencies yourself.
npm WARN @stryker-mutator/mocha-runner@3.0.2 requires a peer of mocha@>= 2.3.3 < 7 but none is installed. You must install peer dependencies yourself.
~~~

**Describe the solution you'd like**
Is there a plan to update Stryker to explicitly support Mocha versions greater than 6?

**Describe alternatives you've considered**
Stryker appears to work correctly with Mocha 7, so simply ignoring the `npm install` warnings is OK for now.

**Additional context**
FYI:
```
"devDependencies": {
    "@stryker-mutator/core": "3.0.2",
    "@stryker-mutator/mocha-framework": "3.0.2",
    "@stryker-mutator/mocha-runner": "3.0.2",
    "@stryker-mutator/typescript": "3.0.2",
    "@types/chai": "4.2.11",
    "@types/express": "4.17.3",
    "@types/mocha": "7.0.2",
    "@types/node": "13.x.x",
    "@types/sinon": "7.5.2",
    "@types/sinon-express-mock": "1.3.7",
    "@types/uuid": "7.0.2",
    "adm-zip": "0.4.14",
    "aws-sdk": "2.641.0",
    "chai": "4.2.0",
    "mocha": "7.1.1",
    "mocha-junit-reporter": "1.23.3",
    "nyc": "15.0.0",
    "rimraf": "3.0.2",
    "sinon": "9.0.1",
    "sinon-express-mock": "2.2.1",
    "ts-node": "8.6.2",
    "tslint": "6.1.0",
    "typescript": "3.8.3"
  },
```

**Comment by nicojs** [comment]
>  Is there a plan to update Stryker to explicitly support Mocha versions greater than 6?

Of course we are 😅. Just didn't get around to it.

Can you confirm that Stryker 3.0.2 works well with mocha 7? On the surface there doesn't seem to be any breaking changes on the mocha API that we're using.
