### ISSUE TITLE
New progress reporter not working on wndows/MINGW64

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#212]
The new progress reporter is not showing up in MINGW64, which is the terminal installed by default using the git installer.

**Comment by nicojs** [comment]
I did some more investigation. It turns out that the current progress reporter will *never* work on windows/MINGW64. Or to be more accurate, on windows + mintty (no idea what the difference is exactly.

It works when you start stryker directly using node (as in `node node_modules/.bin/stryker run`) but not as you let git bash host the node process (as in `node_modules/.bin/stryker run`). 

The way i see it, we have 3 choices:
1. Choose to log an error and don't do progress reporting. Maybe even explain how to solve it (i.e. use cmd or start stryker directly with a node command).
2. Log an error/warning and fallback on the dots reporter (not ideal)
3. Log an error/warning and fallback on a new minimalistic progress reporter. Just log every tenth mutant what the progress percentage is, including number killed, survived, etc.

@bkimminich and @simondel which one should we choose. I would prefer the 3th solution, although it's more work.

Background info:
When using mintty and you start a new process, it's not a *true* integrated command line anymore. Instead it's a pipe (without input stream). Things like `stream.clearLine` and `stream.columns` are not supported. The progress reporter is smart and just [returns without drawing the progress bar](https://github.com/visionmedia/node-progress/blob/master/lib/node-progress.js#L124). We should check `process.stderr.isTTY` before calling the progress reporter. For more information see:  https://github.com/nodejs/node/issues/3006

**Comment by avassem85** [comment]
Maybe this can help as well?  https://github.com/visionmedia/node-progress/issues/110

**Comment by simondel** [comment]
That's very strange. Nice find! I would prefer the third solution. We know the pattern so if all else fails we can just report every once in a while.

**Comment by nicojs** [comment]
Hmm maybe i'll try to fix it in [visionmedia/node-progress#110](https://github.com/visionmedia/node-progress/issues/110). Thanks @avassem85

**Comment by bkimminich** [comment]
I could live with dots, but the new shiny thing would of course be cooler, even with reduced refresh rate.
