### ISSUE TITLE
`coverageAnalysis: 'perTest'` does not work for large coverage results

### ISSUE THREAD

**Issue by zxxc** [stryker-mutator/stryker#214]
I have not very big project, when i tried to switch on mutation on one folder of this project that contains 273 js files, stryker is stuck after executing initial test run
And throws time out exception
![image](https://cloud.githubusercontent.com/assets/13364984/21671013/a18d2076-d329-11e6-8531-c8f8a6465aa3.png)

If i tried to add only some subfolders (doesn't matter which one) with 100 or 150 it's working perfect and i even can see new progress reporter and report. Usually 150 such files is somewhere about 12 000 mutations

**Comment by nicojs** [comment]
@zxxc thanks for creating this issue!

It seems like your *not very big project* is the bigest one I've seen so far. We'll make it work 👍

First of all, could you tell us how long it takes for the timeout to occur? Is it around 5 minutes? Are you using the [stryker-karma-runner](https://github.com/stryker-mutator/stryker-karma-runner)?

Second, can you try to set `coverageAnalysis` to `'all'`? If that doesn't work, could you try `'off'`? Ive got the feeling the timeout occurs while sending back the code coverage results (per test) from the karma process to stryker.  If so, changing the `coverageAnalysis` should work.

If the initial test run succeeds with a different `coverageAnalysis`, it should be able to run mutation testing. However, it might take a while for mutation testing to complete.

**Comment by zxxc** [comment]
![image](https://cloud.githubusercontent.com/assets/13364984/21759626/be1e9a0a-d656-11e6-90a1-939b149ed251.png)

yes, stryker-karma-runner
i set coverageAnalysis = 'all', 
put if to RemoveConditionals by https://github.com/stryker-mutator/stryker/issues/216,
maxConcurrentTestRunners:5,

 and stryker genereted 36000 mutations and seems working, i will run it for all night later

**Comment by zxxc** [comment]
time increased about 10 times compared with 'perTest'
![image](https://cloud.githubusercontent.com/assets/13364984/21759751/c89f6896-d657-11e6-9f57-9123cb9d69b0.png)
we have 1500 tests, without covering, time for one launch is about 13 seconds

**Comment by nicojs** [comment]
@zxxc very cool progress reporter, i will dedicate a tweet to your progress bar (`ETC 60826`  :astonished:). Are you using the `html` reporter? That is the only report that will make sense with so many 16000 mutants.

So the bug belonging to this issue is: ` coverageAnalysis: 'perTest'` does not work for large coverage results.

**Comment by zxxc** [comment]
![image](https://cloud.githubusercontent.com/assets/13364984/21795577/df48a866-d713-11e6-99de-5c2da2a30f19.png)

**Comment by zxxc** [comment]
my conf:
```
// stryker.conf.js
module.exports = function(config){
  config.set({
    files: [
	        'test/unit/imcon.fake.js',

            //bundles/libs
            "Scripts/*.js",

            //bundles/app
            'app/*.js',

             // Tests
            'test/unit/utBootstrapper.js',
            'templates.js',
            //bundles/app
            'app/utils/*.js',

            //bundles/shared
            'app/shared/**/*.js',

            //bundles/components
            'app/components/**/*.js',

            // Tests
            'Scripts/tmhDynamicLocale.js',
            'test/unit/preconditions.js',
			'test/unit/itaPreconditions.js',
            'js/model/ita/result.js',
            'js/model/ita/ResultListModel.js',
            
            'test/unit/app/**/*.js',      
    ],
    mutate: [        
        'app/shared/**/*.js',
        'app/components/**/*.js'
    ],
    testRunner: 'karma',
    testFramework: 'jasmine',
    coverageAnalysis: 'all',
    reporter: ['progress','html'],    
	htmlReporter: {
            baseDir: 'mutation_reports/jstests' 
	},
    maxConcurrentTestRunners:5,
	logLevel: 'debug',
	karmaConfig: {
	    browsers: ['Chrome'],
	    frameworks: ['jasmine'],
	    singleRun: true,
	    autoWatch: false
	}
  });
}
```

**Comment by nicojs** [comment]
> run is failed and hard to say why. Any ideas?

Well... not really. It seems that we could not send a message to the test runner's child process ... for some reason. Could you create a new issue for this? We might have to make that part more resilient (for example, create a new test runner child process and try again).

> or i will split my mutations by 12 000 and start by parts  i have some problems with my app and tests

That should already help a lot, less time mutation testing means less time that this issue could appear.

> Should i reduce maxConcurrentTestRunners:5 to 4?

Well.. that depends.. are you using phantomjs or a different browser? If you are using firefox/chrome: what is your cpu at? If constant > 90%, you might want to lower the number yeah. As i can see from the number of timeouts (9 timeouts out of > 15000 mutants tested) the tests are not suffering. The timeouts that appeared are likely mutants that caused an infinite loop.

**Comment by nicojs** [comment]
For the original issue: `coverageAnalysis: 'perTest'`

Could you try to increase a timeout? In file `node_modules/stryker-karma-runner/src/KarmaTestRunner.js` on line 131. Change `karmaConfig.browserNoActivityTimeout = 1000000;` to `karmaConfig.browserNoActivityTimeout = 10000000;` for example.

Does that fix the initial test run with `codeAnalysis: 'perTest'`?

`

**Comment by nicojs** [comment]
>Could you create a new issue for this?

No need to do that, already did it in #218

**Comment by zxxc** [comment]
![image](https://cloud.githubusercontent.com/assets/13364984/21879535/8024b3c8-d8aa-11e6-8cfd-9a73749b6c0d.png)
My config:
![image](https://cloud.githubusercontent.com/assets/13364984/21879556/90365c30-d8aa-11e6-8489-65e3473dfcfa.png)

**Comment by nicojs** [comment]
Hmm this is a different error if i'm not mistaken. We never had this one during the initial test run. The noActivityTimeout does not occur anymore. How long does it take to produce this error? 

Could you try to rerun it with `logLevel: 'trace'`? That will produce all logging from karma as well. Maybe we can see what the error is.

**Comment by zxxc** [comment]
![image](https://cloud.githubusercontent.com/assets/13364984/21880168/7fcf22b0-d8ae-11e6-9dfe-6a08a376ae0f.png)

**Comment by zxxc** [comment]
logLevel:'trace':

[npm-debug.txt](https://github.com/stryker-mutator/stryker/files/701007/npm-debug.txt)
[run with logLevelTrace.txt](https://github.com/stryker-mutator/stryker/files/701010/run.with.logLevelTrace.txt)
![image](https://cloud.githubusercontent.com/assets/13364984/21881965/8438dc00-d8b9-11e6-9d3d-1c9599411c16.png)

see attached log

**Comment by nicojs** [comment]
@simondel would you agree that this would probably be solved if we could cut down on the amount of data to be send from the karma process to stryker? I'm thinking of a way to only send the valuable coverage results.

Right now, we the coverage (`perTest`) result looks like this:
```javascript
{
   "1": {
       "file1": {
           "s": { "1": 3, "4": 24, /*...*/ }
           },
        "file2" {  /*...*/ },
         /*...*/
        },
   "2": { /*...*/}
    /*...*/
}
```
So a count of *each statement* of *each file* for *each test*. I tested it with [uibootstrap](https://github.com/angular-ui/bootstrap) and the initial test run response is a total of **160219827 bytes (more than 160 MB)**. That is for 1308 tests and 61 files to mutate. I think its just too much data to be sending cross process.

We can cut down the cost considerately if we are smart about it. In fact, you only want to send which statements are actually hit per test. If we leave out the 0's i think we would be a long way in fixing this issue.

**Comment by nicojs** [comment]
I tried it for uibootstrap this morning. 

Leaving out the `0`'s makes for 34111465 bytes (~34 MB). Than i tried to also change the file names from full path to numbers (0, 1, 2 ,etc). This saved again some data, now down to 28564210 bytes (~28.5 MB). 

Than i tried to split the statement map per test. Instead of having one statement map per file per test, i have a blue print taken at the start of the first test. Now per test you only send the hit statements in respect to the blue print. This took the size down considerately: 4444875 bytes (~4,5 MB). You will have to merge it back at the other end, but that should be simple enough. We shouldn't even truly merge it back, as that would mean loading ~160MB back into memory. Just keep the 2 split and do the calculations that way.

**Comment by nicojs** [comment]
Maybe we should use `"baseLine"` instead of `"blueprint"`.

**Comment by nicojs** [comment]
Update: i did the PR on the stryker-api:
https://github.com/stryker-mutator/stryker-api/pull/15

If that is merged i can proceed with the PR on stryker.
