### ISSUE TITLE
The mutator named 'RemoveConditionals' caused an error: TypeError: Cannot read property 'nodeID' of null

### ISSUE THREAD

**Issue by zxxc** [stryker-mutator/stryker#216]
![image](https://cloud.githubusercontent.com/assets/13364984/21759300/63442692-d654-11e6-8e3d-65e9b53d74f9.png)

node.test is absent
![image](https://cloud.githubusercontent.com/assets/13364984/21759346/b7be54ea-d654-11e6-952a-e8e2cc610da7.png)

**Comment by zxxc** [comment]
For now i change string in RemoveConditionalsMutator.js to 
RemoveConditionalsMutator.prototype.applyMutations = function (node, copy) {
        if (node.test && this.canMutate(node)) {

but seems problem somewhere earlier

**Comment by simondel** [comment]
Do you have for-loops without a test?
```
for (var I = 0; ; i++)
```

**Comment by zxxc** [comment]
quick search returns 
![image](https://cloud.githubusercontent.com/assets/13364984/21762317/17b77a8e-d669-11e6-8450-2ebb3a06b57e.png)

is it something that can broke stryker? if so, my fix is ok and can't skip a lot of suitable mutations?

**Comment by zxxc** [comment]
and in qtaController:

**Comment by nicojs** [comment]
This is a known issue.

@simondel do you know if someone is already working on a fix?

**Comment by simondel** [comment]
Ah yes, that's a known bug that we plan to fix (#166). We want to mutate it so it will become
```js
for(;false;) {
```

@nicojs I wrote some code this morning but I haven't tested it yet

**Comment by nicojs** [comment]
Ok, just let me know when i can review it.

@zxxc you can work around it by changing `for(;;)` in `while(true)`

**Comment by simondel** [comment]
Or `for(;true;)`
