### ISSUE TITLE
Stryker .NET throws compile error during initial test run

### ISSUE THREAD

**Issue by kish0** [stryker-mutator/stryker#2207]
Stryker throws a compile error during the initial test run on vstest.
No special configurations, just specified the path for my *.csproj file on cmd. 
Attached the file with logs on the cmd during test run.
[StrykerLogs.txt](https://github.com/stryker-mutator/stryker/files/4628241/StrykerLogs.txt)
 
Please let me know if you need additional information.

**Comment by nicojs** [comment]
Moved to https://github.com/stryker-mutator/stryker-net/issues/1075
