### ISSUE TITLE
NPM run postinstall in Contributing.md  

### ISSUE THREAD

**Issue by RobDWaller** [stryker-mutator/stryker#2217]
**Question**

Under "Runner Stryker" in the Contributing.md should there be a reference to the command `npm run postinstall`?

I ask this because I could not get my local environment running until the `lerna bootstrap` command had run.

**Additional context**

Running in a docker node 12 environment.

**Comment by nicojs** [comment]
It refers to `npm install` which should run `postinstall` automatically. It didn't for you?

See https://docs.npmjs.com/misc/scripts

**Comment by RobDWaller** [comment]
I'm going to rebuild my environment from scratch, most likely I did something wrong first time around. 👍

**Comment by nicojs** [comment]
Ok cool. Closing this issue for now.

Out of curiosity, anything specific you're planning to work on?

**Comment by RobDWaller** [comment]
I'd just like to help out a bit now I have some time, I'm quite good at writing tests so will happily help out with improving test coverage. Or anything else which needs looking at.

**Comment by nicojs** [comment]
That sounds awesome. We're working on implementing mutation switching, which will be a pretty big overhaul. See https://github.com/stryker-mutator/stryker/issues/1514. Please read through it, so you don't write tests for something we want to delete for example.

In short: the following packages will be replaced by the new "instrumenter" package:
* `@stryker-mutator/javascript-mutator`
* `@stryker-mutator/typescript`
* `@stryker-mutator/mutator-specification`

In `@stryker-mutator/core`, I think about 1/3 to 1/2 of the code will be changed.

**Comment by nicojs** [comment]
If you have more questions, don't hesitate to [join our slack channel](https://join.slack.com/t/stryker-mutator/shared_invite/enQtOTUyMTYyNTg1NDQ0LTU4ODNmZDlmN2I3MmEyMTVhYjZlYmJkOThlNTY3NTM1M2QxYmM5YTM3ODQxYmJjY2YyYzllM2RkMmM1NjNjZjM)
