### ISSUE TITLE
Specify Mutation Per Type

### ISSUE THREAD

**Issue by maulikhdave9601672767** [stryker-mutator/stryker#2246]
will this work with mot also ?

I have constant mutant now i need to decide how many mutant i need  ??
for that type?

**Comment by nicojs** [comment]
Hi @maulikhdave9601672767 . I'm not 100% sure that I understand the question. There is currently no way to specify how many mutant Stryker will generate per type. It will just generate as much as it can based on your code. 

You can, however, exclude mutators: https://github.com/stryker-mutator/stryker/tree/epic/mutation-switching/packages/core#mutator

**Comment by maulikhdave9601672767** [comment]
thanks for really quick reply.

i m using MOQ in unit test will stryker will work with that also?

**Comment by nicojs** [comment]
yes, Stryker doesn't care about which specific moching framework or assertion framework you use. Which test runner are you using? Mocha, jest-node, karma en jest are supported.

**Comment by maulikhdave9601672767** [comment]
great help
