### ISSUE TITLE
Append a plugin with command line (without removing configured plugins)

### ISSUE THREAD

**Issue by Garethp** [stryker-mutator/stryker#2253]
**Is your feature request related to a problem? Please describe.**
I want to be able to add a plugin through command line (A new reporter), without removing existing plugins. When writing a tool that tried to add functionality to Stryker, I don't know what plugins are being included with the configuration file, but if I try to add it through `--plugins`, then it removes any plugins already specified (Such as `typescript`)

**Describe the solution you'd like**
I'd like a new `--plugin` argument that *appends* to the array of plugins, rather than replacing it

**Describe alternatives you've considered**
I've considered parsing the config file, but that seems rather onerous since my tool isn't built in JS. I've also considered just adding `@stryker-mutator/*`, but the user might be using other plugins (Like I intend to with Specific Lines filter). 

A workaround that I'll likely use without this feature is to ask users to have this plugin specified in their config file, but it's not something that my tool can verify that they're using (and therefore would cause an error if I try to specify that this reporter should be used), so it would better if my tool can explicitly say that this plugin should be in use

**Comment by nicojs** [comment]
Cool! I think I now understand what you mean.

I see 2 ways of implementing this. 

1. We change the way the `--plugins` works and let it just append plugins (breaking change). We could still allow users to still delete all plugins with `--no-plugins` for example.
2. We add a new command-line argument `--append-plugins` which prevents `plugins` to be cleared (minor change). 

I'm actually leaning towards option 2. 

What do you think @Garethp?

cc @simondel

**Comment by Garethp** [comment]
Option 2 sounds like the clearest way to interact with it

**Comment by nicojs** [comment]
Merged with #2385
