### ISSUE TITLE
JestRunner's option "enableFindRelatedTests" does not seem to work correctly

### ISSUE THREAD

**Issue by Tummerhore** [stryker-mutator/stryker#2296]
I've created the following minimal example:

```
⋮
├─ filterByTerm.js
├─ filterByTerm.spec.js   (one test suite with 2 tests)
└─ stryker.conf.json
```

**Stryker environment**
```
+-- @stryker-mutator/core@3.2.4
| +-- @stryker-mutator/api@3.2.4
| +-- @stryker-mutator/util@3.2.4
+-- @stryker-mutator/javascript-mutator@3.2.4
| +-- @stryker-mutator/api@3.2.4 deduped
+-- @stryker-mutator/jest-runner@3.2.4
| +-- @stryker-mutator/api@3.2.4 deduped
```

**Stryker config**:
```
"mutator": "javascript",
"testRunner": "jest",
"transpilers": [],
"coverageAnalysis": "off",
"files": ["**/*.js", "!node_modules/**/*"],
"mutate": ["**/*.js", "!src/__tests__/**/*", "!**/*spec.js", "!reports/**/*"],
"jest": {
    "enableFindRelatedTests": true
}
```

Running `jest --findRelatedTets filterByTerm.js` runs the tests in file `filterByTerm.spec.js` like expected. However, Stryker with the JestRunner option `"enableFindRelatedTests": true` does not run any test on the mutants, resulting in `Ran 0.00 tests per mutant on average.` and a mutation score of 0%.
Of, course, when disabling this option I get the following result: `Ran 2.00 tests per mutant on average.` and mutation score of 100%.

**Comment by nicojs** [comment]
This might be a duplicate of #2122

@Tummerhore , could you please try the workaround specified in https://github.com/stryker-mutator/stryker/issues/2122#issuecomment-605783668 ?

**Comment by Tummerhore** [comment]
Just tried it with the mentioned workaround (temp folder not hidden) and now it's working. Thanks.

**Comment by nicojs** [comment]
No problem ☺️ I'm curious how you setup to config file. Did you use `stryker init`? 

We might need to add `tempDir: 'stryker-tmp'` by default for jest projects, seeing as this issue is open on jests site for a while.

**Comment by Tummerhore** [comment]
Yes I initially used `stryker init` but edited the config file afterwards because this test project is no git repo. In my post I also omitted some iirelevant attributes (e.g. "reporters", "$schema", ...).

**Comment by nicojs** [comment]
Thanks for the info.
