### ISSUE TITLE
Implement coverage analysis for Jest

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#2316]
**Is your feature request related to a problem? Please describe.**
Since we've implemented mutation switching, we can now implement coverage analysis more easily in jest. 

**Describe the solution you'd like**
We would need a way to retrieve the `__mutantCoverage__` object after the dry run. See https://github.com/facebook/jest/issues/7421

We would also need to hook into the [test environment](https://jestjs.io/docs/en/configuration#testenvironment-string)

**Additional context**
Mutation switching: #1514

**Comment by Djaler** [comment]
Should stryker 4.0.0-beta.0 work with jest when coverage analysis disabled?

**Comment by simondel** [comment]
Hi @Djaler Jest is not yet supported by v4, we will add this support soon. I'll update the blog highlight this better.

**Comment by Djaler** [comment]
Yeap, just so far I have understood that only coverage does not work. Maybe you shouldn't release 4.0.0-beta.0 of jest-runner?

**Comment by nicojs** [comment]
F.y.i: jest is supported in the current beta version (`@stryker-mutator/jest-runner@4.0.0-beta.4`)

**Comment by nicojs** [comment]
Just to be clear, jest is supported in the current version but only _with coverage analysis "off"_. This issue is there to implement coverage analysis in jest. We've also shuffled the names of the variables a bit. Mutant coverage is now reported under `__stryker__.mutantCoverage`.
