### ISSUE TITLE
Unify the casing in all file names

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#2338]
**Is your maintenance request related to a problem? Please describe.**
We've been back and forth with the casing in our file names. We started out with `PascalCase` for all files. Later, we diverged for files that contain only a function, or for files that contain multiple things, to `cammelCase`.

In recent times, we see more and more projects to only use [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Special_case_styles) for files. I've started doing that in the new `instrumenter` package.

**Describe the solution you'd like**
Align with all js projects and use only kebab case.

**Describe alternatives you've considered**
\-

**Additional context**
I don't know if there is a way to automate this process. However, it has the potential to be a huge merge conflict thing. It is a one time pain and I want to do this **AFTER** our 4.0 release.

**Comment by kmdrGroch** [comment]
I think it can be checked in linter... I could setup it later :)
