### ISSUE TITLE
Clean up typescript utils

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#2339]
I have seen a lot of typescript utils in this code, deepPartial, deepMerge etc.  (+ Object.keys....)
I was wondering if in the future we could use my package [TSCream](https://github.com/kmdrGroch/TSCream) for these, instead of having these here, we could have them in different repo. This should make our code a bit cleaner (at least "reduce amount of files"). (although I still have a lot of work in my repo...)

**Comment by nicojs** [comment]
I don't think it's a big deal to have some shared types in `utils`. This way its easy to maintain for us. We don't force semver there, we just add to it and remove whenever we feel like it. Sorry :x 

The older I get, the more I'm cautious with adding dependencies with a low attach rate. Especially those without tests 😉. For example, I'll probably create an issue to swap [surrial](https://www.npmjs.com/package/surrial) for [serialize-javascript](https://www.npmjs.com/package/serialize-javascript) once we have mutation switching in, _even though I'm the maintainer of surrial_ (we don't need the class instance serializing anymore in 4.0, so no reason to keep using surrial). Serialize-javascript is just massively more popular.

**Comment by kmdrGroch** [comment]
"Especially those without tests 😉." - I'm still working on it ;D

Ok, I think pulling these types etc to utils would be the best option then. Closing it for now, we will see in the future if there is something we could do :)
