### ISSUE TITLE
Add support for `.mjs` and `.cjs` file formats

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#2343]
The new instrumenter determins the file types based on the extension. We're missing support for `.cjs` and `.mjs` file types.

**Comment by kmdrGroch** [comment]
what are those CJS files? commonJS files? 🤔

**Comment by nicojs** [comment]
Yeah, just needs to be added here: https://www.github.com/stryker-mutator/stryker/tree/epic%2Fmutation-switching/packages%2Finstrumenter%2Fsrc%2Fparsers%2Findex.ts

**Comment by nicojs** [comment]
More info on these extensions can be found here: https://nodejs.org/api/esm.html

A great read IMHO

**Comment by Omhet** [comment]
Hi @nicojs 

That sounds like not much work to do. Can I try to work on this?

**Comment by nicojs** [comment]
Sure! Thanks in advance!
