### ISSUE TITLE
@stryker-mutator/core not in the npm registry

### ISSUE THREAD

**Issue by Wojciechowski-Marcin** [stryker-mutator/stryker#2358]
**Summary**

Hey I'm trying to install Stryker for the first time on my project following the quickstart instruction, but I can't install it directly from npm. 
```
npm ERR! 404  '@stryker-mutator/core@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```
[https://registry.npmjs.org/@stryker-mutator/core](https://registry.npmjs.org/@stryker-mutator/core) gives response {"error":"Not found"}

Then I tried to workaround installing directly from git using https://gitpkg.now.sh, but then `stryker run` says Stryker is currently not installed and asks to install it again. After I chose npm it gives an error 
```
> npm install -D 'https://gitpkg.now.sh/stryker-mutator/stryker/packages/util?master' 'https://gitpkg.now.sh/stryker-mutator/stryker/packages/api?master' 'https://gitpkg.now.sh/stryker-mutator/stryker/packages/core?master'
[...]
+ @stryker-mutator/api@3.3.1
+ @stryker-mutator/util@3.3.1
+ @stryker-mutator/core@3.3.1
added 93 packages from 100 contributors and removed 2 packages in 67.289s

> stryker run
Stryker is currently not installed.
? Do you want to install Stryker locally? npm
[...]
+ @stryker-mutator/core@3.3.1
updated 1 package in 28.915s
Stryker installation done.
Cannot find module '@stryker-mutator/core' from '/home/prontohub/Code/pronto-mailbox/frontend'
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v12.16.1
| npm              | 6.14.5
| Operating System | Ubuntu 18.04.4 LTS

**Comment by nicojs** [comment]
Hi @Wojciechowski-Marcin 👋

I think this was an issue at NPM side. See this thread: https://twitter.com/npmstatus/status/1291290208344760327

Link works again for me. Closing this issue now. If you think otherwise, please say so and I can reopen this issue.
![image](https://user-images.githubusercontent.com/1828233/89524356-b5277a00-d7e4-11ea-93b5-9c303c4bbaca.png)
