### ISSUE TITLE
Remove files from bithound ignore

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#237]
We've added some files to the bithound rc file to be ignored. We ignore them because new 2.1 TypeScript syntax is not supported yet (namely strict null checks)

We should eventually remove these:

```javascript
      "src/TestFrameworkOrchestrator.ts",
      "src/SandboxCoordinator.ts",
      "src/MutantTestMatcher.ts"
```

**Comment by simondel** [comment]
The SandboxCoordinator was removed with #241
