### ISSUE TITLE
Update `stryker init` with new template for Stryker v4

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#2382]
With Stryker v4 a number of things have changed that also need to be reflected in `stryker init`:

* No more test frameworks (simply remove that question).
* No more transpilers -> Replace with question about which Checker to enable.
* Add question about a build command to run.

Also some configuration options have been changed/added. These should be renamed in the template for the options. Also update `initStrykerConfig` in each package.json

**Comment by brodybits** [comment]
Adding a nit: I recall that `stryker init` sets `coverageAnalysis` to `all` with `command` reporter, which results in an error message.
