### ISSUE TITLE
Remove/deprecate old stryker options

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#2383]
We should remove or deprecate the stryker options that v4 no longer uses. A (maybe non-extensive) list:

* `transpilers`
* `mutator.name`
* Defining `mutator` as string
* `testFramework`

We should remove these, or log a warning when people use them. Maybe we can give a comprehensive error message pointing people to the blog article (that needs to be written).

**Comment by kmdrGroch** [comment]
@nicojs I think as long as we update schema and people would actually use it, they will know that they cant use these options anymore (thats for "log a warning when people use them")

**Comment by nicojs** [comment]
Yeah, true. But that might be a unfriendly message. I was thinking to write a custom message with a link to a future blog article or migration guide thing
