### ISSUE TITLE
Reimplement `excludedMutations` with mutation switching

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#2396]
The current `mutator.excludedMutations` is not yet implemented for mutation switching (v4 beta). Let's bring that back

**Comment by ts46235** [comment]
excludedMutations is not supported yet for the typescript mutator in version 3 or 4, correct? 
When can we expect that?

**Comment by nicojs** [comment]
It's supported in the `typescript` mutator in Stryker 3 as well in Stryker 4 (will be released tomorrow).

Note: Stryker 4 will not require you to configure the "typescript" mutator. TypeScript is supported out-of-the box.
