### ISSUE TITLE
Files and folders with emoji in their paths are ignored by Stryker

### ISSUE THREAD

**Issue by Lakitna** [stryker-mutator/stryker#2418]
**Summary**

I ran into this in #2417

Express has test fixtures: https://github.com/expressjs/express/tree/master/test/fixtures 

These fixtures have to be copied to the sandbox for the tests to pass. So far so good. Notice that the `/snow` folder has an emoji in it. This causes Stryker to ignore the folder and thus not copy the file to the sandbox. This causes the initial test run to fail.

I've looked a bit further, and this is also the case for file names with emojis in them. All other files are copied to the sandbox as expected.

Now, this is a pretty obscure bug, but emoji paths are fully supported by Windows, and probably other OSs as well. Still, I'm not sure if it's worth fixing this.

**Stryker config**

= default init with CommonJS + Mocha

```js
/**
 * @type {import('@stryker-mutator/api/core').StrykerOptions}
 */
module.exports = {
  logLevel: 'debug',
  "mutator": "javascript",
  "packageManager": "npm",
  "reporters": [
    "html",
    "progress"
  ],
  "testRunner": "mocha",
  "transpilers": [],
  "testFramework": "mocha",
  "coverageAnalysis": "perTest"
};
```

**Test runner config**

See https://github.com/expressjs/express

**Stryker environment**

```
    "@stryker-mutator/core": "^3.3.1",
    "@stryker-mutator/javascript-mutator": "^3.3.1",
    "@stryker-mutator/mocha-framework": "^3.3.1",
    "@stryker-mutator/mocha-runner": "^3.3.1",
```

See for test runner deps: https://github.com/expressjs/express

**Test runner environment**

See https://github.com/expressjs/express

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 14.5.0
| npm              | 6.14.5
| Operating System | Windows 10

**Add stryker.log**

Note the absence of `/snow`

[stryker.log](https://github.com/stryker-mutator/stryker/files/5122655/stryker.log)

**Comment by nicojs** [comment]
😁⛄😎
