### ISSUE TITLE
Support `mutator.excludedMutations`

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#2423]
**Is your feature request related to a problem? Please describe.**
Stryker 3 supports users configuring their `excludedMutations`. We also want to support those in Stryker 4.

**Describe the solution you'd like**
Still collect the mutants, but mark them as `ignored` (and not place them in the code). Report them as `ignored` as well.

**Describe alternatives you've considered**
Not supporting `excludedMutations`, but I want to reach feature parity as much as possible.

**Comment by Lakitna** [comment]
Duplicate of #2396

Just to be clear, this does not include #1472 right?

**Comment by nicojs** [comment]
haha :) thanks! We're getting there.
