### ISSUE TITLE
Stryker not finding files

### ISSUE THREAD

**Issue by gramster** [stryker-mutator/stryker#2457]
**Summary**

I am trying to run Stryker against the Python extension for Visual Studio Code. Because this has a fairly complex build, I first run through the extensions own compile/build steps (i.e. up to and including the `npx gulp prePublishNonBundle` step described [here](https://github.com/microsoft/vscode-python/blob/main/CONTRIBUTING.md)).

After that is done, there is an `out` directory in the repo, with an `out/client` directory containing the `.js` files for the extension, and an `out/test` directory containing the unit test files. These are usually run using mocha. There are several mocha config files, chosen based on the command used to the tests (in my case, `npm run test:unittests`). I have replicated the key items from the appropriate mocha config file in the Stryker config file shown below.

I have three issues after this when I try to run Stryker:

- it reports that no files are found to mutate
- it says it can't locate module 'out/test/unittests.js' even though it exists
- it does not terminate.

See the log for details.

**Stryker config**

```js
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "packageManager": "npm",
  "reporters": [
    "html",
    "clear-text",
    "progress"
  ],
  "testRunner": "mocha",
   "mochaOptions": {
    "spec": ["./out/test/**/*.unit.test.js"],
    "require": ["out/test/unittests.js"],
    "ui": "tdd"
  },
  "mutate": [ "./out/client/**/*.js" ]
}
```

**Test runner config**

**Stryker environment**

```
├─┬ @stryker-mutator/core@3.3.1
│ ├─┬ @stryker-mutator/api@3.3.1
│ ├── @stryker-mutator/util@3.3.1
├─┬ @stryker-mutator/mocha-framework@3.3.1
│ ├── @stryker-mutator/api@3.3.1 deduped
│ └── @stryker-mutator/util@3.3.1 deduped
├─┬ @stryker-mutator/mocha-runner@3.3.1
│ ├── @stryker-mutator/api@3.3.1 deduped
│ ├── @stryker-mutator/util@3.3.1 deduped
├─┬ @stryker-mutator/typescript@3.3.1
│ ├── @stryker-mutator/api@3.3.1 deduped
│ ├── @stryker-mutator/util@3.3.1 deduped
├─┬ @stryker-mutator/webpack-transpiler@3.3.1
│ ├── @stryker-mutator/api@3.3.1 deduped

├── @types/mocha@5.2.7
├─┬ mocha-junit-reporter@1.23.0
├─┬ mocha-multi-reporters@1.1.7
```

**Test runner environment**

```shell
# Test command
```

```json
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 12.18.0 |
| npm              | 6.14.4 |
| Operating System | MacOS Catalina |

**Add stryker.log**

```
[32m20:47:58 (16625) INFO ConfigReader[39m Using stryker.conf.json
[32m20:47:58 (16625) INFO BroadcastReporter[39m Detected that current console does not support the "progress" reporter, downgrading to "progress-append-only" reporter
[33m20:47:59 (16625) WARN InputFileResolver[39m No files marked to be mutated, Stryker will perform a dry-run without actually mutating anything. You can configure the `mutate` property in your config file (or use `--mutate` via command line).
[32m20:47:59 (16625) INFO InitialTestExecutor[39m Starting initial test run. This may take a while.
[91m20:48:00 (16625) ERROR StrykerCli[39m an error occurred Error: Error: MODULE_NOT_FOUND (undefined) Error: Cannot find module 'out/test/unittests.js'
Require stack:
- /Users/grwheele/repos/vscode-python-me/node_modules/mocha/lib/esm-utils.js
- /Users/grwheele/repos/vscode-python-me/node_modules/mocha/lib/mocha.js
- /Users/grwheele/repos/vscode-python-me/node_modules/mocha/index.js
- /Users/grwheele/repos/vscode-python-me/node_modules/@stryker-mutator/mocha-runner/src/LibWrapper.js
- /Users/grwheele/repos/vscode-python-me/node_modules/@stryker-mutator/mocha-runner/src/MochaOptionsLoader.js
- /Users/grwheele/repos/vscode-python-me/node_modules/@stryker-mutator/mocha-runner/src/index.js
- /Users/grwheele/repos/vscode-python-me/node_modules/@stryker-mutator/core/src/utils/fileUtils.js
- /Users/grwheele/repos/vscode-python-me/node_modules/@stryker-mutator/core/src/utils/TemporaryDirectory.js
- /Users/grwheele/repos/vscode-python-me/node_modules/@stryker-mutator/core/src/di/buildMainInjector.js
- /Users/grwheele/repos/vscode-python-me/node_modules/@stryker-mutator/core/src/di/index.js
- /Users/grwheele/repos/vscode-python-me/node_modules/@stryker-mutator/core/src/child-proxy/ChildProcessProxyWorker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at exports.requireOrImport (/Users/grwheele/repos/vscode-python-me/node_modules/mocha/lib/esm-utils.js:20:12)
    at Function.exports.handleRequires (/Users/grwheele/repos/vscode-python-me/node_modules/mocha/lib/cli/run-helpers.js:94:34)
    at MochaTestRunner.additionalRequires (/Users/grwheele/repos/vscode-python-me/node_modules/@stryker-mutator/mocha-runner/src/MochaTestRunner.js:146:65)
    at MochaTestRunner.init (/Users/grwheele/repos/vscode-python-me/node_modules/@stryker-mutator/mocha-runner/src/MochaTestRunner.js:28:20)
    at ChildProcessTestRunnerWorker.init (/Users/grwheele/repos/vscode-python-me/node_modules/@stryker-mutator/core/src/test-runner/ChildProcessTestRunnerWorker.js:16:45)
    at ChildProcessProxyWorker.doCall (/Users/grwheele/repos/vscode-python-me/node_modules/@stryker-mutator/core/src/child-proxy/ChildProcessProxyWorker.js:73:56)
    at ChildProcess.<anonymous> (/Users/grwheele/repos/vscode-python-me/node_modules/@stryker-mutator/core/src/child-proxy/ChildProcessProxy.js:133:68)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
[32m20:48:00 (16625) INFO StrykerCli[39m Trouble figuring out what went wrong? Try `npx stryker run --fileLogLevel trace --logLevel debug` to get some more info.
```

**Comment by nicojs** [comment]
Hi, @gramster 👋 thanks for opening this issue.

I regret to say that this is working _by design_. Stryker will, by default, assume that only files that are not ignored by git should be copied to the sandbox directory. This behavior can be overridden by specifying `files`, see https://github.com/stryker-mutator/stryker/tree/master/packages/core#files-string.

Note: You might be interested in testing out Stryker 4 beta. With that version, you can now configure a `buildCommand`, which is actually a better fit for your use case. You can let the source files be mutated and let your build command bundle those mutations into the file to be tested. See https://stryker-mutator.io/blog/2020-07-13/announcing-stryker-4-beta-mutation-switching

Also, note that #1593 exists where we're discussing improvements to the current `git` integration.

**Comment by gramster** [comment]
Thank you! I will start by trying the files option, but will definitely look at the beta too.

**Comment by gramster** [comment]
I did get further, but I get a test failure now which doesn't happen when the tests are run without Stryker.

```
08:53:09 (86806) INFO ConfigReader Using stryker.conf.json
08:53:12 (86806) INFO InputFileResolver Found 769 of 3819 file(s) to be mutated.
08:53:12 (86806) INFO InitialTestExecutor Starting initial test run. This may take a while.
08:54:03 (86806) ERROR InitialTestExecutor One or more tests failed in the initial test run:
	Cross process lock Lock guarantees in-process mutual exclusion
		expected false to equal true
	Cross process lock "after all" hook for "Lock guarantees in-process mutual exclusion"
		Current process attempted to release a lock it does not hold
08:54:03 (86806) ERROR StrykerCli an error occurred Error: There were failed tests in the initial test run.
```

I'll see if I get further with the beta.

**Comment by nicojs** [comment]
That's unfortunate. If this happens, the easiest way to debug is to cd into the sandbox directory and try to run the tests yourself.

You can also try to run with `--logLevel trace` (or `--fileLogLevel trace`, if you don't want your console to be overfloaded) to get the stdout and stderr logging from the test runner process.

**Comment by gramster** [comment]
There were a couple of flaky tests I removed and it looks like it is working now. I get a massive amount of runtime errors that I'm not sure about, but I am going to try the beta now so at least I am working with source.

**Comment by gramster** [comment]
I got this error with the beta:

```
14:00:47 (11162) ERROR Stryker an error occurred Error: Error while placing mutants of type(s) "StringLiteral" on 43:92 with conditionalExpressionMutantPlacer. TypeError: Property argument of TSImportType expected node to be of a type ["StringLiteral"] but instead got "SequenceExpression"
```

Maybe the Checker plugin is meant to avoid that? Unfortunately in my case there are multiple tsconfig.json files used in the build so I didn't see how I could enable that.
