### ISSUE TITLE
Mutate non-code files

### ISSUE THREAD

**Issue by Lakitna** [stryker-mutator/stryker#2480]
I'm wondering if anyone has thought about mutating non-code files like JSON schema, OpenAPI schemas, etc. These examples basically boil down to mutating `.json` and `.yaml` files.

## Background

I'm working a lot with contract-based testing. In provider-driven contract-based testing I use OpenAPI Schemas as the contract. However, I currently have no way of finding out if I'm actually testing the entire contract on the provider-side. Mutation coverage would be a way to get this information, though it's not the only possible way. I'm sure there are more situations where mutating non-code files can be useful.

This also raises the question if we can define a minimum mutation coverage per file. For a schema, I might want to force 100% coverage.

More background on contract-based testing: https://medium.com/@sandervanbeek/contract-based-testing-part-1-introduction-b42e6236720a. Other parts linked in Article.

More background on the type of tooling: https://github.com/rabobank/openapi-contract-validator-server

**Comment by nicojs** [comment]
> I'm wondering if anyone has thought about mutating non-code files like JSON schema

Not directly JSON files. But I did think about mutating angular/vue expressions in HTML files for example. This is why the new `@stryker-mutator/instrumenter` works based on the file extension. In fact, it is heavily inspired by prettier, which is also able to parse all kinds of source files. It should be possible to add a parser and printer for json or yaml.

What kind of mutations would you want?

>  For a schema, I might want to force 100% coverage

Interesting. Could you create a separate feature request for this? Might be something to align on with the other Stryker ports as well.

**Comment by nicojs** [comment]
It must have been a rough day yesterday. 😶

How would mutating json/yaml files work? We're using mutation switching now. This means we're placing all mutants in the code at once, and then switch them on/off with global variables or env variables. How would that work.

For example:

```json
{
  "foo": "bar"
}
```

Might be instrumented as:

```js
{
  "foo": global.__active_mutant__ === 1 ? "" : "bar"
}
```

This is invalid JSON. The same goes for YAML (unless there is a way to create an `if` in YAML, which there might be, since YAML is magic). We might be able to mutate angular expressions in HTML in some way, but that's about it.

So unless you know of a different way to solve this with mutation switching, I feel inclined to close this issue with a "won't fix" label.

🤷‍♂️

**Comment by Lakitna** [comment]
> It must have been a rough day yesterday. 😶

It was a busy day, did it show? Next week I'm off work though :)

JSON can be directly imported with `require`. We could wrap that and treat the JSON as JS. However, I don't think that will work with `import`.

Thinking a bit more about this, things would also break down when you write to a JSON file in your code. Doing that would have to result in an error.

Do you think it'll be possible/feasible to instrument `.json` and `.yaml` files to javascript files before instrumenting the mutations?

> unless there is a way to create an if in YAML, which there might be, since YAML is magic

Non-strict YAML 😨. I consider this approach to be a last resort.

**Comment by Lakitna** [comment]
I don't get the feeling you're enthusiastic 😄.

I'll explore other options for my use case, let's reopen this if anyone else has a better use case.
