### ISSUE TITLE
Broken link in stryker/packages/core/README

### ISSUE THREAD

**Issue by gramster** [stryker-mutator/stryker#2493]
**Summary**

There's a list of the available options that are links to the details for each option. The "files" option is not linked correctly.

**Comment by nicojs** [comment]
Thanks! ❤

**Comment by gramster** [comment]
Here's another one; in https://stryker-mutator.io/stryker/plugins there is a broken link to the HTML reporter README:

For more info, see the [@stryker-mutator/html-reporter readme](https://github.com/stryker-mutator/stryker/tree/master/packages/html-reporter#readme)

**Comment by nicojs** [comment]
I've fixed the link in the Stryker readme.

I've also started to improve the plugin section in the [stryker-4.0](https://github.com/stryker-mutator/stryker-mutator.github.io/tree/stryker-4.0) branch of the https://github.com/stryker-mutator/stryker-mutator.github.io repository.
