### ISSUE TITLE
Improve our build and release workflow

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#250]
I want to use this issue to discuss merging (some) stryker repositories together. 

Right now we have separate repositories for `stryker-api`, `stryker` as well as all of the plugins (`stryker-karma-runner`, `stryker-mocha-runner`, etc). We did this because we want to release them as separate modules to npm. 

This presents a number of challenges to us as maintainers:

1. **Coordinating changes** across modules is a **pain**. You can build modules and install them locally, but the travis build will fail. This leaves you with releasing them under a tag in npm (`@next` for example) to prevent unsuspecting users to install it by accident. 
1. Releasing a new major version often means you need to **release them one by one**. If in the meantime someone installs `npm i stryker stryker-api` for example, it might break for him because `stryker-api` could already be released with the next major release.
1. Steep learning curve for new people wanting to change cross module functionality.

This could all be solved with [lernajs](https://lernajs.io/). With lerna its possible to easily host multiple npm modules in the same git repository. This solves all above challenges:

1. Coordinating changes is simpler, because [lerna bootstrap](https://github.com/lerna/lerna#bootstrap) takes care of linking your npm modules locally.
2. Releasing a new major version can be done using [lerna publish](https://github.com/lerna/lerna#publish), which will first publish to an npm tag "lerna-temp". Only when everything is published, it will tag them with "latest" (the default tag for `npm install`).
3. The steel learning curve will be removed as we can easily tell people to run:
```
git clone git@github.com:stryker-mutator:stryker
cd stryker
npm i
./node_modules/.bin/lerna bootstrap
```
we could even remove the last step by introducing a `post-install` step that does that for you.

However, lernajs is **not a build tool**, each module should still incorporate its own build. This also means that we should change our grunt setup, as `grunt release` now does building, testing and releasing for us. Including updating our contributors and changelog, etc.

Side note: lerna doesn't force us to maintain a single version number. However, it can. See https://github.com/lerna/lerna#how-it-works .

**Comment by nicojs** [comment]
@simondel I'm really leaning towards putting all repo's into one. LernaJS also takes into account the order in which to build. For example: `stryker-api` would be build *before* `stryker`, because `stryker` is dev-dependend on `stryker-api`.

An integration test module is pretty easy to. We should put it outside of the packages and add a relative file dependency on them so we actually test an npm install. 

We could leave versioning for what it is right now.

**Comment by simondel** [comment]
I agree. Let's put it all in one repo and leave the versioning as what it is right now. That will also make it easier to add a npm version badge such as ![](https://img.shields.io/npm/v/stryker.svg). That way you can always see the latest version we released on NPM for each repo.

Right now, making such a change would require a bunch of PR's while having everything in one repo would mean we have 1 PR.

**Comment by simondel** [comment]
I created a branch so we could work on implementing Lerna: https://github.com/stryker-mutator/stryker/tree/lernajs

**Comment by nicojs** [comment]
@simondel, @mthmulders has a point there. Right now he is maintainer of `stryker-jest-runner` which actually works great IMHO. Maybe we make exceptions for plugins maintained by other devs?

**Comment by nicojs** [comment]
Solves with #257
