### ISSUE TITLE
Missing boolean substitutions

### ISSUE THREAD

**Issue by ptoonen** [stryker-mutator/stryker#252]
I see other frameworks (such as humbug) which have boolean substitutions but am missing these in Stryker. Is it an idea to add them?

**Comment by nicojs** [comment]
Yes please!

@ptoonen are you giving it a shot?

**Comment by simondel** [comment]
@ptonen Shall I add this?

**Comment by jeznag** [comment]
How about truthy to falsy as well?
```
if (this.isUnderAttack) {
   fireZeMissiles();
}
```
to

```
if (!this.isUnderAttack) {
   fireZeMissiles();
}
```

Simon mentioned this one is hard to achieve.

**Comment by simondel** [comment]
You can now use this using `stryker@0.6.1`!
