### ISSUE TITLE
flatten `commandRunner` option

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#2523]
I have taken a look at #2522, and noticed our current configuration of `commandRunner` looks like: 
```json
{
  "commandRunner": {
    "command": "npm run mocha"
  }
}
```
can't we make this as:
```json
{
   "commandRunner": "npm run mocha"
}
```
or
```json
{
   "command": "npm run mocha"
}
```
?

**Comment by nicojs** [comment]
Well, i like the deep variant, because it allows for more config options to be added in the future. It is also in line with the other test runners 🤷‍♂️

**Comment by kmdrGroch** [comment]
Ok. Closing it then :)
