### ISSUE TITLE
Stryker 4 beta: Typescript + React expressionMutantPlacer error with "BooleanLiteral"

### ISSUE THREAD

**Issue by ovo-saxon-zerbino** [stryker-mutator/stryker#2527]
**Summary**

Trying to run stryker 4 beta on a react + typescript project and encountering an error during the expressionMutantPlacer step. The line that causes the error is:

```
const [expanded, setExpanded] = React.useState<string | false>('');
```

where the boolean literal `false` is attempting to be mutated. This issue can be worked around in my repo by replacing the above line with: 

```
const [expanded, setExpanded] = React.useState<string | boolean>('');
```

Don't think this is a react specific issue, I think the mutator isn't detecting the boolean literal type correctly.

**Stryker config**

```
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "mutate": [
    "src/**/*.ts?(x)",
    "!src/**/*@(.test|.spec|Spec).ts?(x)"
  ],
  "testRunner": "jest",
  "reporters": [
    "progress",
    "clear-text",
    "html"
  ],
  "htmlReporter": { "baseDir": "coverage/mutation" },
  "coverageAnalysis": "off",
  "timeoutMS": 60000,
  "jest": {
    "projectType": "create-react-app",
    "enableFindRelatedTests": true
  },
  "maxConcurrentTestRunners": 6
}
```

**Test runner config**

Project built with CRA, jest config in package.json is:

```
"jest": {
    "collectCoverageFrom": [
      "**/*.{ts,tsx}",
      "!**/*.d.ts",
      "!**/node_modules/**",
      "!**/vendor/**",
      "!src/models/**",
      "!src/**/styles.ts",
      "!src/styles/**",
      "!src/serviceWorker.ts"
    ]
  }
```

**Stryker environment**

```
"@stryker-mutator/core": "^4.0.0-beta.10",
"@stryker-mutator/jest-runner": "^4.0.0-beta.10",
"@stryker-mutator/typescript-checker": "^4.0.0-beta.10",
```

```
"@stryker-mutator/jest-runner": "^4.0.0-beta.10",
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v14.9.0
| npm              | v6.14.8 with yarn v1.22.5
| Operating System | macOS Catalina 10.15.7

**Comment by nicojs** [comment]
Thanks! Should be an easy enough fix.
