### ISSUE TITLE
Support Hapijs - Lab

### ISSUE THREAD

**Issue by setunde** [stryker-mutator/stryker#254]
It would be nice to use Stryker with Lab and not just Mocha or Karma.

**Comment by nicojs** [comment]
👍 cool! Can we assign this issue to you? You mentioned on Gitter that you're working on it?

**Comment by setunde** [comment]
yep, you can assign this issue to me

But you should know that we are working under the flag of a multi company
so we also have to figure out how we can distribute an open source version.
So please be patient :)

**Comment by nicojs** [comment]
Ok. Tell your bosses we have t-shirts, maybe it helps... 👕

**Comment by setunde** [comment]
https://www.npmjs.com/package/stryker-lab-runner
