### ISSUE TITLE
Test Stryker locally with npm link

### ISSUE THREAD

**Issue by Tummerhore** [stryker-mutator/stryker#2575]
Hi. First of all, I think my issue is not really related to Stryker itself (maybe to Lerna). But as I'm not quite sure, I'm dropping it here, none the less. I try to build Stryker locally and use "my" build with the robobar example. However, I don't really get it to work. Here are my steps:

- Update all Stryker packages to the newest version in the robobar project.
- Checkout the 4.0.0 release of the Stryker monorepo and install dependencies.
- Build Stryker locally with `npm run build` in the root dir of the monorepo (completed successfully)
- Use `npm link` in the core package and use `npm link @stryker-mutator/core` in the robobar project.

But when I try to execute Stryker in the robobar package now , I get a cryptic error message:
```
InjectionError: Could not resolve [token "options"] -> [function markUnknownOptions] -> [token "options"] 
-> [function validateOptions] -> [token "optionsValidator"] -> [class OptionsValidator] -> [token "validationSchema"] 
-> [function buildSchemaWithPluginContributions] -> [token "pluginResolver"] -> [function pluginResolverFactory]. 
Cause: ENOENT: no such file or directory, scandir 'C:\Users\<myaccount>\Desktop\stryker\@stryker-mutator
```

What am I doing wrong here? Any help is appreciated.

**Comment by Tummerhore** [comment]
I also tried installing the  package via a local path (`"@stryker-mutator/core": "file:../stryker/packages/core"`). This also failed, however with a different error:

```
WARN markUnknownOptions Unknown stryker config option "karma".
[...]
cause: Error: Cannot load TestRunner plugin "karma". In fact, no TestRunner plugins were loaded. Did you forget to install it?
[...]
```

**Comment by nicojs** [comment]
Currently, the default plugins are only loaded via sibling packages from the Stryker location. As a workaround, you can load the plugins with a fully location.

```json
{
  "plugins": ["/full/path/to/@stryker-mutator/karma-runner", "/full/path/to/other-plugin"]
}
```

**Comment by Tummerhore** [comment]
That solved it :)
Thanks a lot!
