### ISSUE TITLE
docs/api/plugins.md is outdated

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#2586]
I have noticed we have outdated informations in plugins.md

```md
You can extend Stryker with 6 plugin kinds:

export enum PluginKind {
  ConfigEditor = 'ConfigEditor',
  TestRunner = 'TestRunner',
  TestFramework = 'TestFramework',
  Transpiler = 'Transpiler',
  Mutator = 'Mutator',
  Reporter = 'Reporter',
}
```

it should be updated (and probably also some other parts)

**Comment by nicojs** [comment]
Yes, definitely. It even became more important, since now we're publishing these docs on our website: https://stryker-mutator.io/docs/stryker/api/plugins
