### ISSUE TITLE
Error: MODULE_NOT_FOUND (undefined) Error: Cannot find module '../../web/helpers/date.helper'

### ISSUE THREAD

**Issue by StephanyBatista** [stryker-mutator/stryker#260]
Hello guys.

I'm facing this error: "Error: MODULE_NOT_FOUND (undefined) Error: Cannot find module '../../web/helpers/date.helper'" when I try to run the stryker, node_modules/.bin/stryker run  stryker.conf.js.

Below my stryker.conf.js

module.exports = function(config){
  config.set({
    files: ['tests/models/**/*.js', { pattern: 'models/**/*.js', included: false, mutated: true }],
    testFramework: 'mocha',
    testRunner: 'mocha',
    reporter: ['progress', 'clear-text', 'dots', 'html', 'event-recorder'],
    coverageAnalysis: 'perTest',
    plugins: ['stryker-mocha-runner', 'stryker-html-reporter']
  });
}

**Comment by simondel** [comment]
Stryker copies files in `files` and `mutate` to a sandbox for testing. Your `data.helper` file does not have a .js extension right? What is it''s full path from the root of your project? And are there other non .js files that need to be present when testing?

**Comment by StephanyBatista** [comment]
Sorry. My error.

**Comment by simondel** [comment]
Our error ;) You're not the first person who has this issue.Which documentation did  you use to set up Stryker? The quick start? Did you look at any readme's?

**Comment by StephanyBatista** [comment]
Here! I read o git and did :)

**Comment by StephanyBatista** [comment]
I think that now is rigth, but I have the error: 

[2017-03-30 18:03:51.900] [ERROR] Stryker - One or more tests errored in the initial test run:
        TypeError: Cannot read property 'runResult' of undefined
TypeError: Cannot read property 'runResult' of undefined
    at C:\source\decostore\api\node_modules\stryker-mocha-runner\src\MochaTestRunner.js:31:46

**Comment by simondel** [comment]
That doesn't sound good! Could you open a separate issue for it?

**Comment by sugandhgoyal** [comment]
I am also getting the same error .what should i do 
here is my stryker.conf.js-

module.exports = function(config){
config.set(
  {
 "files": [
{
  "pattern": "src/**/*.js",
  "mutated": true,
  "included": false
},
 "test/**/*.js"
],
 "testRunner": "mocha",
  "reporter": [
    "clear-text",
    "progress"
  ],
 "testFramework": "mocha",
 "coverageAnalysis": "perTest"
}
);
}
