### ISSUE TITLE
unnecessary mutation for JavaScript && operator

### ISSUE THREAD

**Issue by lumosmind** [stryker-mutator/stryker#2644]
**Summary**

Hi, I wrote some code and its unit tests with JavaScript and Jest. I made mutation test on these unit tests.
Stryker lead me to write one extra test. I think this test is meaningless.

Striker lead me to write this extra test

test('throws error for "5" ', () => {
      expect(() => isAge('5'))
        .toThrowError(new Error('age must be a whole number'));
    });
for this mutation

//mutation
```
-     if (!(typeof age == 'number' && Math.trunc(age) == age))
+     if (!(true && Math.trunc(age) == age))
```
But, I have already write this test to test isAge function with string type argument.

test('throws error for "5.5" ', () => {
    expect(() => isAge('5.5'))
      .toThrowError(new Error('age must be a whole number'));
  });
This test should be enough. Because with this test I have already tested falsy_value && falsy_value situation.
But Stryker don not think like that. Stryker wants me to write test to check falsy_value && truthy_value situation.
If first operand of Shortcut And Operator falsy, it is not matter what is the value of second operand(is it truthy or falsy), because result is allays falsy.

```
//is-age.js
function isAge(age) {
  if (!(typeof age == 'number' && Math.trunc(age) == age))
    throw new Error('age must be a whole number');
  return true;
}
module.exports = isAge;
```

```
//is-age.test.js
const isAge = require('./is-age');
describe('the isAgeFunction', () => {
  test('returns true for 5', () => {
    expect(isAge(5)).toBe(true);
  });

  // Stryker wants this extra test
    /*test('throws error for "5" ', () => {
      expect(() => isAge('5'))
        .toThrowError(new Error('age must be a whole number'));
    });*/

  test('throws error for 5.5 ', () => {
    expect(() => isAge(5.5))
      .toThrowError(new Error('age must be a whole number'));
  });

  // I have already wrote this test to test string argument
  test('throws error for "5.5" ', () => {
    expect(() => isAge('5.5'))
      .toThrowError(new Error('age must be a whole number'));
  });
});
```

**Stryker config**

```json
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "packageManager": "npm",
  "reporters": [
    "html",
    "clear-text",
    "progress"
  ],
  "testRunner": "jest",
  "coverageAnalysis": "off"
}
```

**Test runner config**

I used jest with default configuration

**Stryker environment**

stryker-deneme-3-isage@1.0.0 /mnt/d/stryker-deneme-3-isage
└── @stryker-mutator/jest-runner@4.1.2

```
+-- @stryker-mutator/core@4.1.2
+-- @stryker-mutator/xxx-xxx@x.x.x
```

```

+-- jest@26.2.2

```

**Test runner environment**

```shell
# stryker run --mutate is-age.js
```

```json
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 15.1.0
| npm              | 7.0.8
| Operating System |  Ubuntu 18.04.5 LTS

**Add stryker.log**

**Comment by nicojs** [comment]
@Garethp 's response on slack:

> The problem with
> 
> ```js
> expect(() => isAge('5.5'))
>       .toThrowError(new Error('age must be a whole number'));
> ```
> is that you're not really testing that it throws an error for strings. It's something that throws an error even if you don't check for > the type of age at all, which is what Stryker is saying.
> I personally would remove the throws error for "5.5" and only use the throws error for "5" because when you're passing in 5.5 > it's not clear what you're testing. Are you expecting it to fail because it's a string or are you expecting it to fail because it's not a > whole number? If you're testing the string argument, then the test should fail if you remove the check for the string argument.

**Comment by lumosmind** [comment]
@Garethp is totally right. Thank you for this clear explanation. I am new on testing so this example is not good enough. If I found good example for this situation I will write.
