### ISSUE TITLE
error if there is an empty test file

### ISSUE THREAD

**Issue by lumosmind** [stryker-mutator/stryker#2658]
**Summary**

This is not good issue report I know but I have limited time. I'm sorry.
I use cli to run stryker mutator for an individual file like this
` stryker run --mutate src/ex-1.4/ex-1.4.ts`
if there is a unimplemented empty test file like
`src/ex-1.5/ex-1.5.test.ts`
stryker gives this error

```
/mnt/d/oop-ts-jest$ stryker run --mutate src/ex-1.4/ex-1.4.ts
22:46:05 (13919) INFO ConfigReader Using stryker.conf.json
22:46:05 (13919) INFO InputFileResolver Found 1 of 22 file(s) to be mutated.
22:46:05 (13919) INFO Instrumenter Instrumented 1 source file(s) with 20 mutant(s)
22:46:05 (13919) INFO ConcurrencyTokenProvider Creating 4 test runner process(es).
22:46:07 (13919) INFO DryRunExecutor Starting initial test run. This may take a while.
22:46:15 (13919) ERROR DryRunExecutor One or more tests resulted in an error:
        undefinedYour test suite must contain at least one test. Error: Your test suite must contain at least one test.
    at onResult (/mnt/d/oop-ts-jest/node_modules/@jest/core/build/TestScheduler.js:175:18)
    at /mnt/d/oop-ts-jest/node_modules/@jest/core/build/TestScheduler.js:304:17
    at /mnt/d/oop-ts-jest/node_modules/emittery/index.js:260:13
    at Array.map (<anonymous>)
    at Emittery.Typed.emit (/mnt/d/oop-ts-jest/node_modules/emittery/index.js:258:23)
22:46:15 (13919) ERROR Stryker Error: Something went wrong in the initial test run
    at DryRunExecutor.validateResultCompleted (/mnt/d/oop-ts-jest/node_modules/@stryker-mutator/core/src/process/3-dry-run-executor.js:60:15)
    at DryRunExecutor.timeDryRun (/mnt/d/oop-ts-jest/node_modules/@stryker-mutator/core/src/process/3-dry-run-executor.js:70:14)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async DryRunExecutor.execute (/mnt/d/oop-ts-jest/node_modules/@stryker-mutator/core/src/process/3-dry-run-executor.js:33:42)
    at async Stryker.runMutationTest (/mnt/d/oop-ts-jest/node_modules/@stryker-mutator/core/src/stryker.js:36:53)
22:46:15 (13919) INFO Stryker Trouble figuring out what went wrong? Try `npx stryker run --fileLogLevel trace --logLevel debug` to get some more info.
```

**Stryker config**

```json
{
}
```

**Test runner config**

**Stryker environment**

```
+-- @stryker-mutator/core@x.x.x
+-- @stryker-mutator/xxx-xxx@x.x.x
```

```
+-- mocha@x.x.x
+-- jest@x.x.x
+-- karma@x.x.x
+-- angular-cli@x.x.x
+-- react-scripts@x.x.x
```

**Test runner environment**

```shell
# Test command
```

```json
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             |
| npm              |
| Operating System |

**Add stryker.log**

**Comment by nicojs** [comment]
Hi @lumosmind thanks for reporting this issue.

What is the problem here exactly? I think Jest is reporting this error, not Stryker, so not much we can do here.

**Comment by lumosmind** [comment]
I do not know what is the root reason. I just see it while using Stryker and I want to report it.

**Comment by nicojs** [comment]
Ok, but I don't know what the issue here. You didn't describe the problem. 

In your issue you specify:

>  stryker gives this error
> 
> ```
> [...]
> 22:46:15 (13919) ERROR DryRunExecutor One or more tests resulted in an error:
>         undefinedYour test suite must contain at least one test. Error: Your test suite must contain at least one test.
>     at onResult (/mnt/d/oop-ts-jest/node_modules/@jest/core/build/TestScheduler.js:175:18)
>     at /mnt/d/oop-ts-jest/node_modules/@jest/core/build/TestScheduler.js:304:17
>     at /mnt/d/oop-ts-jest/node_modules/emittery/index.js:260:13
>     at Array.map (<anonymous>)
>     at Emittery.Typed.emit (/mnt/d/oop-ts-jest/node_modules/emittery/index.js:258:23)
> 22:46:15 (13919) ERROR Stryker Error: Something went wrong in the initial test run
>     at DryRunExecutor.validateResultCompleted (/mnt/d/oop-ts-jest/node_modules/@stryker-mutator/core/src/process/3-dry-run-executor.js:60:15)
>     at DryRunExecutor.timeDryRun (/mnt/d/oop-ts-jest/node_modules/@stryker-mutator/core/src/process/3-dry-run-executor.js:70:14)
>     at processTicksAndRejections (node:internal/process/task_queues:93:5)
>     at async DryRunExecutor.execute (/mnt/d/oop-ts-jest/node_modules/@stryker-mutator/core/src/process/3-dry-run-executor.js:33:42)
>     at async Stryker.runMutationTest (/mnt/d/oop-ts-jest/node_modules/@stryker-mutator/core/src/stryker.js:36:53)
> 22:46:15 (13919) INFO Stryker Trouble figuring out what went wrong? Try `npx stryker run --fileLogLevel trace --logLevel debug` to get some more info.
> ```

From my understanding, this is perfectly valid. You ran Stryker with an empty test suite, which resulted in an error since your jest configuration specifies that it should fail on empty test suites.

**Comment by lumosmind** [comment]
Yes you are totally right. it is because of jest's running process. Thank you.
