### ISSUE TITLE
DryRunExecutor Starting initial test run. This may take a while.

### ISSUE THREAD

**Issue by LokeshGangaiah** [stryker-mutator/stryker#2676]
**Question**

i keep getting this error : DryRunExecutor Starting initial test run. This may take a while.
Even after increasing the global timeout from 60sec to 90sec did not help
Tried to increase the mutation/core to latest ver which is 4.3.1, but with no luck 
No matching version found for @stryker-mutator/core@~4.3.1

**Stryker environment**

```
├─┬ @stryker-mutator/core@4.2.0
│ ├─┬ @stryker-mutator/api@4.2.0
│ ├─┬ @stryker-mutator/instrumenter@4.2.0
│ │ ├── @stryker-mutator/api@4.2.0 deduped
│ │ ├── @stryker-mutator/util@4.2.0 deduped
│ ├─┬ @stryker-mutator/util@4.2.0
├─┬ @stryker-mutator/jest-runner@4.2.0
│ ├── @stryker-mutator/api@4.2.0 deduped
│ ├── @stryker-mutator/util@4.2.0 deduped
npm ERR! peer dep missing: jest@>= 22.0.0, required by @stryker-mutator/jest-runner@4.2.0
npm ERR! peer dep missing: bufferutil@^4.0.1, required by ws@7.4.1
npm ERR! peer dep missing: utf-8-validate@^5.0.2, required by ws@7.4.1
npm ERR! peer dep missing: bufferutil@^4.0.1, required by ws@7.4.1
npm ERR! peer dep missing: utf-8-validate@^5.0.2, required by ws@7.4.1
npm ERR! peer dep missing: bufferutil@^4.0.1, required by ws@7.4.1
npm ERR! peer dep missing: utf-8-validate@^5.0.2, required by ws@7.4.1
npm ERR! peer dep missing: bufferutil@^4.0.1, required by ws@7.4.1
npm ERR! peer dep missing: utf-8-validate@^5.0.2, required by ws@7.4.1
npm ERR! peer dep missing: bufferutil@^4.0.1, required by ws@7.4.1
npm ERR! peer dep missing: utf-8-validate@^5.0.2, required by ws@7.4.1
```

While config stryker i selectred runner to be from command line, but the git project does have default

```
"@types/mocha": "^8.0.0",
```

**Additional context**

Below is my stryker.confg.js file:

```
/**
 * @type {import('@stryker-mutator/api/core').StrykerOptions}
 */
module.exports = {
  mutate: ["src/features/customers/handlers/customer-create-test.spec.ts"],
  packageManager: "npm",
  reporters: ["html", "clear-text", "progress"],
  testRunner: "command",
  coverageAnalysis: "off",
};
```

The same above config works fine on a different git project, but if i use the config again for the other project it gives me this timeout error

below is the exact error log:
```
stryker run
13:00:49 (14280) INFO ConfigReader Using stryker.conf.js
13:00:49 (14280) WARN PluginLoader Cannot find plugin "/Users/lokesh/git/front-end-api/node_modules/@stryker-mutator/jest-runner".
  Did you forget to install it ?
  npm install /Users/lokesh/git/front-end-api/node_modules/@stryker-mutator/jest-runner --save-dev
13:00:49 (14280) INFO InputFileResolver Found 1 of 335 file(s) to be mutated.
13:00:50 (14280) INFO Instrumenter Instrumented 1 source file(s) with 44 mutant(s)
13:00:50 (14280) INFO ConcurrencyTokenProvider Creating 4 test runner process(es).
13:00:50 (14280) INFO DryRunExecutor Starting initial test run. This may take a while.
13:06:18 (14280) ERROR DryRunExecutor Initial test run timed out!
13:06:18 (14280) ERROR Stryker Error: Something went wrong in the initial test run
    at DryRunExecutor.validateResultCompleted (/Users/lokesh/git/front-end-api/node_modules/@stryker-mutator/core/src/process/3-dry-run-executor.js:60:15)
    at DryRunExecutor.timeDryRun (/Users/lokesh/git/front-end-api/node_modules/@stryker-mutator/core/src/process/3-dry-run-executor.js:70:14)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async DryRunExecutor.execute (/Users/lokesh/git/front-end-api/node_modules/@stryker-mutator/core/src/process/3-dry-run-executor.js:33:42)
    at async Stryker.runMutationTest (/Users/lokesh/git/front-end-api/node_modules/@stryker-mutator/core/src/stryker.js:36:53)
13:06:18 (14280) INFO Stryker Trouble figuring out what went wrong? Try `npx stryker run --fileLogLevel trace --logLevel debug` to get some more info.
```

**Comment by simondel** [comment]
Hi! Could you set your `logLevel` to `"trace"` to see what the command line execution is actually doing?

PS: Does your `npm test` command exit or does is keep the test runner open?

**Comment by LokeshGangaiah** [comment]
@simondel, thanks for the response back, did try with logLevel a "trace" and below is the log. 

 npm test works fine, runs the complete unit test success 

```
34 (29560) DEBUG Sandbox Creating a sandbox for files in /Users/lokesh/git/front-end-api/.stryker-tmp/sandbox3293493
23:27:34 (29560) INFO DryRunExecutor Starting initial test run. This may take a while.
23:27:34 (29560) DEBUG DryRunExecutor Using timeout of undefined ms.
23:27:34 (29560) DEBUG TimeoutDecorator Starting timeout timer (300000 ms) for a test run
23:32:34 (29560) DEBUG TimeoutDecorator Timeout expired, restarting the process and reporting timeout
23:32:35 (29560) ERROR DryRunExecutor Initial test run timed out!
23:32:35 (29560) DEBUG Stryker Not removing the temp dir because an error occurred
23:32:35 (29560) ERROR Stryker Error: Something went wrong in the initial test run
    at DryRunExecutor.validateResultCompleted (/Users/lokesh/git/front-end-api/node_modules/@stryker-mutator/core/src/process/3-dry-run-executor.js:60:15)
    at DryRunExecutor.timeDryRun (/Users/lokesh/git/front-end-api/node_modules/@stryker-mutator/core/src/process/3-dry-run-executor.js:70:14)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async DryRunExecutor.execute (/Users/lokesh/git/front-end-api/node_modules/@stryker-mutator/core/src/process/3-dry-run-executor.js:33:42)
    at async Stryker.runMutationTest (/Users/lokesh/git/front-end-api/node_modules/@stryker-mutator/core/src/stryker.js:36:53)
```

**Comment by LokeshGangaiah** [comment]
@simondel @nicojs any help pls to debug as i am still stuck with this

**Comment by LokeshGangaiah** [comment]
@all, found out that my package.json has : "test": "ng test", and if i remove this line which is the unit test execution, not sure why does that cause it to fail, if i remove that line of code or include this (    "test": "ng test --watch=false",) the stryker run works , i need to investigate why but thought of sharing this if it might be useful to others.

**Comment by simondel** [comment]
Well, that's probably because `ng test` keeps watching for changes by default so in the eyes of Stryker, **the test run is never done**. This causes a timeout.

In your case, I would suggest adding a script such as `"test:ci"` which has watching disabled, or you could check out our Angular guide: https://stryker-mutator.io/docs/stryker/guides/angular

**Comment by LokeshGangaiah** [comment]
@simondel thanks for the response back.
I do have something as below even then it does not work, only when i introduce the --watch=false in test it executes or comment the test line. But this is a dev repo which i am working on need to ask my dev team to get approval to edit the test if it has to be . with out asking the dev's is there a way to make it work, without including the --watch=false in test
``` 
    "test": "ng test",
    "test-ci": "ng test --watch=false --code-coverage --no-progress",
    
```

**Comment by LokeshGangaiah** [comment]
@simondel can we reopen this issue and submit has an Bug to be fixed?
 because as i have explained in my prev comment, the test only runs when i remove the 
``` 
"test": "ng test --watch=false", 
``` 
with removing the test option from the package.json file, i feel it does not run exactly , it returns saying zero mutation score or basically "test": "ng test --watch=false" should still be present and the test should still work which is not happening.

either way i also tried to remove "test-ci": "ng test --watch=false --code-coverage --no-progress", and keep only "test": "ng test --watch=false", even then still no luck, the test does not work.
