### ISSUE TITLE
Jest snapshot tests failing in dry run, but not when run with jest

### ISSUE THREAD

**Issue by tobobo** [stryker-mutator/stryker#2694]
**Summary**

We have two snapshot tests that fail only when run in the Stryker dry run. I've tried to reproduce this when running directly with Jest but I have not succeeded. I've tried running jest in the Stryker sandbox directory, and even modifying our jest config to match the merged config (which adds `"bail": true,"collectCoverage": false,"verbose": false,"notify": false,"reporters": []`). In all cases, the jest tests succeed—both when running the problematic files only, and when running the full test suite.

Is there anything else I should be doing to try to recreate the environment Stryker is using to run the Jest tests so I can isolate the issue?

Both test failures are related to state being modified in a react component + dom manipulation. The changing of body style is performed by the [body-scroll-lock](https://github.com/willmcpo/body-scroll-lock) dependency. These tests pass consistently when run outside of Stryker:

```
Snapshot name: `CommentModalContainer when form is submitted should not change 1`

- Snapshot  - 1
+ Received  + 3

@@ -1,6 +1,8 @@
- <body>
+ <body
+   style=""
+ >
    <div
      id="modal-root"
    >
      .c3 {
    padding: 15px;
```

```
Snapshot name: `AskModal component has not changed 2`

- Snapshot  - 1
+ Received  + 3

@@ -1,6 +1,8 @@
- <body>
+ <body
+   style=""
+ >
    <div
      id="modal-root"
    >
      .c2 {
    background-color: #fff;
```

**Stryker config**

```json
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
	"packageManager": "npm",
	"disableTypeChecks": false,
	"mutate": [
		"src/**/*.{js,ts,tsx}",
		"shared/**/*.{js,ts,tsx}",
		"!**/{__tests__,__mocks__,tests-helpers}/**",
		"!src/cldr/**"
	],
  "reporters": [
		"html",
		"json",
    "clear-text",
    "progress"
	],
	"checkers": ["typescript"],
	"tsconfigFile": "tsconfig.stryker.json",
	"testRunner": "jest",
	"jest": {
		"configFile": "jest.config.ts"
	}
}
```

**Test runner config**

```js
process.env.TZ = 'UTC';

const config = {
	rootDir: '.',
	maxWorkers: 2,
	projects: ['.'],
	testMatch: [
		'<rootDir>/src/**/__tests__/**/*.test.(js|jsx|ts|tsx)',
		'<rootDir>/shared/**/__tests__/**/*.test.(js|jsx|ts|tsx)',
	],
	setupFiles: [],
	setupFilesAfterEnv: [
		'./jest.setup.ts',
		'jest-plugin-unhandled-promise/setup',
		'@testing-library/jest-dom/extend-expect',
		'jest-mock-console/dist/setupTestFramework.js',
	],
	coverageReporters: ['html', 'lcov', 'json-summary'],
	collectCoverageFrom: [
		'src/**/*.{js,ts,tsx}',
		'shared/**/*.{js,ts,tsx}',
		'!**/{__tests__,__mocks__,tests-helpers}/**',
		'!src/cldr/**',
	],
	clearMocks: true,
	moduleFileExtensions: ['ts', 'tsx', 'json', 'js', 'jsx', 'node'],
	moduleDirectories: ['<rootDir>', 'node_modules'],
	moduleNameMapper: {
		'^@/(.*)$': '<rootDir>/$1',
		'intl-polyfill': 'intl',
		// necessary for npm link to work with dependencies
		'^react$': '<rootDir>/node_modules/react',
		'\\.(less|sass|scss|css)$': '<rootDir>/__mocks__/cssMock.js',
		'\\.yml$': '<rootDir>/__mocks__/ymlMock.js',
	},
	transform: {
		'\\.(ts|js)x?$': 'babel-jest',
		'\\.(svg|png)$': '<rootDir>/__mocks__/imgTransform.js',
	},
	transformIgnorePatterns: ['/node_modules/(?!@change/components).+\\.js'],
	watchPathIgnorePatterns: ['/node_modules/'],
	testURL: 'http://localhost:3333/',
	watchPlugins: ['jest-watch-master'],
	modulePathIgnorePatterns: [
		'<rootDir>/.*/__mocks__', // FIXES https://github.com/facebook/jest/issues/2070
		'<rootDir>/node_modules/',
		'<rootDir>/build/',
		'<rootDir>/coverage/',
		'<rootDir>/quality/',
	],
};

module.exports = config;
```

**Typescript config**
tsconfig.stryker.json
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "skipLibCheck": true,
  },
  "include": [
    "src/**/*",
    "shared/**/*",
    "types/**'*",
    "global.d.ts"
  ],
  "exclude": [
    "node_modules",
  ]
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "baseUrl": ".",
    // Target latest version of ECMAScript.
    "target": "es2015",
    "module": "es2020",
    // Search under node_modules for non-relative imports.
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "lib": [
      "es2020",
      "dom",
      "esnext.asynciterable"
    ],
    "typeRoots": ["./node_modules/@types", "./types"],
    "jsx": "react",
    // Process & infer types from .js files.
    "allowJs": true,
    // Don't emit; allow Babel to transform files.
    "noEmit": true,
    // Enable strictest settings like strictNullChecks & noImplicitAny.
    "strict": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    // Disallow features that require cross-file information for emit.
    "isolatedModules": false,
    // Import non-ES modules as default imports.
    "esModuleInterop": true,
    "sourceMap": true,
    "removeComments": true,
    "allowSyntheticDefaultImports": true,
    "preserveConstEnums": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "importsNotUsedAsValues": "error",
    "paths": {
			// fixes an issue where wrong version is used for type checking due to react-i18nify not using peerDependencies
      "date-fns": ["./node_modules/date-fns"],
      "prop-types": ["./node_modules/prop-types"],
      // map project root: src/xxx, shared/xxx, config/xxx
      "*": [
        "./*"
      ],
    }
  }
}
```

**Stryker environment**

```
├── @stryker-mutator/core@4.3.1
├── @stryker-mutator/jest-runner@4.3.1
├── @stryker-mutator/typescript-checker@4.3.1
├── jest@26.6.3
```

**Test runner environment**

```shell
npx jest
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v15.5.0
| npm              | 7.3.0
| Operating System | Mac OS 10.15.7

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker/files/5817548/stryker.log)

**Comment by nicojs** [comment]
Hi tobobo 👋Hmm this is an interesting issue. Stryker's dry run does run on instrumented code, but should actually have the same results since the dry run doesn't activate any mutants. 

> I've tried running jest in the Stryker sandbox directory

How exactly have you done this?

Could you also try to see what happens when you override the stryker-tmp dir to a non-hidden directoy? I've noticed that jest has some strange properties when running inside a hidden directory.

```json
{
   "tempDirName": "stryker-tmp"
}
```

**Comment by tobobo** [comment]
Thanks for the suggestions! I had been using `npx jest` but I tried `../../node_modules/.bin/jest`, including with an explicit path to the config file in the sandbox directory and got the same result. I'm also getting the same results when I change `tempDirName`.

I heard this morning from other engineers that these tests have been flaky in the past, and they were able to come up with a fix. The fix had to do with preventing a leak of DOM state, and stryker's initial test run now passes with the fix implemented.

This suggested to me that the failure might have had to do with Jest's concurrency settings, which might have been preventing this state leak in my tests. Based on the way Stryker sets up its test runner processes, I was pretty sure that it was running only one process for each jest run. Sure enough, running `npx jest --concurrency=1` reproduced the failure every time.

Thanks for offering your thoughts on this! Really excited to be using Stryker for our project.

**Comment by nicojs** [comment]
Wow! Great news! Have fun using Stryker!
