### ISSUE TITLE
Babel parse error on flow syntax

### ISSUE THREAD

**Issue by benadamstyles** [stryker-mutator/stryker#2704]
**Summary**

I am getting a `BABEL_PARSE_ERROR` on flow type syntax, and I _think_ it's because stryker is adding instrumentation to the top of my files, which means that the `// @flow` pragma is no longer at the top of those files, so the [babel flow plugin](https://babeljs.io/docs/en/babel-plugin-transform-flow-strip-types) no longer runs against those files.

**Stryker config**

```js
{
  packageManager: 'yarn',
  reporters: ['html', 'clear-text', 'progress', 'dashboard'],
  testRunner: 'jest',
  coverageAnalysis: 'perTest',
  disableTypeChecks: false,

  sandbox: {
    fileHeaders: {
      // I think this is ignored?
      '**/*.js': '// @flow\n\n',
    },
  }
}
```

**Stryker environment**

```
├─ @stryker-mutator/api@4.3.1
├─ @stryker-mutator/core@4.3.1
│  ├─ @stryker-mutator/api@4.3.1
│  ├─ @stryker-mutator/instrumenter@4.3.1
│  ├─ @stryker-mutator/util@4.3.1
├─ @stryker-mutator/instrumenter@4.3.1
│  ├─ @stryker-mutator/api@4.3.1
│  ├─ @stryker-mutator/util@4.3.1
├─ @stryker-mutator/jest-runner@4.3.1
│  ├─ @stryker-mutator/api@4.3.1
│  ├─ @stryker-mutator/util@4.3.1
├─ @stryker-mutator/util@4.3.1
```

```
├─ @jest/core@25.4.0
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 14
| npm              | 6
| Operating System | macos

**Add stryker.log**

> Will add if it's absolutely necessary

**Comment by benadamstyles** [comment]
I have just confirmed that my suspicion was correct – that this is due to the `// @flow` pragma no longer being at the top of the file – by adding a function above the pragma in one of my source files and running my jest tests as normal: the same error occurs.

**Comment by nicojs** [comment]
Thanks for bug report and triage! This should be a simple fix.

Could you maybe create a small hello-world-like example that reproduces this issue? We would be happy to add it to our e2e test suite so it won't ever break again.

**Comment by nicojs** [comment]
[flow-project.zip](https://github.com/stryker-mutator/stryker/files/5866555/flow-project.zip)

I tried my hand at reproducing this myself, but couldn't. See zip.

Unzip and cd into the directory. Then run

```shell
npm i
npm run test # see that normal unit testing works
npm run test:mutation # see that Stryker works
```

**Comment by swist** [comment]
@nicojs here's a MRE: https://github.com/swist/stryker-flow-bug
