### ISSUE TITLE
Stryker cannot kill any mutant on Windows

### ISSUE THREAD

**Issue by tmhung88** [stryker-mutator/stryker#2712]
**Summary**

I integrated Stryker into a NodeJS + TypeScript project. For some reasons, Stryker was not able to kill any mutant on Windows. I executed the same source code on Ubuntu, and received some killed mutants. Could someone advise?

Windows reports:
![image](https://user-images.githubusercontent.com/2813016/105690945-34457180-5f2f-11eb-90eb-2639ce18cd97.png)

Ubuntu 20 reports:
![image](https://user-images.githubusercontent.com/2813016/105690866-1710a300-5f2f-11eb-8ee2-db81c3508edd.png)

**Stryker config**

```json
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "checkers": [
    "typescript"
  ],
  "tsconfigFile": "tsconfig.json",
  "testRunner": "jest",
  "coverageAnalysis": "all",
  "jest": {
    "projectType": "custom",
    "configFile": "jest.config.json",
    "config": {
      "testEnvironment": "node"
    },
    "enableFindRelatedTests": true
  },
  "files": [
    "# include everything in backend",
    "**/*.*",

    "# ignore irrelevant directories",
    "!{.stryker-tmp,build,node_modules,report}/**/*.*",

    "# ignore integration tests",
    "!{src/core,src/iac,src/repositories,src/resolvers}/**/?(*.)+(spec|test).ts"
  ],
  "mutate": [
    "{src,lib}/**/*.ts",

    "# ignore tests",
    "!{src,lib}/**/__tests__/**/*.ts",
    "!{src,lib}/**/?(*.)+(spec|test).ts",
    "!{src,lib}/**/*+(Spec|Test).ts",

    "# ignore modules which are covered with integration tests",
    "!{src/core,src/iac,src/repositories,src/resolvers}/**/*.ts"
  ]
}
```

**Test runner config**

```
{
  "preset": "ts-jest",
  "testEnvironment": "node",
  "testPathIgnorePatterns": ["<rootDir>/build/", "<rootDir>/integration-test", "<rootDir>/.stryker-tmp"],
  "collectCoverage": true,
  "collectCoverageFrom": ["<rootDir>/src/**/*.ts"],
  "coverageDirectory": "build/coverage",
  "coverageThreshold": {
    "global": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": 100
    }
  },
  "restoreMocks": true
}

```

**Stryker environment**

```
    "@stryker-mutator/core": "^4.3.1",
    "@stryker-mutator/jest-runner": "^4.3.1",
    "@stryker-mutator/typescript-checker": "^4.3.1"
```

```
"jest": "^26.6.3",
"ts-jest": "^26.4.4",
"ts-node": "^9.1.1",
"typescript": "^4.1.3",
```

**Test runner environment**

```shell
npm test
```

```json
// jest.config.json
{
  "preset": "ts-jest",
  "testEnvironment": "node",
  "testPathIgnorePatterns": ["<rootDir>/build/", "<rootDir>/integration-test", "<rootDir>/.stryker-tmp"],
  "collectCoverage": true,
  "collectCoverageFrom": ["<rootDir>/src/**/*.ts"],
  "coverageDirectory": "build/coverage",
  "coverageThreshold": {
    "global": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": 100
    }
  },
  "restoreMocks": true
}

```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v15.6.0
| npm              |7.4.0
| Operating System | Windows 10 Pro. Build. 19042.746

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker/files/5865744/stryker.log)

**Comment by nicojs** [comment]
Hi @tmhung88 👋 thanks for opening this issue.

Could you try to specify a non-hidden temp dir? 

```json
{
  "tempDirName": "stryker-tmp"
}
```

**Comment by tmhung88** [comment]
@nicojs Thanks for your quick response. As I updated the temp dir, I got the same results on Ubuntu. Thanks a lot!

New Windows Reports:
![image](https://user-images.githubusercontent.com/2813016/105692831-84253800-5f31-11eb-8a4d-8391dbb5141a.png)


New Stryker log:
[stryker.log](https://github.com/stryker-mutator/stryker/files/5865822/stryker.log)

**Comment by nicojs** [comment]
Happy to help,

Feel free to upvote the issue on the jest issue tracker 😉
