### ISSUE TITLE
Enable "plugin:@typescript-eslint/recommended-requiring-type-checking" in eslint

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#2717]
**Is your maintenance request related to a problem? Please describe.**
First, let me specify that I'm pretty happy with what we have now. We've got a robust test set and our listing rules are preventing some bugs. However, I think we can improve our listing further.

We currently have an extensive custom ruleset. This is something I personally don't prefer because it costs us time to maintain and we're missing out on new rules that might be added to the recommended ruleset.

**Describe the solution you'd like**
Enable "plugin:@typescript-eslint/recommended-requiring-type-checking" in eslint and remove _all custom rules we currently have_. except for the once to do with import order (they are not in the recommended ruleset). Then run once with `--fix` to fix all issues that can be fixed automatically.

Next, we should disable _some rules_ (not a whole lot). We will need to disable at least some because running with "plugin:@typescript-eslint/recommended-requiring-type-checking" will add **a lot** of errors.

> ✖ 1212 problems (1054 errors, 158 warnings)
>   6 errors and 0 warnings potentially fixable with the `--fix` option.

Rules that I think is OK to remove for now:
`@typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access, `

Rules that I would really want to keep enabled:
`@typescript-eslint/await-thenable, @typescript-eslint/require-await, @typescript-eslint/explicit-module-boundary-types`.

In general, I would prefer to enable rules, rather than disable them. But it's fine to disable for now and create a separate issue per the disabled rule.

**Describe alternatives you've considered**
Keeping the current setup, but as specified, I would like to improve our eslint rules.

**Additional context**
@kmdrGroch what do you think of this approach?

Please wait for #2714 to be merged.

**Comment by kmdrGroch** [comment]
Sure thing @nicojs, I can see what could be done :) we can talk it through during thursday community maintenance :)

**Comment by kmdrGroch** [comment]
New proposal has been stated in Pull Request #2726 - use "all" configuration, and customize it to our needs.
