### ISSUE TITLE
Rename "Stryker" to "StrykerJS"

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#2754]
It's time...

When we started with Stryker back in 2014, there was no Stryker.NET or Stryker4s (hack, there was no webpack for that matter). Since then, we're maintaining 3 mutation testing frameworks, all under the "Stryker Mutator" flag 👽🏳. 

However, it is more and more common to refer to all three as "Stryker" (instead of "Stryker Mutator"). It is very common to refer to Stryker itself as "StrykerJS". I myself have caught myself doing exactly that.

I think it is time to rebrand Stryker as StrykerJS. 

@stryker-mutator/stryker-js-and-friends-maintainers what do you think?

The website URL should also be updated: 

```diff
-https://stryker-mutator.io/docs/stryker
+https://stryker-mutator.io/docs/stryker-js
```

- [x] Update `custom_edit_url`'s in docs
- [x] Update links in the readme's
- [x] Update headers in the readmes (Stryker -> StrykerJS)
- [x] Update links in the package.json
- [x] Update guide links in the custom initializes (react, vue, angular)
- [ ] Update website
    - [ ] Configure redirect link in docusaurus
- [ ] Rename repository (stryker -> stryker-js)

**Comment by nicojs** [comment]
Note: this wouldn't have any technical implications. In StrykerJS's source code, it's still fine to refer to StrykerJS as Stryker. This would mostly mean renaming the repository (updating a lot of links) and rebranding Stryker on the website.

**Comment by Garethp** [comment]
Sounds good to me. I always search StrykerJS in google anyway so that I don't get results for some company called Stryker

**Comment by nicojs** [comment]
I've did a little bit of digging. I think Github should arrange redirects to the new url: https://docs.github.com/en/github/administering-a-repository/renaming-a-repository

> When you rename a repository, all existing information, with the exception of project site URLs, is automatically redirected to the new name, including:
> 
>     Issues
>     Wikis
>     Stars
>     Followers


Project site URLs are Github pages. Luckily, we're not using that for Stryker (we're using the organization-wide GitHub pages website)

**Comment by nicojs** [comment]
We'll probably do this the next date we have a day to work on Stryker, just so we don't forget something during hacking at night session.

**Comment by nicojs** [comment]
Which was today! Name change complete! 🎉
