### ISSUE TITLE
Sample reduction

### ISSUE THREAD

**Issue by jeznag** [stryker-mutator/stryker#276]
I came across this study that argues that using just 10% of all possible mutants is only 16% less accurate than using the full set. i.e. the mutant kill score will be pretty similar even if you don't test all the mutants as long as the mutants are randomly selected.
http://www.sciencedirect.com/science/article/pii/0164121294000980

In light of that, it might be worth adding a config option for mutantSampleSize which would default to 100%. Let me know if you think it's worthwhile and I'll work on it.

**Comment by simondel** [comment]
Interesting idea! Do you have a way to read the entire article?

**Comment by jeznag** [comment]
Here's the full article: http://sci-hub.io/10.1016/0164-1212(94)00098-0#

**Comment by nicojs** [comment]
This is indeed interesting. If we implement it, we should make sure that you will still get the same result with the same sample reduction settings. That way everyone in your dev team will get the same results with the same settings.

@jeznag how would you choose the samples to run? Just every 10th sample? Or would you take mutation type into account somehow?

**Comment by jeznag** [comment]
Good point RE reliability
How about:
1. Sort mutants into different types
2. Take first 10% of all mutants in that group (use Math.ceil so always taking at least 1)

**Comment by nicojs** [comment]
Ive reviewed your work on #288 . Thanks for the help and cool idea!

**Comment by simondel** [comment]
We're closing this issue for now. In the future we will revamp the way we mutate and test code to speed up performance.

Feel free to work on this if anyone wants to, but let us know so we can help you where needed.
