### ISSUE TITLE
Ability to combine multiple mutants together

### ISSUE THREAD

**Issue by jeznag** [stryker-mutator/stryker#295]
According to this study, single token mutations do not resemble real bugs https://ir.library.oregonstate.edu/xmlui/bitstream/handle/1957/47353/acm_sigproc.pdf?sequence=1

Most bugs consist of 3-4 incorrect tokens. Could we look at offering a mode that would combine mutations together?

e.g.
```
if (blah && blah2 > blah4) {
  someCode();
}
```

2 mutants:
```
if (blah && blah2 > blah4) {
  //someCode();
}
```

Not sure what a good solution would be.

**Comment by simondel** [comment]
It is an option, but how would you know which mutations should be combined to create a natural bug that spans more than one token? 

It's important to note that you're testing your tests by making changes to your source code that don't always have to be bugs.

**Comment by simondel** [comment]
We will likely include this in the future. //cc @nicojs @richardwerkman

**Comment by simondel** [comment]
This is something we'll do in the future. We'll create a separate issue for it and close this one for now.
