### ISSUE TITLE
Binary file corruption

### ISSUE THREAD

**Issue by fstoerkle** [stryker-mutator/stryker#297]
## Expected behavior
The content of binary files is not changed/corrupted when copying files from the source location to the sandbox

## Observed behavior
The content of binary files is changed/corrupted when copying files from the source location to the sandbox

## Steps to reproduce
1. Add an entry to your `files` option, that should not be `mutated` and `included`, but copied because it is needed to run the tests, e.g.: `{ pattern: 'build/**', mutated: false, included: false }`
1. Put a binary file at the specified location (e.g. `build/test.png`).
1. Run `stryker` and compare the file copied to the sandbox with the original file – they have different file contents (check e.g. with `diff` or by calculating a checksum e.g. via `md5`).

## Notes
- The tests were run on macOS Sierra `10.12.4 (16E195)`
- I pinpointed the `encoding` option in these two lines as the cause:
https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/src/utils/StrykerTempFolder.ts#L52
- I'm happy to create a PR for that (my idea would be to not set the encoding for files that are `included`, be should not be `mutated`).
- Here is a regression test that fails on current `master`, and succeeds if I don't set the `encoding` option when copying the files in `StrykerTempFolder`: https://github.com/fstoerkle/stryker/blob/fix-binary-file-corruption/packages/stryker/test/integration/utils/StrykerTempFolderSpec.ts

**Comment by simondel** [comment]
Thanks for opening this issue! Is your suggestion to set the encoding when reading and writing to `null`? Because I think if you don't give an encoding, it defaults to `'utf8'`

**Comment by fstoerkle** [comment]
@simondel in my case, removing the whole option object "fixed" the issue, see [my branch](https://github.com/fstoerkle/stryker/blob/fix-binary-file-corruption/packages/stryker/src/utils/StrykerTempFolder.ts#L52).

However, I think it is not that simple to just drop the options, as they probably are necessary when you actually want to mutate the file.
That being said, no tests are failing when removing the options. I'm not familiar with Stryker internals, so I don't know what other issues dropping the encoding option might have. Also, this might behave differently in another environment/OS

**Comment by nicojs** [comment]
Good catch. Copying files to the sandboxes is done in this method:
https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/src/utils/StrykerTempFolder.ts#L52

We'll have to investigate further to see what the best approach is. We need to support these 3 scenario's:
1. Copying javascript and other utf8 encoded text files
2. Instrumenting javascript code for code coverage
3. Copying binary files.

**Comment by avassem85** [comment]
Working on a solution to check if file is binary to set encoding to binary and otherwise use utf-8.

**Comment by fstoerkle** [comment]
@avassem85 please note, that setting the encoding to `binary` did as well corrupt the file for me. Only leaving the `encoding: ...` option away did not corrupt the file.

**Comment by nicojs** [comment]
@fstoerkle  is this still an issue in the latest release of stryker? We refactored the part which copies the binary files and this should work now.

**Comment by fstoerkle** [comment]
@nicojs thanks for the heads-up, I will test this and get back to you...

**Comment by fstoerkle** [comment]
@nicojs did not have the time to look into this until now, feel free to close – I'd reopen if I run into this issue again

**Comment by nicojs** [comment]
Thanks! I will. We still would like to have an `encoding: ...` option in the near future. For now, we handle a list of file extensions as binary (black list): https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/src/utils/fileUtils.ts#L42
