### ISSUE TITLE
clearTextReporter: add option to reduce output to statistics only

### ISSUE THREAD

**Issue by unlight** [stryker-mutator/stryker#306]
I want to see following:
```
17 total mutants.
8 mutants survived.
0 mutants timed out.
9 mutants killed.
Ran 3.00 tests per mutant on average.
Mutation score based on covered code: 52.94%
Mutation score based on all code: 52.94%
```
Without additional information which and how file was mutated.

Please, add option to configuration.

**Comment by simondel** [comment]
That would certainly be possible!

@nicojs What do you think? Separate the reporters or use a config property?

**Comment by unlight** [comment]
Or, maybe better, split clearTextReporter to two different reporters.

**Comment by nicojs** [comment]
I've been thinking about this a lot. I would like to keep it a single mutator which can be configured with a `clearTextReporter` property. Also i would like to have a nicer summary at the end, one which also draws a table with the mutation score per folder, subfolder etc. Like the html reporter basically. This is next on my personal backlog.

**Comment by nicojs** [comment]
Let's implement this when #309 is merged

**Comment by nicojs** [comment]
@unlight I'm closing this because we've implemented this already. Instead of using your suggestion, it now prints a table to the console. Pretty neat. :)
