### ISSUE TITLE
Rename ConfigWriter

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#311]
We have an interface named `ConfigWriter` in the stryker-api that allows plugins to alter the stryker config at runtime (before stryker starts testing). However, these plugins don't actually write any config, they just modify the existing config. 

This interface (and everything that implements it) should be renamed to reflect this in order to prevent confusion with the `StrykerConfigWriter` in the initializer code. The `StrykerConfigWriter` does not implement `ConfigWriter` and **is** responsible for writing config.

**Comment by sharikovvladislav** [comment]
So the task is: rename ConfigWrite interface and fix each class which implements it, right?

**Comment by nicojs** [comment]
Yes. Question is: in what. Maybe `Configurator`?

@simondel what do you think?

**Comment by sharikovvladislav** [comment]
May be be `ConfigEditor` or `ConfigModifier` since:

> they just modify the existing config

**Comment by sharikovvladislav** [comment]
So it will be like F2 on the interface definition, change name and commit, right? :)

**Comment by sharikovvladislav** [comment]
You can see the result there: https://github.com/stryker-mutator/stryker/pull/357. What do you think folks? @simondel @nicojs

**Comment by nicojs** [comment]
@simondel what do you think of the naming?

* `ConfigEditor`
* `Configurator`
* `ConfigModifier`
* Something else?

**Comment by simondel** [comment]
@nicojs I like `ConfigEditor` the most. An implementing class will edit the config, but it won't (shouldn't) write it to disk like the `StrykerConfigWriter`
