### ISSUE TITLE
Stryker should not do a dry-run when there are no files

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#312]
Repro steps:
* Create a new directory
* Call `npm init` and skip through it
* Install mocha: `npm i -D mocha`
* Call `stryker init` and choose *mocha - mocha*
* Run stryker

Current behavior:
![image](https://cloud.githubusercontent.com/assets/4221997/26750993/92709336-482f-11e7-9bd8-20216d7f9e55.png)

Expected behavior:
No crash. Just a message that no files have been found.

**Comment by legopiraat** [comment]
I'll take this one

**Comment by simondel** [comment]
Awesome! If you need any help, feel free to let us know :)

**Comment by simondel** [comment]
Thanks for fixing this @legopiraat!
