### ISSUE TITLE
Unable to determine test failure in Mocha runner

### ISSUE THREAD

**Issue by jmpresso** [stryker-mutator/stryker#331]
I am using mocha for the runner and framework. Stryker previously worked properly. After some code changes (and not running Stryker in a while, due to being unable to run Stryker in my build process for a different bug), I receive a test failure in Stryker. Running Mocha outside of Stryker, there are no failures. This is my error:

[2017-06-20 17:36:38.758] [ERROR] Stryker - One or more tests failed in the initial test run:
	 "after each" hook for "<mytestnamehere>"
	Cannot read property 's' of undefined

I am not sure how to track down what is causing this failure. Unfortunately there is no stack trace, so I don't know where it's failing. I've tried removing pieces of my code, but still can't track it down. I believe Mocha can display more information if --full-trace is specified.

1) Is there any way to pass that Mocha configuration in with Stryker to try to debug the test?
2) If not, any idea how I could update that as an option to try it out? I assume it's in MochaTestRunner?
3) Is there any way I can debug a Mocha test (like with Webstorm) being run by Stryker?
4) Lastly, any other suggestions as to what I can do to investigate this?

I am using:
    "stryker": "0.6.2"
    "stryker-api": "0.5.3"
    "stryker-mocha-framework": "0.1.2"
    "stryker-mocha-runner": "0.4.0"

**Comment by nicojs** [comment]
Thanks for reporting this issue.

Is it true that you are running Stryker with `coverageAnalysis: 'perTest'` (which is the default). If so, you might want to try `coverageAnalysis: 'all'`.  I'm triggered by the error message: ` Cannot read property 's' of undefined`. It so happens to be that `s` is the name for the coverage counter created by [`istanbul`](https://github.com/gotwarlost/istanbul).

Once you're able to run your tests with `coverageAnalysis: 'all'`, i think the real problem will be clear. I believe that there are some problems with the selecting of your files. Would you mind also copy-pasting the content of your stryker.conf.js file here?

**Comment by jmpresso** [comment]
Thanks for the quick response! It looks like with `coverageAnalysis:all`, it doesn't fail. It's only failing with perTest.

I had copied the example conf from here, where it had included=false on the src directory- https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/README.md#configuration

When I set src to included, it worked with perTest.

**Comment by nicojs** [comment]
@jmpresso good to hear you got it working. Just to be sure, you do include the source files in your test by using `require`?

**Comment by jmpresso** [comment]
I do. I scanned through most of them, and didn't see any offhand that appeared to be missing any requires.
