### ISSUE TITLE
Report about tests which never failed

### ISSUE THREAD

**Issue by heynest** [stryker-mutator/stryker#333]
# User Story
As a **Stryker user** I would like to get a **report about tests which never failed** so that I can **identify the useless tests**.

# Details
Let's assume this is my test code:
```
var assert = require('assert');
var oMathHelper = require("../src/MathHelper");

describe('MathHelper', function() {
    describe('#sumUp()', function() {
        it('adds up two possitive numbers', function() {
            assert.equal(oMathHelper.sumUp(2, 2), 4);
        });

        it('adds up two float numbers', function() {
            assert.equal(oMathHelper.sumUp(0.5, 0.5), 1);
        });

        it('adds up two negative numbers', function() {
            oMathHelper.sumUp(-10, -10); // note: no assertion
        });
    });
});
```
I would like to have a hint by the framework, that the last test ('adds up two negative numbers') never failed (as the developer forgot to put an assert).

As far as I understand Stryker, the test run is always **stopped as soon as the mutant has been killed**. However, for the purposed feature, the **test run should continue until the end** and it should count as often every test failed. This should be a **separate Stryker option or mode** because it will be much slower then the original stop-when-killed mode.

**Comment by simondel** [comment]
Thanks for the detailed issue! This was something we were thinking about as well :)
