### ISSUE TITLE
Transpiler plugin support

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#343]
In order to support different types of projects such as Babel and TypeScript projects, the way we generate mutants and decide which code should be placed in the Sandbox changes.

The MutatorOrchestrator in Stryker will be replaced using a Transpiler interface that can transpile code to the format required for the Sandbox and that can mutate code. A regular JavaScript transpiler won't actually change to code during the transpilation phase while a TypeScript transpiler would change the code (from TypeScript to JavaScript).

## Suggested API change
Remove the [Mutator interface](https://github.com/stryker-mutator/stryker/blob/master/packages/stryker-api/src/mutant/Mutator.ts) because it specifically targets JavaScript code
Remove the [MutatorFactory class](https://github.com/stryker-mutator/stryker/blob/master/packages/stryker-api/src/mutant/MutatorFactory.ts)
Remove the [IdentifiedNode interface](https://github.com/stryker-mutator/stryker/blob/master/packages/stryker-api/src/mutant/IdentifiedNode.ts)
Move the [Mutant](https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/src/Mutant.ts) to the stryker-api because Transpilers will have to return it
Add the Transpiler interface:
```typescript
interface Transpiler {
   new (sourceFiles: SourceFile[]): Transpiler;
   transpile(): SourceFile[];
   mutate(): Mutant[];
}
```
Make the SourceFile interface extend the InputFile interface so it has the `mutated` property that is already present in the InputFile interface. The new interface will look like this:
```ts
interface SourceFile extends InputFile {
  content: string;
}
```

## Open issues
* The `Mutant` class has no way to tell a difference between the code that was mutated and the code that should be placed in the sandbox. The code that was mutated may be TypeScript code, while the code for the sandbox could be JavaScript. The TypeScript code would be interesting to save in a Mutant for reporting purposes.

**Note:** *This post will be updated to always show the latest info.*

**Comment by nicojs** [comment]
This feature is released in stryker 0.10 as part of the TypeScript support. Seel #376 and #344
