### ISSUE TITLE
Stryker quits with "TypeError: Cannot read property 'runResult' of undefined"

### ISSUE THREAD

**Issue by steadweb** [stryker-mutator/stryker#347]
I'm unable to run stryker on my current project. Error log and config below:

#### Error log

```
[2017-08-02 15:54:40.571] [WARN] InputFileResolver - Globbing expression "test/unit/**/*.js" did not result in any files.
[2017-08-02 15:54:40.595] [INFO] InputFileResolver - Found 33 of 33 file(s) to be mutated.
[2017-08-02 15:54:40.597] [INFO] SandboxCoordinator - Starting initial test run. This may take a while.
[2017-08-02 15:54:41.787] [ERROR] Stryker - One or more tests errored in the initial test run:
        TypeError: Cannot read property 'runResult' of undefined
TypeError: Cannot read property 'runResult' of undefined
```

#### stryker.conf.js

```
module.exports = function(config){
  config.set({
    files: [
      'test/unit/**/*.js',
      { pattern: 'src/**/*.js', included: false, mutated: true }
    ],
    testFramework: 'mocha',
    testRunner: 'mocha',
    reporter: ['progress', 'clear-text', 'dots', 'html', 'event-recorder'],
    coverageAnalysis: 'off',
    plugins: ['stryker-mocha-runner', 'stryker-html-reporter']
  });
};
```

Command I'm running to generate this error:

```
./node_modules/.bin/babel-node ./node_modules/.bin/stryker run
```

_Note: I've had a look in the `.stryker-tmp` directory, and the `___testHooksForStryker.js` file is empty. Assuming this is incorrect?_

**Comment by steadweb** [comment]
Currently running version `0.6.7`:

```
$ ./node_modules/.bin/stryker -V
0.6.7

```

**Comment by simondel** [comment]
Thanks for the detailed issue! It seems like the stryker-mocha-runner is confused because no tests were executed (if I have to guess).

This is something we'll fix, but could you check if the path `test/unit/**/*.js` is correct? Stryker can't seem to find any files that match it.

**Comment by nicojs** [comment]
Yeah, the bug is here that stryker-mocha-runner doesn't deliver a valid result to stryker when no teats could be found. You should be able to solve it by adding at least 1 test. Probably have another look at the globbing expression for your tests

**Comment by steadweb** [comment]
Thanks @simondel / @nicojs - the folder was indeed named incorrectly 😞  - `tests` instead of `test`. I am facing other issues but I believe these are related to ES6.

**Comment by simondel** [comment]
Glad that you got it working for your case! We'll still look into how we can show users a proper message instead of the error. What kind of issues are you facing and are you in any position to share code?

**Comment by steadweb** [comment]
The issues _I think_ I'm facing now are down to ES6 and bootstrapping. At the moment, when we run tests, we use `tests/bootstrap.js` which does quite a bit (examples below):

```
require('app-module-path').addPath(__dirname + '/../src/');
require('app-module-path').addPath(__dirname);

global.sinon = require('sinon');
```

Below are the errors I'm facing which I believe are related:

### tests/unit/lib/git/add_test.js

The error that halts stryker is as follows. The test that's causing this tries to import a module that _does_ exist, but relies on `bootstrap.js` to do some setup.

```
import {add} from 'lib/git';
```

Error generated by stryker.

```
[2017-08-03 09:48:25.515] [ERROR] Stryker - One or more tests errored in the initial test run:
        Error: MODULE_NOT_FOUND (undefined) Error: Cannot find module 'lib/git'
```

### src/config/data.js

I'm also seeing a lot of errors output in the console which _I believe_ are related to ES6 support. 

```
import fs from 'fs';
// ...
```

This generates the following error (I have quite a few of these, mostly moaning about line 1, which usually consists of `import`:

```
[2017-08-03 09:48:24.595] [ERROR] CoverageInstrumenterStream - Error while instrumenting file "/Users/lsteadman/FU/product-marketing-info-tool/src/config/data.js", error was: Error: Line 1: Unexpected token
Failed to parse file: /src/config/git.js
```

**Comment by nicojs** [comment]
If the error is with the `CoverageInstrumenterStream `, can it be that you changed the `coverageAnalysis` setting to something other than `'off'`? If coverage instrumentation is `'off'` it should not try to instrument for code coverage.

That being said: we we're not supporting es6 syntax natively yet. A feature request for it can be found here: https://github.com/stryker-mutator/stryker/issues/133. To make it work, we're starting to migrate to more language agnostic way of working, as can be read in our [latest blog article](http://stryker-mutator.github.io/blog/2017-07-14/road-to-stryker-1-0.html). So it might take some time before we natively support things like the `import` statement.

For the time being, you can use stryker by first transpiling the code yourself before handing it of to Stryker. First make sure your normal unit tests are passing when ran over the transpiled code though. 

Lets keep this issue about the original error message. If you run into anything else, please feel free to update #133  or report new issues when they arise.

**Comment by simondel** [comment]
Hi! We fixed the original error so the issue has been closed. Please upgrade to:
 - stryker-api@0.8.0
 - stryker-html-reporter@0.7.0
 - stryker-mocha-framework@0.4.0
 - stryker-mocha-runner@0.7.0
 - stryker@0.9.0
