### ISSUE TITLE
Mutation testing in node based environments can generate false warnings

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#350]
When running stryker using a node-based test runner like mocha, we generally see some warnings:

```
(node:4860) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: fail
(node:4860) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4860) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
fail
```

If you are new to these messages, read up here: https://stackoverflow.com/questions/40920179/should-i-refrain-from-handling-promise-rejection-asynchronously/40921505

This seems pretty serious to end users, but it isn't really. After all, we mutated the code. These warnings can be expected.

We can add handlers in the sandboxes for these warning like this:

```javascript
process.on('unhandledRejection', function (reason) {
  log.info(`Noticed an unhandled promise rejection, reason: ${reason}`);
});
process.on('rejectionHandled', (reason) => {
  log.info(`Noticed an unhandled promise (reported earlier) was handled after all, but asyncronously. Reason: ${reason}`);
});
```

**Questions:**

1. Do we still want to log something in these handlers? (IMHO: yes, but maybe as debug)
2. Do we want the initial test run to fail when an unhandled (or asyncronous handled) promise occurs? (IMHO: no, it might be the choice of the implementer).

**Comment by simondel** [comment]
1. I would log them as something other than info. Your suggestion of using debug sounds good!
2. I would log them as info using the same message during the initial test run and warn the user that such messages will be logged as debug during mutation testing

**Comment by nicojs** [comment]
The beauty about the test runner sandboxes right now is that they don't care about whether or not they're running an initial test run or not. So it is quite hard to make that distinction. We could let the message bubble through all the way to the top, but that would require a bigger change: namely making the test runners implement an event mechanism (that also survives the process boundary of a sandbox). I would keep things simple for now.
