### ISSUE TITLE
html reporter has issues when directories only have one file

### ISSUE THREAD

**Issue by jmpresso** [stryker-mutator/stryker#363]
**Issue:**
My project separates source and test code into separate directories (src/test). The directory structure is the same on both sides.

src/directory1/directory2/file.js
test/directory1/directory2/file.spec.js

If there is only one file in a directory, Stryker fails with an error such as this:

_[2017-08-28 16:52:44.288] [ERROR] BroadcastReporter - An error occurred during 'wrapUp' on reporter 'html'. Error is: Error: ENOENT: no such file or directory, open 'C:\...\reports\mutation\html\src\directory1\directory2\file.js.html'
[2017-08-28 16:52:44.584] [INFO] Stryker - Done in 12 seconds._

**Analysis**
This issue began to occur when I upgraded the html reporter from 0.4.2 to 0.6.0. It looks like the problem is that when there is only one source file, it's failing to first create the subdirectory that it is in for the report HTML. This looks like it should occur in HtmlReporter.prototype.writeChildren, but I'm not exactly sure how it's intended to work there.

**Comment by nicojs** [comment]
@jmpresso thanks for your detailed report. 

Do you have a test project to reproduce this issue? Better yet would be an export of your events by using the `event-recorder` reporter (events will be serialized to disk at 'reports/mutation/events').

**Comment by j-truax** [comment]
Seeing the same error as @jmpresso Adding additional info in case it helps in debugging/testing.

Stryker Module Versions...
```
        "grunt-stryker": "0.7.0",
        "stryker": "0.8.0",
        "stryker-api": "0.7.0",
        "stryker-html-reporter": "0.6.0",
        "stryker-jasmine": "0.4.0",
        "stryker-karma-runner": "0.6.0"
```

Project Structure...
```
Github Sample Project --> REPORT SUCCESSFUL
|
|__src
    |
    |__blaat
    |   |
    |   |__two
    |       |
    |       |__Array.js
    |       |__Circle.js
    |
    |__Add.js


Bad Project --> REPORT UNSUCCESSFUL
|
|__src
    |
    |__blaat
        |
        |__two
            |
            |__three
                |
                |__four
                |   |
                |   |__Circle.js <-- Report's index.html shows row for this but clicking shows 404 because there is no corresponding sub-report html file.
                |
                |__Add.js
                |__Subtract.js



Good Project --> REPORT SUCCESSFUL
|
|__src
    |
    |__blaat
        |
        |__two
            |
            |__three
                |
                |__four
                |   |
                |   |__Array.js <-- Additional file seems to fix the issue
                |   |__Circle.js
                |
                |__Add.js
                |__Subtract.js
```

**Comment by jmpresso** [comment]
Thanks @j-truax. I have to imagine it could be pretty easily reproduced by deleting two of the src/spec files in grunt-stryker-test. I attempted to confirm, but am having some issues setting it up locally.

**Comment by jmpresso** [comment]
So I'm not certain whether the issue is with html reporter or ScoreResultCalculator. When ScoreResultCalculator generates [facts](https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/src/ScoreResultCalculator.ts#L33), it has the fact name like "directory2/file.js". Other facts are namedlike "file1.js".

In the clear text reporter, instead of showing the file grouped under the folder like it does for the others, it shows it like the fact name as "directory2/file.js". It does work properly though otherwise. Is this intentional, or no? If not intentional, I imagine the fix needs to be handled in scoreResultCalculator (perhaps in determineCommonBasePath). Otherwise, it's a fix in scenarios the HTML reporter needs to handle.
