### ISSUE TITLE
Refactor the `stryker-cli` class

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#364]
The stryker-cli is untestable at the moment. See https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/src/stryker-cli.ts. Simply `require`-ing the file is enough to start mutation testing. I would rather see an implementation with a class.

So instead of `require('../src/stryker-cli)` in the [stryker binary](https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/bin/stryker) i would like to see something like `const StrykerCli = require('../src/StrykerCli'); new StrykerCli(process.argv).run()`.

Next we should create some unit tests for the cli.

**Comment by bicep** [comment]
Hello again! I've written some code for this, but I'm not sure how to send the pull request. I created a new branch and pushed but it seems that I don't have permission to. Should I make a pull request on  an existing branch?

**Comment by simondel** [comment]
Hi! Thanks for wanting to contribute :) I think you're trying to push to our repository. That is the output of the command `git remote get-url origin` is it this repository?

To contribute, you can *fork* this repository (top right of the github page). That creates a copy of stryker on your profile at https://github.com/bicep/stryker. You can then push to that repository can create a PR from there.  You can use the command `git remote set-url origin https://github.com/bicep/stryker` to change the url of the remote named _origin_.

If you need any help. let us know! Also, have you signed up for hacktoberfest?

**Comment by bicep** [comment]
Thank you for your reply and guidance. Just submitted the PR.
And yes!! Signed up for Hacktoberfest already :)

**Comment by bicep** [comment]
@simondel  I really messed up on the last PR, decided to create a new one without the package-lock.json. It should be good to go now!

**Comment by simondel** [comment]
Fixed with #426 🎉
