### ISSUE TITLE
Readonly options

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#365]
We should refactor most (if not all) `stryker-api` interfaces to be `readonly`. This has no effect on the resulting JavaScript. Instead, it has the effect that our TypeScript code interacting with our API will not have undesired side effects.

- [ ] API: Make options like `plugins`, `maxConcurrentTestRunners`, etc... required in the `StrykerOptions` inteface
- [ ] API: Remove `Config` class. Update all related interfaces to take a `ReadonlyStrykerOptions` instead of `Config` directly
- [ ] API: Add the default options in a `DefaultOptions` frozen object (can be exported from `stryker-api/core`? @simondel, what do you think?)
- [ ] Stryker: Update stryker package: update the ConfigReader with a `set` method that sets options on a `StrykerOptions` config object.
- [ ] Rest: Update all packages to use `StrykerOptions` instead of `Config`.

**Comment by bicep** [comment]
Hello! I'm looking for a first open source project to contribute to- may I give this issue a shot?

**Comment by nicojs** [comment]
Hi bicep, awesome to have you onboard the Stryker train. I think in hindsight that this issue might not be that beginner friendly. You might wanna take a look at others with this label. Issue #336 might be the simplest

**Comment by bicep** [comment]
Is there a quick guide regarding all the different source files and what they do?

**Comment by simondel** [comment]
Awesome that you want to help! We don't have a description of all files right now.

I would like to point out that Hacktoberfest will start in a few days. It may be fun for you to sign up :) More info: https://hacktoberfest.digitalocean.com

**Comment by nicojs** [comment]
@bicep As @simondel already explained, we don't have a clear description right now. You can take a look at our [contribution guide](https://github.com/stryker-mutator/stryker/blob/master/CONTRIBUTING.md#runner-stryker-locally) to see how to run stryker locally. 

You can start by taking a look at the main [`runMutationTest` method in the `Stryker` class](https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/src/Stryker.ts#L52). If you have any questions: don't hesitate to ask via gitter, email or the issue at hand. We're happy to help.

**Comment by nicojs** [comment]
I've renamed this issue as the options object is the only thing that should become readonly.

Now that I have taken a closer look, i think this we should remove the `Config` class all together. It doesn't add any value. The implementation of the `set(options: Partial<StrykerOptions>)` method is the only thing in there and it doesn't belong in the `stryker-api`. In fact, it isn't serializable using the `surrial` module. 

I'll update the main issue with a todo list.

**Comment by simondel** [comment]
@nicojs Do we also want to update the RunResult and RunOptions and such?

**Comment by nicojs** [comment]
Yes, they can be readonly as well

**Comment by nicojs** [comment]
I'm closing this issue. It's still a nice-to-have, but we don't want to invest time in this a.t.m.
