### ISSUE TITLE
Discussion: in-memory testing?

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#366]
I want to open a discussion on whether or not we should move to in-memory testing instead of writing each mutant to disk before running the tests.

We should be able to do this rather easy in nodejs based test runners by creating [`require.extensions`](https://nodejs.org/api/modules.html#modules_require_extensions) hooks for all files. More info in this excellent article: https://medium.freecodecamp.org/requiring-modules-in-node-js-everything-you-need-to-know-e7fbd119be8

For browser based test runners, like karma, its a different story as it usually involves starting a web services and serving static files. For these solutions we could still load it from disk (stryker-karma-runner would than be responsible for writing the files to disk), or adding a middleware that serve the in-memory-files (see [middleware](http://karma-runner.github.io/1.0/config/configuration-file.html)). 

@mthmulders do you think some solution would also be possible for the stryker-jest-runner?

**Comment by mthmulders** [comment]
Just did a quick check: before registering the Jest runner, I inserted the following code:

    const requireJs = require.extensions['.js'];
    require.extensions['.js'] = (module: string, filename: string) => {
      // write some logging to see when/how we have been invoked
      return requireJs(module, filename);
    };

The logging revealed that only files from `./node_modules/` have been required with this patched function. From [AddSpec.js#L1](https://github.com/stryker-mutator/stryker-jest-runner/blob/790d317a8a740cbdcb3e07c10c195dd99091da8a/testResources/sampleProject/src/__tests__/AddSpec.js#L) I would've hoped that the logging would also include `../Add`, but it did not.

So I think we need something different for Jest. I can see a few points where we _might_ be able to hook into Jest:
1. [resolver](http://facebook.github.io/jest/docs/en/configuration.html#resolver-string)
2. [moduleLoader](https://github.com/facebook/jest/blob/dfdca8b115a8d484c8e8b00cf3ceab7d54919ba1/packages/jest-runner/src/run_test.js#L65) would allow us to plug in a patched [Runtime](https://github.com/facebook/jest/tree/master/packages/jest-runtime), but I couldn't get that to work - yet
3. custom [Resolver](https://github.com/facebook/jest/blob/master/packages/jest-resolve), but it seems that is currently a [hard-coded implementation](https://github.com/facebook/jest/blob/dfdca8b115a8d484c8e8b00cf3ceab7d54919ba1/packages/jest-runtime/src/index.js#L216)

**Comment by simondel** [comment]
With mutation switching this will be less relevant so I'm closing this issue for now.
