### ISSUE TITLE
Breaking thresholds don't work with grunt-stryker

### ISSUE THREAD

**Issue by jmpresso** [stryker-mutator/stryker#367]
**Issue:**
I'm using grunt-stryker 0.7.0, and stryker 0.8.0, with the thresholds configuration. Ex:
```
thresholds: {
            high: 100,
            low: 100,
            break: 100
        }
```

When my score drops below the threshold, it reports the failure, but does not fail the grunt task.

> [2017-08-29 12:04:25.590] [ERROR] ScoreResultCalculator - Final mutation score 99.53 under breaking threshold 100, setting exit code to 1 (failure).
> [2017-08-29 12:04:25.590] [INFO] ScoreResultCalculator - (improve mutation score or set `thresholds.break = null` to prevent this error in the future)
> [2017-08-29 12:04:25.971] [INFO] HtmlReporter - Your report can be found at: file:///C:/Users/up50/projects/vg-ccc-client.npm/reports/mutation/html/index.html
> [2017-08-29 12:04:26.070] [INFO] Stryker - Done in 11 seconds.
> 
> Done, without errors.
> 
> Process finished with exit code 0

You can see the process exit code is 0 (successful), when it should've failed.

**Analysis**
When the mutation score is under 'break', it does invoke [setExitCode ](https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/src/utils/objectUtils.ts#L72)in objectUtils, setting process.exitCode to 1.

In grunt-stryker, I verified it receives the process.exitCode as 1. However, the process still exits with an exitCode of 0. I suspect this has something to do with the [this.async](https://gruntjs.com/api/inside-tasks) call in [stryker.js](https://github.com/stryker-mutator/stryker/blob/master/packages/grunt-stryker/tasks/stryker.js#L32). . If I remove this 'done' call, it appears to work properly. When a break occurs the grunt process will exit with a code of 1, otherwise it will exit with a normal code of 0.

this.async must not respect an exitCode. Perhaps the error code needs to be checked, and a false passed to done if its >0? That's assuming this.async is really needed here with a promise. When I removed the line, it still appeared to wait and end appropriately.

**Comment by simondel** [comment]
This has been fixed with `grunt-stryker@0.8.2` Thanks for fixing it @jmpresso !
