### ISSUE TITLE
Input file resolver should allow multiple entries for the same files

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#370]
The input file resolver should allow entries for multiple files.

For example: 

```javascript
files: [
  'src/**/*.js',
  { pattern: 'src/cli.js', included: false} // Double entry for src/cli.js. 
]
```
EDIT: `InpitFileDescriptor` is removed. Same goes without the descriptor.

If a second pattern is detected for the same file, it should be **enriched** with the information. In the example above: only the file 'src/cli.js' should not have `included = false`.

**Comment by roelandvanbatenburg** [comment]
I investigated this, but as far as I can see the object pattern structure has been removed so this can no longer be accomplished. And you can get this behavior by proper glob patterns. So this issue should be closed.

**Comment by nicojs** [comment]
True, but same goes for: 

```
files: [
  'src/**/*.js',
  'src/cli.js'// Double entry for src/cli.js. 
]``

**Comment by roelandvanbatenburg** [comment]
That is already handled here: https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/test/unit/input/InputFileResolverSpec.ts#L260

Or am I missing the point?

**Comment by nicojs** [comment]
Wow! Didn't even know it was already implemented. Thanks for pointing it out!
