### ISSUE TITLE
Wrong indents in stryker.conf.js file after stryker init command

### ISSUE THREAD

**Issue by sharikovvladislav** [stryker-mutator/stryker#371]
Hi!

Right after `stryker init` command executed successfully I get this code in `stryker.conf.js`:

```
svlad at sharikovvlad in ~/sandbox/test-stryker
$ cat stryker.conf.js

  module.exports = function(config){
    config.set(
      {
  "files": [
    {
      "pattern": "src/**/*.js",
      "mutated": true,
      "included": false
    },
    "test/**/*.js"
  ],
  "testRunner": "jest",
  "reporter": [
    "clear-text",
    "progress"
  ],
  "coverageAnalysis": "all"
}
    );
  }
svlad at sharikovvlad in ~/sandbox/test-stryker
$
```

All indents are saved. 

Why don't you use some format tool when creating the config file?

**Comment by sharikovvladislav** [comment]
Is it bug or feature?

If it is a bug can I try to fix this? I think that it will be nice idea to use some format tool like `prettier`. What do you think?

Example of usage is here: https://github.com/prettier/prettier#prettierformatsource--options

**Comment by sharikovvladislav** [comment]
I think return value of `wrapInModule` method in `StrykerConfigWriter` class should be passed through `prettier.format`. What do you think @nicojs @simondel ?

**Comment by sharikovvladislav** [comment]
Here is the result with my fix:

```
svlad at sharikovvlad in ~/sandbox/test-stryker
$ cat stryker.conf.js
module.exports = function(config) {
  config.set({
    files: [
      {
        pattern: "src/**/*.js",
        mutated: true,
        included: false
      },
      "test/**/*.js"
    ],
    testRunner: "jest",
    reporter: ["clear-text", "progress"],
    coverageAnalysis: "all"
  });
};

svlad at sharikovvlad in ~/sandbox/test-stryker
$
```

What do you think?

**Comment by nicojs** [comment]
Looks great. Prettifier doesn't have additional deps. Go for it

**Comment by sharikovvladislav** [comment]
Ye I already have diff... I have problems with my git... 

Just woooooot:

```
svlad at sharikovvlad in ~/dev/stryker on format-stryker-conf-on-init [+!?$]
$ git commit -m 'fix: #371 indents in "stryker.conf.js" file after "stryker init" command'
error: gpg failed to sign the data
fatal: failed to write commit object

svlad at sharikovvlad in ~/dev/stryker on format-stryker-conf-on-init [+!?$]
$
```

Did you ever has such problem?

**Comment by sharikovvladislav** [comment]
@nicojs ok, done.

**Comment by simondel** [comment]
@sharikovvladislav It works like a charm! Thanks for the hard work!
![image](https://user-images.githubusercontent.com/4221997/30119396-de36c470-9325-11e7-85cc-fe55f0358045.png)
