### ISSUE TITLE
Move to seperate modules

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#38]
We should move styker-api, stryker-karma-runner, stryker-jasmine to seperate repositories before release 1

We should add dev-dependencies to them to add integration tests.

**Comment by nicojs** [comment]
Done, just in time for the 0.4 release :+1:

**Comment by simondel** [comment]
_(We still have to move stryker-jasmine to a separate github, but I'll ignore that for now :+1:)_

**Comment by nicojs** [comment]
I disagree. There is no peerDependency on `jasmine` or `jasmine-core`, so i don't see a direct need for it. I'm perfectly happy with testselectors in de stryker repo.
