### ISSUE TITLE
Make stryker config file mandatory

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#390]
Running stryker with command line options won't read a stryker.conf.js file. This results in unexpacted behavior, for example:

```bash
$ stryker run
[2017-09-22 15:30:17.180] [INFO] ConfigReader - Using stryker.conf.js in the current working directory.
...
[2017-09-22 15:30:29.083] [INFO] Stryker - Done in 11 seconds.

$ stryker run --logLevel debug
[2017-09-22 15:30:35.483] [INFO] ConfigReader - No config file specified. Running with command line arguments
```

I think it would be more useful to always require a stryker.conf.js file to be specified.

**Comment by Be-ngt-oH** [comment]
Hi there :-),

got here by the hacktoberfest label and I'd like to fix this. However, I suggest a slightly different behavior.

Either we have a config file specified or not. If we have one - great, use it! If we don't - let's try `stryker.conf.js`. In both cases, command line arguments should override settings from the config file.
If there is no config specified and no `stryker.conf.js` in the dir, then it will just be the command line arguments.

What do you think?

**Comment by nicojs** [comment]
Hi @Be-ngt-oH 😄 

Great idea, let's do that.

**Comment by simondel** [comment]
Hi @Be-ngt-oH

Glad to hear that the tag is working! If you need any more info, feel free to ask for it :)

Happy hacking!

**Comment by j-truax** [comment]
To make sure I understand correctly, is this request removing the ability to directly define a grunt task in Gruntfile.js that has all the config settings in it?

example...
```
stryker: {
	mutate: {
		options: {
        		files: [
            			{ pattern: 'src/**/*.js', mutated: true},
            			'test/**/*.spec.js'
        		],
        		testRunner: 'karma',
        		testFramework: 'jasmine',
        		coverageAnalysis: 'all',
        		reporter: ['clear-text', 'html', 'event-recorder'],
        		thresholds: {
            			high: 90,
            			low: 50,
            			break: 95
        		}
		}
	}
}
```

**Comment by nicojs** [comment]
Well, it might have if @Be-ngt-oH didn't step in and did his suggestion. So your example should still work
