### ISSUE TITLE
TypeScript: Override some quality options

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#391]
When transpiling typescript code, we should override *some* of the compiler options designed for code quality. For example: if we now mutate an if statement to `if(false)` and the user has the code quality option `allowUnreachableCode=false` the mutant will not be tested and is treated as a false positive (basically). 

I don't think this is what we want. If you think about it: indeed, nobody in their right mind would mutate an if statement like that and typescript is right to report a warning when done so, but at the same time, that is *not* what we want to test when we mutate the if-statement. We want tot see if your tests can detect the side effect of *never* going in the if statement.

See https://www.typescriptlang.org/docs/handbook/compiler-options.html for a list of compiler options. I think we should override the following:

* `allowUnreachableCode` should be true 
* `noUnusedLocals` should be false 
* `noUnusedParameters` should be false

Another way to look at it: we're mutating code, of course the code quality will be less. That doesn't mean that the mutant is invalid.

**Comment by Mrna1** [comment]
@nicojs: Is it possible to add an overriding module from tsconfig?
For example:

For mutation I need 
`
"module": "commonjs",
`
For compilation and deployment to our environment
`
"module": "esnext",
`

Thank you

**Comment by nicojs** [comment]
Hi @Mrna1 , thanks for asking 😄 

The easiest way is to use TS's `extends` property. So basically create a second `tsconfig` file: `tsconfig.stryker.json` and [`extends`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#configuration-inheritance-with-extends) and override only the `"module"` option. Then specify that in your stryker.conf.js file. 

For now it is not possible to override tsconfig options directly from Stryker. See https://github.com/stryker-mutator/stryker/issues/1437 for more info on that.
