### ISSUE TITLE
HTML Reporter: Show code coverage

### ISSUE THREAD

**Issue by Archcry** [stryker-mutator/stryker#395]
It would be nice to also show the code coverage in Stryker's report. That way there is one place in which all data the programmer needs is reported.

**Comment by nicojs** [comment]
This is a great idea. Our html report is far more fancy than any other coverage report out there. How would you expect this to work? We don't want to overload the end user with too much info.

In order for this to work, we need a new reporter callback function. Something like `onCoverageMeasured` or something. Next, we would need to implement it in the html reporter (will be a big task).

**Comment by mscharley** [comment]
My build pipeline usually looks like:

- Unit tests (with coverage stats generated via `nyc`)
- stryker vs unit tests

If the HTML reporter could pick up the stats already generated by other tools, perhaps that would simplify things?

Definitely agree that a lot of the code coverage reports are pretty... bland.

**Comment by Archcry** [comment]
Well I talked with Nico about this and the bigger problem is the way we want to display the coverage because showing to much could clutter up the page to much. We'd like to offer a clean page with the information people need without adding to much extra noise. So suggestions on how to show the coverage information without overflowing the user with to much information would be nice.

**Comment by simondel** [comment]
As we have no clear way to show the coverage combined with the mutation report, I'm closing this issue for now. If anyone has a good idea on how to do it, let us know!
