### ISSUE TITLE
Refactor IsolatedTestRunnerAdapter to use ChildProcessProxy

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#398]
Since Stryker@0.10, we have a new (generic) way of spawning child processes and proxy-ing between them. It's called `child-process/ChildProcessProxy.ts`. We should refactor (replace) the `isolated-runner/IsolatedTestRunnerAdapter.ts` class to make use if it.

**Comment by simondel** [comment]
@nicojs This has been fixed right?

**Comment by nicojs** [comment]
Yep #976
