### ISSUE TITLE
Reporting severity

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#4]
It would be nice to have support for multiple severities for the console reporter such as `info` or `debug`. This gives the user the option to see as much or as little output as he/she wants.

**Comment by simondel** [comment]
@nicojs We support this since #89 and #94 right? Can this issue be closed?

**Comment by nicojs** [comment]
Well... not exactly. We support severity of *log messages*, but not for the *console reporter*.

I'm not sure if you want the `ConsoleReporter` to support severity. You either want the report and enable it, or you don't and you disable it. 

P.s. I'm also in the process of converting the `ConsoleReporter` into to reporters: `progress` and `clear-text`. The `progress` reporter reports on the *progress* (with `..S..T..` etc.). The `clear-text` reporter reports which mutants survived at the end. The `clear-text` can either write to console, or to a file.

**Comment by nicojs** [comment]
So... do we close this issue?

**Comment by simondel** [comment]
Yeah, I think we can close this issue :)
