### ISSUE TITLE
Upgrade sinon to version 4.0

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#406]
We should update to the latest release of sinon (4.0.0). In order to do that we need to fix these deprecation warnings:

```
sandbox.stub(obj, 'meth', val) is deprecated and will be removed from the public API in a future version of sinon.
 Use sandbox.stub(obj, 'meth').callsFake(fn) instead in order to stub a function.
 Use sandbox.stub(obj, 'meth').value(fn) instead in order to stub a non-function value.
```

So: everywhere we use `sandbox.stub(obj, 'meth', val)` we should refactor it with `sandbox.stub(obj, 'meth').value(fn)`. After that, we can upgrade to Sinon 4.

**Comment by Be-ngt-oH** [comment]
There are no type definitions for sinon 4.0 yet ([latest are 2.3](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sinon/index.d.ts)). I'll try to update the types for 4.0 and get it into the DefinetlyTyped-repo.

Actually, we could do this refactoring without updated types (there shouldn't be any conflicts). Though, I think it would be a bit unclean to use outdated typings.

**Comment by nicojs** [comment]
Awesome you're willing to pick this one up :metal:

> I'll try to update the types for 4.0 and get it into the DefinetlyTyped-repo.

That sounds good! I'll review them as quickly as i can (i'm one of the reviewers).

> Actually, we could do this refactoring without updated types (there shouldn't be any conflicts). 

Probably true.

> Though, I think it would be a bit unclean to use outdated typings.

Fine by me.

**Comment by avassem85** [comment]
Fixed in https://github.com/stryker-mutator/stryker/pull/474
