### ISSUE TITLE
Report Mutation Percentage with Sonar Coverage Measure

### ISSUE THREAD

**Issue by j-truax** [stryker-mutator/stryker#408]
Was able to verify that the [Stryker Sonar Plugin](https://github.com/stryker-mutator/sonar-stryker-plugin) captured survived & not covered mutants in our Sonar DB and were viewable on the project dashboard.

Currently the above metrics are reported as issues. However, it would be nice if this plugin also stored a Coverage Measure that captured Mutation Coverage % similar to Line & Condition.

**Comment by nicojs** [comment]
@j-truax great to hear that the stryker sonar plugin is working for you. I just now see that you opened an issue there. Sorry for the delay, i will respond there and close this one:

https://github.com/stryker-mutator/sonar-stryker-plugin/issues/5
