### ISSUE TITLE
Is it possible to pass parameters to test runner?

### ISSUE THREAD

**Issue by artkoshelev** [stryker-mutator/stryker#417]
In our project, mocha runs with options passed through file:
```
mocha --opts src/test/mocha.opts
```

Is there any way to pass this options when running stryker?

**Comment by simondel** [comment]
Hi! This is not possible right now but we can add it. What's in your mocha.opts?

**Comment by artkoshelev** [comment]
some random stuff, e.g.
```
--slow 20
--reporter spec
--require src/test/support/setup
--check-leaks
--globals=sandbox
```
`require` param is especially critical

**Comment by nicojs** [comment]
Sounds like that should be possible to add. We're calling mocha programmatically using this api and most options map 1 to 1:

https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically#set-options

I'm misshing the `--require` option, but that we can do ourselves (just require once at the beginning). Not sure how to pass `--globals` though. What exactly does it do? We actually also define a global `sandbox` variable when running stryker tests. However, we don't declare it in `--globals`.

**Comment by nicojs** [comment]
Apprearently, we can [pass the globals to the mocha instance](https://github.com/mochajs/mocha/blob/master/bin/_mocha#L331). Shouldn't be a problem.

**Comment by nicojs** [comment]
@artkoshelev support is added and released in stryker-mocha-runner 0.9.0. Can you verify that this is working for you?

For more info: see the related readme: https://github.com/stryker-mutator/stryker/tree/master/packages/stryker-mocha-runner#configuring

**Comment by artkoshelev** [comment]
It's hard to say if it works, because if i set `require: [ 'src/test/support/setup' ]` it fails with message:
```
Error: Cannot find module 'src/test/support/setup'
```
If i set it to `require: [ '../../../src/test/support/setup' ]` it fails for different reason:
```
[2017-10-23 14:19:32.066] [ERROR] InitialTestExecutor - One or more tests failed in the initial test run:
	dependencies node_modules must strictly contain exactly dredd-transactions@4.2.2, precisely!
		ENOENT: no such file or directory, open '/Users/akoshelev/src/my-project/.stryker-tmp/sandbox4404772/node_modules/dredd-transactions/package.json'
```
so it looks like runner looking for dependencies in wrong place

**Comment by nicojs** [comment]
You could try `mochaOptions`: { require: [require.resolve('./src/test/support/setup')] }`

**Comment by artkoshelev** [comment]
> You could try mochaOptions: { require: [require.resolve('./src/test/support/setup')] }
fails with same error:
```
[ERROR] InitialTestExecutor - One or more tests failed in the initial test run:
	dependencies node_modules must strictly contain exactly dredd-transactions@4.2.2, precisely!
		ENOENT: no such file or directory, open '/Users/akoshelev/src/my-project/.stryker-tmp/sandbox4404772/node_modules/dredd-transactions/package.json'
so it looks like runner looking for dependencies in wrong place
```
> EDIT: Or add src/test/support/setup.js it to the files array
it's already in files array

**Comment by nicojs** [comment]
Hmm I've got the feeling that the setup file can now be found, but something else is wrong. 

Do you have any idea why it is looking for dredd-transactions@4.2.2 in the sandbox folder? Do you `require('dredd-transactions')` somewhere and is it actively used? It seems that dredd-transactions has a strong opinion about where it should be installed (or the dependency using dredd-transactions does). 

You could also add the dredd-transactions to your sandbox: 

```javascript
  files: [
    { pattern: 'node_modules/dredd-transactions/*.*', included: false, mutated: false, transpiled: false }
  ]
```

If that doesn't work, maybe we could create an issue at the dredd-transactions github to understand where there error is coming from.

You should be able to reproduce this issue by running mocha yourself from the sandbox folder (/Users/akoshelev/src/my-project/.stryker-tmp/sandbox4404772). It is only deleted when stryker runs successfully, in other cases its left untouched for debugging purposes.

**Comment by artkoshelev** [comment]
It turns out there is a test in our codebase checking for specific versions for few dependencies. Sorry for bothering you and thank you for implementing feature so fast and help with debugging!

**Comment by nicojs** [comment]
@artkoshelev no problem, glad to be of help. So you have a unit test for testing your own `package.json`'s dependencies. Interesting.

**Comment by Zikoel** [comment]
Hi, what is the syntax for pass a boolean parameter to `mocha` es: `mocha test/ --exit` how should be passed the options?

**Comment by nicojs** [comment]
@Zikoel right now, only these options are supported for the mocha runner: https://github.com/stryker-mutator/stryker/tree/master/packages/stryker-mocha-runner#configuring

When looking through mocha's options I found: `--exit     force shutdown of the event loop after test run: mocha will call process.exit`

This should not be needed. Stryker will manage the life-cycle and call [`subprocess.kill`](https://nodejs.org/api/child_process.html#child_process_subprocess_kill_signal) on the sandboxed process when it's done testing.
