### ISSUE TITLE
Method chaining mutator

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#418]
It would be nice if we can mutate method chaining. For example:

```javascript
this.someArray()
    .sort()
    .map(x => someFunction(x))
    .filter(someFilter);
```

Putting the .sort() method in comments did not fail a test.

So I am longing for a mutator that strips out array functions that do not alter the items (like map) but only affect the sequence (like sort and filter).

Originally reported by @riezebosch in #92

**Comment by simondel** [comment]
We're closing this issue right now. If we wanted to do this, we would have done it already.
