### ISSUE TITLE
New api for Mutant

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#42]
We need a new api for Mutant. Right now: mutants handle their own file IO. The save the mutation to disk to a file of their choosing (using `fileUtils.createFileInTempFolder`). There are 2 issues with this way of working.

1. we want to spin up an *n* number of test runners. After a test runner is created, we cannot change the targeted files by that test runner (Karma doesn't support it). The only way to do this (that i can think of) is that we copy over all source code to a separate folder before hand. That copy of the source files will be created per test runner and given to the test runner at construction time. A mutation can than be made in that copy of the source files. These can also run in pure isolation, as long as every mutation gets reverted after wards
2. All IO is done synchronously. This is unnecessary, because we should be able to run multiple mutations at once on multiple test runners. It would be a shame if all testrunners are waiting on a blocking IO call

I would suggest the following API per test mutation

```
Mutant
+ sourceFile: string; // path to original source file`
+ mutationPosition: Location; // location of the line to be mutated
+ substitude: string; // the piece of code to substituted (the actual 'mutation)
```

The orchestration of which source file corresponds to which source file per test runner should be done outside of the Mutant class

@simondel Do you agree?

**Comment by simondel** [comment]
Saving the Mutant JIT in the correct folder seems like a good idea to me :)

The API has to be extended in order for this to work. The Mutant has to know its original location, so it can overwrite the correct file. 

I would suggest changing the save method of Mutant to accept a parameter `foldername` so the mutant knows where to save the mutated code. I think a `revertOriginalCode` method could also be a part of the Mutant class.

The Mutant also has to have knowledge of the Mutation which has been applied for the reporter.

**Comment by nicojs** [comment]
I would like that saving of the mutant to disk is not the responsibility of
the mutant anymore. I think separation of concerns is in order here. The
figuring out which folder/file to save to should be coordinated by the same
class that is responsible for copying the files per test runner.

**Comment by simondel** [comment]
I'm fine with some other class saving/restoring the code as long as the Mutant knows the (origina realtive) path to the file for which it has the mutated code

**Comment by nicojs** [comment]
How about this api:
``` typescript
interface MutantInfo {
  location: ESTree.SourceLocation;
  fileName: string;
  mutatedNode: ESTree.Node;
  status?: MutantStatus;
  substitution?: string;
}
```
The idea is that a Mutation only has to set the location, filename and the mutatedNode. The Stryker framework will than go on and set the status and substitution. 

The positive thing is that we can reuse this object for reporting as well as creating mutants. The bad thing is that it could be unclear for mutation plugin developers in the future. But i guess we could split it when we want to in the future.

**Comment by nicojs** [comment]
I removed the milestone, as we agree to not put this new API in the v1 release

**Comment by simondel** [comment]
https://github.com/stryker-mutator/stryker-api/blob/master/src/report/MutantResult.ts
