### ISSUE TITLE
html reports not working on gh-pages

### ISSUE THREAD

**Issue by riezebosch** [stryker-mutator/stryker#420]
Directories started with underscores are treated as special by jekyll and that's whats running on gh-pages by default. Therefor the `__resources` directory is not served breaking the css and js downloads.

To fix this either include a `_config.yml`:

```
include: 
 - __resources
```

Source: https://github.com/jekyll/jekyll/issues/1352#issuecomment-23229143

Or include a `.nojekyll` file to disable jekyll processing. Source: https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/

**Comment by nicojs** [comment]
Ok, so you suggest to add a `.nojekyll` fole in the html report by default? It might not really be the task of the html reporter.

**Comment by riezebosch** [comment]
True, it isn't an issue per se but thought it worth mentioning.

**Comment by nicojs** [comment]
> True, it isn't an issue per se but thought it worth mentioning. Maybe something for on the wiki, getting started or faq.

Maybe we can rename the directory. I called it `__resources` to make sure no naming clashes can occur. Maybe we can do something else to make sure of this, maybe `resources__`?

>Take a look at my report 🤓

Wow! 100%. Congrats! Glad to see that the typescript support solves your problems with false positives! What do you think of the new report?

**Comment by riezebosch** [comment]
Absolutely fantabulous 😃

**Comment by simondel** [comment]
Perhaps we could also use something like `strykerReportRe
