### ISSUE TITLE
Rationale on mutators desirable

### ISSUE THREAD

**Issue by riezebosch** [stryker-mutator/stryker#423]
Most mutators speak for itself but for me the ArrayLiteral did not. From the specs I can somewhat deduce what it's doing but for me it was not apparent what's wrong with this code and how I can fix it: 

```typescript
// original
return [].concat.apply([], files.map(_ => [_, separator])).slice(0, -1);

// mutant
return [[]].concat.apply([], files.map(_ => [_, separator])).slice(0, -1);
```

This is, as far as I know, a pretty [common trick](https://stackoverflow.com/a/10865042/129269) to flatten arrays.

Clickable links from the report would be awesome. Or all mutators should be self-describing. Is there some source where you got the inspiration from?

**Comment by nicojs** [comment]
Well.. the `ArrayLiteral` mutator mutates.... well, array literals. The reason it mutates `[]` to `[[]]` is to add an element to your array. Would it be more clear if it adds `'Stryker was here'`, or something like that?

A general description about the mutators is more difficult, as it would need to be language specific. The TypeScript mutator has a different mutator setup than the es5 mutator because of the way the AST is structured.

**Comment by riezebosch** [comment]
No, not per se. But I could not get the grasp of what was wrong with my array literal and why and how I should fix it. The reason is _not_ 'to add an element to your array', that's what it does. The reason is not apparent to me _why_ it adds an element to my array.

**Comment by nicojs** [comment]
Ah I now see your point. And it's a good point.

Looking at your piece of code i can see why you are confused. In fact, stryker generated an [*equivalent mutant*](https://en.wikipedia.org/wiki/Mutation_testing#Mutation_testing_overview) here. You could rewrite it to be (also shown in your link):

```javascript
return [].concat(files.map(_ => [_, separator])).slice(0, -1);
```

Why create an empty array just to call it's `concat` method on an other empty array. 

So, one could say the rational behind this mutator is to prevent code from creating empty array's just to use it's `Array.prototype` methods ;). But i agree that that is not a strong rationale.

@simondel how do you think we can make this kind of things more clear for users?
