### ISSUE TITLE
Reach consensus and implement stronger tslint rules

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#436]
Right now, we're using tslint, but without much rules enabled. We should agree on a good rule set and enforce it by fixing all inconsistencies and enforcing them in the build

**Comment by mscharley** [comment]
[I have opinions on this topic](https://github.com/mscharley/generic-type-guard/blob/master/tslint.json)

I spent way too long with the TSLint and ESLint rule lists.

**Comment by nicojs** [comment]
It's hard to comment on this. Could you create a PR for this? 

Could you try to place this TSConfig in the root of the repo and simply use 

```ts
{
  "extends": [
    "../../tsconfig.json"
  ],
```

Everywhere else?

**Comment by kmdrGroch** [comment]
@nicojs I think it can be closed and removed from ``backlog``

**Comment by nicojs** [comment]
Yes this one can be closed. What solution did you find for forcing an import order?

**Comment by kmdrGroch** [comment]
@nicojs there is an option in tslint, but honestly i dunno how it works (ASCII i suppose, SOMEHOW)
