### ISSUE TITLE
Refactor: Partial interfaces

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#439]
Since TS 2.2 we can use mapped types. A common mapped type is the `Partial<T>`. We could use this type to remove a lot of interfaces. Two use cases that i can think of:

* `Config` and `StrykerOptions` (`StrykerOptions` is pretty much a `Partial<Config>`).
* `Reporter` and `StrictReporter` (`Reporter` is a `Partial<StrictReporter>`)

Maybe we can also think of others here.

**Comment by simondel** [comment]
We've made changes to the reporter and config recently which makes this issue obsolete right now in m opinion. I'm closing this issue.
