### ISSUE TITLE
typescript declaration .d.ts files not being picked up

### ISSUE THREAD

**Issue by mikehaas763** [stryker-mutator/stryker#443]
I'm getting TypeScript errors in my stryker output that are the same errors as if I didn't have certain global declarations in a .d.ts file in my src/ directory. So, I'm assuming for some reason the stryker typescript compilation isn't picking up my .d.ts file despite it being picked up during my normal webpack typescript compile. Is there just a configuration I'm missing?

stryker.conf.js
```js
module.exports = function(config) {
  config.set({
    files: [],
    testRunner: "karma",
    mutator: "typescript",
    transpilers: ["typescript"],
    tsconfigFile: "tsconfig.json",
    reporter: ["clear-text", "progress"],
    testFramework: "jasmine",
    coverageAnalysis: "off",
    // logLevel: "trace",
    karmaConfigFile: "karma.typescript.conf.js",
    mutate: ["src/**/*.ts"]
  });
};
```

Update: with trace mode, I do see a line logged like "src/common/type-extensions.d.ts (included: true, mutated: true)"

**Comment by simondel** [comment]
Thanks for opening this issue! I was going to ask if you could post trace logging because I had a feeling that stryker was loading the `.d.ts` files but I see that you posted that in the update 👍 

Could you add ` '!src/**/*.ts'` to our `files` array in the stryker.conf.js and then test if that changes anything?

**Comment by mikehaas763** [comment]
No problem! Hopefully I can help figure out what's going on. After adding that to `files` I get an error for what looks like every *.ts file like "[2017-10-29 19:14:12.441] [ERROR] StrykerCli - an error occurred Error: Could not find mutate file "path/file.ts" in list of files."

**Comment by simondel** [comment]
Is that the actual file name? In either case, does it exist on disk and should it be mutated?

**Comment by mikehaas763** [comment]
I get that error for every *.ts file (~400) so I was just using it as an example

**Comment by mikehaas763** [comment]
I'm doing some debugging and I noticed by the time a `LanguageServiceHost` is created and passed into `ts.createLanguageService()` that the *.d.ts file is filtered out of the list of files that `getScriptFileNames()` expected to return. That filtering is happening here: https://github.com/stryker-mutator/stryker/blob/master/packages/stryker-typescript/src/helpers/tsHelpers.ts#L50

Idk if it's the correct intended behavior or not. Personally, when I removed the section of code that filters out *.d.ts I no longer saw the error, but instead saw a new error "error TS2300: Duplicate identifier". I know very little of the TypeScript compiler APIs and language service so trying to wrap my head around it 🙂

**Comment by nicojs** [comment]
@mikehaas763 that sounds like an interesting usecase you've got there. So basically, you have your own `d.ts` included in your build? Sounds like that is not yet supported by stryker-typescript yet. As a workaround you could try to rename it to a `.ts` file, thats sometimes possible. The reason that you get duplicate identifier error is that some of your `d.ts` files are now included twice I think.

Thanks for your investigation.  I will have a look later today or tomorrow. A small repo that reproduces the issue could help speed up things even more.

**Comment by mikehaas763** [comment]
@nicojs idk why but I subconsciously made the assumption that *.d.ts files had a special meaning to the compiler, maybe thought that it would automatically pick up the types from it. Seems I was wrong, that's not necessary. After renaming it to .ts I still get the same duplicate identifier error as I did from directly changing the code.

It seems it's because people on my team have added in their own module files code like `declare var myDate: any;` but I have since added types for that in my type-extensions.ts file to provide the types globally for all files. Although not ideal, I think it's a valid use case, as my normal typescript build doesn't complain about this, but it does when being built via stryker

I'll look into setting up a small repo that can reproduce this hopefully soon

**Comment by nicojs** [comment]
I created a small project that reproduced this issue. You can see it here: https://github.com/stryker-mutator/stryker/tree/fix/support-header-files/packages/stryker-typescript/testResources/useHeaderFile

@mikehaas763 is this similar to your use case (but massively simplified)?

This project will be used as an integration test.
