### ISSUE TITLE
Stryker not picking up standard lib typings?

### ISSUE THREAD

**Issue by hrb90** [stryker-mutator/stryker#446]
I have a [TypeScript project](http://github.com/hrb90/slick-mongoose) on which I'm using Stryker. I recently refactored to use the es2016 lib instead of es5, and since then, I'm getting transpilation errors when I try to run a mutation test.

stryker.conf.js:

```javascript
var tsconfig = require("./tsconfig.json");

module.exports = function(config) {
  config.set({
    files: [
      {
        pattern: "src/geom.ts",
        mutated: true,
        included: false
      },
      {
        pattern: "src/planar_graph.ts",
        mutated: true,
        included: false
      },
      {
        pattern: "src/thomassen.ts",
        mutated: true,
        included: false
      },
      { 
        pattern: "src/*.ts",
        mutated: false,
        included: false
      },
      "test/**/*.ts"
    ],
    mutate: ["src/geom.ts", "src/planar_graph.ts", "src/thomassen.ts"],
    tsconfig: tsconfig,
    mutator: 'typescript',
    testRunner: "jest",
    reporter: ["clear-text", "progress"],
    transpilers: ['typescript'],
    coverageAnalysis: "off"
  });
};
```

tsconfig.json:

```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "sourceMap": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "module": "commonjs",
    "lib": ["dom","es2016","dom.iterable","scripthost"],
    "target": "es5",
    "jsx": "react",
    "allowJs": true
  }
}
```

**Comment by nicojs** [comment]
I think i found the issue and did a PR to fix it here: https://github.com/hrb90/slick-mongoose/pull/4

You cannot simply require the tsconfig and provide it to stryker with `tsconfig: tsconfig`. Doing that won't let typescript resolve the config file. The `tsconfig` option is there to be able to *override* specific settings in your tsconfig file. What can we do to improve our documentation?

I close this issue for now. Please keep discussing improvements on the docs. 👍
