### ISSUE TITLE
Extend binary file extentions list

### ISSUE THREAD

**Issue by legopiraat** [stryker-mutator/stryker#447]
Hi,

Earlier Me and Nico where trying to use Stryker on an Typescript project. We noticed we had some failing tests. After some debugging we found out our .zip files were correctly interpreted as binary files.

Some additional file extensions would be nice.
`tar`, `zip`

(Sorry for the unclear explanation)

Greets

**Comment by simondel** [comment]
Good call! Would you be interested in adding it yourself? You can find the code [here](https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/src/utils/fileUtils.ts)

**Comment by nicojs** [comment]
Maybe we should also give people the change to specify that a file should be handled as binary. For example: 

```javascript
files: [{ pattern: '/path/to/binary', binary: true }]
```

**Comment by simondel** [comment]
We could add that as an extension as well 👍

**Comment by nicojs** [comment]
Hmm maybe it's better to do something like this:

```javascript
files: [{ pattern: '/path/to/binary', encoding: 'buffer' }]
```

Using the string `'buffer'` for binary files seems to be pretty common in the node world. You can see it used a lot here: https://nodejs.org/api/fs.html. Also: it will also allow for other encodings for text files. Right now: all text files are read using `'utf8'`.
