### ISSUE TITLE
TypeError when running Stryker with Vue.js

### ISSUE THREAD

**Issue by ckjeldgaard** [stryker-mutator/stryker#453]
Hi,

I'm facing a problem when attempting to run Stryker on a project using [Vue.js](https://vuejs.org/) with TypeScript tested with Jest.
If I declare Vue.js components as TypeScript classes my tests run successfully, but Stryker exits with a TypeError.

```
TypeError: Object prototype may only be an Object or null: undefined
```

I have created an example repository called [vuejs-stryker-mutation](https://github.com/ckjeldgaard/vuejs-stryker-mutation) which reproduces the problem. `npm run test` executes successfylly, but running `npm run stryker` yields the following output:

```
[ERROR] InitialTestExecutor - One or more tests resulted in an error:
        TypeError: Object prototype may only be an Object or null: undefined
[ERROR] StrykerCli - an error occurred Error: Something went wrong in the initial test run
    at InitialTestExecutor.validateResult (~/vuejs-stryker-mutation/node_modules/stryker/src/process/InitialTestExecutor.js:94:15)
    at InitialTestExecutor.<anonymous> (~/vuejs-stryker-mutation/node_modules/stryker/src/process/InitialTestExecutor.js:33:30)
    at step (~/vuejs-stryker-mutation/node_modules/tslib/tslib.js:129:27)
    at Object.next (~/vuejs-stryker-mutation/node_modules/tslib/tslib.js:110:57)
    at fulfilled (~/vuejs-stryker-mutation/node_modules/tslib/tslib.js:100:62)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

The problem seems to be caused by the `HelloComponent` in `/src/hello-component.ts` which extends Vue:

```typescript
@Component
export class HelloComponent extends Vue {
    helloString: string = 'Hello from Vue';
}
```

[An issue in the webpack project](https://github.com/webpack/webpack/issues/4520#issuecomment-288228218) suggests that this issue might be related to circular dependencies in Typescript, but it is unclear to me why this might be a problem for Stryker in this case, if it's not for the test framework.
Therefore, I'm not sure whether this is actually a bug or can be overcome by configuring either Stryker, test framework or Vue correctly. Any help in this regard will be highly appreciated.

**Comment by nicojs** [comment]
Thanks for reporting this issue! I will try to have a look later today.

**Comment by nicojs** [comment]
Sorry it took me so long to get back to you.

If i understand correctly you're using custom jest config here: https://github.com/ckjeldgaard/vuejs-stryker-mutation/blob/master/package.json#L10

The stryker-jest-runner at the moment does not support using custom config (as stated here: https://github.com/stryker-mutator/stryker-jest-runner#configuring). This is a problem we want to address in the near future. For now, i'll close this issue. Once we have an update about it, i'll add a comment here.
