### ISSUE TITLE
The block remover TypeScript mutator doesn't remove lambda function bodies

### ISSUE THREAD

**Issue by mscharley** [stryker-mutator/stryker#456]
```
export const isNumber: TypeGuard<number> = (n): n is number =>
  typeof n === "number";
```

Currently the only thing mutated about the above function is the equality. Considering there is a tslint rule to force all functions to be defined this way, which I use, this is a reasonably serious bug.

**Comment by mscharley** [comment]
Further investigation has revealed this is only if you use the shorthand for `return`, the following will be elided correctly:

```
export const isNumber: TypeGuard<number> = (n): n is number => {
  return typeof n === "number";
}
```

**Comment by nicojs** [comment]
Awesome, thanks for your investigation! Do you also want to implement the feature? 

It would mainly be adding a test here: 
https://github.com/stryker-mutator/stryker/tree/master/packages/stryker-typescript/test/unit/mutator
 
And implementing the mutator here:
https://github.com/stryker-mutator/stryker/tree/master/packages/stryker-typescript/src/mutator

You can look at the standard `Block` mutator as an example.

**Comment by nicojs** [comment]
The `SyntaxKind` is an `ArrowFunction`.

![image](https://user-images.githubusercontent.com/1828233/32771046-c7451db6-c921-11e7-8f1a-552788981932.png)

**Comment by mscharley** [comment]
I'll see if I can get a chance to take a look over the next couple days. I'm pretty busy at work, but worst case I should be able to find some time over the weekend. Thanks for the pointers!

For my info, what is the VSCode plugin you have that exposes the AST like that?

**Comment by nicojs** [comment]
@mscharley this awesome plugin: https://marketplace.visualstudio.com/items?itemName=krizzdewizz.vscode-typescript-ast-explorer
