### ISSUE TITLE
StringLiteral mutator should not empty strings that are exported directly.

### ISSUE THREAD

**Issue by mscharley** [stryker-mutator/stryker#465]
Examples that shouldn't be modified:

```
export { foo } from "foo";

export const foo = "bar";
export const bar = `baz`;
```

Examples that should be modified:

```
export const baz = `${foo}{$bar}`;
export const quux = () => "foo";
```

This last example is still implementing some small piece of functionality. The static strings however can't usefully be **unit tested** without simply duplicating the string itself into the unit test.

I'll probably pick this ticket up, but I'm leaving a note for myself here.

**Comment by nicojs** [comment]
I actually disagree. Tests shouldn't depend on production implementation if it can be helped. Not even string literals.

That being said, there are valid reasons to not fully tests these cases. That's why we don't advise to force a 100% mutation score.

**Comment by mscharley** [comment]
Can we at least agree that exports shouldn't be modified as in:

```
export { foo } from "foo";
```

The other is arguable and I'm honestly not sure which side of the fence I'm on right now. I'd be happy to leave that out for now but modifying exports will always be a transpile error for the same reason that modifying imports are.

**Comment by nicojs** [comment]
hmm true. We shouldn't mutate exports or imports. We also still have some imports being mutated like: 

```typescript
import zip = require("./ZipCodeValidator");
```

To summarize, this should not be mutated: 

```typescript
import { ZipCodeValidator } from "./ZipCodeValidator";
import "./my-module.js";
import $ from "JQuery";
import zip = require("./ZipCodeValidator");
export {ZipCodeValidator as RegExpBasedZipCodeValidator} from "./ZipCodeValidator";
export * from "./StringValidator"
declare module "hot-new-module";
declare module "*!text" { }
```

(pulled from https://www.typescriptlang.org/docs/handbook/modules.html)

**Comment by bharaninb** [comment]
Working on it

**Comment by kswope** [comment]
Was this successful?  I'm getting

```
[Survived] StringLiteral
src/lib/globals.ts:1:27
-   export const FORAGE_KEY = "bookmarks"
+   export const FORAGE_KEY = ""
Ran all tests for this mutant.
```

I can't imagine in what chaotic universe I'd need to test my constants.
