### ISSUE TITLE
Stryker Javascript Mutator typescript peer dependency

### ISSUE THREAD

**Issue by webdevian** [stryker-mutator/stryker#478]
I get the following peer dependency warning even though my project doesn't include any typescript. Should this peer dependency exist?

```
warning " > stryker-javascript-mutator@0.2.2" has unmet peer dependency "typescript@^2.5.3"
```

**Comment by nicojs** [comment]
Wouw, copy-paste error. We'll be quick to fix this issue. Thanks for reporting!

**Comment by simondel** [comment]
`stryker-javascript-mutator@0.2.3` has been released with this fix. Thanks for notifying us!
