### ISSUE TITLE
Angular (cli) Support

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#526]
See https://github.com/angular/angular-cli/issues/8744

**Comment by simondel** [comment]
@nicojs What are the plans for this since Angular 6 came out?

**Comment by nicojs** [comment]
I've decided on a slightly different approach. I'm extending the `KarmaTestRunner` to also support the `npm test` setup. Similar to the jest runner's ability to use different presets, the karma runner will have a way to support different runner implementation.

@stryker-mutator/contributors what should the config look like? It would be nice if we can make a sensible configuration option, like with jest:

```js
karma: {
        project: 'default', // or 'ng'
        configFile: 'path/to/karma.conf.js'
        config: {
             browsers: ['ChromeHeadless'] // override config settings
        }
 }
```

But this would be a breaking change, since we now support the `karmaConfig` and `karmaConfigFile` settings.

Also I don't like the `'default'` name. I think it should be `custom`. What do you guys think? If you agree we should also make the change to the jest runner.

I've decided to go this route instead of creating a new `AngularCliTestRunner` as both implementation would look the same. It does mean some refactoring though, hope to get that done sometime this week.

**Comment by mthmulders** [comment]
Well... `default` suggests it should work in most cases. I usually start with defaults to see if things work. If not, I switch to something else (provided it is documented, available, ...). So I think we should be careful to promote something as being the _default_.

**Comment by nicojs** [comment]
My point is that the name `project: 'default'` is a strange *default* setting. It doesn't make sense saying that the `default` setting is *default* imo. If _default_ is the _default_ what does that mean? Can't we really not think of something better.

The reason why I call it "custom" for jest, is that you can use a "custom jest configuration". Another name could be "manual".

For karma, we could maybe use "karma" (default) or "angular". What do you think?

**Comment by simondel** [comment]
> But this would be a breaking change, since we now support the karmaConfig and karmaConfigFile settings.

I don't see those two settings in your example. I would prefer `karma` and `angular` as values

**Comment by nicojs** [comment]
@simondel that's why its breaking. But we can support both with a deprecation warning

**Comment by nicojs** [comment]
Let's go with this configuration for now. Seems clean and less breaking:

```
karma: {
        project: 'custom', // or 'angular-cli'
        configFile: 'path/to/karma.conf.js' // default `undefined`
        config: { // default `undefined`
             browsers: ['ChromeHeadless'] // override config settings
        }
 }
```

I'll also make the following changes:

* Make sure `karmaConfig` and `karmaConfigFile` both work with a deprecation warning. 
* Remove `karma` as peer dependency (as it could also be `@angular/cli`)
* Add a check on the `@angular/cli` version (as the minimal version should be 6.0.8).

**Comment by simondel** [comment]
Sounds good!

**Comment by mnahkies** [comment]
@nicojs is there any chance you could link whatever changes / documentation came out of this issue?

**Comment by nicojs** [comment]
Sure! For people getting started with angular-cli + Stryker: please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/guides/angular.md
