### ISSUE TITLE
Extensive plugin config validation

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#548]
It would be nice if every plugin could validate the config he expects. This would prevent frustrating errors by users.

For example: 

```javascript
{ 
   tsconfig: { 
       compilerOptions: {
            // ...
       }
   }
```

The `stryker-typescript` config editor should fail this stryker run early with a clear error message saying that: if `tsconfig` is used directly, it should contain the `compilerOptions` directly.

While we're creating this ConfigValidator stuff, we should also make sure users don't have any additional configuration. For example: 

 ```javascript
{ 
   stconfig: { 
        // ...
   }
```

This should result in an error, because the user misspelled the config setting here.

**Comment by simondel** [comment]
To me, the layer of complexity that added with this centralized validation early in the process is not worth the usability improvement right now.

I'm fine with every plugin doing its own validation when it needs to use the config settings.

**Comment by simondel** [comment]
As discussed, I'm closing this issue as we don't think we'll work on it in the near future. It is, however, something we would like to have.
