### ISSUE TITLE
Feature Idea: Mutate only modified files (based on git)

### ISSUE THREAD

**Issue by shybyte** [stryker-mutator/stryker#551]
Mutationtesting can need a lot of time. For example mutation testing Stryker itself needs 45 minutes on my computer. This makes it very unusable for this workflow:

1. Implement a feature/bug fix (sometimes together with tests)
2. Write some/more tests
3. Run mutationtest to check if something in the new code is not tested. If something important is missing go back to 2.
4. Commit and Push (Complete mutationtest runs on CI)

Now the thing is: Actually in step 3 I don't care for all mutations outside of my changes. Yes, in theory they might be connected with my new code, but it's just not practical to wait so long in step 3.

Therefore I have developed the following workaround, which mutates only changed files:
```js
const {execSync} = require('child_process');

function listModifiedFiles(regexp) {
  const modifiedFiles = execSync('git ls-files -m', {encoding: "UTF8"})
    .split('\n')
    .filter(fileName => !!fileName);
  return modifiedFiles.filter(fileName => regexp.test(fileName));
}

module.exports = function (config) {
  config.set({
    files: ['!**/*.*', 'src/**/*.ts', 'test/**/*.ts'],
    mutate: ['!**/*.*'].concat(listModifiedFiles(/src.*\.ts/)),
    testRunner: "karma",
    mutator: "typescript",
    transpilers: ["typescript"],
    reporter: ["html", "baseline", "clear-text", "progress"],
    coverageAnalysis: "off",
    karmaConfigFile: "karma.conf.js",
    tsconfigFile: "tsconfig.json",
  });
};

```
(Complete working example project: https://github.com/shybyte/stryker-mocha-karma-ts)

I wonder:
 * Is this approach something that can/should be directly integrated into stryker?
 * Does is makes sense to document this approach?

**Comment by nicojs** [comment]
> Is this approach something that can/should be directly integrated into stryker?

I woulnd't want to use git as a source of files, as it would tightly couple with it. I think we already have a fairly good improvement idea for this using something we've been calling incremental analysis here: #322. I'm curious what your take is on this approach.

> Does is makes sense to document this approach?

Yes it does! What do you think a good place for config examples would be?

**Comment by shybyte** [comment]
I guess approach #322 is more solid but also a lot more complicated. 

> What do you think a good place for config examples would be?

In this particular case it's about "How do I speed it up Stryker?" so maybe just a link in the FAQ on https://stryker-mutator.github.io/faq.html to this issue could help others.

**Comment by nicojs** [comment]
> In this particular case it's about "How do I speed it up Stryker?" so maybe just a link in the FAQ 

Sounds good. Maybe we can reserve a place in the stryker main repo for example configs. So you can point to that from the FAQ. @simondel what do you think? Maybe we could create an `examples` folder. Others can contribute to, for example with a working example for config using typescript, babel + flow, ...

**Comment by simondel** [comment]
I think it's a good idea to add a folder with examples. Inside of that folder I would suggest adding folders with some example code and documentation. 
For example:
- repo root
   - examples
      - README.md
      - speedIncrease
         - mutateBasedOnGit
            - README.md
            - stryker.conf.js

We should test if the script above also works on Windows because it splits on `\n` instead of `\r\n`.

**Comment by simondel** [comment]
We have the handbook with example configuration: https://github.com/stryker-mutator/stryker-handbook

Our quickstart has also improved a lot in the past few months. I'm closing this issue for now.
