### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by Koko2034** [stryker-mutator/stryker#556]
Hello everybody!

I'm using your stryker settings, but when I run tests over typescript's class, I always get the same error:

Uncaught ReferenceError: exports is not defined

I suppose this reference to "exports" is for our class.

Could you help me?

**Comment by simondel** [comment]
Hi! Could you share your stryker.conf.js? If you can't share this publicly you can always share it privately with either me or @nicojs on [gitter](https://gitter.im/stryker-mutator/stryker) or send me an [email](mailto:simondelang@gmail.com)

**Comment by nicojs** [comment]
@Koko2034 did you make any progress on this issue? What test runner are you using?

**Comment by simondel** [comment]
Since we didn't get an update on this issue, I'll close it for now. If this issue is still present, please let us know!
