### ISSUE TITLE
Stryker-cli: description disappears when moving cursor

### ISSUE THREAD

**Issue by Archcry** [stryker-mutator/stryker#570]
When using `stryker init` you get a short description of what to do in a particular menu (e.g. "Use arrow keys", "Press <space> to select, <a> to toggle all, <i> to inverse selection"). When I was testing the stryker-cli with an colleague he noted that it would be better to not let this description disappear when moving the cursor.

**Comment by simondel** [comment]
I can't find a way to configure this in the inquirer readme, so I'll close this issue for now.
