### ISSUE TITLE
Add interpret support for stryker config file

### ISSUE THREAD

**Issue by unlight** [stryker-mutator/stryker#580]
Link: https://github.com/js-cli/js-interpret
Main purpose is to get typings support in configuration file.

Gulp, Webpack, karma uses it.

`stryker.conf.js` can be re-written as `stryker.conf.ts`
```ts
import { Config } from 'stryker-api/config';

export = (config: Config) => {
    config.set({
        files: [],
        testRunner: 'jest',
        mutator: 'typescript',
        transpilers: ['typescript'],
        reporter: ['html', 'clear-text', 'progress'],
        coverageAnalysis: 'off',
        tsconfigFile: 'tsconfig.json',
        mutate: ['app/**/cat.controller.ts'],
        timeoutMs: 10 * 1000,
        // timeoutFactor: 2,
        htmlReporter: {
            baseDir: '.testresults/mutation'
        },
    });
};
```

**Comment by nicojs** [comment]
This looks pretty interesting. I haven't heard of `js-interpret` or `liftoff` before. Maybe we should investigate this a little more. They both look interesting.

@unlight are you interested in contributing on this issue?

**Comment by unlight** [comment]
Sorry I was a little wrong, Webpack uses `interpret`, gulp (gulp-cli) are using `liftoff` + `interpret`.
Karma has limited predefined list: `karma\lib\cli.js:106` and uses strange loading, but anyway, you got the point.

> are you interested in contributing on this issue?

I can say that, it's "nice to have" feature for me (configration does not change often) , I just get used to TypeScript and Intellisense.

I can invest 1-2 evenings to research how it can be used, and later maybe can submit pull request.

**Comment by simondel** [comment]
Since no-one has shown interest in this for a while, I'm closing this issue. If someone still wants to do it, let us know!
