### ISSUE TITLE
Configurable list of babylon plugins for the javascript mutator

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#616]
As of now, the javascript-mutator does not support a configurable list of plugins it provides to the babylon parser. We cannot simply enable all plugins, as some might interfere with each other (like `'typescript'` and `'flow'`). 

The default list now is (at the time of writing): 

```js
plugins: [
   'jsx',
  'flow'
  'flow',
  'objectRestSpread',
  'classProperties',
  'asyncGenerators',
  'dynamicImport'
]
```

I suggest to allow users to configure the list of plugins in stryker.conf.js. Something like:

```js
{
  mutator: { name: 'javascript', plugins: [ 'flow', 'dynamicImports' ]
}
```

If a user provides a list of plugins, the javascript mutator should no longer choose its own plugins (no mix-and-matching).

See https://github.com/babel/babel/tree/master/packages/babylon#plugins for the list of plugins. Watch out! Some plugins are not yet released (like the 'typescript' plugin). For the current list of plugins: https://www.npmjs.com/package/babylon#plugins

Also see #612

**Comment by simondel** [comment]
This is possible right now, more info: https://www.npmjs.com/package/@stryker-mutator/javascript-mutator
