### ISSUE TITLE
Unable to provide webpack as a dependency for a preprocessor in karma.config file

### ISSUE THREAD

**Issue by anithashok1910** [stryker-mutator/stryker#618]
Using->
AngularJS 1.5.7
Node 6.5.0
WebPack 3.0.0
OS : MacOS

I have configured the **stryker.config** file using stryker init and it is generated as follows:

```
module.exports = function(config){
	config.set({
		testRunner: 'karma',
		testFramework: 'jasmine',
		karmaConfigFile: 'karma.conf.js',
                coverageAnalysis: 'off',
		reporter: [
			'progress', 
			'clear-text', 
			'dots', 
			'html', 
			'event-recorder'
		],
		plugins: [
			'stryker-jasmine',
			'stryker-karma-runner',
			'stryker-html-reporter'
		]
	});
}
```

and in **karma.conf.js** as :

```
'use strict';

var webpackConfig = require('./config/webpack.test.config.js');

module.exports = function (config) {
	config.set({
		basePath: '',
		frameworks: ['jasmine'],
		port: 9800,
		colors: true,
		logLevel: config.LOG_INFO,
		autoWatch: false,
		browsers: ['PhantomJS'],
		singleRun: true,
		files: [
			'./node_modules/angular/angular.js',
                       // .. and some more dependencies like jquery and the 
			'./test.index.js'
		],
		preprocessors: {
			'./test.index.js': ['webpack']
		},
	
		webpack: webpackConfig
	});
};
```

and in **test.index.js**

```
var __karmaWebPackManifest__ = [];

var testsContext = require.context("../unit/", true,/Spec$/);

function inManifest(path){
return __karmaWebpackManifest__.indexOf(path) >=0;
}

var runable = testsContext.keys().filter(inManifest);

if(!runnable.length){
runnable = testsContext.keys();
}

runnable.forEach(testsContext);
```
The **webpack.test.config.js**
```

var webpack = require('webpack');
var path = require('path');
module.exports = {
	resolve: {
		modules: [{
test:/\.js$/,
loader: 'webpack-replace',
},{
        test:/\.js$/,
        include:path.resolve('../src/'),
        exclude:/\.spec.js$/,
        loader: 'istanbul-instrumenter-loader',
}		],
	},
	plugins: [
		new webpack.ProvidePlugin({
			$: 'jquery',
			jQuery: 'jquery',
			'window.jQuery': 'jquery',
			'window.jquery': 'jquery',
                        '_':'underscore'
		}),
	],
resolve:{
       alias:{
         'angular-translate':'angular-translate/angular-translate'
                }
           }
  };

```
The error I m getting:

**Error:** No provider for "files" !  (Resolving: preprocess -> preprocessoer: webpack -> framework:jasmine -> files)
**ERROR** [preprocess]: Can not load "webpack"!
ReferenceError: Webpack is not defined

**DEBUG** [karma]: Registered a load error of type preprocessor with the name webpack

Am I missing something ?
Can you please help me for the same ?

Sorry for omitting some portions of code.

**Comment by nicojs** [comment]
@anithashok1910 thanks for reporting this issue.

If you run stryker with `logLevel: 'trace'` you will be able to see the karma output. I'm particularly interested in the part where it says: `[TRACE] TestRunnerChildProcessAdapter - [2018-02-08 13:36:12.522] [INFO] KarmaTestRunner - using config`. Could you look that up and confirm that the expected files are present in the array.

That being said, I'm not sure if this plugin is something we can support in the long run. We're working on getting coverage analysis support for webpack and friends. That means that Stryker should be in charge of the bundling/transpiling process. Could you try to use the [`stryker-webpack-transpiler` plugin](https://github.com/stryker-mutator/stryker/tree/master/packages/stryker-webpack-transpiler)? Your karma config would remain the same, except without `"preprocessors"`.
