### ISSUE TITLE
Stryker crashes: Cannot find module 'source-map-support/register'

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#620]
```bash
$ stryker init
Cannot find module 'source-map-support/register'
```

Introduced on 2018-02-03 and released yesterday.

**Comment by nicojs** [comment]
Fixed in commit https://github.com/stryker-mutator/stryker/commit/095619475b92ce2e4a39177423ca81c2168d6a50. Release is running.

**Comment by nicojs** [comment]
Fixed in  stryker@0.19.2

**Comment by simondel** [comment]
How do things like these pass our CI?

**Comment by nicojs** [comment]
This is one of the dev dependencies in our parent project. To really test these things, we should move our integration tests outside of the root dir
