### ISSUE TITLE
Support webpack 4

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#630]
Webpack release 4 contains a lot of breaking changes. 

https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202

We should migrate the stryker-webpack-transpiler to support this version. It might make sense to not support 3 anymore (anyone interested in webpack 3 can still use the old version).

**Comment by nicojs** [comment]
Release notes here: https://github.com/webpack/webpack/releases/tag/v4.0.0

**Comment by Archcry** [comment]
https://github.com/stryker-mutator/stryker/pull/664
