### ISSUE TITLE
Projectroot in stryker configuration object

### ISSUE THREAD

**Issue by Archcry** [stryker-mutator/stryker#650]
Currently we are using `process.cwd()` in a lot of plugins to resolve the current working directory in some of our stryker packages. This is undesirable in tests we sometimes want to mock the current working directory to "pretend" we're somewhere else. The only way to do this at the moment is to mock `process.cwd()` which can cause side effects. It would be better to define a `projectRoot` or `base` property on the Stryker config object that points to the current working directory. This way we can make our own Stryker config with a `projectRoot` or `base` that points somewhere else without harming `process.cwd()`.

**Comment by nicojs** [comment]
How about `basePath`? (same as Karma)

A list of components that should use this property:

* stryker: input file resolver and mutate property
* karma-runner: use to locate karma configuration
* typescript-transpiler: locate the tsconfig file
* babel-transpiler: use to locate babelrc
* webpack-transpiler: use to locate wepack config file.
* mocha-runner: locate mocha.opts file

Let's first finish #589

**Comment by Archcry** [comment]
> How about `basePath`? (same as Karma)

Sounds good

**Comment by nicojs** [comment]
OK, the way it should work:

`basePath` will always be set by stryker and defaults to `.` (current directory). 

If `basePath` is set in stryker.conf.js: that basePath is used, relative to the stryker.conf.js file. For example: `path.resolve(path.dirname('path/to/stryker.conf.js'), options.basePath)`

This should also solve #245

**Comment by nicojs** [comment]
I think this also solves #137

**Comment by simondel** [comment]
I'll get to work on this 👍

**Comment by simondel** [comment]
As discussed we won't do this right now.
