### ISSUE TITLE
Add support for web component tester

### ISSUE THREAD

**Issue by Joengenduvel** [stryker-mutator/stryker#662]
### Summary

We would like to use Stryker with [Polymer](https://www.polymer-project.org/), but I cannot find a plugin for [wct ](https://github.com/Polymer/web-component-tester) on: https://stryker-mutator.io/plugins.html

**Comment by simondel** [comment]
@nicojs Can this be closed?

**Comment by simondel** [comment]
Yes :) this is available. You can read up on it in this blog: https://stryker-mutator.io/blog/2018-12-24/anouncing-stryker-0-34
