### ISSUE TITLE
inconsistent use of Array<> and []

### ISSUE THREAD

**Issue by Archcry** [stryker-mutator/stryker#666]
We should make a clear decision on which of the notations we'd like to use. The codebase now contains both `Array<T> var` and `var[]` aswell as `ReadOnlyArray<T>`. I vouch for the most explicit version (`Array<T>`).

**Comment by nicojs** [comment]
Let's use https://github.com/stryker-mutator/stryker/issues/436 for any static code analysis rules.

IMO we should use `[]` notation for simple arrays. There is a tslint config for that.

**Comment by simondel** [comment]
I agree with @nicojs
