### ISSUE TITLE
Need an example of typescript + jest + ts-jest

### ISSUE THREAD

**Issue by aleccool213** [stryker-mutator/stryker#668]
### Summary

I am trying to run Stryker with a small sample project and running into an issue.

```
[2018-03-25 21:06:01.085] [ERROR] InitialTestExecutor - One or more tests resulted in an error:
	  ● Test suite failed to run

    ReferenceError: System is not defined

    > 1 | import { isOldEnough } from '../sample';
      2 |
      3 | describe('isOldEnough', () => {
      4 |   it('should return true if old enough', () => {

      at Object.<anonymous> (src/sample-module/__tests__/sample.test.ts:1:2102)

[2018-03-25 21:06:01.085] [ERROR] StrykerCli - an error occurred Error: Something went wrong in the initial test run
```

I followed the README on how to use Jest as a test-runner/framework and installed the stryker typescript plugin as well. `jest` runs fine and `tsc` passes as well. Anyone run into this before?

### Stryker config

```
module.exports = function (config) {
  config.set({
    files: [
      '!src/**/*.ts',
      {
        pattern: 'src/**/*.ts',
        mutated: true,
        included: false
      },
      '!src/**/__tests__/*.ts',
      {
        pattern: 'src/**/__tests__/*.ts',
        mutated: false,
        included: true
      }
    ],
    logLevel: 'trace',
    testRunner: 'jest',
    testFramework: 'jest',
    mutator: 'typescript',
    coverageAnalysis: 'off',
    // transpilers: ['typescript'],
    reporter: ['progress', 'clear-text', 'dots', 'html', 'event-recorder'],
    tsconfigFile: './tsconfig.json'
  });
};
```

```js
module.exports = function(config){
  config.set({
    ....
  });
}
```

### Stryker environment

```
─┬ stryker@0.19.4
├─┬ stryker-api@0.13.0
├─┬ stryker-html-reporter@0.12.1
├─┬ stryker-jest-runner@0.5.1
├─┬ stryker-typescript@0.9.1
```

### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             | 8.9.1
| npm              |  5.6.0
| Operating System | MacOSX

**Comment by aleccool213** [comment]
Update: 

Doesnt seem like a stryker-typescript-plugin issue as I get the same error with this config:

```
module.exports = function (config) {
  config.set({
    files: [
      {
        pattern: 'src/**/*.ts',
        mutated: true,
        included: false
      },
      {
        pattern: 'src/**/__tests__/*.ts',
        mutated: false,
        included: true
      }
    ],
    logLevel: 'trace',
    testRunner: 'jest',
    testFramework: 'jest',
    // mutator: 'typescript',
    coverageAnalysis: 'off',
    // transpilers: ['typescript'],
    reporter: ['progress', 'clear-text', 'dots', 'html', 'event-recorder']
    // tsconfigFile: './tsconfig.json'
  });
};
```

**Comment by aleccool213** [comment]
Seems like my tsconfig.json file was just bad. I used the default one and it didn't provide things like `moduleResolution`. Here is the tsconfig.json file which finally got it working:

```javascript
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "moduleResolution": "node",
    "importHelpers": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "declaration": false,
    "inlineSourceMap": true,
    "skipLibCheck": true,
    "strictNullChecks": true,
    "isolatedModules": true,
    "lib": ["es2017"]
  },
  "include": ["src/**/*.ts"]
}
```

**Comment by simondel** [comment]
Glad to hear you managed to solve your issue! That's a sneaky one..

For our reference, where would you look for an example? What kind of an example would you want? (Blog, GH repo, something else)

PS: If you're having an issue with many timeouts during mutation testing, please let us know!

**Comment by aleccool213** [comment]
@simondel 

Hi! A quick blog post describing how to set it up with Jest and Typescript would be nice. Increased visibility of this repo would also be the benefit of that. One of the things I found challenging to understand at first was that if Jest (with ts-jest) was already running my tests, I didn't need the stryker typescript transpiler plugin. I initially thought I needed this because of mutations but it seems like typescript mutations is built into the base repo!

P.S. Very awesome project, keep up the good work.

**Comment by MaxVynohradov** [comment]
Hi! @aleccool213 could.you please provide example how to run jest + ts-jest + stryker ?
Got next:
```
Details:

/Users/max/projects/ts-mutation-testing-example/.stryker-tmp/sandbox4527871/src/__tests__/fn1.spec.ts:56
import { f1 } from '../fn1';
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:86:7)

```
