### ISSUE TITLE
Support coverageAnalysis 'perTest' for stryker-webpack-transpiler.

### ISSUE THREAD

**Issue by ashah2193** [stryker-mutator/stryker#670]
### Stryker config

```js
module.exports = function(config){
  config.set({
    ....
  });
}
```

### Stryker environment

```
+-- stryker@x.x.x
+-- stryker-api@x.x.x
```

### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             | 
| npm              | 
| Operating System |

**Comment by simondel** [comment]
We'll change the way we do coverage analysis in the future so I'm closing this issue for now.
