### ISSUE TITLE
TS StringLiteralMutator should not mutate JSX attribute's strings

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#701]
The StringLiteralMutator in the stryker-typescript package should not mutate strings in a JSX attribute. 

The code `<Record class="row" />` creates one mutant right now: `<Record class="" />`.

We can probably prevent this from happening by changing the check on parent nodes to:
```ts
  private isInvalidParentNode(node: ts.Node): boolean {
    return node.kind === ts.SyntaxKind.ImportDeclaration ||
      node.kind === ts.SyntaxKind.LastTypeNode ||
      node.kind === ts.SyntaxKind.JsxAttribute;
  }
```

This is the same check on JsxAttributes that is used in the stryker-javascript-mutator

**Comment by nicojs** [comment]
You're pretty harsh classifying it as a bug ;)

**Comment by simondel** [comment]
You're right! You could also see this as a feature. To me it is a bug because we have behaviour that we did not intend and if we had come across this feature/bug during the development of the TypeScript mutator, we would probably have decided not to mutate the JSX elements like we do now.
