### ISSUE TITLE
mocha-test-runner doesn't find any tests (typescript)

### ISSUE THREAD

**Issue by boehmers** [stryker-mutator/stryker#704]
Hey everyone,

as we wanted to try stryker in our project, we tried to set it up in our node-express-backend  to mutation-test the project. We use typescript and mocha to run our tests.

We ran into the issue, that no tests to be executed can be found at all. I read this issue, maybe the problem is similar: https://github.com/stryker-mutator/stryker/issues/684

### Summary

These are the used dependencies:
```
"devDependencies": {
    "@types/chai": "^4.1.2",
    "@types/express": "^4.11.1",
    "@types/mocha": "^5.0.0",
    "@types/node": "^9.6.2",
    "chai": "^4.1.2",
    "cross-env": "^5.1.1",
    "mocha": "^5.0.5",
    "stryker": "^0.22.1",
    "stryker-api": "^0.16.0",
    "stryker-mocha-framework": "^0.9.1",
    "stryker-mocha-runner": "^0.11.1",
    "stryker-typescript": "^0.10.1",
    "supertest": "^3.0.0",
    "ts-node": "^5.0.1",
    "typescript": "^2.8.1"
  }
```

Our tests are executed succesfully with this command:
```
"scripts": {
    "test": "cross-env NODE_TLS_REJECT_UNAUTHORIZED=0 mocha -r ts-node/register src/**/*.spec.ts --timeout 5000",
}
```

This is the project-file-structure:
```
package.json
stryker.conf.js
tsconfig.json
src
-- index.ts
-- [sone other ts-files]
-- [some other folders with ts-files]
-- test
---- testfile.spec.ts
```

The Output:
```
rm -rf .stryker-tmp && cross-env NODE_TLS_REJECT_UNAUTHORIZED=0 stryker run

[2018-04-18 08:46:33.524] [INFO] ConfigReader - Using stryker.conf.js in the current working directory.
[2018-04-18 08:46:33.924] [INFO] TypescriptConfigEditor - Loading tsconfig file /**/**/tsconfig.json
[2018-04-18 08:46:34.005] [INFO] InputFileResolver - Found 17 of 26 file(s) to be mutated.
[2018-04-18 08:46:34.006] [INFO] InitialTestExecutor - Starting initial test run. This may take a while.
[2018-04-18 08:46:36.443] [ERROR] StrykerCli - an error occurred Error: [MochaTestRunner] No files discovered (tried pattern(s) [
  "src/**/*.spec.js"
]). Please specify the files (glob patterns) containing your tests in mochaOptions.files in your stryker.conf.js file.
Error: [MochaTestRunner] No files discovered (tried pattern(s) [
  "src/**/*.spec.js"
]). Please specify the files (glob patterns) containing your tests in mochaOptions.files in your stryker.conf.js file.
```

### Stryker config

We read into the issue mentioned above, and this is the result of our stryker-conf after taking the suggestions there into consideration. But we still get no tests to run.

```js
module.exports = function(config) {
  config.set({
    mutate: [
      "src/**/*.ts"
    ],
    testFramework: "mocha",
    testRunner: "mocha",
    tsconfigFile: "tsconfig.json",
    mutator: "typescript",
    transpilers: ["typescript"],
    reporter: ["clear-text", "progress"],
    coverageAnalysis: "off",
    mochaOptions: {
      files: "src/**/*.spec.js",
      timeout: 5000
    }
  });
};
```
We tried `mochaOptions` with files as array and with .ts-extension, but nothing worked.

### Stryker environment

```
+-- stryker@0.22.1
+-- stryker-api@0.16.0
+-- stryker-mocha-framework@0.9.1
+-- stryker-mocha-runner@0.11.1
+-- stryker-typescript@0.10.1
```

### Your Environment

We tried both npm and yarn, but normally use yarn.

| software         | version(s)
| ---------------- | -------  
| node             | 8.9.4
| yarn              | 1.3.2
| npm              | 5.6.0
| Operating System | macOS High Sierra 10.13.4

Thanks in advance!

**Comment by simondel** [comment]
Thanks for opening this detailed issue and going through the other issues before opening one for yourself. We appreciate that :heart:. I'll create a demo project tomorrow to test this out myself and hopefully reproduce the issue.

**Comment by nicojs** [comment]
@boehmers I've been trying to recreate it with a simple project. Unfortunately I've not been successful. Could you try again with `stryker run --logLevel debug`? I'm especially interested in this part: 

```
[2018-04-20 16:00:36.259] [DEBUG] InitialTestExecutor - Transpiled files: [
  ... lots of files
]
```

There you should be able to spot your expected transpile output. Could you verify this?

**Comment by boehmers** [comment]
@nicojs I inspected the debug-output myself first and found the problem:
The typescript-transpiler transpiled the files to a "build"-directory, but my stryker.conf.js was looking for the transpiled files in the src-directory. I fixed my config to the following, which made everything work properly:
```
module.exports = function(config) {
  config.set({
    mutate: [
      "src/**/*.ts"
    ],
    testFramework: "mocha",
    testRunner: "mocha",
    tsconfigFile: "tsconfig.json",
    mutator: "typescript",
    transpilers: ["typescript"],
    reporter: ["clear-text", "progress"],
    coverageAnalysis: "off",
    mochaOptions: {
      files: "build/**/*.spec.js",
      timeout: 5000
    }
  });
};
``
`

With this, I will close this issue, because there is no bug at all, just a user error ;-) 
Maybe this could help others understand, that stryker with this setup (typescript + mocha) needs to look for test-files in the typescript-output-directory.

Thanks for your effort!

**Comment by nicojs** [comment]
@boehmers great to hear it! You can also try to set `coverageAnalysis` to `"perTest"`. That should give your stryker test runs a performance boost.

Yes, this issue documents the solution nicely. It should definitely be part of #718

**Comment by nicojs** [comment]
Cool! What is the performance gain if I may ask? I'm kind of curious seeing as it took quite some time to implement, but I don't have many performance statistics yet

**Comment by boehmers** [comment]
Hey,

unfortunately, we didn't get an increase in performance with the option `coverageAnalysis: "perTest"`. In fact, turning off the coverageAnalysis was about 5 seconds faster (40-43s VS. 47-49s). But what we got out of it, and what's imho more interesting is a more detailed and more correct mutation score. This made us work to kill the last surviving mutants ;-)

Keep it up!

**Comment by nicojs** [comment]
Yeah, the overhead might not be worth it for smaller projects. On Stryker itself it saves a couple of minutes. The console reporter also displays the amount of tests/mutant. For example `Ran 171.68 tests per mutant on average`. The lower that number the higher the performance gain.

Thanks for the reply!
