### ISSUE TITLE
Document known configurations

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#718]
In order to better help our users get up to speed, we should document known configurations. I think it would be smart to not use the wiki for this because it's difficult to accept PRs for a wiki.

I think it would be smart to have a folder for each type of application (Angular, React, React Native... Etc.). In that folder we could have the different types of configurations showing an example Stryker config, which plugins are recommended and other related config such as tsconfig or the jest config.

**Comment by nicojs** [comment]
We could also use the wiki functionality on github for this. Than anyone should be able to contribute without the hassle of creating a PR.

**Comment by simondel** [comment]
How would that work? I thought only people with write access could edit a wiki page

**Comment by simondel** [comment]
Ok, it is possible to open up a wiki:
https://help.github.com/articles/changing-access-permissions-for-wikis/

But then anyone would be able to make any change and I'm not sure if that's what we'd like.

**Comment by nicojs** [comment]
I think a public wiki is fine for now. We can always make it more private later if we experience problems right? Maybe we can also make it our home for in-depth development documentation.

**Comment by Archcry** [comment]
What are the alternatives to using a WIKI? We could document it on out website, then people will be able to make pull-requests.

**Comment by nicojs** [comment]
Duplicate of #1049 ?

**Comment by simondel** [comment]
This is now the stryker-handbook :) https://github.com/stryker-mutator/stryker-handbook
