### ISSUE TITLE
Remove conditionals in return 

### ISSUE THREAD

**Issue by Binau** [stryker-mutator/stryker#721]
### Summary
Remove conditionals in return 

### Stryker config
```js
module.exports = function (config) {
    config.set({
        testRunner: "mocha",
        files: [
            "tmp/**/*.js"
        ],
        mutate: [
            "tmp/src/dep.js"
        ],
        transpilers: [],
        reporter: ["clear-text"],
        coverageAnalysis: "all",
        mochaOptions : {
            files : [
                "tmp/test/*.js"
            ]
        }
    });
};
```

### Stryker environment
```
+-- stryker@0.22.4
+-- stryker-api@0.16.1
+-- stryker-mocha-runner: 0.11.2,
```

### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             | 9.11.1
| npm              | 5.8.0
| Operating System | win10 

### Problem
this code  :
```js
isEnfant(val) {
    return val <= 18;
}
```
is not mutated to :
```js
isEnfant(val) {
    return true;
}
```

Test mocha (i test only val=5) :
```js
describe('TEST ', () => {
    it('test', () => {
        assert.ok(isEnfant(5));
    }));
});
```

**Comment by simondel** [comment]
I think a better way to look at this would be to change the RemoveConditionals to no longer do it for if-statements but instead do it for every conditional it finds. We would of course still have to look at parent nodes to find out if we're not causing infinite loops with for-statements for example.

**Comment by nicojs** [comment]
Sounds great. Just for my understanding, this is something we also don't mutate right now?

```js
const foo = bar > 3 ? 'foo' : 'bar';
```

**Comment by simondel** [comment]
Exactly. With this change we can also start doing that.
