### ISSUE TITLE
Support automatic port selection in stryker-karma-runner

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#740]
At this moment whenever karma (automatically) selects the next open port, stryker will report it as an error. We should support this feature.

When we support this feature, we can also remove the `port` config in stryker-api, making the api much cleaner (remove test runner specific configuration)

**Comment by nicojs** [comment]
Discovered in #715

**Comment by simondel** [comment]
@nicojs As discussed. This is not yet implemented.

**Comment by nicojs** [comment]
No it is not. If the port that Stryker has chosen for karma is unavailable, karma will automatically select the next available port. That part works perfect. However, when next Stryker executes `karma run`, it does so using the old port. In other words, the port that karma opens still needs to be fed back to the `stryker-karma-runner`.

**Comment by bharaninb** [comment]
@simondel we can get port from karma that they've selected.
[https://github.com/karma-runner/karma/blob/master/lib/server.js#L173](https://github.com/karma-runner/karma/blob/master/lib/server.js#L173)
I am working on updating stryker config after port changes.
