### ISSUE TITLE
Log to a file

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#748]
For ease of debugging issues, it would be useful to log all messages (log level trace) to a file. Comparable to what npm does: when an npm command fails, the user is informed that a log file can be found in the temp directory.

In order to do this, all stryker packages need to share log4js configuration. In order to do this, we need to move log4js to a shared peer dependency. The only one we have is the stryker-api, so I suggest to add the `getLogger` method there. We best use our own api and not rely in log4js for this. That way we can choose a different implementation rather easily. The stryker-api should not have a dependency on log4js, rather it would provide a way to set the log implementation. By default, it has a `noop` implementation and should log a warning (comparable to [SLF4J](https://www.slf4j.org/) for JVM).

This would also remove the necessity to call `setGlobalLogLevel` in every plugin to configure the log level on his instance of log4js.

**Comment by nicojs** [comment]
I've created the first draft of the logging api.  @simondel @Archcry could you maybe have a look?

https://github.com/stryker-mutator/stryker/tree/748-logging-api/packages/stryker-api/src/logging

**Comment by nicojs** [comment]
For the file logging: I'm thinking of keeping it simple. Add a config option for the file log level: 


```ts
/**
   * The log level for logging to a file. If defined, stryker will output a log file called "stryker.log".
   * Default: undefined
   */
  fileLogLevel?: LogLevel;

  /**
   * The log level for logging to the console. Default: "info".
   */
  logLevel?: LogLevel;
```

@stryker-mutator/contributors any feedback is welcome.

**Comment by mthmulders** [comment]
@nicojs why two different levels? I would expect (as you pictured in the original idea) that _all_ logging is sent to a file, so that when something goes wrong, that file contains all information that has been collected thus far. The `fileLogLevel` and its comments suggests that there will be logging _iff_ that variable is defined.

Also, just like SLF4J does, it might be useful to signal when logging is probably not set up correctly. In the case of SLF4J this can happen when there are multiple implementations on the classpath; in our case, it might be when the `noop` logger isn't overwritten by another one.

**Comment by nicojs** [comment]
> I would expect (as you pictured in the original idea) that all logging is sent to a file, so that when something goes wrong, that file contains all information that has been collected thus far

Yeah, I've thought about it. The problem is that I cannot guarantee it doesn't impact performance in a negative way. We still don't have performance tests. I've tested a first implementation on Stryker itself and the log file was 23MB. Do you think that this is a problem?

> Also, just like SLF4J does, it might be useful to signal when logging is probably not set up correctly. 

Great idea, I'll add it to the original issue

**Comment by mthmulders** [comment]
> I've tested a first implementation on Stryker itself and the log file was 23MB. Do you think that this is a problem?

Allocating 23 MB of disk space with the risk of throwing it away? Personally, it doesn't seem like a big deal to me, if it gave the benefit of very detailed log messages for troubleshooting.

**Comment by nicojs** [comment]
Hmm ok, you've convinced me. It serves the use case of reporting issues. Whenever we have more use cases, we can change it again.

**Comment by simondel** [comment]
Let's go for an _opt-in_ setting and place the log file in the current working directory.
