### ISSUE TITLE
Release v1.0.0 of all depedencies that we maintain ourselves

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#799]
Before we release v1.0.0 we should also release v1.0.0 of the dependencies that we maintain ourselves:

- [x] [surrial](https://www.npmjs.com/package/surrial)
- [x] [link-parent-bin](https://www.npmjs.com/package/link-parent-bin)
- [x] [typed-inject](https://www.npmjs.com/package/typed-inject)
- [x] [typed-html](https://www.npmjs.com/package/typed-html)
- [x] [install-local](https://www.npmjs.com/package/install-local)

**Comment by simondel** [comment]
Why?

**Comment by nicojs** [comment]
It will be easier for semantic versioning. It's not a hard requirement.
