### ISSUE TITLE
Align test runner config options

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#809]
Right now, each test runner has his own setup when it comes to custom configuration.

* The stryker-jest-runner uses a `jest` key as a container for its config.
* The stryker-karma-runner uses the `karmaConfig` and `karmaConfigFile` keys.
* The stryker-mocha-runner uses the `mochaOptions` config key
* The stryker-jasmine-runner uses the `jasmineConfigFile` key (has no other way of configuring as of yet).

It's kind of a mess. I feel like we should align on a standard way of providing test runner options.

I've been toying with the following idea:

```js
{
  testRunner: {
    name: 'karma',
    settings: { 
        /* custom settings go here */
        configFile: 'karma.conf.js',
        config: {
           browsers: [ 'ChromeHeadless' ]
        }
    }
  }
}
```

This would make the way of providing settings unified across test runners. It will also make it really clear that the settings are in fact to configure the test runner, keeping it nicely together.

@stryker-mutator/contributors what do you think?

**Comment by mthmulders** [comment]
I like the idea to have all runners that we maintain work in a more-or-less similar way. Makes it easy for us, makes it easy for Stryker users.

Having said that, my personal preference would be to clearly separate the *Stryker* configuration from that of the *test framework* (Jest, Karma, ...). Sure, they can live in the same file, but the naming should make it clear that whatever you provide there applies to the *test framework* that you use. I think that your naming suggestion addresses that.

Also, we might take the opportunity to standardise on prevalence. In your example, imagine `karma.conf.js` also has a setting `browsers`. What will the final configuration value be? I wouldn't be surprised if the different Stryker runners currently have different rules for that.

**Comment by nicojs** [comment]
> Having said that, my personal preference would be to clearly separate the Stryker configuration from that of the *test framework* (Jest, Karma, ...). 

The problem is that separating it might make it confusing. For example, the `stryker-jasmine-runner` would use the `jasmine` key in your example. But this is to configure the *jasmine test runner*, not the *jasmine test framework*. You even made the mistake on your comment. Moving it to the `testRunner` settings would eliminate this problem.

My idea would be to inject the settings under `testRunner.settings` directly into the test runner, instead of the entire stryker options. Simular approaches could also be taken for `testFramework` and others if we need it.

> Also, we might take the opportunity to standardise on prevalence. In your example, imagine karma.conf.js also has a setting browsers. What will the final configuration value be? I wouldn't be surprised if the different Stryker runners currently have different rules for that.

I think the general rule should always be: use the config file, but allow people to override settings. That way users can use there normal test runner settings, but override specific details for stryker.

**Comment by bharaninb** [comment]
Working on it

**Comment by nicojs** [comment]
@bharaninb Cool! If you run into difficulties, let me know. As you probably noticed, I've got some spare time this week, so can react to your requests.

**Comment by bharaninb** [comment]
@nicojs Thanks. Will let u know.
