### ISSUE TITLE
Stryker test runners timing out on travis

### ISSUE THREAD

**Issue by avdg** [stryker-mutator/stryker#825]
### Summary

All tests on travis timed out. This seems fixed after setting `maxConcurrentTestRunners` to a value like 8.

Example: https://travis-ci.com/avdg/wasm-decompile/jobs/126547066

Note that the number of available cores on travis is 2, but in a bursted configuration. That means there are more cores that may be available (as long as other builds don't use them).

### Stryker config

```js
module.exports = function(config){
    testRunner: "mocha",
    mutator: "typescript",
    transpilers: [],
    reporter: ["html", "clear-text", "progress"],
    testFramework: "mocha",
    coverageAnalysis: "off",
    tsconfigFile: "tsconfig.json",
    files: ["src/**/*", "test/**/*", "tsconfig.json", "package.json"],
    mutate: ["src/**/*.ts"],
    // maxConcurrentTestRunners: 8, // Note: uncommenting this line seemed to fix the issue
    mochaOptions: {
        files: [ 'test/**/*.spec.ts' ],
        require: ['ts-node/register', 'source-map-support/register'],
        timeout: 300
    },
    webpack: {
      configFile: "webpack.config.js"
    },
    logLevel: 'info'
  });
}
```

### Stryker environment

```
+-- stryker@0.24.0
+-- stryker-api@x.x.x (woops, seems none was installed `WARN stryker@0.24.0 requires a peer of stryker-api@^0.16.0 but none is installed.`. But apparently I can have successful build even with this error)
```

### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             |  v8.11.2 and v10.3.0
| npm              | 5.6.0 and v6.1.0 respectively
| Operating System | linux

**Comment by simondel** [comment]
@nicojs mentioned that the cores should now be reported as '2' by Travis. I'm closing this issue for now.
