### ISSUE TITLE
Read config from a config file

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#86]
I would like to add a way to read config using a config file instead of command line arguments. Very similar to what karma uses.

_Note: the current command line arguments would NOT be replaced with a config file_

Proposal:

* When you call `stryker` you can supply a config file with `--configFile` (or `-c`?). ~~If you don't supply one it will use `stryker.conf.js` as a default.~~ 
* the config file should look like this:

```javascript
module.exports = function(config) {
    config.set({
      files: [
           'lib/**/*.js',
           'src/**/*.js',
           'test/**/*.js'
       ],
       mutate: [
            'src/**/*.js'
       ],
    
        // additional optional options with default values: 
         testFramework: 'jasmine',
         testRunner: 'karma',
         timeoutMs: 2000,
         timeoutFactor: 1.5,
         plugins: ['stryker-*'],
         port: 9234
    });
};
```
* By default: any plugin is loaded from the node_modules folder starting with the name `stryker-`.
* A plugin will also have the possibility to register a ConfigWriter to the `ConfigWriterFactory`.
    * Config writers will be applied _after_ the reading of the normal `stryker.conf.js` file. Indeed it has to, because that file defines the plugins to be loaded in the first place.
    * For example: a plugin with the name `stryker-karma-runner` could register an additional `ConfigWriter` with the name `'karma'` to the `ConfigWriterFactory`. That `KarmaConfigWriter` can look for a property with the name `karmaConfigFile` in the existing config. It can read that `karma.conf.js` file and than choose to override some of the settings in the `stryker.conf.js` file. For example override the `files` based on the `karma.conf.js`'s `files` key.
    * This way, plugin implementers can have maximum flexibility in adding config based on config settings that live outside the stryker process.

Does everybody agree with this proposal?

* **Note**: I just changed some parts. This will not replace the command line arguments, just add a new one. I would like to maybe add a `stryker-cli` in the future where you would only accept a config file.*

**Comment by nicojs** [comment]
I added a proposal for the api in the new `feature-read-config` branch: https://github.com/stryker-mutator/stryker/tree/feature-read-config/src/api

**Comment by simondel** [comment]
I like the idea! I can't find the `files` and `mutate` properties in the API. Is there a reason why they aren't there?
