### ISSUE TITLE
Mochery incompatibility

### ISSUE THREAD

**Issue by Zikoel** [stryker-mutator/stryker#873]
### Summary

I like to use [Mockery](https://www.npmjs.com/package/mockery) tools for isolate my component under test. Obviously mockery can be invasive on require system... seems that this break stryker mechanism.
Well I created a simple repository that can reproduce this issue [Here](https://github.com/Zikoel/mutation) in the hope that a solutions can be found.

Thank you!

### Stryker config

```js
module.exports = function(config) {
  config.set({
    testRunner: "mocha",
    mutator: "javascript",
    transpilers: [],
    symlinkNodeModules: false,
    reporter: ["html", "clear-text", "progress"],
    testFramework: "mocha",
    coverageAnalysis: "perTest",
    mutate: ["src/**/*.js"]
  });
};
```

### Stryker environment
```
├─┬ stryker@0.24.1
├─┬ stryker-api@0.17.2
├─┬ stryker-html-reporter@0.14.2
├─┬ stryker-javascript-mutator@0.7.2
├─┬ stryker-mocha-framework@0.10.2
└─┬ stryker-mocha-runner@0.12.2
```

### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             | 8.11.2
| npm              | 6.1.0
| Operating System | Ubuntu 17.10

**Comment by nicojs** [comment]
@Zikoel thanks for reporting this issue and the clear reproduction steps!

I've cloned your repo and reproduced the problem:

```
[ERROR] InitialTestExecutor - One or more tests failed in the initial test run:
        "after each" hook for "compute"
                Cannot read property 's' of undefined
```

I think I know what the problem might be.

When using mocha with coverage analysis `"perTest", stryker injects an`afterEach` hook in the mocha test framework. It uses this hook to graps the coverage result for that test (it can be found under `global.__strykerCoverageCurrentTest__.s`). However, mockery seems to do something with the [*global*](https://nodejs.org/api/globals.html#globals_global) object as it doesn't seem to contain the statement coverage anymore (`__strykerCoverageCurrentTest__` is undefined). 

After switching coverageAnalysis to `"all"` stryker seems to run fine. Could you verify this? 

That all being said: I'm not a big fan of using something like mockery as it is really dependent on the way node modules work. It will probably break when es modules are a thing.

**Comment by nicojs** [comment]
@Zikoel Any luck? I'm closing this issue for now. Don't hesitate to contact us if you have more problems.
