### ISSUE TITLE
 how to use this with Angular-cli v6

### ISSUE THREAD

**Issue by ankeshdave** [stryker-mutator/stryker#897]
I read some issues about how to configure Stryker typescript, but still didn't find nething on how to use this with Angular Projects, esp. With Angular cli, I am new to mutation testing world, any pointers on what to try to make it work with Angular cli would be great..
Thanks

**Comment by simondel** [comment]
Thanks for opening an issue! For Angular projects you could take a look at this repo: https://github.com/nicojs/angular-stryker-example

**Comment by nicojs** [comment]
@ankeshdave thanks for this issue. I'm working on better integration (the one in https://github.com/nicojs/angular-stryker-example is kind of a dirty hack and might break in future releases of the angular cli). See this issue: https://github.com/stryker-mutator/stryker/issues/526

Are you willing to test it once issue 526 is solved? 

Closing this issue for now.

**Comment by ankeshdave** [comment]
Yup, I'll test this once its resolved , I have been trying to introduce mutation testing to my team :)

**Comment by simondel** [comment]
@ankeshdave We have started working on a handbook for Stryker. Our first guide will be a guide for Angular projects. Could you take a look at it as well? https://github.com/stryker-mutator/stryker-handbook/pull/2

**Comment by nicojs** [comment]
@ankeshdave see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/configuration/angular.md. Feel free to introduce Mutation testing to your team. Be the star of the day! ⭐️
