### ISSUE TITLE
Yarn support?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [stryker-mutator/stryker#917]
### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             | 10.x
| npm              |  _(nope!)_
| Operating System | Windows 10

I use Yarn on a project. Stryker's commands all run with npm, which cause weird and angry installation errors due to differences in how the two resolve modules.

Two suggestions:
* Offer the user which they're using, with npm as the default?
* Detect a `yarn.lock` without a `package-lock.json` and switch the default to yarn if so?

**Comment by nicojs** [comment]
Thanks @JoshuaKGoldberg for this feature request. I think you're specifically mean the `stryker init` command right? 

Should be fairly straight forward to implement. Do you want to give it a shot? It might take some time for us, as we're focusing on releasing 1.0 right now.

**Comment by JoshuaKGoldberg** [comment]
I'm in a bit of a time crunch right now but sure, why not :smile:. Do you have any tips for getting started?

**Comment by nicojs** [comment]
Haha, I think I know the feeling.

The initializer logic is all in the [initializer](https://github.com/stryker-mutator/stryker/tree/master/packages/stryker/src/initializer) directory. The actual npm call is here: https://github.com/stryker-mutator/stryker/blob/ca16dc0408e7661a3e3709719fc57ead9ef95909/packages/stryker/src/initializer/StrykerInitializer.ts#L142

I think a quick question using the [inquirer](https://github.com/stryker-mutator/stryker/blob/ca16dc0408e7661a3e3709719fc57ead9ef95909/packages/stryker/src/initializer/StrykerInquirer.ts#L9) will be enough.

However, this is only for the install command after the questionnaire. If you've installed the [stryker-cli](https://github.com/stryker-mutator/stryker-cli) and want to configure stryker on a new project using `stryker init`, you will first get a prompt asking to install stryker locally. If you want to add yarn support for that as well, you'll need to create a PR there as well. [This line](https://github.com/stryker-mutator/stryker-cli/blob/31c55a399c22f327df7acd1a79af69c76f411617/src/stryker-cli.ts#L8) is where the npm command is constructed there.

Everything is unit tested (d'uh) using mocha. Please take a look at our [contribution guide](https://github.com/stryker-mutator/stryker/blob/master/CONTRIBUTING.md#vscode-environment-configuration) for some hints to get you started with your dev environment (compiling typescript, debugging tests, etc).

**Comment by JoshuaKGoldberg** [comment]
Filed an issue in the stryker-cli repo; this one is enough for me! Thanks for the support! 🙌
