### ISSUE TITLE
Migrate grunt/js-mutation-testing mutators

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#92]
grunt-mutation-testing and js-mutation-testing contain mutators which are not yet supported by Stryker.

_The existing mutators have to be reviewed to decide which mutators should be supported by Stryker._

@paysdoc @jimivdw  How would you like to migrate the mutators? Do _you_ want to migrate them, do you want to do it together with me? Do you want me to do all of them?

The mutators of stryker are currently being overhauled. The most recent version can be found on the [new-mutator branch](https://github.com/stryker-mutator/stryker/tree/new-mutator/src/mutators)

**Comment by simondel** [comment]
I have migrated the block statement mutator from js-mutation-testing as an example. 

You can find it [here](https://github.com/stryker-mutator/stryker/commit/036e075d26cad0dd3842fc034f91dce059a752e2)

**Comment by riezebosch** [comment]
Stumbled upon a piece of code like this in a project:

```js
this.someArray()
                        .sort()
                        .map(x => someFunction(x))
                        .filter(someFilter);
```

with no test demanding the sort being present. Putting the .sort() method in comments did not fail a test.

So I am longing for a mutator that strips out array functions that do not alter the items (like map) but only affect the sequence (like sort and filter).

**Comment by simondel** [comment]
That's an interesting mutator! Unfortunately it's also quite difficult to implement because the AST does not contain information on what the result of the `someArray()` is. We could of course create a mutator that removes one function call. What do you think of that?

**Comment by riezebosch** [comment]
That would be awesome. Just stripping out function calls one by one in a method chain.

**Comment by nicojs** [comment]
Do we still want the grunt/js-mutation-testing mutators? If not; i want to close this issue and maybe create another issue for the method chaining mutator of @riezebosch

**Comment by simondel** [comment]
Let's close this One :)
