### ISSUE TITLE
Html-reporter support for other languages

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker#925]
### Summary

At the moment the stryker-html-reporter is custom made for Stryker (js). As we now see the trend of a broader support of languages within Stryker (C#, Scala) it would be great if the html reporter could be used by other mutation test frameworks. A single json file to generate would greatly simplify this collaboration between different frameworks.

### Example
``` json
{
"Files": 
     {
        "File":"Example.cs",
        "SourceCode": "using System; using.....",
        "Mutations": 
              {
                    "DisplayText": "+ to - mutation",
                    "Type": "BinaryMutation",
                    "Span": { "Start": 560, "End": 589 },
                    "MutatedCode": "3 - 6",
                    "Status": "Killed"
              }
     }
}
```

Is this change acceptable for Stryker? It would be very useful for other frameworks. Above json is just some idea, data could be added or removed if needed.

**Comment by nicojs** [comment]
@richardwerkman thanks for this feature request.

I'm actually thinking of totally moving the _actual_ html report generation to a separate git repo and module, for example: html-mutation-reporter. A generic api, with a CLI would be preferable. That way, it's fairly easy to either:

1. Generate a json file and call the CLI for non-nodejs tools.
2. Call the programmatic api for node- tools.

@stryker-mutator/stryker-core do you agree with this approach?

As for your json example: I was thinking to also add the directory results. Furthermore, this generic html reporter should be simply generating a report. Not do any calculations or anything. Otherwise, metrics like the mutation score, or mutation score of covered code, etc might be slightly different in the html report versus other reports. Lastly, strings in json files is generally camelCased.

With these changes, the my suggestion would look more like this:

```js
{    // The root DirectoryResult
    "name": "src",
    "path":  "/usr/full/path/to/src",
    "killed": 8,
    "survived": 1,
    "noCoverage": 1,
    "timeout": 0,
    "runtimeErrors": 2,
    "compileErrors": 3,
    "totalDetected": 8,
    "totalUndetected": 2,
    "totalValid": 10,
    "totalInvalid": 5,
    "totalMutants": 15,
    "mutationScore": 80,
    "mutationScoreBasedOnCoveredCode": 88,89,
    "health": "ok", # or "warning", or "danger",
    "childResults": [
        { "name": "src/module1", ... } // another DirectoryResult
        { 
            "name": "src/Example.cs", // A FileResult
            "path":  "/usr/full/path/to/src/Example.cs",
            "killed": 1,
            "survived": 1,
            "timeout": 0,
            "noCoverage": 1,
            "runtimeErrors": 0,
            "compileErrors": 1,
            "totalDetected": 1,
            "totalUndetected": 2,
            "totalValid": 3,
            "totalInvalid": 1,
            "totalMutants": 4,
            "mutationScore": 33.33,
            "mutationScoreBasedOnCoveredCode": 33.33,
            "health": "danger",
            "source": "using System; using.....",
            "mutants": [
                 "id": "321321",  // A unique id, can be used to correlate this mutant with other reports
                 "mutatorName": "BinaryMutator",
                 "replacement": "-",
                 "span": [21,22], // starts at position 21 (inclusive), ends at position 22 (exclusive)
                 "status": "Killed" // or "Survived", "NoCoverage", "CompileError", "RuntimeError", "Timeout"
            ]
        }    
    ]
}
```

**Comment by hugo-vrijswijk** [comment]
We have the starting position of the mutation. We could then calculate the span from that. 

How would that work with multi-line statements? (E.g. emptying a function)

**Comment by nicojs** [comment]
@hugo-vrijswijk that is an excellent idea! I didn't even think of that. 

It might even be pretty simple to do, as the current source code is already TypeScript. One thing we would need to do is  make it a single page application, as we cannot rely on the generation of HTML files anymore. We might be able to do it using web components or something like that. 

Deep linking should work as well. We can only use a [URL fragment](https://en.wikipedia.org/wiki/Fragment_identifier) for that, as [html's pushstate](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_pushState()_method) would result in url's that do not exist. 

And I want it to work fully offline as well, without a webserver. 

We should also add a `"language"` property to a `FileResult`. That way we can configure the correct syntax highlighting using [highlightjs](https://highlightjs.org/).

> How would that work with multi-line statements? (E.g. emptying a function).

It would work the same as an html report in Stryker right now. The location would span multiple lines, but the replacement is `""` (empty)

About the score results in the columns. Missing values could just be ignored. We would only add columns for provided fields. Now that I think of it, we should group them together! That way we can easily render the columns dynamically and the mutation testing framework has full control over it. 

An updated structure:

```js
{    // The root DirectoryResult
    "name": "src",
    "path":  "/usr/full/path/to/src",
    "totals": {
       "choose": 8,
       "custom": 1,
       "columns": 1,
       "here": 0,
       "like": 2,
       "mutation score": 80,
    }
    "health": "ok", // or "warning", or "danger",
    "childResults": [
        { "name": "src/module1", ... } // another DirectoryResult
        { 
            "name": "src/Example.cs", // A FileResult
            "path":  "/usr/full/path/to/src/Example.cs",
            "totals": {
               "detected": 1,
               "undetected": 2,
               "valid": 3,
               "invalid": 1
             },  
            "health": "danger",
            "language": "cs", // Or any other highlightjs identifier, see https://highlightjs.org/static/demo/
            "source": "using System; using.....",
            "mutants": [
                 "id": "321321",  // A unique id, can be used to correlate this mutant with other reports
                 "mutatorName": "BinaryMutator",
                 "replacement": "-",
                 "span": [21,22], // starts at position 21 (inclusive), ends at position 22 (exclusive)
                 "status": "Killed" // or "Survived", "NoCoverage", "CompileError", "RuntimeError", "Timeout"
            ]
        }    
    ]
}
```

**Comment by legopiraat** [comment]
Would be very cool if we could achieve this. The json format looks fine to make. @stryker-mutator/stryker4s @stryker-mutator/stryker-net @stryker-mutator/stryker-core could we make a decision on this format for the team being? So we can start the development to fulfill this fields as we do not have all this info out of the box available at this moment.

**Comment by nicojs** [comment]
@legopiraat yes, you can already start implementing. The json structure might change a little bit, but as long as @richardwerkman and @hugo-vrijswijk are happy for now, there shouldn't be any major changes.

We should create a [json-schema](http://json-schema.org/) for it, so it's absolutely clear exactly which fields are optional and which aren't.

> We could also add a field in there to specify how long the mutation test took to complete. Not sure if this information really adds any value though.

I would not add that in this first release. It's interesting for a future release though... 

>What do you mean with "health": "ok", // or "warning", or "danger",? 

This determines the color of the score. Either green, orange or red. Like I said before, I don't want the mutation report to make any decisions, as it might conflict with a console reporter or something.

**Comment by legopiraat** [comment]
Good plan on the `json-schema` found a tool online that can create a basic json schema based on the json structure [json schema generator](http://json-schema.org/specification.html).

**Comment by nicojs** [comment]
I've created a repository for it. I suggest we continue discussing there.
