### ISSUE TITLE
Warn when test files are mutated?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [stryker-mutator/stryker#928]
### Summary

If your `mutate` setting neglects to exclude however you define your tests, Stryker will apply mutations to those files as well.

For example, with Jest, I'm defining tests as `src/**/*.test.ts` and source files as `src/**/*.ts`. Stryker is now reporting mutant survivors that converting test descriptions from `it("some name", () => ` to `it("", () =>`.

### Stryker config

```js
module.exports = function(config) {
    config.set({
        coverageAnalysis: "off",
        files: [
            "config/**/*.js",
            "config/**/*.js.map",
            "config/**/*.ts",
            "src/**/*.js",
            "src/**/*.ts",
            "test/unit/setup.js",
            "test/unit/styleMock.js",
            "tsconfig.json",
            "tsconfig.test.json",
        ],
        mutate: [
            "src/**/*.ts",
            "src/**/*.tsx",
            "!src/**/*.d.ts",
        ],
        mutator: "typescript",
        reporter: ["baseline", "clear-text", "dashboard", "html", "progress"],
        testRunner: "jest",
        tsconfigFile: "tsconfig.json",
    });
};

```

### Stryker environment

```
    "stryker": "0.24.1",
    "stryker-api": "0.17.2",
    "stryker-baseline-reporter": "1.0.3",
    "stryker-cli": "0.1.3",
    "stryker-html-reporter": "0.14.2",
    "stryker-jest-runner": "0.7.0",
    "stryker-typescript": "0.11.2",
    "stryker-webpack-transpiler": "0.5.1",
```

### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             |  10.X
| npm              | 5.6.0
| Operating System |  Windows 10

**Comment by nicojs** [comment]
@JoshuaKGoldberg thanks for excellent suggestion.

What would be your preferred solution? It is difficult to scan the _actual file content_ for tests itself (file could be TS/JS/CoffeeScript and use Mocha, Tap, or anything else). I think an easier approach is to use the names of the files.

For example: when mutating these files:

```bash
src/mutator.js
test/mutatorSpec.js
test/mutator.spec.js
test/mutatorTest.js
test/mutator.test.js
__tests__/mutator.tsx
```

We could log: 

```
Warning: 5 files that you want me to mutate smell like test files. You should not mutate test files, only actual source files. Set `noWarningOnMutateTestFiles` to `false` in your stryker config to ignore this warning. Files in question were: test/mutatorSpec.js
test/mutator.spec.js
test/mutatorTest.js
test/mutator.test.js
__tests__/mutator.tsx
```

I've added the `noWarningOnMutateTestFiles` so people can ignore this warning if our regex matching wonders do not work for them.

I'm open to other suggestions as well, please let me know.

**Comment by JoshuaKGoldberg** [comment]
That sounds good! As long as the regex wonders are sourced from whatever config the user has specified.

**Comment by nicojs** [comment]
I've not implemented my suggestion (which is still a great suggestion, I don't want to piss past Nico off), but I've implemented an improved default regex: 

```
public mutate: string[] = [
    '{src,lib}/**/*.js?(x)',
    '!{src,lib}/**/__tests__/**/*.js?(x)',
    '!{src,lib}/**/?(*.)+(spec|test).js?(x)',
    '!{src,lib}/**/*+(Spec|Test).js?(x)'
  ];
```

If someone still wants to implement this, go ahead. For now, we're closing this issue in order to keep things tidy.
