### ISSUE TITLE
Request: mutator to remove async/await

### ISSUE THREAD

**Issue by nosideeffects** [stryker-mutator/stryker#933]
In a transition to using `async/await` from callbacks or Promises, these very important keywords can be lost in merges. Unit tests _should_ catch these omissions, so I propose the addition of the following mutators:

before | after
------ | -----
`await (expression)` | `(expression)`
`async function() { }` | `function() { }`
`async () => {}` | `() => {}`

**Comment by andrepm06** [comment]
Fanstastic suggestion!

**Comment by nicojs** [comment]
This is indeed a good suggestion. @simondel do you agree? @nosideeffects do you want to take a swing at this feature?

**Comment by nosideeffects** [comment]
@nicojs I can definitely make an attempt. Should I implement both a TypeScript and JavaScript mutator?

**Comment by nicojs** [comment]
That would make sense yes. They also share tests, so should be easy. 

@simondel what should the mutator name be? Create 2? One for `await` and one for `async`?

**Comment by simondel** [comment]
@nosideeffects Do you still have plans to implement this? Else we'll close the issue until someone wants to pick it up.

**Comment by simondel** [comment]
Since we didn't hear anything back, we're closing this for now. If anyone wants to add it in the future. Please open a new issue.
