### ISSUE TITLE
Show ETC as minutes or hours when applicable

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [stryker-mutator/stryker#956]
### Summary

When on a laptop with 4 cores instead of a dev machine with 16, Stryker takes quite a bit longer for large projects:

![image](https://user-images.githubusercontent.com/3335181/42417913-d71cf394-8249-11e8-8020-e9a0b7e48c08.png)

Could we get this in hours instead, please? 

### Stryker environment

```
    "stryker": "0.24.1",
    "stryker-api": "0.17.2",
    "stryker-baseline-reporter": "1.0.3",
    "stryker-cli": "0.1.3",
    "stryker-html-reporter": "0.14.2",
    "stryker-jest-runner": "0.7.0",
    "stryker-typescript": "0.11.2",
    "stryker-webpack-transpiler": "0.5.1",
```

### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             |  8.8
| npm              | 5.6
| Operating System | Windows 10 

Edit: how about using [`moment`](https://momentjs.com) or [`luxon`](https://moment.github.io/luxon)?

**Comment by nicojs** [comment]
We could, but it wouldn't make it go faster ;).

Seems like a fair request and a good first issue for anyone interested. Thanks @JoshuaKGoldberg

**Comment by nicojs** [comment]
@JoshuaKGoldberg both moment and luxon are good suggestions, but both come at a cost (namely download size). Let's try to avoid them if the only thing we need is a human readable ETC.

**Comment by Archcry** [comment]
It seems like this ain't as easy as we thought it would be, we are using https://github.com/visionmedia/node-progress and it does not support any other format.

As seen in this issue https://github.com/visionmedia/node-progress/issues/63 there have been multiple pull-requests for this but none was accepted.

**Comment by nicojs** [comment]
Please upvote: https://github.com/visionmedia/node-progress/issues/174
