### ISSUE TITLE
Mutation score is not very descriptive

### ISSUE THREAD

**Issue by jordyheutinck** [stryker-mutator/stryker#96]
Mutation score is not very descriptive and a bit ambiguous.

```
248 mutants tested.
13 mutants untested.
14 mutants timed out.
186 mutants killed.
Mutation score based on code coverage: 80.65%
Mutation score based on codebase: 76.63%
```

Should probably be explained a little better. Perhaps renaming it would also increase readability. For example, percentage of killed mutations, or, "Stryked mutations" ;)

**Comment by nicojs** [comment]
@jordyheutinck we've updated it slightly in the `0.5` release. What do you think of this?

```bash
1130 total mutants.
499 mutants survived.
  of which 248 were not covered by the tests.
5 mutant(s) caused an error and were therefore not accounted for in the mutation score.
6 mutants timed out.
620 mutants killed.
Ran 22.15 tests per mutant on average.
Mutation score based on covered code: 71.38%
Mutation score based on all code: 55.64%
```

**Comment by simondel** [comment]
We're closing this issue for now. If you still have feedback on way the mutation score is showed right now, please let us know!
