### ISSUE TITLE
Support for CSS-in-JS style creators?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [stryker-mutator/stryker#963]
### Summary

We use [Glamor](https://github.com/threepointone/glamor) with React to declare our CSS styles in JS. For example:

```tsx
import * as React from "react";

const createStyles = (color: string) => ({
    color,
    fontWeight: "bold",
});

export interface IColoredTextProps {
    color: string;
    text: string;

    /** Proxies { css } from "glamor" (stubbed out in unit tests) */
    glamor: IStyleProvider;
}

export const ColoredText = ({ color, glamor, text }: IColoredTextProps) => (
    <span style={glamor.css(color)}>
        {text}
    </span>
);
```

We do have unit tests for `ColoredText` to ensure it displays `{text}`, but it's against our preference to include unit tests for, say, `fontWeight: "bold"`. Unit testing CSS is too detailed for us and we prefer using visual regression testing for that kind of scenario.

Stryker will notice that unit tests don't fail when `createStyles` changes.

Short of disabling tests on all `*.jsx`/`*.tsx` files, how can we disable mutators on these kinds of methods?

### Stryker config

```js
module.exports = function(config) {
    config.set({
        coverageAnalysis: "off",
        files: [
            "src/**/*.js",
            "src/**/*.ts",
            "src/**/*.tsx",
            "tsconfig.json",
        ],
        mutate: [
            "src/**/*.ts",
            "src/**/*.tsx",
            "!src/**/*.test.ts",
            "!src/**/*.test.tsx",
            "!src/**/*.d.ts",
        ],
        mutator: "typescript",
        reporter: ["baseline", "clear-text", "dashboard", "html", "progress"],
        testRunner: "jest",
        tsconfigFile: "tsconfig.json",
    });
};

```

### Stryker environment

```
    "stryker": "0.24.1",
    "stryker-api": "0.17.2",
    "stryker-baseline-reporter": "1.0.3",
    "stryker-cli": "0.1.3",
    "stryker-html-reporter": "0.14.2",
    "stryker-jest-runner": "0.7.0",
    "stryker-typescript": "0.11.2",
    "stryker-webpack-transpiler": "0.5.1",

```

### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             | 9.X
| npm              | 5.6
| Operating System | Windows 10

**Comment by simondel** [comment]
I'm not sure if we can detect this. What are your thoughts @nicojs?

**Comment by simondel** [comment]
If you don't want to test this, you could exclude string mutations all together.
