### ISSUE TITLE
tslib dependency is a few versions behind

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [stryker-mutator/stryker#967]
### Summary

`tslib` is now at 1.9.3. Your versions are:
* `stryker`: ^1.5.0
* `stryker-api`: ^1.6.0
* `stryker-javascript-mutator`: ^1.8.0
* `stryker-karma-runner`: ^1.6.1
* `stryker-mocha-framework`: ^1.5.0
* `stryker-mocha-runner`: ^1.5.0
* `stryker-typescript`: ^1.5.0

 I'm particularly fond of [Greenkeeper](https://greenkeeper.io/) for CI and [npm-check-updates](https://github.com/tjunnone/npm-check-updates) for local development. Staying up-to-date on packages is generally a good idea:
* You get the latest bug fixes and improvements, particularly security patches
* You don't fall out of date with API needs (e.g. #566!)
* Users have fewer duplicate npm dependency versions resolved

**Comment by nicojs** [comment]
This is strange. @dependabot, any idea why this versions are behind?

**Comment by simondel** [comment]
It is not behind actually. See: https://github.com/stryker-mutator/stryker/pull/904 for example.

A clean install should give us the latest version of tslib for each package. We could either: add a package.lock.json again or remove the `^` before the version so Dependabot will give a PR with every version.

**Comment by JoshuaKGoldberg** [comment]
Ah my apologies, I didn't think to check whether you already had Dependabot :)

+1 to explicit version ranges!

**Comment by simondel** [comment]
No problem :) bots can be sneaky. What would you suggest as a version range for tslib? Pinning major and minor versions down but not the patch version?

**Comment by JoshuaKGoldberg** [comment]
I prefer exact versions to be sure of the exact version.

Package authors sometimes "mess up

**Comment by JoshuaKGoldberg** [comment]
I prefer exact versions to be sure of the exact version.

Package authors sometimes "mess up

**Comment by JoshuaKGoldberg** [comment]
_(sorry, large thumbs on mobile)_

+1 to including major and minor versions.

Even with `package-lock.json`/`yarn.lock`, there are benefits to explicitly stating your version. It's impossible to exactly follow semver, as even additions to an existing API can be breaking changes (e.g. to checks of whether some APIs exist). It's also clearer to non-package-authors what versions you're using: both in practice (as a convenience for quick scans) as as your _intent_ (what versions you explicitly intend to support).

Also, you remove the possibility of version X being specified, X + 1 shipping with a bug, X + 2 fixing the bug and being what you're used to, and a user with some particular dependency chain resolving to X instead of X + 2.

**Comment by nicojs** [comment]
> +1 to including major and minor versions.

This should be done for all dependencies, right? Not only tslib

**Comment by nicojs** [comment]
@JoshuaKGoldberg I've created PR #974. Would you mind reviewing this one?
