### ISSUE TITLE
Use prettier colors on the CLI reporter?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [stryker-mutator/stryker#975]
### Summary

https://twitter.com/_nicojs/status/1017154960834945024

Referring to colored output in terminals:

> We should use that in #StrykerMutator's clear text console reporter 😎

**Comment by nicojs** [comment]
I was actually referring to the deep linking. It would be awesome if you could click to the exact location where the mutant is located. Pretty colors are nice as well, we already have some colors I think, but as I said in the twitter chat, it might all use a make over 💄. You may work your magic by all means 👍 

The code is already prepared to write to file as well (it uses an output stream). Not sure if anyone is waiting for that feature, but if you want, you can add it as well. When writing to file we should remove color codes I guess.

The console report is also pretty verbose, which bothers me a little. It prints several lines per mutant. Not sure if others agree @stryker-mutator/contributors ?

**Comment by JoshuaKGoldberg** [comment]
Is there a dedicated emoji for scope creep? 🐍 perhaps?

What is the total feature set discussed here?

💄 Color make over for the CLI if in tty mode?
🔗 Links to original file lines in output?
👽 Emoji decorations in output if in a terminal that supports them?

**Comment by nicojs** [comment]
> Is there a dedicated emoji for scope creep?

I think you just coined the emoji: 🐍 it is! 🥇

>  💄 Color make over for the CLI if in tty mode?

Yes. Well... I'm not sure if tty is the correct check to be making. Non-tty can support colors and emoj.

For example:

In vscode debugger terminal:
![image](https://user-images.githubusercontent.com/1828233/42642057-43dc7fa4-85f6-11e8-9bf8-9a364276ca82.png)

In [conemu](https://conemu.github.io/):

![image](https://user-images.githubusercontent.com/1828233/42642097-5ca7d506-85f6-11e8-8c3a-01552df27a06.png)
 
In command prompt:

![image](https://user-images.githubusercontent.com/1828233/42642117-6a802c8c-85f6-11e8-8e61-2be7f9a8f9e1.png)

>🔗 Links to original file lines in output?
> 👽 Emoji decorations in output if in a terminal that supports them?

If that is feasible for you :)

**Comment by nicojs** [comment]
There is an issue for emoji support in Windows console: https://github.com/Microsoft/console/issues/190

It seems that there already is _some_ support. So no need to actively check for support I think
