### ISSUE TITLE
Runtime errors

### ISSUE THREAD

**Issue by samfoot** [stryker-mutator/stryker#977]
### Summary

I am getting a large number of runtime errors when running stryker. I have tried running with loglevel: 'debug' but I don't see any obvious errors, the tests run manually with jest without issue. How can I find out what is causing me to have so many runtime errors?

### Stryker config

```js
module.exports = function(config) {
  config.set({
    testRunner: "jest",
    mutator: "javascript",
    transpilers: [],
    // logLevel: 'debug',
    reporter: ["clear-text", "progress"],
    coverageAnalysis: "off",
    mutate: [
      'src/**/*.js',
      '!src/**/*.test.js',
      '!src/test/*',
    ],
  });
};
```

### Stryker environment

```
stryker@0.24.2
stryker-api@0.17.3
stryker-javascript-mutator@0.7.3
stryker-jest-runner@0.7.0
jest@23.3.0
```

### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             |  10.6.0
| npm              | 6.1.0
| Operating System | OSX 10.13.5 

### Screenshot

<img width="478" alt="screen shot 2018-07-12 at 10 52 25" src="https://user-images.githubusercontent.com/818528/42626263-bec9e98e-85c1-11e8-8f83-4d8f44ed8fb9.png">

**Comment by nicojs** [comment]
Hmm interesting. Could you try again with `loglevel: 'trace'`? Testrunner processes are currently silenced unless loglevel is trace.

**Comment by samfoot** [comment]
Thanks for getting back to me @nicojs 

I just ran it again with `loglevel: 'trace'` and I am now getting a load of `Mutant caused runtime error` errors on the output, screenshot below.

<img width="925" alt="screen shot 2018-07-12 at 11 07 55" src="https://user-images.githubusercontent.com/818528/42627147-19e58c5e-85c4-11e8-928e-5e0203a08ad6.png">

**Comment by samfoot** [comment]
thanks for getting back to me @nicojs 

I ran it with `trace` and I am now getting loads of `Mutant caused a runtime error!` errors in the output:

<img width="925" alt="screen shot 2018-07-12 at 11 07 55" src="https://user-images.githubusercontent.com/818528/42627272-703e2188-85c4-11e8-9203-a3ebd48ff849.png">

**Comment by nicojs** [comment]
If you scroll up you should be able to see the runtime errors themselves. It is printed before the actual results. We're working on a feature for logging to a file. Untill then, you could use `stryker run > out.txt` to redirect output to a file

**Comment by samfoot** [comment]
I can't see any runtime errors in the output, could I send you the output directly to take a look?

**Comment by samfoot** [comment]
I just ran one of the test manually copying the trace output: 

```{"collectCoverage":false,"collectCoverageFrom":["**/*.{js,jsx}","!**/node_modules/**","!src/test/**","!coverage/**","!src/index.js"],"coverageReporters":["text","lcov"],"coverageThreshold":{"global":{"branches":10,"functions":10,"lines":10,"statements":10}},"verbose":false,"bail":false,"rootDir":"/Users/sf/proj1/.stryker-tmp/sandbox7222091","reporters":[]}```

When I run the above I get no output at all, if I remove `"reporters":[]` I see jest running the tests correctly.

**Comment by nicojs** [comment]
Hmm ok, so we know the problem is somewhere in Stryker. Could you send me the console output somehow? You can use nicojs [AT] infosupport [DOT] com (no spaces)

**Comment by samfoot** [comment]
With the help of @nicojs we found the problem to be on of my tests leaking state, a global `Object.defineProperty` in one of my dependencies was causing Jest to throw a `TypeError: Cannot redefine property:` error, this happens in Stryker because the same test is being run multiple times in the same process.

Currently these errors are not being output to the user even with the  `loglevel: 'trace'` configuration, which makes it hard to debug.

Many thanks to @nicojs for the help, and the whole Stryker team for creating an awesome tool.

**Comment by Prerna237** [comment]
> With the help of @nicojs we found the problem to be one of my tests leaking state. A global `Object.defineProperty` in one of my dependencies was causing Jest to throw a `TypeError: Cannot redefine property:` error, this happens in Stryker because the same test is being run multiple times in the same process.
> 
> Currently these errors are not being output to the user even with the `loglevel: 'trace'` configuration, which makes it hard to debug.
> 
> Many thanks to @nicojs for the help, and the whole Stryker team for creating an awesome tool.

Could you name the dependency that was causing this problem? I am facing a similar issue here
